### ISSUE TITLE
Architecture question ( module import / plugins load )

### ISSUE THREAD

**Issue by radpet** [ProjectMirador/mirador#1003]
@rsinghal  
I need to implement my own annotation endpoint, but as far as I am into mirador's code I don't see a another way than putting it into the build workflow and make custom builds or putting it between mirador.js load and its instance initialisation.  It would be really cool if I am able to specify path in the config and mirador automatically loads the module when it inits ( I am speaking about annotation endpoints).

Such module system would help mirador to take less space because, sometimes some of the modules are not needed and there is no need for loading any code for them.

It would also improve unit testing. Currently it is really hard to unit test something because it is tightly coupled with a lot of other functionalities. What do you think?

**Comment by dicksonlaw583** [comment]
You can add the annotation endpoint as another embedded script on the page embedding `mirador.js`. It doesn't have to be a part of the build, especially if it's custom-made.

**Comment by radpet** [comment]
@dicksonlaw583 Yup that is what I meant by putting it between mirador.js load and initialisation but I don't really like the idea. With mirador.js I will load couple of other files I don't use. For example the tinymce editor etc

**Comment by rsinghal** [comment]
@radpet This makes a lot of sense.  I don't have the time to include this in Release 2.1, but is a great idea for a future release.

**Comment by radpet** [comment]
@rsinghal 
https://github.com/systemjs/systemjs this look promising take a look at it

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
