### ISSUE TITLE
Annotation/Adjustment controls become inactive when switching images 

### ISSUE THREAD

**Issue by ViktorRibchev** [ProjectMirador/mirador#1018]
Annotation/Adjustment controls become inactive when switching images. 
Please see https://www.youtube.com/watch?v=ubOtnWCuv4c
![mirador console](https://cloud.githubusercontent.com/assets/17718464/16908915/a86e4a10-4cd7-11e6-8a2d-94bfac5b4886.png)

**Comment by rsinghal** [comment]
@ViktorRibchev Please try https://github.com/IIIF/mirador/commit/fdad8270a805bb146835559ce1212d875e05366d - it should be fixed now.  The only outstanding item is it is not preserving the border/fill choices after pagination.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
