### ISSUE TITLE
Adjust location of trash and rotate points when they are near the edge of the canvas

### ISSUE THREAD

**Issue by rsinghal** [ProjectMirador/mirador#1021]
@radpet  If a shape is drawn near the bottom of the image, the trash can icon is not visible.  Likewise, if the shape is drawn near the top of the image, the rotate point is not visible.

![screen shot 2016-07-19 at 4 04 41 pm](https://cloud.githubusercontent.com/assets/2371632/16993141/25665578-4e70-11e6-8405-0d2e0715e6e1.png)
![screen shot 2016-07-19 at 3 54 10 pm](https://cloud.githubusercontent.com/assets/2371632/16993140/2566320a-4e70-11e6-9522-2b0d4ff20989.png)

Lastly, the rotate point is not adjusting in size as the user zooms in and out.

**Comment by versae** [comment]
One possible workaround is to set `'visibilityRatio': 0.95` when creating the `OpenSeadragon` instance in `imageView.js`, so the image can be panned far enough to fill the viewport with a maximum of 5% background. In that 5% of background there is room to show the handlers for both the rotation and trash can icons.


![rotation-trash-handlers](https://cloud.githubusercontent.com/assets/173537/23482194/095ecc3e-fe83-11e6-85de-c51057e249e2.gif)

**Comment by rsinghal** [comment]
I think that could be a nice workaround.

**Comment by versae** [comment]
Nice, I'll bump it up to 10% as per @aeschylus' recommendation.

**Comment by rsinghal** [comment]
Since it's not possible to click the icons even after changing the `visibilityRatio`, another alternative is to move the icons into the middle of the shape.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3 annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
