### ISSUE TITLE
Grunt uglify

### ISSUE THREAD

**Issue by radpet** [ProjectMirador/mirador#1027]
I saw there is uglify task in the gruntfile but I do not see where it is used. 
What about adding it at as subtask for the build?

**Comment by aeschylus** [comment]
I think that's a good idea, as it will reduce our bundle size and increase load times. However, the build system is getting an overhaul at the moment, so I'm not sure it will be a durable change.

**Comment by aeschylus** [comment]
I think this is back on the table for 2.1.2/2.2 given the delays on the build system revamp.

**Comment by aeschylus** [comment]
@versae @csbailey5t 

Can you guys turn this on (branching off of 2.1.2)?

Essentially its written in the Gruntfile, but not turned on/exposed to the outside or integrated into the build process. See: http://gruntjs.com/creating-tasks

**Comment by csbailey5t** [comment]
Implemented in 90ffc2020f533d9e763f43b6c4604558364be0c5, though not yet merged into the release branch
