### ISSUE TITLE
Better handling of very wide thumbnail images

### ISSUE THREAD

**Issue by rsinghal** [ProjectMirador/mirador#1034]
http://gallica.bnf.fr/iiif/ark:/12148/btv1b525067595/manifest.json provides thumbnail URLs, which are smaller than Mirador would normally request.  The manifest page assumes a specific width and height for each thumbnail, which distorts the thumbnail significantly.

**Comment by mejackreed** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
