### ISSUE TITLE
2.1 - mouse wheel doesn't work to zoom with annotation dialog open and pointer selected

### ISSUE THREAD

**Issue by beaudet** [ProjectMirador/mirador#1067]
I understand why the mouse wheel wouldn't be enabled when drawing a shape, but even with the pointer tool selected, the mouse wheel doesn't work to zoom in / out.  Also, I see when creating a new shape that the shape previously selected continues to be selected.  That would certainly make it faster to create a lot of the same sized shapes, so I understand the rationale there, but I also don't seem to be able to create multiple shapes without clicking save in between unless I click on a different shape icon first, e.g. I click on the square, create a shape.  I should immediately be able to create a new square, but I cannot.  I first have to select circle, then square again.  Also, clicking on the pointer destroys any shapes I haven't saved and I'm not prompted.  I think the pointer is a valid tool to use when the annotation dialog is open, isn't it?
- [ ] mouse wheel zooming
- [x] create multiple of the same shape without having to re-select
- [x] clicking pointer destroys changes without prompting

**Comment by rsinghal** [comment]
added checklist to breakdown the issues a bit further as they get fixed

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
