### ISSUE TITLE
Annotation menu and context controls menus overlap when Mirador frame is smaller

### ISSUE THREAD

**Issue by ViktorRibchev** [ProjectMirador/mirador#1071]
Annotation menu and context controls menus overlap when Mirador frame is smaller
![overlap](https://cloud.githubusercontent.com/assets/17718464/17967886/7bd90904-6ad2-11e6-9f9c-301a0e5d74b5.png)

**Comment by rsinghal** [comment]
Ah yes, this is good to know!  What size is the Mirador frame in that screenshot?

**Comment by ViktorRibchev** [comment]
Each slot is approximately 450px in width.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
