### ISSUE TITLE
2.1 -  cross browser testing needed

### ISSUE THREAD

**Issue by beaudet** [ProjectMirador/mirador#1072]
Not sure whether IE 11 is supposed to work with 2.1 or not (is there a list of browsers this release is targeting?), but the head of our conservation department reports the following with the 2.1 demo site:

"Having problems. I first opened it in IE (11) but there was overlaid text where the annotation tools are supposed to be. I then tried Firefox and all seemed well until I actually tried to place a selected annotation circle or square or etc on the image." 

followups:

"It works well in Chrome. I love it and so pleased we moved to Mirador. 

The only problems I encountered:
•	The polygon annotation tool does not let me add text and it continues to add data points until I click on something else.
•	I could not get the arrow tool to work.
•	Sometimes – not often - the text did not appear when I moused over an annotation.

I just tried Firefox a second time and this time it worked. I also tried Chrome again and the arrow tool for panning worked.  Life is a mystery. Should the arrow be a panning hand symbol?"

So, it seems IE 11 still has some issues and the above is mostly UX feedback on the annotation experience.

**Comment by radpet** [comment]
> • The polygon annotation tool does not let me add text and it continues to add data points until I click on something else.

You should double click to finish drawing.We should add guide I suppose.

**Comment by beaudet** [comment]
More browser testing results by a conservator within our organization [this testing was done on a Mac]:

Safari
1.  Added each of the annotations and comments: all worked.    
2.  Replace object / Add slots / Toggle side panel / Arrows for panning in/out:  all worked. 
3.  **Change Layout did not work** — it got hung up with the spinning ball and I had to close.  

Firefox
1.  **The annotations will not prompt me to add comment unless it is the first one I pick**;  in other words, I have to clear existing annotations to get the comment box. [I have asked for more specifics on this]
2.  Everything else OK.

Chrome
1.  Everything worked.

**Comment by rsinghal** [comment]
Thanks, this is really helpful

**Comment by beaudet** [comment]
FYI - This is what IE 11 looks like when opening a manifest.

![image](https://cloud.githubusercontent.com/assets/77699/18133343/36937452-6f68-11e6-945b-93205e00403c.png)

**Comment by rsinghal** [comment]
@beaudet I can't recreate either of the issues mentioned for Safari or Firefox.  Can you get more information to recreate?

**Comment by beaudet** [comment]
I've asked for more information including Safari version and OSX version.

**Comment by beaudet** [comment]
The on-screen CSS based controls for contrast, brightness, grayscale, etc. have no effect on on IE11.  MS Edge seems to work ok.  Here's a screenshot from a test using browserstack.com showing grayscale enabled (yet the sepia color still shows) and brightness at 0% which obviously isn't happening.

![image](https://cloud.githubusercontent.com/assets/77699/18180755/3c4518c6-7056-11e6-8732-541dad032e58.png)

**Comment by beaudet** [comment]
I think we need to decide as a community what browsers to support.  The problem for organizations that are still running Windows 7 Enterprise (like us) is that the Edge browser requires a later operating system, so I'd strongly encourage the community to continue to support IE 11 for the sake of those who are subject to the Enterprise IT gods.

**Comment by thehabes** [comment]
http://caniuse.com/#feat=css-filters

Unfortunately, not everything supports the CSS3 filter property which is
what those controls use.  See the table of support above. That will tell
you right away what browsers those controls will and won't work in.

Alternative approaches to supporting the manipulation controls in browsers
that don't support the CSS3 filter property are a bit out of scope for the
filter functions currently written.  Helper javascript functions would have
to be introduced to get the job done where CSS3 filters are not supported.
It would look something a lot like what is found on these posts (which show
grayscale, but the brightness, contrast and saturation helper functions
would be about the same) :

http://www.majas-lapu-izstrade.lv/cross-browser-grayscale-image-example-using-css3-js/

http://www.majas-lapu-izstrade.lv/cross-browser-grayscale-image-example-using-css3-js-v2-0-with-browser-feature-detection-using-modernizr/

That would give the power to pick and choose what browsers are supported.
You can see the list of supported browsers for this function listed on the
website and weight it against the caniuse.com table to see the difference
in cross-browser support you will gain, or if you are just worried about
having it work in a specific browser, you can model a solution off that bit.

I weighed those choices when writing the functions for my applications and
settled with taking whatever would support CSS3 filters for the ease of
sharing that function between applications (and ultimately with you all!).
Sadly, IE stopped supporting the -ms-filter property, and some old versions
of browsers don't know what the filter property is, so this introduced
restrictions which now you are seeing as well.

This should give you an overview of the choices you can make and the work
involved with making them for the filters.  Let me know if there are
questions.

**Comment by beaudet** [comment]
Would it make sense to hide the controls that don't work if the browser is detected to have no support for CSS filters?

**Comment by cubap** [comment]
I support simply hiding the CSS controls if feature detection doesn't have them possible. My understanding of the CSS is for simple and in-place controls of the image, which not every browser or user (depending on vendor, platform, and preferences) may support. There is a more deliberate and limited manipulation that would just rerequest the image as grayscale or any future supported transformation. The most compatible option would be canvas element transformations, which would allow for very rich filters, but would have to be performance tested and would require integration into the OSD module, which may not be worth the complexity.

So, +1 @beaudet for hiding the CSS filters. 

Perhaps the future (or fork) feature from this would allow for transformations to the canvas simply by annotation of script or a few simple preloaded functions. In this way, users would be able to develop very [specific-case](http://www.html5rocks.com/en/tutorials/canvas/imagefilters) and complex tools to run on images, even support for edge-detection and [RTI](http://culturalheritageimaging.org/Technologies/RTI/) and save them for future reference. The current CSS _can_ do this, but not within Mirador and still to the limits of compatibility.
