### ISSUE TITLE
2.1 Edges of zoomed and rotated images difficult to view

### ISSUE THREAD

**Issue by higginsr** [ProjectMirador/mirador#1083]
Loaded one of our objects http://iiif.durham.ac.uk/manifests/dul/clb/clb2-107.json to try the new rotate feature. The letter text is written in two directions. Rotated page 1 90 degrees anti-clockwise and zoomed in to read text added down left edge of the letter. When you drag the image up to read this text it springs back towards the middle. The only way you can read the text at what is now the bottom of the viewer is to drag and hold the image in place with the mouse button - a workaround. This bouncy-edged image behaviour happens with Chrome and Firefox on Windows.

**Comment by aeschylus** [comment]
This is a "feature" that we will undo in an upcoming release (2.1.1, rather than 2.1). The spring behaviour is part of the openseadragon initial settings that we should investigate tweaking. We have also had complaints of the controls being too sensitive.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
