### ISSUE TITLE
2.1 - no way to resize the annotation dialog box

### ISSUE THREAD

**Issue by beaudet** [ProjectMirador/mirador#1100]
I realize this is a feature request, but when an image is embedded in the annotation text, it gets kind of lost.  Perhaps either the size of the dialog could be provided by the annotation source or Mirador would remember the size of the annotation editing dialog once resized.

**Comment by mejackreed** [comment]
I was looking into this, and it seems like we rely on jquery-ui to handle dragging for the annotation box. I am wondering if removing the jquery-ui dependency for dragging/resizing and using:

http://interactjs.io/

instead.

**Comment by rsinghal** [comment]
We used jquery-ui because it is already used in other parts of the application - no reason this functionality can't use something better.

**Comment by mejackreed** [comment]
Thanks @rsinghal !

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
