### ISSUE TITLE
2.1 - video playback in annotation resets when leaving focus of annotation dialog

### ISSUE THREAD

**Issue by beaudet** [ProjectMirador/mirador#1101]
If a video is playing in the annotation dialog, I think the annotation dialog should either be sticky or pause. Also, full screen from youtube doesn't seem to work when playing inside annotation dialog.  Annotation dialog should probably also expand to display the full video size.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
