### ISSUE TITLE
Annotations become invisible when switching canvases while annotation display is on.

### ISSUE THREAD

**Issue by gigamorph** [ProjectMirador/mirador#1103]
For example, if I load a canvas 1 into the window and click on the ballon icon, I see the annotations along with the edit controls. If I switch to another, say, canvas 2, the controls are there but I don't see any annotations even if there should be some. If I switch back to image 1, I don't see any annotations either. 

I have to turn off the "display/edit" mode and back on to see the annotations again.

![anno_disappear](https://cloud.githubusercontent.com/assets/86015/18179863/5b4d5390-7052-11e6-8e8c-a51623551038.gif)

**Comment by radpet** [comment]
@gigamorph are there any exceptions in the console? I suppose that there is something like this:

> Uncaught event displayOn inappropriate in current state pointer

**Comment by gigamorph** [comment]
@radpet Yes, see it.

**Comment by gigamorph** [comment]
The fix in #1104 doesn't seem to take into account the case where new annotations will be loaded "asynchronously". `displayOn` should be called after the the annotations are ready. Otherwise `this.list` in the draw tool will always be empty.

**Comment by rsinghal** [comment]
That bit of code is simply to re-set the state and UI of the various annotation tools when a user switches to another image within a canvas.  Actual annotations that are loaded use other events and populate other parts of the application through those events.

**Comment by jbaiter** [comment]
I can reproduce this bug in my end, although there are no messages on the console. I managed to track down the cause of the bug on my end: `OsdRegionDrawTool.render()` is called *before* `AnnotationsLayer.updateRenderer`, which causes the `list` attribute on the draw tool to be empty, and hence no annotations are displayed. There is a commented-out call to `this.modeSwitch` in the `updateRenderer` function, maybe this has something to do with it?
