### ISSUE TITLE
Annotation figure can be selected when not in edit mode

### ISSUE THREAD

**Issue by ViktorRibchev** [ProjectMirador/mirador#1110]
Please see: 
[Mirador 2 select.zip](https://github.com/IIIF/mirador/files/463379/Mirador.2.select.zip)

A figure can be selected when not in edit mode when the figure is next to a border of the canvas.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
