### ISSUE TITLE
Synchronise gh-pages repo with this repo

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1115]
The gh-pages repo is not stored as the gh-pages branch of this repo. Instead it is kept at https://github.com/IIIF/mirador.iiif.io. This is bad because we have made local edits directly to the generated code of the gh-pages branch in the main mirador repository.

This means that edits to the generating code will overwrite local edits to the generated code here if the new static site is copied over this one. As the newer tutorial demos and demo object updates are here in the mirador repo, we can't edit stylesheets, for instance, to handle the gitbook, in a reasonable way in the https://github.com/IIIF/mirador.iiif.io.

**Comment by bencomp** [comment]
The referred repository no longer exists. Does that mean this issue is solved?

**Comment by mejackreed** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets. This issue does seem to be resolved.
