### ISSUE TITLE
ManifestListItem member variables need documentation

### ISSUE THREAD

**Issue by markmatney** [ProjectMirador/mirador#1124]
I'm having trouble understanding some of the member variables in ManifestListItem (https://github.com/ProjectMirador/mirador/blob/release2.1/js/src/viewer/manifestListItem.js#L12) - what they are, and particularly how they are used in ManifestListItem.updateDisplay (https://github.com/ProjectMirador/mirador/blob/release2.1/js/src/viewer/manifestListItem.js#L182). Wondering if someone can give a description of `resultsWidth`, `maxPreviewImagesWidth`, `repoWidth`, `metadataWidth`, `margin`, `remainingWidth`, `imagesTotalWidth`. It would be good to have comments of this info in the source.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
