### ISSUE TITLE
Official integration API

### ISSUE THREAD

**Issue by radpet** [ProjectMirador/mirador#1125]
Hello,
 I suppose that a lot of organisations that use Mirador make use of some of its events to communicate with it. Do you plan to add official API which will be kept up to date with every release?

**Comment by gigamorph** [comment]
I second that, along with a plugin interface (if you meant the event system only. e.g., annotation editor, besides annotation endpoint is now sort-of pluggable but the interface is not well defined.)

**Comment by radpet** [comment]
@gigamorph Well there is a sort of event api for integrating external annotation editor, but I suppose we should refactor it with more meaningful and structured events and/or provide interface and plugable component

**Comment by lunactic** [comment]
This would be greatly appreciated.

I would love to write a plug-in at one point that could feed results from automatic methods to display them in Mirador (e.g. TextLine extraction).
But if there would be a stable API for doing that, would be of great help.

**Comment by aeschylus** [comment]
We put in a good amount of work on this in the last documentation sprint, but there's still a bit to go. I'll be adding it to the docs page in the next few days.

Thanks for the feedback all!

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
