### ISSUE TITLE
Problems with annotationEndpoint

### ISSUE THREAD

**Issue by radpet** [ProjectMirador/mirador#1126]
Does anybody use Mirador with annotation endpoint different from the local storage? It seems to me that when used with simpleASEndpoint or any other that loads the annotations asynchronous there are problems with the annotations rendering. What I found is that it renders the shapes before it loads the new annotations list.

**Comment by gigamorph** [comment]
Yes, I use a different one that uses asynchronous calls and I had commented about it at https://github.com/ProjectMirador/mirador/issues/1103 .

**Comment by radpet** [comment]
@rsinghal take a look at the commits ahead in https://github.com/SirmaITT/mirador/tree/feature/release2.1, I suppose that you have deleted those lines from the official 2.1 (this is kind of workaround it is not fixing the problem in its root)

**Comment by rsinghal** [comment]
Take a look at https://github.com/ProjectMirador/mirador/tree/2.1.1.  @gigamorph I will also look into #1103 again since I was doing all of my testing against the local storage endpoint, which completes actions much faster than an endpoint that requires network calls.

**Comment by beaudet** [comment]
@radpet can you clarify here?  It sounds like you introduced a workaround for this that was removed from the 2.1 official release.  Is that accurate?  Would putting those missing lines of code back into the 2.1 release fix this issue?

**Comment by radpet** [comment]
@beaudet  @rsinghal  @aeschylus  I think I have merged a proper fix inside 2.1.2 :)

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
