### ISSUE TITLE
Can draw figures while in annotation edit mode and pointer is selected

### ISSUE THREAD

**Issue by ViktorRibchev** [ProjectMirador/mirador#1128]
Please see: [annotations edit mode.zip](https://github.com/ProjectMirador/mirador/files/481761/annotations.edit.mode.zip)

**Comment by versae** [comment]
One option could be to disable the pointer icon when in edit mode.

**Comment by csbailey5t** [comment]
That seems like it would work, but from a user interaction perspective, it might seem strange, as we often thing of clicking on a pointer to be able to drag and move existing shapes. You can do that while rectangle is selected, but it intuitively makes sense with pointer. 

If we disabled or grayed out pointer, we might need to consider some good tooltips to explain interactions.

**Comment by versae** [comment]
Curiously enough, when in edit mode you drag or change the size of an annotation the pointer behavior is back, regardless of the annotation tool selected.
