### ISSUE TITLE
Image manipulation settings are preserved between next/previous image

### ISSUE THREAD

**Issue by regisrob** [ProjectMirador/mirador#1130]
... without being applied to the current image.

This issue forces the user to reset the settings each time he opens the next/previous image. Moreover it causes a bug on the buttons state (e.g. Invert or Grayscale), where the active/inactive states are inverted

**Comment by aeschylus** [comment]
Is this happening consistently or intermittently, and which browser are you seeing this behaviour in?

Thanks for the catch.

**Comment by aeschylus** [comment]
Is this happening consistently or intermittently, and which browser are you seeing this behaviour in?

Thanks for the catch.

**Comment by regisrob** [comment]
Actually the states are not inverted, but when you toggle an image to grayscale and then you switch to the next or previous image, the corresponding button is still in active state and you have to click twice to apply the same grayscale filter.

Another related (?) bug:
- set contrast to 200% on an image
- click next or previous button
- apply any filter to the image, e.g Invert colors
=> the 200% contrast is applied too

(tested tonight on Chromium 51 and Firefox 48.0 on Ubuntu 14.04 ; will test again tomorrow on Mac OS 10.11)

**Comment by regisrob** [comment]
Tested again today on Chrome 53.0.2785.116 (Mac OS 10.11.5): I can observe the same bugs as in the previous comment.
