### ISSUE TITLE
Multiple regions are a single SVG, should be multiple targets

### ISSUE THREAD

**Issue by azaroth42** [ProjectMirador/mirador#1138]
Instead of using multiple targets, Mirador creates annotations with a single region that spans non contiguous areas.  
Multiple target areas is covered:
  https://www.w3.org/TR/annotation-model/#cardinality-of-bodies-and-targets
or, in the OA spec we currently reference:
  http://openannotation.org/spec/core/core.html#MultipleBodyTarget

Note also the explicit warning against using <g> for multiple regions in the Open Annotation SvgSelector specification:
  http://openannotation.org/spec/core/specific.html#SvgSelector

**Comment by rsinghal** [comment]
@azaroth42 Would the following make sense?
```
"on" : {
    "@type" : "oa:SpecificResource",
    "full" : "http://dams.llgc.org.uk/iiif/2.0/4574752/canvas/4574755.json",
    "selector" : {
      "@type": "oa:Choice",
      "default": {
        "@type" : "oa:Composite",
        "item": {
          "@type" : "oa:FragmentSelector",
          "value" : "xywh=2218,3217,371,78"
        },
        "item": {
          "@type" : "oa:FragmentSelector",
          "value" : "xywh=100,400,200,50"
        }        
      },
     "item": {
        "@type" : "oa:Composite",
        "item" : {
          "@type":"oa:SvgSelector",
          "value": "<svg xmlns=\"...\"><path d=\"...\"/></svg>"
        },
        "item" : {
          "@type":"oa:SvgSelector",
          "value": "<svg xmlns=\"...\"><path d=\"...\"/></svg>"
        }        
      }
    }
  }
```

**Comment by azaroth42** [comment]
Currently, yes, but Composite and List go away in the Web Annotation model to become simpler, so it would introduce some technical debt to then fix them in the not too distant future.  If you went straight to multiple targets, you'd solve multiple issues at once.

**Comment by rsinghal** [comment]
I'm not sure I understand how you would want that modeled - can you provide a short JSON snippet?

**Comment by azaroth42** [comment]
Basically, a list for the body or target (`on`) is an AND, and the list for selectors is OR.

```
"on": [
  {
    "@type": "oa:SpecificResource",
    "full": "..."
    "selector": [
      {"@type": "oa:FragmentSelector",
        "value": "xywh=0,0,100,100"}, // OR
      {"@type": "oa:SvgSelector",
        "value": "<svg> ...</svg>"}
    ]
  }, // AND 
  {
    "@type": "oa:SpecificResource",
    "full": "..."
    "selector": [
      {"@type": "oa:FragmentSelector",
        "value": "xywh=5000,1000,250,600"},
      {"@type": "oa:SvgSelector", // OR
        "value": "<svg> ...</svg>"}
    ]
  }
]
```

Selects two regions, each of which can be described by two different selectors.  At the same time it also allows the two different regions to be on different canvases when full (the target) is a different URI :)

**Comment by rsinghal** [comment]
Ok, that makes sense.  But in a previous comment, https://github.com/ProjectMirador/mirador/issues/1137#issuecomment-255325516, you indicated that we can't use an array for the `selector` for OA.  We have to use `oa:Choice` instead.

**Comment by azaroth42** [comment]
Right the above is the web annotation pattern ... hence...

> It would introduce some technical debt to then fix them in the not too distant future. If you went straight to multiple targets, you'd solve multiple issues at once.

You could still do multiple targets, and use `oa:Choice` for the selectors though, which would fit with OA and make for less change down the line.

```
"on": [
  {
    "@type": "oa:SpecificResource",
    "full": "..."
    "selector": {
       "@type": "oa:Choice",
       "default": 
          {"@type": "oa:FragmentSelector",
            "value": "xywh=0,0,100,100"},  // OR
      "item":   
          {"@type": "oa:SvgSelector",
            "value": "<svg> ...</svg>"}
    }
  }, // AND 
  {
    "@type": "oa:SpecificResource",
    "full": "..."
    "selector": ...
  }
]
```

**Comment by rsinghal** [comment]
One last question - would it be wrong to use an array for `on` even if it contains only one target?  Or should `on` switch to an object in that case?

**Comment by azaroth42** [comment]
It wouldn't be wrong, just either more complex (unnecessary singleton array) or more consistent (always an array, even of only one), depending on your point of view :)
