### ISSUE TITLE
viewingHint="top" breaks table of contents in Mirador 2.1

### ISSUE THREAD

**Issue by higginsr** [ProjectMirador/mirador#1140]
Using Mirador 2.1 to view manifests that had worked in 2.0, those with tables of contents only displayed the top level "Table of contents" for the whole book and did not load or display the rest of the toc.

The table of contents worked again if "viewingHint":"top", was deleted from the top level range declaration.
So replacing
```
    "structures": [
    {
      "canvases": [
"http://iiif.durham.ac.uk/manifests/cat/hunter/DCL_Hunter_100/canvas/p1",
"http://iiif.durham.ac.uk/manifests/cat/hunter/DCL_Hunter_100/canvas/p2",
  .......
"http://iiif.durham.ac.uk/manifests/cat/hunter/DCL_Hunter_100/canvas/p254",
"http://iiif.durham.ac.uk/manifests/cat/hunter/DCL_Hunter_100/canvas/p255"
      ],
      "@id": "http://iiif.durham.ac.uk/manifests/cat/hunter/DCL_Hunter_100/range/r1",
      "@type": "sc:Range",
      "viewingHint":"top",
      "label": "Table of Contents"
    },
        {
      "canvases": [
        "http://iiif.durham.ac.uk/manifests/cat/hunter/DCL_Hunter_100/canvas/p1",
     ..........
```

which had worked in Mirador 2, with
```
    "structures": [
    {
      "canvases": [
"http://iiif.durham.ac.uk/manifests/cat/hunter/DCL_Hunter_100/canvas/p1",
"http://iiif.durham.ac.uk/manifests/cat/hunter/DCL_Hunter_100/canvas/p2",
  .......
"http://iiif.durham.ac.uk/manifests/cat/hunter/DCL_Hunter_100/canvas/p254",
"http://iiif.durham.ac.uk/manifests/cat/hunter/DCL_Hunter_100/canvas/p255"
      ],
      "@id": "http://iiif.durham.ac.uk/manifests/cat/hunter/DCL_Hunter_100/range/r1",
      "@type": "sc:Range",
      "label": "Table of Contents"
    },
        {
      "canvases": [
        "http://iiif.durham.ac.uk/manifests/cat/hunter/DCL_Hunter_100/canvas/p1",
     ..........
```
works in Mirador 2.1.
It might just be that viewingHint has no purpose here, but the specification mentions it as used in this context.

**Comment by rsinghal** [comment]
@higginsr Can you post the link to the full manifest?

**Comment by higginsr** [comment]
http://iiif.durham.ac.uk/manifests/cat/hunter/DCL_Hunter_100.old.json
 is the old version that worked with 2.0 but not with 2.1
http://iiif.durham.ac.uk/manifests/cat/hunter/DCL_Hunter_100.json
is the same apart from removing the viewingHint line, doing which makes the toc work in 2.1
Loading both into http://projectmirador.org/demo/, only the second one has a full table of contents

**Comment by aeschylus** [comment]
From where I am, your manifests are behind a firewall. Can you open these up so we can test with them?

On the face of it, of the five cases we described, this seems like the one we vowed to ignore:

Pres. API 2.0 Range Cases
	1.	Structures has one viewingHint top
	⁃assume it is a root
	⁃	recurse to rebuild the tree
	⁃	Ignore the possible existence of other roots. There may be other root nodes, but we have no way to know they are root nodes since ‘within’ has become optional
	2.	Structures has multiple viewHint top (Not really different from case1)
	⁃	assume they are all roots
	⁃	recurse each to build trees
	⁃	recurse to rebuild the tree
	3.	No viewingHint top - no ranges have any child ranges
	⁃	take the structures array as the dummy root
	⁃	display them all
	4.	No viewingHint top - some have children, some don’t
	⁃	there is no way to know which are roots and which aren’t
	⁃	as a stop gap, assume the first range is the root
	⁃	recurse to rebuild the tree

**Comment by higginsr** [comment]
Sorry about that; it isn't a firewall issue. There was a power outage over in University IT which triggered a rebuild of the server which clearly hasn't quite worked and is giving a misleading security error message ...

I don't know if viewingHint top ever did anything. I have deleted it from the manifests concerned and they now work with 2.1, so it may be that it is just something to flag up. If you upgrade and your table of contents stops working, check for viewingHint top and try deleting it. I don't know if it needs any fixing or just recording as a possible issue?

**Comment by rsinghal** [comment]
@higginsr The issue is that the manifest has a 2.0 `@context`, but you are using a 1.0 range.  The `within` property is used in 1.0 (http://iiif.io/api/metadata/1.0/#structure-range), while 2.0 uses `ranges` (http://iiif.io/api/metadata/1.0/#structure-range).  

So the code sees the `@context` and attempts to parse it as a 2.0 range. `top` is meaningful, so if we see that, we act accordingly, but the rest of the Range doesn't follow the correct pattern, which is why the Table of Contents isn't displaying anything other than the `top` range.
