### ISSUE TITLE
Cannot mouse-select text in Chrome

### ISSUE THREAD

**Issue by gigamorph** [ProjectMirador/mirador#1143]
When index.html is first loaded with the manifest list view, you can easily select a text with your mouse (see "object" is highlighted with blue background in the following screenshot).

<img width="749" alt="mirador1" src="https://cloud.githubusercontent.com/assets/86015/19125705/15297384-8b06-11e6-8e5c-59838aa81b47.png">

If you load a canvas by selecting a thumbnail, it becomes harder to select a "partial" text. In the screenshot below, "Plans" is highlighted, but I did it by double clicking on the word, not by clicking and dragging over the selection, because at this point dragging to highlight is highly unresponsive or just impossible.

<img width="753" alt="mirador2" src="https://cloud.githubusercontent.com/assets/86015/19125711/18cda44c-8b06-11e6-9663-56f7ded7f494.png">

If you go back to the manifest list (see first screenshot) by choosing the "Replace Object" menu, you can see that texts there are (near) impossible to select too, while it was easy when the view was first loaded.

This currently happens with the Chrome browser only AFAIK -- on my Mac, and I also checked for Windows on Sauce Labs. On Firefox and Safari (and a very old version of Chrome on Linux - again, Sauce Labs), for example, I don't see the problem at all. 

Being able to select arbitrary text is important for me both for plain copy and pasting, and also for implement selection based functionalities (search, dictionary reference, etc.).

**Comment by aeschylus** [comment]
This seems likely due to various mousemove listeners on the window. Thanks for the report. This clearly needs to be fixed soon.

**Comment by mejackreed** [comment]
I've narrowed this down to `mousemove` events.
