### ISSUE TITLE
IE: Some image manipulation options are missing from menu

### ISSUE THREAD

**Issue by ViktorRibchev** [ProjectMirador/mirador#1158]
IE11 version: 11.321.14393.0. 
Win 10 version: 1607 (OS Build 14393.321) 
Image manipulation options are missing from menu: 
![mirador ie](https://cloud.githubusercontent.com/assets/17718464/19758842/ee1fba4e-9c32-11e6-9a87-530e23a7a4a0.png)

**Comment by rsinghal** [comment]
The CSS filter properties do not work in IE, so they have been disabled for those browsers.  See #1072
