### ISSUE TITLE
Border/Fill color drop-downs go out of canvas when working in lower resolution

### ISSUE THREAD

**Issue by ViktorRibchev** [ProjectMirador/mirador#1160]
Border/Fill color drop-downs go out of canvas when working in lower resolution. 
![mirador1](https://cloud.githubusercontent.com/assets/17718464/19795886/8952c640-9ce8-11e6-8f99-340c6d9bbd96.png)
![mirador2](https://cloud.githubusercontent.com/assets/17718464/19795887/8958ce50-9ce8-11e6-8f73-4e75ec60d0f2.png)

Browser resolution: 1280x1024 and lower.

**Comment by mejackreed** [comment]
Would a right justify satisfy this?
![screen shot 2016-11-07 at 10 42 41 am](https://cloud.githubusercontent.com/assets/1656824/20063948/f2e7a77e-a4d6-11e6-99bd-e8cab2e81c80.png)

**Comment by ViktorRibchev** [comment]
@mejackreed Right justify will solve the problem

**Comment by mejackreed** [comment]
Spectrum.js seems to apply inline styles to position this element. Are there patterns that mirador uses to override out of the box plugin functionality? 

Or is `!important` ok to use in this context?

**Comment by versae** [comment]
Is it OK to fix the `left` property, or do we want the widget to be shown aligned to the lower-right corner of the control buttons?
```css
.mirador-osd-color-picker .sp-container {
    left: 133px !important;
```
