### ISSUE TITLE
Mirador assumes an image service available via canvas.thumbnail supports arbitrary /w,/ requests

### ISSUE THREAD

**Issue by tomcrane** [ProjectMirador/mirador#1170]
Related to #872

I've been experimenting with optimising thumbnails, and including enough info in the manifest for a client to request lots of fast thumbs without having to dereference an info.json.

Each canvas has a thumbnail property in the manifest like this:

```javascript
"thumbnail": {
  "@id": "https://dlcs.io/thumbs/wellcome/1/79fbc149-42b9-43d2-979d-c66c435073e4/full/64,100/0/default.jpg",
  "@type": "dctypes:Image",
  "service": {
    "@context": "http://iiif.io/api/image/2/context.json",
    "@id": "https://dlcs.io/thumbs/wellcome/1/79fbc149-42b9-43d2-979d-c66c435073e4",
    "protocol": "http://iiif.io/api/image",
    "height": 1024,
    "width": 651,
    "sizes": [
      {
        "width": 64, "height": 100
      },
      {
        "width": 127, "height": 200
      },
      {
        "width": 254, "height": 400
      },
      {
        "width": 651, "height": 1024
      }
    ],
    "profile": [
      "http://iiif.io/api/image/2/level0.json"
    ]
  }
}
```

from http://library-uat.wellcomelibrary.org/iiif/b28047345/manifest

This is a level 0 service with only these four sizes available, but enough of the image information inline in the manifest for a client to use straight away. This is telling a client "I *only* have these sizes available for thumbs, I really want you to use them!"

Mirador identifies the service - but doesn't recognise it as a level 0 service, so starts asking for thumbs from it that are not available. It can't just do this:

`thumbnailUrl = $.Iiif.makeUriWithWidth(service['@id'], width, version);`

(https://github.com/ProjectMirador/mirador/blob/master/js/src/utils/utils.js#L43)

...instead it needs to decide whether it can use one of the sizes available, and if so construct an Image API request to the thumb service for it, and if not, use the main image service. Identifying that it's level 0 and using the main image is likely to be the quickest solution if client-side scaling would cause problems.

I'd like to release that inline thumbnail service to the live environment for Wellcome, but I don't want to do that if it means a Wellcome manifest has broken thumbs when viewed in Mirador!

**Comment by beaudet** [comment]
At the risk of taking this a little off-track:

Thumbnails work well for the vast majority of use cases where a manifest only has a single image resource on it and is fairly straightforward layout-wise, but I'm wondering whether depending on the server to generate thumbnails is going to get us in trouble in the future.  It probably wouldn't be feasible for a server to generate an accurate thumbnail of a complicated canvas - at least not without image servers supporting the Presentation API, so perhaps the client should just render the canvas to produce the thumbnails?

Related to server-side thumbnail generation, there might also be an opportunity to specify the data representing the thumbnails into the manifest itself as base64 encoded data.  IIIF Clients could just in-line that image data directly without requiring a subsequent HTTP request.

**Comment by tomcrane** [comment]
These are two use cases on either side of my one I think.

1) If you can't decide on a single image thumb for the canvas because it has multiple complex image annos, then you could just decline to provide canvas.thumbnail and let the client have a go if it can. A super smart client will render the default state of the canvas (image choice etc) as the thumbnail. Other clients would jump to the first image annotation, look for a service, and make a thumb from that.

2) (me) I've got a sensible single thumbnail for the canvas (even when I sometimes have multiple image annos available), and I've got it in a number of sizes, I want to offer the range of sizes and I promise they will all be fast (compared with an arbitrary size request) because they are precomputed and/or cached. 

3) base64 inline all the thumbnails into the manifest (as another service) - the manifest is (a lot) bigger, but that's it as far as HTTP requests go - you're done! You can render a whole field of thumbs from the single manifest request. The manifest would start getting very large if you had a choice of sizes and/or large thumbs.

Feels like 2) is easier than 1 or 3 and more of a sweet spot for now. But both 1) and 3) might have specialist uses.
