### ISSUE TITLE
Links in annotation pop-up screen are opened in the same tab of the browser

### ISSUE THREAD

**Issue by ViktorRibchev** [ProjectMirador/mirador#1199]
If you have an annotation with a link in it - let's say google.com. 
When you click on the link then the browser attempts to open it in the same tab. In this case it leads to 404 page. 

Would be nice if the link is opened in a new tab of the browser or new window.

**Comment by radpet** [comment]
@aeschylus Should I send a pull request? Do you like the idea to have the links opened in new tab?

**Comment by aeschylus** [comment]
@radpet Certainly if you have a moment. This is a quick fix that will save a lot of pain for unsuspecting users.
