### ISSUE TITLE
Create annotation iframe bug 

### ISSUE THREAD

**Issue by radpet** [ProjectMirador/mirador#1204]
In CS space project we are using mirador inside iframe and we found the following issue:

Start drawing annotation
Drop the cursor out of the iframe
Then when come back to the iframe a new shape is created and the old one (the initial) is drawn on the canvas but it is not active and persisted after save

It seems the mouse up event is not fired properly. Any ideas for fix?

I recorded a video representing the issue :)

[mouseup_bug_iframe.ogv.zip](https://github.com/ProjectMirador/mirador/files/600578/mouseup_bug_iframe.ogv.zip)

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
