### ISSUE TITLE
Cannot annotate when more than one slot is inside annotation mode

### ISSUE THREAD

**Issue by radpet** [ProjectMirador/mirador#1208]
This issue is not presented in 2.1.1 so it seems to be a regression. 

The steps to reproduce are:

Open a new slot (or test inside http://projectmirador.org/demo/ {by default more than 1 slot} )
Open annotation menu on slot 1
Open annotation menu on slot 2

Click a shape tool on slot 1
Click a shape tool on slot 2
Start drawing on slot 1

Result:
The shape seems to be enlarged and the annotation popup is inside slot 2
After save the shape disappears

If you need any screens tell me :)

**Comment by PpyMohan** [comment]
Hi,
Same problem i am facing in openseadragon with paperjs annotations on two canvas view.
can you tell how to clear this problem.
