### ISSUE TITLE
http manifest urls - load unsafe content

### ISSUE THREAD

**Issue by bcail** [ProjectMirador/mirador#1210]
If mirador is served as https, Chrome won't let you pull an http manifest url onto mirador for viewing (doesn't allow unsafe content, and if you click to allow the unsafe content, it reloads the page so you lose the content you pulled over). Any thoughts/solutions to this issue?

**Comment by rsinghal** [comment]
@bcail In general, browsers are discouraging this (see: https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content). This is not something that can be fixed within Mirador, as it is a more general problem that browsers are enforcing.
