### ISSUE TITLE
osd-svg-rectangle is not correctly parsing xywh fragment selectors to paperjs segments

### ISSUE THREAD

**Issue by rsinghal** [ProjectMirador/mirador#1245]
@radpet @beaudet

http://dms-data.stanford.edu/data/manifests/Stanford/ege1/manifest.json has a series of annotation lists that are in `xywh` format.  However, in [`_createSegments`](https://github.com/ProjectMirador/mirador/blob/2.1.3/js/src/annotations/osd-svg-rectangle.js#L41) in `osd-svg-rectangle`, the original x and y points are not the resulting points used when creating the segments.  

The first screen shot is what the rectangles look like with a version of Mirador before paperjs (the first canvas in the manifest).
![screen shot 2017-02-02 at 2 27 24 pm](https://cloud.githubusercontent.com/assets/2371632/22564855/0154f476-e954-11e6-8dd8-79205f98d745.png)

The second screen shot is what the rectangles look like in the 2.1.3 branch of Mirador using paperjs.  All of their start points are shifted up and to the left and are now overlapping, which they shouldn't be doing.
![screen shot 2017-02-02 at 2 28 50 pm](https://cloud.githubusercontent.com/assets/2371632/22564882/26863c3c-e954-11e6-85e8-bbf5d0bf33d6.png)

**Comment by radpet** [comment]
That is good catch thanks, it is caused by the point arithmetic and maybe by how xywh format is parsed. Anyway I found that if you zoom enough and reset the annotations there is little-to-no-space so the point arithmetic should be more accurate in order to draw the rectangles with the correct coordinates.
