### ISSUE TITLE
Unable to change stroke width of annotation shapes

### ISSUE THREAD

**Issue by tangfucius** [ProjectMirador/mirador#1247]
This is probably not a bug - I am not quite familiar with how paper.js and Mirador work together. Right now all annotated shapes in Mirador has a path thickness of 1 px once drawing is complete, making it hard to see, so I want to adjust its thickness. However, tweaking the strokeWidth attributes don't help - no matter what I do (e.g. changing to `shape.strokeWidth = 20` in polygon's `createShape`), I am always left with the 1px line after I close my shape.

**Comment by radpet** [comment]
try changing https://github.com/ProjectMirador/mirador/blob/2.1.3/js/src/annotations/osd-svg-polygon.js#L26 to higher value mb this value should come from the settings

**Comment by tangfucius** [comment]
I tried changing it but it only has effect while I am creating the polygon. Once I am done closing the shape and saving it, the polygon immediately turns into width of 1px.

**Comment by radpet** [comment]
@tangfucius My mistake, you should change it in one more place, because the replace function is called after each drawn shape 
https://github.com/ProjectMirador/mirador/blob/2.1.3/js/src/annotations/osd-svg-overlay.js#L794

We should change those values to come from one source

**Comment by tangfucius** [comment]
Yep, that does it! Thanks @radpet!
