### ISSUE TITLE
Configure TinyMCE to support non-Latin (ie. Hebrew and Greek, possibly Arabic) alphabets

### ISSUE THREAD

**Issue by blalbrit** [ProjectMirador/mirador#1252]

**Comment by jkeck** [comment]
Is this actually solved by #1267?  It seems like that allows for both Latin and Arabic alphabets.  Not sure if there has been a specific encoding problem specified.

**Comment by mejackreed** [comment]
This ticket should be closed. TinyMCE doesn't need any configuration changes to support UTF-8 characters and additional alphabets
