### ISSUE TITLE
Annotate across pages

### ISSUE THREAD

**Issue by blalbrit** [ProjectMirador/mirador#1253]
Story:

As a curator, I want to bring up two separate pages in Mirador, and create an annotation that addresses targets on both pages.

**Comment by beaudet** [comment]
FYI - I asked @azaroth42 about standards implications for this and he says: "This is just multiple targets, just with different resources rather than different parts of the same resource."

**Comment by rsinghal** [comment]
The changes in 2.1.3 handle this from a modeling perspective, but Mirador doesn't allow for drawing on multiple canvases.

**Comment by blalbrit** [comment]
@rsinghal - do you mean that ^^ from a perspective of "doesn't currently allow, but could with development" or "really doesn't allow"?

**Comment by rsinghal** [comment]
It should be technically feasible, though it would require rethinking how to have functionality in Mirador that crosses multiple slots.  Mirador doesn't currently allow for that so it shouldn't be done without really thinking through the architecture so it can be added cleanly without negatively impacting other aspects of the app.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
