### ISSUE TITLE
Add mirror control to image manipulation tool bar

### ISSUE THREAD

**Issue by blalbrit** [ProjectMirador/mirador#1254]
Desire is to be able to show mirror image via an image manipulation tool

**Comment by mejackreed** [comment]
@blalbrit any thoughts on what icon should be used?

**Comment by blalbrit** [comment]
@mejackreed - are we restricted to a certain set of icons, or is anything fair game? If the latter, then:
https://cdn.iconscout.com/public/images/icon/premium/png-512/mirror-horizontally-rotate-design-graphic-tool-3e43ea204bdf097f-512x512.png 
or
https://cdn4.iconfinder.com/data/icons/unigrid-design/60/022_flip_reflect_horizontal_mirror_tool-512.png

seem to fit the purpose.

B

**Comment by mejackreed** [comment]
Ideally we are restricted to https://material.io/icons/

Adding a new icon font to Mirador for one icon (we already have two) feels problematic.

@rsinghal suggested these: (I like the first one)
![screen shot 2017-02-28 at 8 14 01 am](https://cloud.githubusercontent.com/assets/1656824/23406659/0631a77a-fd8e-11e6-9229-d270a2155bec.png)
![screen shot 2017-02-28 at 8 13 52 am](https://cloud.githubusercontent.com/assets/1656824/23406660/063314ca-fd8e-11e6-90f6-95ce0295daaa.png)

**Comment by mejackreed** [comment]
We also have these to choose from: http://fontawesome.io/icons/

**Comment by rsinghal** [comment]
https://material.io/icons/#ic_flip could also be an option

**Comment by blalbrit** [comment]
My vote is for the first one Rashmi suggested to you. https://cdn4.iconfinder.com/data/icons/unigrid-design/60/022_flip_reflect_horizontal_mirror_tool-512.png
