### ISSUE TITLE
Implement support for image choice and detail images

### ISSUE THREAD

**Issue by blalbrit** [ProjectMirador/mirador#1257]
See http://bit.ly/2hNsJWb for details.

**Comment by aeschylus** [comment]
I'm assuming this is a stub and going to attach lots of tickets to this.

#1280

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets. Mirador 3's implementation of layers can be tested out at: https://mirador-dev.netlify.app/__tests__/integration/mirador/layers.html
