### ISSUE TITLE
Snap-to-grid functionality for adjusting annotation regions of interest

### ISSUE THREAD

**Issue by blalbrit** [ProjectMirador/mirador#1258]
the availability of a function like “snap to grid” for adjusting rectangles of transcribed texts and other annotations (in addition to free-form drawing)

**Comment by versae** [comment]
What the size of the grid should be? And should the grid be zoom agnostic? It seems like there is no builtin functionality for a "snap-to-grid" in Paper.js, and we might need to modify it.

**Comment by blalbrit** [comment]
Good questions - this is definitely in the backlog for now @versae - not a ready-to-work ticket.

**Comment by gigamorph** [comment]
I don't know whether the above description covers it but one thing which may be of great demand is the the ability to snap to horizontal and vertical lines when creating polygons so one can create polygons only with right angles to cover certain parts of a text.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
