### ISSUE TITLE
Support for controlled vocabulary tagging

### ISSUE THREAD

**Issue by blalbrit** [ProjectMirador/mirador#1259]
Within the annotation-creation box, for tags, support controlled vocabulary for:

- project-defined mandatory tags (annotation author, for instance)
- project-defined optional tags
- freely-added tags

**Comment by beaudet** [comment]
FYI - from @azaroth42 in response to a question I raised regarding controlled vocabulary support for tags in OA:

A tag is just a Body with the motivation “tagging”.  For a controlled vocab tag, see the example in: https://www.w3.org/TR/annotation-model/#purpose-for-external-web-resources

**Comment by blalbrit** [comment]
Thanks @beaudet . Just to clarify: for the purposes of this ticket, as motivated by the particular Vatican use-case, we are not talking about an external controlled vocabulary, but rather a project-specific controlled vocabulary with motivation "tagging". That is, the project team could build up a set of local controlled terms that would populate a drop-down list of available tags.

**Comment by csbailey5t** [comment]
@blalbrit Can you describe the use case for controlled, project specific tagging? We're trying to work through how these tags would be used to understand what we would need to think about for implementation.

**Comment by azaroth42** [comment]
External or internal wouldn't affect the model -- the semantic tag (to use the OA terminology) is just a URI that could be controlled by the project or by an "authority" organization just the same. The difference would be "freely-added tags" if they are supposed to be text rather than an identifier.

**Comment by versae** [comment]
It is not entirely clear what a mandatory tag is. It looks like it should behave like a key-value pair, in which case it seems like a different feature. Furthermore, we haven't been able to find how to implement key-value tags as part of the OA spec.

The current PR address project-defined optional tags, and freely-added tags.

**Comment by blalbrit** [comment]
@versae that will be fine - the "mandatory" aspect is project-defined, not app-defined. The mandatoriness will be determined by the user.
