### ISSUE TITLE
Support enlarging the annotation-creation area

### ISSUE THREAD

**Issue by blalbrit** [ProjectMirador/mirador#1261]
For very long annotations, the current size of the TinyMCE creation box is inadequate. Looking for support for dynamic re-sizing of the text area of that box.

**Comment by blalbrit** [comment]
Sept 2017 - renewed request from the Vatican curatorial team for this feature.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
