### ISSUE TITLE
Release 2.1.3 before establishing 2.2 working branch as default for current work cycle. 

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1265]
Hey @rsinghal, 

What remains for the 2.1.3 release? I'd like to establish a 2.2 (or maybe 2.1.4 depending on the severity of feature changes for the upcoming sprints) as our default branch for upcoming features.

We can call it done and move on, but I want to make sure we get your changes in when they are ready.

**Comment by rsinghal** [comment]
Just need to test the changes I made to `2.1.3-patch` with another developer at Harvard and then it should be good to go.
