### ISSUE TITLE
annotation tools not working in latest version of Chrome on OS X

### ISSUE THREAD

**Issue by inlutero** [ProjectMirador/mirador#1272]
Hi, We've (@mrwho ) been testing out an updated version Mirador and we are having issues with it working in Chrome Version 56.0.2924.87 (64-bit) in OS X. Seems to work fine with Firefox. I have tested our own site as well as the Mirador demo.

http://digitalcollections.frick.org/digico/compare.html#3fdd6967-640e-4b69-88d5-a80feb3b5318

http://projectmirador.org/demo/

**Comment by csbailey5t** [comment]
@inlutero Can you be more precise about what is not working?

**Comment by rsinghal** [comment]
I believe he is referring to annotating when multiple slots are broken.  Related to #1208
