### ISSUE TITLE
annotation UX issue when deleting last shape

### ISSUE THREAD

**Issue by beaudet** [ProjectMirador/mirador#1273]
I think there's a UX issue when the last annotation shape for an annotation is deleted.  I think at that point, there should be a dialog requesting whether the entire annotation should be deleted or whether the user wishes to retain it, possibly even creating more shapes for it, or possibly leaving it to apply to the page.  Furthermore, it's too easy to hit the "cancel" button in the annotation editor at this point which then restores all of the deleted shapes.  The current state isn't a bug, per se, but it might make sense to adjust the UX a bit to account for the different scenarios.  Perhaps the last shape simply shouldn't be able to be deleted?  This would require deletion and recreation of an annotation with shapes in order to promote it to a canvas level annotation, but how many times does that happen?  Any other quick fix ideas?

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
