### ISSUE TITLE
Define a behaviour for the layers sidebar that disables it when it cannot be used.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1281]
In the "overview" or "thumbnails" view, the layers tab doesn't make any sense. Therefore it should be grayed out or hidden, and the view will need to detect and respond to this change.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
