### ISSUE TITLE
Embedded div on a web page - Full screen Failed

### ISSUE THREAD

**Issue by jpadfield** [ProjectMirador/mirador#1282]
Hi, 

I have just tried the "Inside a div on same web page" example of an embedded viewer on the Getting Start page. It all seems to work well except that the Full Screen option does not quite work properly. The browser does swap to full screen but the viewer still appears as a smaller embedded window rather than expanding to fill the page.

There are probably a number of ways to adjust this, but I tried dropping the viewer inside another div, with the id "viewerholder" and adjusted the css for the two to be:

    #viewerholder {
      display: block;
      width: 90%;
      height: 600px;
      margin: 0px;
      position: relative;
    }
    #viewer {
      display: block;
      width: 100%;
      height: 100%;
      margin: 1em 5%;
      position: relative;
    }

The result looks the same and the "Full Screen" option actual expands the viewer to fill the screen.

Thanks

Joe

**Comment by gigamorph** [comment]
To make it embeddable in any "positioned" element and also resizable to fit the containing element, I found it best to do the following:

```
#viewer {
  display: block !important;
  position: absolute !important;
  width: 100%;
  top: 0;
  bottom: 0;
}

#viewer * {
  box-sizing: content-box; // To prevent Semantic UI or others from overriding * with "border-box".
}
```

**Comment by jpadfield** [comment]
Thanks I will have a look.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
