### ISSUE TITLE
Proposal: Move working default branch to `develop` to be more inline with git flow

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1288]
Without always knowing what the semantic version is in advance, moving the default branch to `develop` for PR's might help bring in multiple features to a branch at a given time. This was proposed on the mirador slack channel, but I wanted to raise it as an issue so that others might see it.

**Comment by rsinghal** [comment]
I like this.  Also means we don't have to keep setting the new branch to be protected each time we create a new one.

**Comment by csbailey5t** [comment]
This is in progress, but we need to update the docs to clarify the new structure, i.e., that the default branch that PRs should be made from is `develop`
