### ISSUE TITLE
Localisation token for table of contents not being rendered correctly.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1291]
<img width="1440" alt="screen shot 2017-02-25 at 22 20 03" src="https://cloud.githubusercontent.com/assets/145874/23337619/d223514a-fba8-11e6-984f-5570bd24991b.png">

**Comment by morpheus-87** [comment]
I think, this issue has a relation to #1285, @aeschylus.

**Comment by mejackreed** [comment]
Potentially solved by: https://github.com/ProjectMirador/mirador/pull/1286 ?

**Comment by morpheus-87** [comment]
In my opinion, the issue is solved by #1286:

![screenshot-projectmirador org-2017-02-28-09-04-34](https://cloud.githubusercontent.com/assets/19190936/23396679/32c7ea18-fd95-11e6-9a71-001a6f6b7474.png)
