### ISSUE TITLE
TinyMCE edit dialogs don't stack properly in "fullscreen" view

### ISSUE THREAD

**Issue by c-alers** [ProjectMirador/mirador#1293]
I just re-tested this on the latest 2.2.0 clone:

- Open the annotation layer on a canvas 
- Set the canvas to "fullscreen"
- Create or Edit an annotation to open the TinyMCE dialog
- In TinyMCE, choose an option that triggers its own dialog (like insert/edit) image
 **The dialog does not appear**
- Close the annotation (doesn't matter if you choose to save or cancel it)
- Exit "fullscreen"
**The TinyMCE dialog is now visible**

The dialog becoming visible actually is dependent on how large the initial window is. In the case of using an iframe to embed, I have seen this result in the dialog being "off screen" and the transparent modal layer under it rendering all other controls for Mirador un-clickable. 

I haven't dove too deeply into the code myself, but this definitely looks like an issue with the TinyMCE dialog properly stacking above the layer used for "fullscreen" mode. Our general use case involves embedding which makes "fullscreen" editing an important feature for our authors.

**Comment by c-alers** [comment]
I did a bit more digging and have found the cause of the issue. The dialog for plugins like "image" open as a div directly under body which puts them outisde of the stack space of the fullscreen viewer. I found a workaround by resetting the z-index of the dialog after it's opened. But that only solved part of the issue. When the viewer is embedded, you can still loose the ability to use it when you minimize due to the edit dialogue being outside of the view frame window. I had to workaround that by adding a listener for the fullscreenchange event. 

While I have a working workaround for my client's need, this is something that definitely needs to be addressed more gracefully for FullScreen mode in general. I'm attaching the workaround editor that I'm using in case it helps. 
[nga-tinymce-annotation-editor.zip](https://github.com/ProjectMirador/mirador/files/809096/nga-tinymce-annotation-editor.zip)

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
