### ISSUE TITLE
Bug: Draw annotation in one window/slot to create an annotation in another

### ISSUE THREAD

**Issue by csbailey5t** [ProjectMirador/mirador#1298]
After opening two windows and entering into annotation mode in both, you can select the rectangle tool from the left window, draw on the canvas in the right window, and it creates an annotation on the canvas in the left window. 
![anno_bug](https://cloud.githubusercontent.com/assets/4672869/23439006/7041ae54-fdc9-11e6-8faf-24246ad23fbc.gif)

**Comment by aeschylus** [comment]
Wow.

**Comment by radpet** [comment]
https://github.com/ProjectMirador/mirador/issues/1208

**Comment by csbailey5t** [comment]
My guess is that several of the multiple window annotation errors are related. In this case, it seems that the global `paper` object is not being set to the correct `paperScope`. Several github issues and SO threads on this. 

http://stackoverflow.com/questions/16865863/paper-js-how-to-set-up-multiple-canvases-using-only-javascript

https://github.com/paperjs/paper.js/issues/677

**Comment by PpyMohan** [comment]
Have you got any solution for this issue??
