### ISSUE TITLE
Add additional line weights/thicknesses to Line Style drop-down on annotation creation

### ISSUE THREAD

**Issue by blalbrit** [ProjectMirador/mirador#1299]
Desire is to have access to thicker lines for annotation bounding boxes in addition to line, dashes, and dots-and-dashes

**Comment by jkeck** [comment]
Do we know which line thicknesses we want to include?  Should they be pixels?  `2px`, `3px`, ???

**Comment by drh-stanford** [comment]
Is it enough to have the default be thicker, and make it configurable? 

Or do you want a pulldown to choose thicknesses? If so, the annotation stroke width will need to persist on both creation and view so we'll need to save that information in the state.

**Comment by jkeck** [comment]
@drh-stanford my understanding is that the desire is to include additional options for thicker lines.

**Comment by drh-stanford** [comment]
So I took a brief look at this assuming we just need thin/normal/thick options and there's a number of places that need changes -- see https://gist.github.com/drh-stanford/7c7e50a205ed064cf466c11fbe002757 

```
	modified:   js/src/annotations/osd-svg-ellipse.js   ... and rectangles, etc.
	modified:   js/src/annotations/osd-svg-overlay.js
	modified:   js/src/settings.js
	modified:   js/src/widgets/contextControls.js
	modified:   locales/en/translation.json
```

The code is pretty scattered, and I didn't look into how the hover/display state needs to change but the display of the annotation drawings also needs to persist.

Anyway, we need a decision on what the UI should look like to select the border widths. A drop down with a few choices? Or a +/- control to increase/decrease the width by pixel? Or what?

**Comment by blalbrit** [comment]
All - I think a few set choices would be fine (thin, normal, thick - or current, thicker, thickest). I wasn't sure if there was a set of pre-configured widths that we were drawing from or not (line, dash, dots-and-dashes seemed pretty generic) from which we could just add a couple more widths.

The additional choices could simply appear in the current dropdown if possible, so that the options would be:

- current line
- thicker line
- thickest line
- dashes
- dots-and-dashes

Further configuration beyond that isn't necessary.

**Comment by jkeck** [comment]
@blalbrit and just to confirm, supporting thicker dashed or dots-and-dashed borders is not in scope?

**Comment by blalbrit** [comment]
@jkeck  - correct, only requirement is a few options for thicker solid lines.

**Comment by drh-stanford** [comment]
this is complicated a bit by the fact that the stroke width is hardcoded in various places -- e.g., in hover mode, it doesn't honor the dashes, it just shows a yellow default width solid line.

these are the modalities:

- display mode (solid/dashed and width)
- edit mode (solid and width)
- hover mode (solid and width)

**Comment by drh-stanford** [comment]
@blalbrit is this what you had in mind for the line style selection?

![screen shot 2017-03-03 at 11 19 24 am](https://cloud.githubusercontent.com/assets/1861171/23565660/5d94b238-0003-11e7-975b-54575b83de07.png)

**Comment by blalbrit** [comment]
Yep - that looks good @drh-stanford - I'm sure people might quibble with the labels, but this meets the requirement.

**Comment by drh-stanford** [comment]
FYI the Pin/Marker tool honors the line style so existing behavior is that if you select a dashed line style, the Pin marker outline will also be dashed. This seems odd to me -- maybe that's another ticket or is this expected/desired behavior?

**Comment by blalbrit** [comment]
hmm - that seems weird to me, but maybe @aeschylus knows if this was a deliberate decision?

**Comment by rsinghal** [comment]
I don't know if it was.  It may have been added because it was easier not to add a special case for the pin marker.
