### ISSUE TITLE
Proposal: Format/Write all code by given convention

### ISSUE THREAD

**Issue by radpet** [ProjectMirador/mirador#1318]
I suggest discussing the format rules and committing them inside mirador using http://editorconfig.org/ and following https://github.com/airbnb/javascript as base model of writing code

**Comment by mejackreed** [comment]
👍  I've enjoyed working with Airbnb style guides. I would maybe say could we use a tool that works with a given Airbnb config? https://github.com/airbnb/javascript#resources

Perhaps jshint or eslint? Mirador is already configured with jshint?

Also I'm assuming the es5 configuration? https://github.com/airbnb/javascript/blob/master/linters/.jshintrc

**Comment by aeschylus** [comment]
https://github.com/ProjectMirador/mirador/issues/514#issuecomment-92476971

At the time JSCS looked like a good tool, since it would actually force the code into a certain style (rather than producing style warnings during a PR). At one point we had jshint preventing pushes using a githook, but that ended up being problematic and was disabled.

Very eager to revisit this now that we have more people being harmed by style issues. 👍

**Comment by sdellis** [comment]
I don't know of any tool that will just flag new additions/edits. I personally really like [StandardJS](http://standardjs.com/) for maintaining consistency in style. No configuration (so you have to be ok with the rules) and you catch the style errors before they are submitted as PRs. 

I haven't touched the Mirador code in a while, so it's up to the people who work on it the most, but just throwing it out as something you should check out that would be pretty easy to set up and maintain.

**Comment by mejackreed** [comment]
We have used HoundCi to do only changed line style checking, but it can be a bit noisy on GitHub comments.

**Comment by csbailey5t** [comment]
I think eslint is a great tool combined with the Airbnb plugin. I'm also not averse to strictly enforced style automatically done by https://github.com/prettier/prettier.

@mejackreed I think keeping some sense of the historic character of the code is great, but that will always exist in the git history. In theory, I'm inclined to think that enforced standards for the whole codebase may be worth it. In practice, using eslint with the airbnb-es5 rules (by way of https://www.npmjs.com/package/eslint-config-airbnb-es5) there are `6972 problems (5753 errors, 1219 warnings)` in `js/src`. Eslint can autofix some of these, resulting in: `2234 problems (1023 errors, 1211 warnings)`. 

That likely means that conforming the whole codebase to those guidelines is out of reach. You can use the `--cache` option to only check changed files, though, which would allow the community to gradually conform the codebase over time. 

For what it's worth, StandardJS gives `10098 problems` in the `js/src` director.

**Comment by gigamorph** [comment]
Enforcing no trailing white-spaces and 2-space soft-tabs will be also good, I think. Many people have auto formatting to such effect enabled in their code editors anyway, and we can converge to less conflicts by having a standard in this area.

**Comment by mejackreed** [comment]
Thanks @csbailey5t for the comment. Yep I understand it will always be in history, its just not a great experience digging through several style commits to understand historical context. Not opposed to it, but based on your analysis wholesale moving the codebase doesn't look like an option. 

Maybe then a solution could be a gradual migration:

 - agree on a style
 - run these style checks in CI but do not fail build
 - Mirador devs as they contribute update style independently of features
 - Eventually fail on errors
 - Eventually fail on warnings

**Comment by aeschylus** [comment]
@csbailey5t prettier looks like a better solution to style enforcement than JSCS, implementation-wise. I would also like to move toward automated enforcement eventually (perhaps adding one more bullet to Jack's list), but I think the path Jack has described is a good one. So far I've heard a lot of agreement over AirBnB's ES5 styleguide, which I'm also in favour of (which specifies 2-space soft tabs).

**Comment by aeschylus** [comment]
I still think editorconfig is a good idea, as it solves this at what is usually the source, and most editors respect it.

**Comment by csbailey5t** [comment]
Given that there is a PR for adding eslint now, once that is merged in, would there be an aversion to a PR based on using `eslint --fix` to bulk handle spacing inconsistencies and such, or would it be preferable to fix style file by file over time?

**Comment by mejackreed** [comment]
I'm not against it. just wanted to raise my concerns about the potential downsides.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
