### ISSUE TITLE
Horizontal grey lines showing up periodically.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1320]
To reproduce: create an annotation, but cancel it without saving. Move the mouse without going outside the window or hovering over any exiting annotation regions. You will see a horizontal gray line. Inspecting this in the developer tools reveals it to be the tooltip for the canceled annotation.

**Comment by sdellis** [comment]
I just ran into this today on the demo on the ProjectMirador.org site. This is definitely tooltip "residue", but I got to it by different means. 

1. Go to the demo. 
2. Close one of the slots.
3. Click the annotation icon in the remaining slot.
4. Move over the image and you will see the gray line appear.
5. It prevents me from then drawing a target with any of the shape tools.

**Comment by gigamorph** [comment]
Appears every time I enable the annotation overlay and the mouse cursor enters the canvas. Disappears when I hover over an existing annotation. I added the screenshots in the wrong ticket: https://github.com/ProjectMirador/mirador/issues/1328

**Comment by radpet** [comment]
Thats qtip element.. Check it out in the dom tree. I think the ConsSpace implementation does not have this problem because it has few lines that are different from the mirador codebase, I can contribute them if you want :)

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
