### ISSUE TITLE
When I update an annotation (or change its form or colour), and I close the tab and open it again, I can’t view the last version of that annotation.

### ISSUE THREAD

**Issue by blalbrit** [ProjectMirador/mirador#1324]
From Vatican staff:

When I update an annotation (or change its form or colour), and I close the tab and open it again, I can’t view the last version of that annotation.

i.e. Vat.lat.588, f. 1r: first version
![vat lat 588](https://cloud.githubusercontent.com/assets/796990/23596710/f7c22928-01e1-11e7-9739-c316d4e2406f.png)
i.e. second version: I saved updates but now they seem to have disappeared
![2](https://cloud.githubusercontent.com/assets/796990/23596723/0f28e976-01e2-11e7-843f-7f4807a234b6.png)

**Comment by blalbrit** [comment]
Note: I'm not sure I entirely understand the problem being reported. Will try to duplicate the problem on Vatican machine.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
