### ISSUE TITLE
Is the pin annotation marker resizable?

### ISSUE THREAD

**Issue by blalbrit** [ProjectMirador/mirador#1327]
From the Vatican team:

We think that the shape of pin annotation is too small and it is not easy to display: how to enlarge it?

![1488902265323](https://cloud.githubusercontent.com/assets/796990/23665126/75e92c22-030c-11e7-9df1-7e47e547dd91.png)

**Comment by radpet** [comment]
I think this can be done via the drawingToolsSettings property in your configuration, set the fixedShapeSize to a bigger number.
Check setting.js for the exact syntax :).

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
