### ISSUE TITLE
annotation will show but mouse movement will highlight a different annotation

### ISSUE THREAD

**Issue by drh-stanford** [ProjectMirador/mirador#1328]
See this screenshot...

![annotation-hover](https://cloud.githubusercontent.com/assets/1861171/23719649/102f5bc8-03f1-11e7-81be-a2f0bcfd0b7c.gif)

**Comment by radpet** [comment]
The popup toolbox is rather buggy should we sth think about refactoring?

**Comment by gigamorph** [comment]
A possibly related example. When you set the border of tooltip, in this case `border solid 10px red`, you can see random empty tooltip sticking around when you move the mouse around. This happens quite frequently.

![screen shot 2017-03-09 at 9 39 33 am](https://cloud.githubusercontent.com/assets/86015/23754873/895927ac-04ac-11e7-91f8-92c83f71abfb.png)

**Comment by gigamorph** [comment]
Actually it seems to happen every time you enable the annotation view mode and then move the mouse cursor to enter the image area. Look at the gray horizontal line on the forehead.

![screen shot 2017-03-09 at 9 54 20 am](https://cloud.githubusercontent.com/assets/86015/23755497/8eb8a90a-04ae-11e7-9a3c-78a63fce4d44.png)

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
