### ISSUE TITLE
Top to Bottom and Bottom to Top Editing of Annotation bodies.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1329]

**Comment by gigamorph** [comment]
Top-to-bottom, right-to-left. At least that was the case I presented. E.g. http://www.komeiharada.com/japanese/Tategaki.gif

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3 annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
