### ISSUE TITLE
Proposal: Pass osd properties via the initial config

### ISSUE THREAD

**Issue by radpet** [ProjectMirador/mirador#1330]
In ConsSpace project we had to add the `preserveImageSizeOnResize` property to the osd options on initialization but since they are hardcoded I had to modify the source code. I would like to make some properties configurable what do you think?

**Comment by gigamorph** [comment]
I'm currently hardcoding `zoomPerClick` and `zoomPerScroll`. It'd nice to be able to set them in config or even better change them runtime.

**Comment by aeschylus** [comment]
Yeah, I think this has been requested a few times. Seems reasonable to me. Would gladly accept a pull request. The runtime option also sounds good, though it might be affected by the current layers work, which changes how openseadragon is initialised and run.

**Comment by radpet** [comment]
@aeschylus  In order to get the configs I think I will need a reference to the state, which I add in this pr https://github.com/ProjectMirador/mirador/pull/1306, would you check it before proceeding?
