### ISSUE TITLE
Supporting preserveViewport in OSD

### ISSUE THREAD

**Issue by tangfucius** [ProjectMirador/mirador#1332]
Although the 'preserveViewport' property is set to true when Mirador initializes the Openseadragon viewer, the viewport position/zoom level always resets to default when clicking through the images. Can this feature be easily activated in Mirador?  If not, can someone give me an outline of how I can implement it myself?

**Comment by radpet** [comment]
Hi, 

The osd resets the bounds because a new instance is created on each new image, thus making the value of this property more or less useless. A workaround would be to save somewhere the last bounds, attach to the osd open event and change the new image bounds

**Comment by tangfucius** [comment]
Thanks @radpet ! Imageview provides a `setBounds` function, so I just need to call it within `updateImage`. The client side works pretty much as expected now, but now I see a couple of new problems:
1. Does Mirador come with something like a spinner when an image is loading?  My images are pretty big and can take a while to load.
2. OSD keeps throwing Image timeout exceeded errors, probably because my IIIF image server can't handle that many requests at the same time. Is it possible to have Mirador to try reloading the image if it fails?

Sorry for these being unrelated to the topic. Just thought it might be more convenient to ask them in the same thread.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
