### ISSUE TITLE
There should be an event for changing "fullscreen" modes

### ISSUE THREAD

**Issue by c-alers** [ProjectMirador/mirador#1333]
I've recently been working on adjusting annotation dialog sizing based on whether or not the user was in fullscreen mode. I didn't find any way through the Mirador viewer to determine when the screen mode changed. Instead I had to add my own window listener for fullscreen changes in the page using the Mirador viewer. While this is possible, it also required extra work to make sure the target of the screen change was actually the viewer. Having the viewer keep track and notify about screen changes is a lot more straightforward.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
