### ISSUE TITLE
When results are returned last hit is not shown completely

### ISSUE THREAD

**Issue by versae** [ProjectMirador/mirador#1345]
There is a specific CSS rule limiting the size of results shown after search to 99%. Therefore, depending on the size of the screen, the scroll bar indicator and a part of the last hit can fall out of the visible area.

![search-within-scroll-results](https://cloud.githubusercontent.com/assets/173537/24110364/780d2118-0d50-11e7-87e0-19260bd9c981.gif)

**Comment by csbailey5t** [comment]
It looks like the `height: 70%` rule on `.search-results-container` is an immediate cause of this. A (probably brittle) fix is adjusting that to around `55%`. A better fix might be refactoring the css for more of the sidepanel to have a bit better control over this.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

Mirador 3's implementation of the Search API can be tested out at:
https://mirador-dev.netlify.app/__tests__/integration/mirador/contentsearch.html
