### ISSUE TITLE
sanitizeHtml is too restrictive for base TinyMCE functions

### ISSUE THREAD

**Issue by c-alers** [ProjectMirador/mirador#1350]
This was pointed out in a previous ticket #1233 but only the "target" attribute for a tags was addressed in it. There are many default enabled features in TinyMCE (img constraints, list, embeded video, etc....) That are either partially or completely removed from the display annotations by the sanitizeHtml function. 

At the very least, the OOTB implementation of this method should allow anything that the default TinyMCE features would create. A better step up would be allow for the function to be either overridden completely or its  "allowedTag" and "allowedAttributes" settings via the config settings when creating a Mirador viewer.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
