### ISSUE TITLE
Highlight the result annotation

### ISSUE THREAD

**Issue by versae** [ProjectMirador/mirador#1356]
Focusing on the bounding box might not be enough. Complementary alternatives could be:
- Show a persistent bounding box (maybe in a different color than the annotation system?) (@jeffreycwitt)
- Fade in and then fade out the bounding box

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
