### ISSUE TITLE
Add the ability to configure the title display

### ISSUE THREAD

**Issue by jkeck** [ProjectMirador/mirador#1357]
We have a use case where we will use Mirador in a wrapping page that also includes the title as a heading.  It would be nice if we could configure the title to not display for these cases.

**Comment by rsinghal** [comment]
This could be a part of a well defined "zen" mode

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

This is now included as a default setting for Mirador 3
https://github.com/ProjectMirador/mirador/blob/b15cbb61a7b60118b50469675d66e672748cb39e/src/config/settings.js#L264
