### ISSUE TITLE
How to translate interface

### ISSUE THREAD

**Issue by victorricardo** [ProjectMirador/mirador#1362]
How to translate interface for Spanish

**Comment by regisrob** [comment]
You just need to edit the spanish translation file: [locales/es/translation.json](https://github.com/ProjectMirador/mirador/blob/2.4.0/locales/es/translation.json). Note that you have to sync the spanish file with the english one first, by adding all the keys that have been added in the past few weeks (just make a diff between en/es to see the differences and update the spanish file accordingly).

**Comment by victorricardo** [comment]
Thank you

**Comment by victorricardo** [comment]
How to enable for defauld interface for Spanish
