### ISSUE TITLE
Proposal: Save imageBounds to the currentConfig

### ISSUE THREAD

**Issue by radpet** [ProjectMirador/mirador#1363]
Currently only the osdBounds are saved to the config and converting them to imageBounds out of openseadragon/mirador is not trivial. Should we include the imageBounds inside the config? I see that such event is fired but not handled inside the saveController, why so ?

**Comment by radpet** [comment]
Edit: My mistake the math behind is not so complex, we can decline this proposal :)
```python
def getRatio(width,height):
	return 1.0* width/height


height = 1.8287937743190659
width = 2.4902723735408556
x = -0.7450172815385462
y = -0.00046680505470209077

imageWidth = 257
imageHeight = 792

imageRatio = getRatio(imageWidth,imageHeight)

regionPosX = x * imageWidth
regionPosY = y * (imageHeight*imageRatio)
regionWidth = width * imageWidth
regionHeight = height * (imageHeight*imageRatio)
```

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
