### ISSUE TITLE
Object returned by window events contains bad canvasID value

### ISSUE THREAD

**Issue by jbhoward-dublin** [ProjectMirador/mirador#1373]
When working with windowUpdated events, the object returned includes a canvasID property with a bad value. For example: the manifest 

https://data.ucd.ie/api/img/manifests/ucdlib:40851

references a single image, where the canvasID is:

https://data.ucd.ie/api/img/ucdlib:40851/canvas/ucdlib:42220

However, the object returned by the windowUpdated event includes a canvasID property with this value:

https://data.ucd.ie/api/img/ucdlib:40851/canvas/ucdlib:40851

There is no such canvas referred to in the manifest. (The same thing happens with Mirador.Workspace WINDOW_ADDED events.)

**Comment by jbhoward-dublin** [comment]
A further observation: when a resource is annotated, the malformed canvasID is included in the annotation (we observe it registered in our deployment of SAS).

The issue is occurring with the Mirador 2.4 pre-release build; annotations created with Mirador 2.0 have the expected canvasID.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
