### ISSUE TITLE
Fullscreen support is incomplete for IE 11

### ISSUE THREAD

**Issue by c-alers** [ProjectMirador/mirador#1374]
You can use the arrow icon to open the Mirador viewer into "fullscreen", but the arrows do not work take the viewer out of "fullscreen" (you have to use the ESC key). Also, the Mirador.fullscreenElement function does not properly return the element in IE 11. This turns out to be a problem between IE 11 vs edge. In IE11, the exit function is called "msExitFullscreen" and the fullscreen element is called "msFullscreenElement". Updating utils.js resolves this issue.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
