### ISSUE TITLE
Lost Fullscreen and MetaDataTooltip when window gets too narrow

### ISSUE THREAD

**Issue by c-alers** [ProjectMirador/mirador#1376]
I have a window that include the options to "change view type", "view meta data", and "toggle fullscreen"
![image](https://cloud.githubusercontent.com/assets/25848168/24769188/970b7d22-1ad3-11e7-879f-40cb9cfc2e4d.png)

If the browser winder (or column window for an embedded viewer) gets to narrow, those options disapear
![image](https://cloud.githubusercontent.com/assets/25848168/24769259/dbea5274-1ad3-11e7-9f73-183f2f414149.png)

These options need to be reachable no matter how narrow the window gets.

**Comment by mapninja** [comment]
Same issue, here.  The issue happens when you get above 4 item slots horizontally, for me. 
![image](https://cloud.githubusercontent.com/assets/1517244/25648500/7240c3fe-2f81-11e7-85d3-78322766998b.png)

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
