### ISSUE TITLE
New annotations border styles (Thick & Thickest) do not work

### ISSUE THREAD

**Issue by radpet** [ProjectMirador/mirador#1377]
We applied them to some annotations and did not discovered any difference when saved between them and the solid one.

**Comment by radpet** [comment]
Fixed inside https://github.com/ProjectMirador/mirador/pull/1361

**Comment by csbailey5t** [comment]
@radpet On the current `develop` branch, the "thick" and "thickest" border styles seem to create clearly different border thicknesses when creating new annotations. They also seem to work when editing the annotation and changing the line thickness. 

I've included an example below that shows the difference, from the `develop` branch. Perhaps you could include a gif of them not working or specify more specifically the context in which they are not working. 

![screenshot 2017-04-13 10 59 53](https://cloud.githubusercontent.com/assets/4672869/25017525/f852bdba-2038-11e7-9e6a-f8c35be044ca.png)

**Comment by radpet** [comment]
[border_styles_issues.zip](https://github.com/ProjectMirador/mirador/files/920784/border_styles_issues.zip)
Here you are :)

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
