### ISSUE TITLE
ImageView.createOpenSeadragonInstance should export fetched info.json metadata

### ISSUE THREAD

**Issue by markmatney** [ProjectMirador/mirador#1378]
For context, please see [this issue](https://github.com/dbmdz/mirador-plugins/issues/2) on the "dbmdz/mirador-plugins" repository.

Currently, if an implementer supplies physical dimension metadata according to schemes 3) or 4) (i.e., embedded in or referenced by `info.json`), that [PhysicalRuler](https://github.com/dbmdz/mirador-plugins/tree/master/PhysicalRuler) plugin breaks. The problem is that once the info.json metadata is [fetched](https://github.com/ProjectMirador/mirador/blob/5c62bc4cb71cfb54d92634b7c14101e80496fabb/js/src/widgets/imageView.js#L540), it is thrown away when the callback returns. In order to support the physical ruler plugin move towards complete spec compliance, the metadata should be made available as a property on the `ImageView` object. So, inside that callback function, do something like

```
createOpenSeadragonInstance: function(imageUrl) {
    ...
    jQuery.getJSON(infoJsonUrl).done(function (infoJson, status, jqXHR) {
        ...
        _this.currentInfoJson = infoJson;
        ...
    });
}
```

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
