### ISSUE TITLE
Scope the modular scale of font sizes to Mirador, to avoid conflicts with a containing application. 

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1379]
Currently, many Mirador instances in the wild suffer from a bloated-looking table of contents. This is because we have allowed the user-agent stylesheets (or other, previously-defined styles) to affect our font hierarchy. This might work if we were more consistent with this as a design principle, but currently the styling and layout logic of the application does not handle this inheritance very well. We don't usually notice it in development because we are not imposing a font hierarchy from above, but in many containing applications the headings have an existing modular scale which starts quite a bit larger than Mirador's assumed, user-agent supplied scale.

By explicitly setting our font sizes to a set of hard values, this will allow rendering of the table of contents to be consistent across installations.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
