### ISSUE TITLE
Improve CSS so image manipulation controls move up when annotations are disabled

### ISSUE THREAD

**Issue by rsinghal** [ProjectMirador/mirador#1381]
http://beta.biblissima.fr/fr/ark:/43093/mdatad8066ee591c0b7ddc381b7072a0e4679fa32b34b and select image view.  Right now the image manipulation controls are hardcoded to appear below the annotation controls, which of course looks odd when the annotation controls are disabled and hidden.

**Comment by regisrob** [comment]
+1. It was on my "things-to-do-or-issues-to-create" list :)

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
