### ISSUE TITLE
Annotations race condition on loading

### ISSUE THREAD

**Issue by radpet** [ProjectMirador/mirador#1386]
If you switch really fast between images the annotations array is not properly populated and contains annotations from the previous image since the `getAnnotations` function contains both sync and async (annotation endpoint) code that populates that array.

**Comment by radpet** [comment]
The latest commit on https://github.com/ProjectMirador/mirador/pull/1380 fixes it :)

**Comment by aeschylus** [comment]
@radpet Thanks for the catch. Is this with the most recent 2.4.0 release?

**Comment by radpet** [comment]
Yup, here you are the line that causes it
https://github.com/ProjectMirador/mirador/blob/develop/js/src/workspaces/window.js#L857
Since all the calls share one array reference nobody assures you when concatenating there will be no stale annotations inside. Here you can find the fix https://github.com/radpet/mirador/blob/c985e593caac24f19920c130e5292c6e5a0b2136/js/src/workspaces/window.js#L835
there are few lines that are redundant though

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
