### ISSUE TITLE
Timing When Dynamically Adding Manifests and Windows

### ISSUE THREAD

**Issue by jpadfield** [ProjectMirador/mirador#1394]
Hi,

I am exploring how to add manifests and actual windows/slots to a viewer after is has been loaded in. I have found a process for doing this but I was a questions about timing.

With the various vars defined in the code I can add a new images using:
cviewer.eventEmitter.publish('ADD_MANIFEST_FROM_URL', newManifest, newManifestLocation);	cviewer.workspace.eventEmitter.publish('SPLIT_RIGHT', cslot);
cviewer.workspace.eventEmitter.publish('ADD_WINDOW', cfig);

However, the final step fails if the manifest has not finished loading in, this can be fixed by adding in a delay on the final step, but I wanted to know is there a way of asking Mirador to only add the window once the manifest has loaded in?

Thanks

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
