### ISSUE TITLE
Config option for adding download links/buttons to images?

### ISSUE THREAD

**Issue by ryanfb** [ProjectMirador/mirador#1397]
See: https://twitter.com/SLevelt/status/854738252619812865

With IIIF, I can imagine a few different ways this could go - but users/implementors will probably want to control if this feature is enabled and what resolutions it would present to end users. This could default to full-resolution, or present large/medium/small options, etc.

Maybe this should instead be filed against OpenSeadragon, with some documentation about how to pass that config option into the OpenSeadragon viewer used by Mirador. The only related OpenSeadragon issue I found was openseadragon/openseadragon#477, which has a partial workaround for using JS to render the current canvas out to a file - but I think this could be done much better with IIIF, so that the user doesn't have to know to zoom in to max resolution to get the full resolution download.

**Comment by azaroth42** [comment]
See: `rendering` - http://iiif.io/api/presentation/2.1/#rendering

**Comment by edsu** [comment]
Is it currently possible to download an image from Mirador?

**Comment by ryanfb** [comment]
See also https://github.com/dbmdz/mirador-plugins/tree/master/DownloadMenu and #2194.

**Comment by karenmajewicz** [comment]
We implemented the download plugin/menu into our Mirador instance for the Big Ten Geoportal. Here is an example: https://geo.btaa.org/catalog/p16022coll245:973

Unfortunately, our users are not aware that the download is an option as it is only accessible after clicking on the kebab icon. Has anyone looked into this as a design issue?

**Comment by jkeck** [comment]
@karenmajewicz we ran into some similar feedback from our users.  We customized the button in [our instance](https://purl.stanford.edu/fw090jw3474) of mirador.  You can see how we accomplished that in  sul-dlss/sul-embed#1101.

**Comment by karenmajewicz** [comment]
Thank you @jkeck! That customization is much clearer. I'm tagging our developer so they can check it out - @ewlarson

**Comment by mejackreed** [comment]
Now that https://github.com/ProjectMirador/mirador-dl-plugin is working in production, we will close this issue.
