### ISSUE TITLE
Can't edit border style of an annotation

### ISSUE THREAD

**Issue by gigamorph** [ProjectMirador/mirador#1398]
Probably related to #1377 but I can't edit border style (solid, thick, thickest, dashes, dots & dashes) of an existing annotation. I hover over an annotation, click on the "edit" link of the tooltip, click on the border of the shape, and choose the style from the dropdown. When I save, it doesn't get changed.

I can change other attributes (stroke color and fill color) by editing this way. I can also create one with specified border style, that is, if I select the style first before drawing the shape. If I select the style after creating the shape -- I guess this can be considered editing vs. creating -- then the selection doesn't get reflected when saving.

Tested with the develop branch and with http://projectmirador.org/demo/.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
