### ISSUE TITLE
With single canvas in viewer, bottomPanel cannot be minimised

### ISSUE THREAD

**Issue by jbhoward-dublin** [ProjectMirador/mirador#1418]
When a manifest with a single canvas is loaded from the manifest panel, the bottomPanel remains visible, with CSS attribute 'display: block' specified in HTML 'style' attribute, while the ellipsis which enables toggling the bottomPanel is minimised and therefore inaccessible to the user.

This experienced with downloadable release of Mirador 2.4.0.

**Comment by jbhoward-dublin** [comment]
Note: this can be addressed by setting value of ```bottomPanelVisible``` to 'false' in ```windowSettings``` and ```windowObjects```, but with default settings the problem described occurs

**Comment by azaroth42** [comment]
We have exactly the same behavior with our content. As a museum, the vast majority of our manifests only have a single canvas. Thanks to @jbhoward-dublin for the work around until this can be fixed for real!

**Comment by azaroth42** [comment]
Fix we came to:

In window.js, after line 93 in the init function, we added:

```
if (_this.imagesList.length == 1) {
  this.bottomPanelVisibile = false;
}
```
