### ISSUE TITLE
derivation of manifest version too simple?

### ISSUE THREAD

**Issue by nicolasfranck** [ProjectMirador/mirador#1428]
I've tried to load this manifest in mirador
```
https://adore.ugent.be/IIIF/manifests/liberfloridus-quires
```

But the ranges are not loaded. It shows an error in the javascript console:
```
toc.js:69 Uncaught TypeError: Cannot read property 'length' of undefined
    at $.TableOfContents.getTplData (toc.js:69)
    at $.TableOfContents.init (toc.js:34)
    at $.TableOfContents (toc.js:22)
    at $.SidePanel.loadSidePanelComponents (sidePanel.js:82)
    at $.SidePanel.init (sidePanel.js:67)
    at $.SidePanel (sidePanel.js:18)
    at $.Window.updateSidePanel (window.js:517)
    at $.Window.toggleFocus (window.js:643)
    at $.Window.toggleImageView (window.js:696)
    at $.Window.init (window.js:210)
```

That last function "getTplData" (js/src/widgets/toc.js) uses a derived attribute "manifestVersion",
which wasn't set because the previous method "manifest.getVersion()" (js/src/manifests/manifest.js) failed to retrieve the value.

Reason: manifest.getVersion() assumes that "@context" is a string, and tries to map this string to a value.

But in my case, it's an array.
Yes, an array, because I needed to add some premis metadata elements. Not sure whether this is necessary or not.

**Comment by nicolasfranck** [comment]
@jbaiter : yep, that seems like a workable solution. Thanks!

**Comment by aeschylus** [comment]
Solved in https://github.com/ProjectMirador/mirador/pull/1429

**Comment by coy123** [comment]
I just encountered this problem with getVersion() on Mirador 2.7. The code:
```
getVersion: function() {
   var versionMap = {
     'http://www.shared-canvas.org/ns/context.json': '1', // is this valid?
      'http://iiif.io/api/presentation/1/context.json': '1',
      'http://iiif.io/api/presentation/2/context.json': '2',
      'http://iiif.io/api/presentation/2.1/context.json': '2.1'
    };
    return versionMap[this.jsonLd['@context']];
}
```
doesn't take into account if the context link starts as https. I changed the context links back to http to solve it. I am not sure if it is mirador's responsibility to take https into account but I just wanted to report the current status.

**Comment by regisrob** [comment]
Per [this comment](https://github.com/IIIF/api/issues/1640#issuecomment-419261219) by @azaroth42  on the api repo, I'm guessing the JSON-LD context URIs will remain HTTP, and thus the HTTP url will still be the canonical form to be matched by an application to detect the version of a given IIIF API

**Comment by azaroth42** [comment]
That's correct. The contexts are available via https, but the correct URI is http.

In particular,

> The value of the @context property must be either the URI `http://iiif.io/api/presentation/3/context.json` or a JSON array with the URI `http://iiif.io/api/presentation/3/context.json` as the last item.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
