### ISSUE TITLE
No support for nested ranges

### ISSUE THREAD

**Issue by tpendragon** [ProjectMirador/mirador#1439]
https://plum.princeton.edu/concern/scanned_resources/ps75276654/manifest doesn't display the table of contents in Mirador, but it works in UV. Looks like Mirador doesn't support nested ranges - nor does it recognize the "top" viewingHint.

**Comment by aeschylus** [comment]
Hm. I believe it supports both, but there were some edge cases that didn't get covered. Adding some references here that may be related (and so we have access to this manifest while addressing those other issues).

https://github.com/ProjectMirador/mirador/issues/1427
https://github.com/ProjectMirador/mirador/issues/1140
See https://github.com/ProjectMirador/mirador/issues/1140#issuecomment-250608748

There seems to be a problem in https://github.com/ProjectMirador/mirador/blob/develop/js/src/widgets/toc.js#L144-L231

**Comment by azaroth42** [comment]
IIIF Presentation API 2.1 does not support nested ranges. 

> References to ranges within the current range. Each included range must be referenced via a string containing the range’s URI. 

This is a feature that is coming in 3.0

**Comment by tpendragon** [comment]
Ha! We've always used nested ranges because it made sense, and it worked in UV so we assumed we had it right.

**Comment by mejackreed** [comment]
@tpendragon do you have any handy examples of this that are public? We are thinking this is resolved in Mirador 3 and would love to test it.

**Comment by tpendragon** [comment]
@mejackreed We don't do nested ranges anymore - we switched to the 2.1 spec when we moved everything over from Plum to Figgy. The manifest referenced in this ticket is https://figgy.princeton.edu/concern/scanned_resources/f008d403-fe9c-4d62-ac50-7ab734b6f3c6/manifest now.

**Comment by mejackreed** [comment]
Awesome it seems to working well. Thanks for the quick response!
![Screen Shot 2020-10-08 at 5 25 31 PM](https://user-images.githubusercontent.com/1656824/95523211-494fc200-098b-11eb-89c5-ad349a0928ff.png)
