### ISSUE TITLE
new circular reference in JSON.stringify in saveController.js

### ISSUE THREAD

**Issue by jeffreycwitt** [ProjectMirador/mirador#1441]
In progress toward 2.5, it seems like there is now a problem with the JSON.stringify function in this code block in the saveController.js:
```javascript
$.LocalJSONBlobAPI.prototype = {
        readSync: function(blobId) {
            return JSON.parse(this.options.storage.getItem(blobId));
        },
        save: function(blob) {
            var deferred = jQuery.Deferred(),
                uuid = generateUUID();
            this.options.storage.setItem("BM-" + uuid, JSON.stringify(blob));
            deferred.resolve("BM-" + uuid);
            return deferred.promise();
        }
    };
```
This prevents the ability to save the current state of Mirador.

I believe @regisrob found the source of the circular reference in Mirador's state. Perhaps he can add it to this issue.

**Comment by regisrob** [comment]
I just gave a quick check this morning and noticed that each `windowObjects` in the configuration object now has a `canvases` object which contains functions inside (see `dispatcher`and `thumbnailResource` for instance). I have not investigated more than that...

**Comment by aeschylus** [comment]
Yes, this is the source of the circular references. The serialisation function needs to be updated. No test caught this, so we have a regression.

I will be resolving this this week, but have a couple other 2.5-related problems to address before this, so if someone else could look at this, it would be a great help. Have a look at: https://github.com/ProjectMirador/mirador/blob/develop/js/src/utils/saveController.js#L270-L274

There may also be other places where unfiltered objects (including their methods) are placed in the currentConfig through the "Set" function on saveController.

**Comment by rsinghal** [comment]
A generic test that loops through the `currentConfig` checks for that would help a lot in preventing regressions.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
