### ISSUE TITLE
Add support for "multi-part" objects.

### ISSUE THREAD

**Issue by tpendragon** [ProjectMirador/mirador#1442]
These are IIIF collections with the "multi-part" viewingHint. We use them for Multi-Volume works.

The way these should (probably) work is they'd show up with the label of each manifest in the collection in the structure pane on the left, and clicking the label would load up that manifest. An example manifest:

https://plum.princeton.edu/concern/multi_volume_works/ppv63h2457/manifest

It looks like this in UV:

http://universalviewer.io/examples/#?manifest=https%3A%2F%2Fplum.princeton.edu%2Fconcern%2Fmulti_volume_works%2Fppv63h2457%2Fmanifest&c=0&m=0&s=0&cv=0&xywh=-1744%2C-927%2C6053%2C5394

**Comment by tpendragon** [comment]
This ticket's old enough we've migrated repositories by now. The manifest URL is now https://figgy.princeton.edu/concern/scanned_resources/ab2c354b-ff2d-4a0a-9334-1b14316efe3a/manifest

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

@tpendragon @jrgriffiniii MVW are now supported in Mirador 3. You can take it for test drive at in the [live demo](https://mirador-dev.netlify.app/__tests__/integration/mirador/). Also note there are some proposed changes to the current design in #3248.
