### ISSUE TITLE
Show mandatory image attribution, license

### ISSUE THREAD

**Issue by azaroth42** [ProjectMirador/mirador#1444]
Mirador does not follow the requirement of the Image API to show the rights properties.  This means that we have had to put that information into our manifest, such that they do show.  This is not correct (as our images and metadata have different licenses), but necessary in order to work around this bug.

**Comment by jpadfield** [comment]
Hi, I was just wondering if this has moved at all, are there any plans to display further image specific details, such as licenses ?
