### ISSUE TITLE
Mirador Release 2.5.0 does not contain mirador.js in build.zip

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1450]
The Mirador v2.5.0 release does not contain the `mirador.js` in its `build.zip` folder. Was this release created using the release creation script here?

https://github.com/ProjectMirador/mirador/blob/develop/bin/create_release.sh

If so, maybe we need to fix that?

**Comment by aeschylus** [comment]
Yes, we could. In running the main build script, the create_release wasn't present in the project. Not sure why. I created it "manually" using the existing grunt task.
