### ISSUE TITLE
Mirador 2.5 - Mirror view no longer retains annotation view

### ISSUE THREAD

**Issue by blalbrit** [ProjectMirador/mirador#1451]
In mirror view, outlines of annotations persist, but the viewer no longer shows the annotations. This was not the case when the feature was under development and seems to be a discrepancy between master and the develop branch. Compare https://youtu.be/E5TP5DSEXrI?t=45s with 

![m25_3](https://user-images.githubusercontent.com/796990/27360846-78994cee-55d8-11e7-9aaf-c7d7441e1e7c.gif)

**Comment by blalbrit** [comment]
Likewise, annotation creation in the mirror view no longer works as it did in the develop branch:
![m25_4](https://user-images.githubusercontent.com/796990/27360938-0087394a-55d9-11e7-85b3-29e4a003c8e1.gif)

**Comment by aeschylus** [comment]
https://github.com/ProjectMirador/mirador/blob/develop/js/src/annotations/osd-region-draw-tool.js#L167-L169

and 

https://github.com/ProjectMirador/mirador/blob/a53d537f2025e0c2bbfb674500be9cb1f8dff0e0/js/src/annotations/osd-svg-overlay.js#L495-L497

Seem to be the culprits. These two logic branches use the old non-canvas-normalised coordinate system. I thought I tested annotations in mirrored mode before deploying, but I can't get it to work anymore.

I should be able to patch this pretty easily.
