### ISSUE TITLE
POST update in simpleASEndpoint incorrect?

### ISSUE THREAD

**Issue by jorisvanzundert** [ProjectMirador/mirador#1458]
I'm not entirely sure this is a genuine bug or a side effect of my currently heavily experimenting with adapting mirador viewer, but suddenly I noticed that the update request in 

https://github.com/ProjectMirador/mirador/blob/develop/js/src/annotations/simpleASEndpoint.js#L137

seems malformed. I'm using SimpleAnnotationStore, that tells me so. I changed the line to:

url: _this.url + "/update?uri="+encodeURIComponent(annotationID) + "&APIKey=" + _this.APIKey, //this.prefix+

which makes it work, at least in my case. 

Apologies if I just messed up something in my own context. I'm experimenting with the frontend stuff, and am not particularly concerned with the backend. But I just noticed it not updating and thought I'd report it. 

Cheers
--J.

**Comment by aeschylus** [comment]
https://github.com/glenrobson/SimpleAnnotationServer/issues/21
