### ISSUE TITLE
Mirador expects 'default' instead of 'full' to reference full image from segment resource

### ISSUE THREAD

**Issue by bencomp** [ProjectMirador/mirador#1467]
In the [Segments](http://iiif.io/api/presentation/2.1/#segments) section of the Presentation API 2.1 an example shows that as part of a `oa:SpecificResource` a link to the full image is included using the `full` key:

```
{
  "@context": "http://iiif.io/api/presentation/2/context.json",
  "@id": "http://example.org/iiif/book1/annotation/anno1",
  "@type": "oa:Annotation",
  "motivation": "sc:painting",
  "resource": {
    "@id": "http://www.example.org/iiif/book1-page1/50,50,1250,1850/full/0/default.jpg",
    "@type": "oa:SpecificResource",
    "full": {
      "@id": "http://example.org/iiif/book1-page1/full/full/0/default.jpg",
      "@type": "dctypes:Image",
      "service": {
        "@context": "http://iiif.io/api/image/2/context.json",
        "@id": "http://example.org/iiif/book1-page1",
        "profile": "http://iiif.io/api/image/2/level2.json"
      }
    },
    "selector": {
      "@context": "http://iiif.io/api/annex/openannotation/context.json",
      "@type": "iiif:ImageApiSelector",
      "region": "50,50,1250,1850"
    }
  },
  "on": "http://www.example.org/iiif/book1/canvas/p1#xywh=0,0,600,900"      
}
```

When I model my manifest after this example, Mirador breaks with a type error because it looks for a `default` key and cannot find it. For example, when I try to load <https://digitalscholarship.nl/manifests/UBL_BPL_14A/manifest2-split.json> in the demo, this stacktrace is printed in the console:

```
TypeError: service is undefined[Learn More]  manifest.js:128:12
	getThumbnailForCanvas     manifest.js:128:12
	fetchTplData     manifestListItem.js:107:14
	init      manifestListItem.js:47:6
	$.ManifestListItem      manifestListItem.js:26:4
	onManifestReceived     http://projectmirador.org/demo/mirador.min.js:87:31
	listenForActions/<      manifestsPanel.js:56:12
	dispatch      jquery.min.js:3:10263
	add/q.handle     jquery.min.js:3:8325
	trigger     jquery.min.js:4:5625
	trigger/<    jquery.min.js:4:6129
	each      jquery.min.js:2:2712
	each     jquery.min.js:2:1000
	trigger     jquery.min.js:4:6108
	$.publish     ba-tiny-pubsub.js:17:4
	$.EventEmitter.prototype[action]       eventemitter.js:102:6
	addManifestFromUrl/<      viewer.js:304:10
	i     jquery.min.js:2:28011
	fireWith     jquery.min.js:2:28782
	A     jquery.min.js:4:14032
	c/<      jquery.min.js:4:16322
```

When I replace `full` with `default`, this type error is not thrown and the manifest loads. E.g., <https://digitalscholarship.nl/manifests/UBL_BPL_14A/manifest-split-default-pyramid.json> loads correctly.

If the specification is correct, then this looks like a bug in Mirador's thumbnail URL generation.

**Comment by cbutcosk** [comment]
+1 to this, ran into a similar issue wiring up a quick demo: http://iiif.museum.colby.edu/presentation/experiments/4-segmented.json

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
