### ISSUE TITLE
Book view loads/shows full image resources instead of fragments

### ISSUE THREAD

**Issue by bencomp** [ProjectMirador/mirador#1468]
In my manifest I paint fragments on a canvas to 'virtually split' scans of facing pages. Because of #1467 I use `default` instead of `full` to reference the full image from the `oa:SpecificResource` that describes the fragment. In the Image view this works as intended, i.e. Mirador shows half of the scan, but in Book view it loads the full images resulting in two spreads next to each other.

For example, when I load <https://digitalscholarship.nl/manifests/UBL_BPL_14A/manifest-split-default-pyramid-book.json> in [the demo]() and open the Image view, I see

<img width="1278" alt="screen shot 2017-08-21 at 10 30 28" src="https://user-images.githubusercontent.com/1303898/29510525-5e22d38a-865c-11e7-8698-5af5ce363d74.png">

But when I select the book view, I get

<img width="1274" alt="screen shot 2017-08-21 at 10 30 40" src="https://user-images.githubusercontent.com/1303898/29510526-65083a46-865c-11e7-899c-6f801cf7af3d.png">

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
