### ISSUE TITLE
Manifest list page has an overflow styling issue (develop branch)

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1472]
![screen shot 2017-09-11 at 16 33 40](https://user-images.githubusercontent.com/145874/30301347-0ba0f4ac-970f-11e7-8907-e958b5ba38d7.png)
![screen shot 2017-09-11 at 16 33 51](https://user-images.githubusercontent.com/145874/30301348-0ba3c4a2-970f-11e7-9ba4-8bca132317f2.png)

The thumbnails wrap and are visible behind and below the first row of thumbs, which should instead be truncated. May have something to do with manifest parsing.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
