### ISSUE TITLE
.jshint and .estlint default config

### ISSUE THREAD

**Issue by rit** [ProjectMirador/mirador#1476]
When runnig `grunt lint`, it outputs:

`
...
8809 problems (7516 errors, 1293 warnings)
...
`

What should be in the .jshint and .eslint?

**Comment by mejackreed** [comment]
That's correct. We added jshint late in the project in hopes to move towards a consolidated style. We aren't there yet but added `grunt lint` as a way to check to make sure developers were not added more style violations. The AirBnb ES5 style guide is the agreed upon style guide: https://github.com/ProjectMirador/mirador/blob/develop/.eslintrc#L2-L16

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
