### ISSUE TITLE
convergence of Mirador implementation of Presentation API annotations and "http://www.w3.org/ns/anno.jsonld"?

### ISSUE THREAD

**Issue by christopher-johnson** [ProjectMirador/mirador#1479]
As you certainly know, the current Mirador annotation implementation is divergent with the broader Web Annotation Data Model `@context`.  

Problematically, quite a few Mirador methods depend on compacted (and localized) Presentation API 2.1 property aliases (e.g. "on", "within", "full") and not namespace prefixed terms.  Additionally, there are several properties that have been dropped or changed completely. (content:chars, dcterms:isPartOf) in the newer model.  

statically defining any aliased properties as constants to expanded IRIs is probably the easiest way to maintain the code against multiple API implementations (semantically versioned and referenced via `@context` URIs).  I think that instantiating new annotation object properties with constant values is also a good practice rather than local variable aliases.  This allows for optimal portability downstream. 

Is there a roadmap in place?  I may be able to help sort this out as it is important to my use case to have correctly versioned and valid linked data.

**Comment by mejackreed** [comment]
Closing this as it doesn't seem directly actionable at the moment.
