### ISSUE TITLE
Logo as array - iiif 2.1 version compliance

### ISSUE THREAD

**Issue by prilia** [ProjectMirador/mirador#1487]
Hello,
By the iiif.io spec of presentation api logo can be array
http://iiif.io/api/presentation/2.1/#logo
But mirador not accepts logo as array only single  value.
Is it possible to add 2.1 version compliance.
Thank you !

**Comment by Eyal-R** [comment]
Mirador also doesn't accept a single logo in an array, only single logo in a single value.

**Comment by mejackreed** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets. This has been resolved in Mirador 3.
