### ISSUE TITLE
Vertical thumbnail strip in left panel

### ISSUE THREAD

**Issue by snydman** [ProjectMirador/mirador#1488]
Learned in Japan that for languages primarily displayed top to bottom, Mirador is not being adopted because when the available height is small, the horizontal thumbnail strip is too obtrusive. Need to add a configurable option to display the thumbnail strip vertically on the left or right side panel.

**Comment by mejackreed** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets. This feature specifically has been added to Mirador 3.
