### ISSUE TITLE
Annotations not working in IE

### ISSUE THREAD

**Issue by morpheus-87** [ProjectMirador/mirador#1492]
At the moment, the annotation functionality does not work properly in the Internet Explorer:

![screenshot](https://user-images.githubusercontent.com/19190936/31769638-b9d541d0-b4d4-11e7-9f92-2ae440457829.png)

As you can see in the screenshot above, it's neither possible to type any text in the box nor to style the text.

My first thought was, that the version of TinyMCE is the problem - but that wasn't the fact, I tried it out.

A curious thing about this issue is, that the official demo of TinyMCE (https://www.tinymce.com/docs/demo/full-featured/) works as expected.

**Comment by Susa70** [comment]
Hello from 2019. This problem still exists :( Also annotations works in [official demo](https://projectmirador.org/demo/) . Any clue? I work with v2.7.0

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
