### ISSUE TITLE
Annotations in local install on MacOS

### ISSUE THREAD

**Issue by Alph2** [ProjectMirador/mirador#1493]
Hi,

I am trying to setup a local installation of Mirador on my personal machine in order to collate manuscripts offline from local tiff files (weak internet connexion). I almost managed to get it working (with [digilib](http://digilib.sourceforge.net) server); but it remains useless without the ability to persistently store annotations… I am stuck there: devil's in the details…

Unfortunately [Catch from Harvard](https://github.com/annotationsatharvard/catcha) is a dead-end on macOS (java 7 cannot be installed); I did not try [Triannon from Stanford](https://github.com/sul-dlss-deprecated/triannon) (looks like it is deprecated); the SimpleAnnotationServer module seems to be [bugged](https://github.com/glenrobson/SimpleAnnotationServer/issues/21); Elastic Search runs fine but I couldn't find a working adaptation module (there is a custom module named [frickendpoint](https://gist.github.com/Wedjaa/1f8a1fd0c0c4a904572d) out there, but it also seems to be broken)…
Does anyone have an idea as how to solve this last problem? Is there a way to adapt the Local Storage module for a persistent storage in a custom directory?

**Comment by juliaanvaneijndt** [comment]
Hello,

[This](https://gist.github.com/juliaanvaneijndt/cc19ad0485ce89d1c4f2910f0d99a0d9) is my own attempt to write a module for elasticsearch.

Use the following config:
`         "annotationEndpoint": { "name":"ElasticSearch Endpoint", "module": "ElasticEndpoint", "options":{"url": 'http://localhost:9200/mirador-latest'} , "storeId":'comparison', "APIKey":'user_auth'}`

I am not sure if this is done right (if anyone with proper coding skills would like to review my work, by all means, go ahead, please) but it works fine with the latest build of mirador.

Cheers!

**Comment by mejackreed** [comment]
Worth noting, we are now using [Annotot](https://github.com/mejackreed/annotot) for annotations within a Rails application. @jeffreycwitt has wrapped that up into a docker container: https://github.com/jeffreycwitt/rails-annotation-server

The needed Mirador endpoint is also included in that repo.

**Comment by jeffreycwitt** [comment]
Mirador config should look like this: 
"annotationEndpoint": {
            "name": 'Annotot',
            "module": 'AnnototEndpoint',
            "options": {
              "endpoint": "<annotot end point>"
            }
          },

And you need to add this file to your Mirador build: 

https://github.com/mejackreed/annotot/blob/master/app/assets/javascripts/annotot/annotot_endpoint.js

either with a <script> tag below the Mirador include. Or bundled with mirador.

**Comment by mejackreed** [comment]
Closing this issue as I hope it is answered. Please reopen if needed.
