### ISSUE TITLE
Erratic bug in ToC and thumbnail strip navigation

### ISSUE THREAD

**Issue by regisrob** [ProjectMirador/mirador#1495]
Version 2.6.0 seems to introduce a major bug in ToC and thumbnail strip navigation...

To reproduce:
- open "MS Richardson 7" (https://iiif.lib.harvard.edu/manifests/drs:5981093)
- navigate through the toc and thumbnail strip, for instance click on "f. 5v. (seq. 14)" in the ToC: it should raise an error in the console which breaks the navigation, and from this point you have to click twice on a thumbnail or a ToC entry to be able to proceed.

JS errors are: 
- `Uncaught TypeError: Cannot read property '_transformBounds' of null` (this one is then raised on mousemove hover the Mirador viewport, so hundreds of times...)
- `Assertion failed: [Viewport._setContentBounds] bounds.width must be greater than 0`

Tested on Mac OS X in Chrome 61.0.3163.100

**Comment by aeschylus** [comment]
Hm. This is serious.

**Comment by aeschylus** [comment]
Is this happening with all objects you have tried that have a toc?

**Comment by regisrob** [comment]
Strangely the error seems to happen only on Harvard and NLW manifests that have ToC... Like this one http://dams.llgc.org.uk/iiif/newspaper/issue/3320640/manifest.json (Cambrian (1804-01-28)), and all the others from Harvard in the demo

The other manifests with ToC are working fine...

**Comment by aeschylus** [comment]
I believe this has been solved by those institutions updating their manifest parsing. There were changes to the Spec/Community consensus about the interpretation of 2.0 and 2.1 ranges that made their formats no longer valid. I can expand if necessary, but an closing this issue for now.

**Comment by regisrob** [comment]
:+1
