### ISSUE TITLE
en-US localization file is missing from project mirador demo site page

### ISSUE THREAD

**Issue by beaudet** [ProjectMirador/mirador#1499]
Causes a 404 to appear in JavaScript console which causes unnecessary alarm.  It would be better to avoid a 404 even if there truly is no en-US localization file - or perhaps one should be created if one doesn't exist?

@lavigne - originally identified missing files in #779 

![image](https://user-images.githubusercontent.com/77699/32078659-b6739054-ba75-11e7-9ac1-c5a98481f80a.png)

**Comment by mejackreed** [comment]
I think this is an issue with how i18next handles locales. We want to enable more specific lookups like `zh-CN` and `zh-TW` so when the browser looks up `en-US` it fails falls back to `en`. If we don't want this behavior we could move `en` to `en-US`, and set that as the fallback perhaps? Still other language browsers that access the site will get a 404 if there language does not exist and then the fallback will be used.

**Comment by mejackreed** [comment]
Closing this as it has now been resolved for Mirador 3 and the main demo shows Mirador 3.
