### ISSUE TITLE
Supporting 1-level collection on initial load vs collection tree view

### ISSUE THREAD

**Issue by jeffreycwitt** [ProjectMirador/mirador#1506]
I wanted to change a behavior change in Mirador after the merge of @dicksonlaw583 collection tree PR #1405

Any collection now loaded in the config data property with "collectionUri" is now getting passed into the collectionManifestPanel instead of the default manifestPanel.

The relevant changed block of code is here:

https://github.com/ProjectMirador/mirador/pull/1405/files#diff-78dd9471e983fbeee0c86bfdeb827128L282

I wouldn't exactly call this is bug, but it is a significant behavior change. If anyone has relied on passing URL of collections to Mirador, Mirador will no longer load these collections as a list of Manifests. 

Instead the collectionManifestPanel must be enabled (BTW, I still can't figure out how to enable this in the configuration.), and once enabled the collection will show up in the collection explorer.

Would it be possible to load collections as they have been loaded in the past when the collectionManifestPanel is not enabled? And load them into the collection explorer only when the collectionManifestPanel is enabled?

Is this conditional behavior desirable? I'm not sure.

My only point right now is that if someone has relied on the previous behavior but wants to pull in the newest release of Mirador, they will experience this update as a breaking change.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
