### ISSUE TITLE
NPM package installation is slow.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1508]
Consider moving NPM packages all in dev-dependencies and publishing only the bundles. It also may be advisable to have multiple bundles, some of which include the dependencies and some of which don't. Yarn may help as well, but not on first install.

**Comment by mejackreed** [comment]
I think this would be fine with Mirador in its current npm state. Ideally down the road (perhaps v3?) I would like to see npm dependencies reflect a real dependency structure on which Mirador can be built against.

**Comment by mejackreed** [comment]
This should be resolved now with Mirador 3.
