### ISSUE TITLE
image list in left pane

### ISSUE THREAD

**Issue by stephanpauls** [ProjectMirador/mirador#1511]
If you want the list of images in the left pane, then you have to let your viewer read the sequence and not just the ranges of the manifest file.
Is there a reason why you why did no do this?

Stephan Pauls

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
