### ISSUE TITLE
Clicking on "close slot" button opens up the manifest selector panel instead

### ISSUE THREAD

**Issue by gigamorph** [ProjectMirador/mirador#1516]
From the Mirador demo site, add any (empty) slot, and try to close it by clicking on `X Close`. Instead of closing the slot, it opens up the manifest selector panel. Apparently the `a.addItemLink` element is covering the whole slot area and is preventing click events reaching the `a.remove-slot-option` element.

**Comment by aeschylus** [comment]
I think @markmatney solved this in this pull request:
https://github.com/ProjectMirador/mirador/issues/1516

We haven't done a release since then, so the demo site is still broken. I should probably do a release soon.
