### ISSUE TITLE
direct url to a book

### ISSUE THREAD

**Issue by federicolucca** [ProjectMirador/mirador#1524]
Hi,

There is the possibility to have/manage a direct link to a book? (manifest json data of one book loaded and show)

Federico

**Comment by aeschylus** [comment]
Hi Federico. Mirador provides a mechanism for opening any resource to a particular state. This is communicated in the configuration. You can see a guide for this here in the "[getting started](http://projectmirador.org/docs/docs/getting-started.html)" section of the project website. You may also find the [configuration guide](https://github.com/ProjectMirador/mirador/wiki/Configuration-Guides#specifying-which-manifest-will-open) and the default [settings](https://github.com/ProjectMirador/mirador/blob/develop/js/src/settings.js) file helpful.

As far as URLs are concerned, Mirador does not know anything about the URL bar by default. You can enable state-saving, but you must have a backend available to save the state. This is also in the configuration guide. My suggestion would be to decide what URL scheme you would like to use for your installation, and write some short translation code to initialise Mirador with the options you pass there when the page loads. Let me know if I can give any more clarification.

**Comment by federicolucca** [comment]
Thanks, i will try to understand how i can do it.
My situation is [mirador domain]/[typeofbook]/[bookid]
must load to the the [backend API]/[typeofbook]/[bookid] for load the json and show the first page

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
