### ISSUE TITLE
Quotes in some manifest titles are not being properly escaped/represented

### ISSUE THREAD

**Issue by doingandlearning** [ProjectMirador/mirador#1529]
When working with some RTL manifests, some of the escaped quotes are being displayed as &quot; rather than " in thumbnails only.

Attached is an example of one file name from the three places it is represented.

These two are correct:
![screen shot 2018-04-17 at 10 04 17](https://user-images.githubusercontent.com/8320213/38859849-cf88a4c4-4226-11e8-993f-08aca28624d6.png)
![screen shot 2018-04-17 at 10 04 20](https://user-images.githubusercontent.com/8320213/38859858-d1607902-4226-11e8-988b-5c4e8fbe5757.png)

This one isn't:
![screen shot 2018-04-17 at 10 03 53](https://user-images.githubusercontent.com/8320213/38859897-df966824-4226-11e8-9e3f-5fe9807fb706.png)

I have the relevant manifest but can't upload json.

Here is the relevant section:

` "label": {
            "@value": "\"ملف 61/14 XV (D 62) العلاقات بين نجد والعراق (تمرد الإخوان)\" [داخلي‎-‎أمامي‎] (٥٩٥/٢)",
            "@language": "ar"
          },`

Imagining it has something to do with how characters are being escaped in the filmstrip.

**Comment by mejackreed** [comment]
Could you post some example manifests so we could test this in Mirador 3?

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
