### ISSUE TITLE
Initial window loading sequence assumes non-empty array.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1534]
This doesn't cause a huge problem, but does output an error to the console. We should check that it is empty before attempting ot fire off fail-fated requests.

<img width="669" alt="screen shot 2018-06-20 at 1 34 24 pm" src="https://user-images.githubusercontent.com/145874/41683161-b5defe8e-748e-11e8-8761-5ee1fcb609a8.png">

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
