### ISSUE TITLE
PNG files being changed to jpg

### ISSUE THREAD

**Issue by ogloke** [ProjectMirador/mirador#1535]
I'm having trouble getting Mirador to display png files with transparency.
My manifest requests that the layer image be returned as a png (see excerpt below) 
![image](https://user-images.githubusercontent.com/41384976/43387183-af1de9d4-93dd-11e8-9b4e-a3848d791d23.png)

But mirador seems to request a jpg when it comes to displaying the image.
Here's what my browser's network inspector shows when the file is requested
![image](https://user-images.githubusercontent.com/41384976/43386973-154a1b66-93dd-11e8-85b2-a5c24ef7d789.png)
Does anybody know why this is or if there is a way of getting mirador to show the file as a png?

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
