### ISSUE TITLE
can't load new manisfest

### ISSUE THREAD

**Issue by defaliz** [ProjectMirador/mirador#1536]
Hello,
i try to load 2 news manisfest in my mirador appliance but nothing happened (with last version of mirador)
http://bibliotheque-numerique.inha.fr/iiif/32862/manifest
http://bibliotheque-numerique.inha.fr/iiif/10055/manifest

when i load this 2 urls in mirador demo, that works..
thanks for help
regards
alain

**Comment by regisrob** [comment]
Hello @defaliz,
These manifests work for me too in beta.biblissima.fr/mirador
Is your Mirador instance running on HTTPS? (if yes, this is the problem)
Are there some errors in your browser console?

**Comment by defaliz** [comment]
Yes you're wright, we must have HTTPS on bibliotheque-numerique web site...

Alain
