### ISSUE TITLE
How to access Mirador events with an event listener?

### ISSUE THREAD

**Issue by martin-hinze** [ProjectMirador/mirador#1541]
Hi everyone,

there is a list of Mirador events defined in the wiki: https://github.com/ProjectMirador/mirador/wiki/Events-in-Mirador
I don't understand yet, how to access and listen to these events and how to define the event listener function. E.g., if the user opens a new canvas, the currentCanvasIDUpdated-event should be triggered. How could I print the Updated Canvas ID to the javascript console, to get started? I would like to that with a seperate js-script. Are there maybe examples or instructions available? Any suggestions highly welcome. :-)
Best wishes,
Martin

**Comment by Susa70** [comment]
Hi, Martin. I was stuck with this too. First at all, that link with set of events is not coincidence with actual set in build version. I found some examples with using this events inside source code and next code work for me:
```JS
var miradorInstance = new Mirador({/*config*/});
miradorInstance.eventEmitter.subscribe('slotRemoved', handlerFunc);
```
Mirador v2.7.0

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
