### ISSUE TITLE
HTML elements in annotation content

### ISSUE THREAD

**Issue by iTReprise** [ProjectMirador/mirador#1542]
Hi,

I have annotations that render text and I want to underline and overline certain characters or words.
In my annotation list I'm using `"@type": "dctypes:Text"` and `"format": "text/text"`. My content is placed in a `"chars": "myText"` element.
I found out that it's possible to change the text via HTML inline-elements like `<i>` or `<b>`.
However I don't find a way to underline text. I've tried `"chars": "<p class=\"ul\">myText</p>"` and
```
.ul {
  text-decoration: underline;
}
 ```
in my web page, but that only seems to render a slightly bigger annotation and no underline.
`"chars": "<span class=\"ul\">myText</span>"` also doesn't change anything.

I'm really new with this framework and would love any help!

**Comment by iTReprise** [comment]
Thank you very much! Exactly what I missed.

**Comment by ajf-ajf** [comment]
FYI, I had this same issue, and overrided the sanitization code, but I noticed this in the spec the other day:

http://iiif.io/api/presentation/2.1/#html-markup-in-property-values
