### ISSUE TITLE
Opening a manifest can be very slow when there are many ranges.

### ISSUE THREAD

**Issue by peterprovaznik** [ProjectMirador/mirador#1544]
Hi,

we have some manifests with a large number (about 6000) of ranges for the TOC. When opening such a manifest, Mirador "freezes" for up to 15-20 seconds.

Example: http://www.cantusplanus.at/de-at/austriaca/mira/rism.php?rism=A-VOR90

Manifest: https://iiifp-mufo.oeaw.ac.at/mahss/A-VOR90/manifest

Is there a way to make the TOC-assembly perform better? If that is not an option, would it be possible to show a "Loading..." indicator, so the user at least has some indication that something is happening?

(Tested with version 2.6.0.)

Thank you,
Peter

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets. Here are some TOC examples:
https://mirador-dev.netlify.app/__tests__/integration/mirador/toc.html
