### ISSUE TITLE
Build with info layer

### ISSUE THREAD

**Issue by ericvanderlinden** [ProjectMirador/mirador#1545]
I have seen the bbmn-demo with the info layer. Is there a build that contains this functionality?

**Comment by ericvanderlinden** [comment]
Thanks for the info... I'm playing with the meta data but it seems that jQuery elsewhere in the page can only detect a click in the div with the id viewer. 
Is that deliberate?
It is not possible to detect a click on one of the thumbnails.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
