### ISSUE TITLE
请教如下图所示的错误怎么解决

### ISSUE THREAD

**Issue by hkc2017** [ProjectMirador/mirador#1546]
按照步骤所有的依赖包全部打好，npm start的时候就报下图的错误了，也没有提示具体的错误原因，请大神帮忙解决一下
![qq 20180925094943](https://user-images.githubusercontent.com/31505056/45988208-5f420100-c0a8-11e8-8de3-2b592c4d8170.png)

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
