### ISSUE TITLE
Support current node version

### ISSUE THREAD

**Issue by Sozialarchiv** [ProjectMirador/mirador#1548]
It would be great if the current or at least the LTS version of node would be supported.

At the moment node < 7 is supported which is outdated.
https://github.com/ProjectMirador/mirador/blob/develop/package.json#L88

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
