### ISSUE TITLE
'Book View' incorrect for R-to-L Manuscripts with an odd number of pages. 

### ISSUE THREAD

**Issue by Jennief** [ProjectMirador/mirador#1549]
If a manuscript has an odd number of pages, and the right-to-left viewing direction, the pages shown in 'book view' are incorrectly paired (so it no longer looks like you are opening the book). If the same manifest has a page deleted so it has an even number of pages the book view displays correctly. 

For example a manifest showing the problem (odd number of pages):
https://raw.githubusercontent.com/Jennief/randomstuff/master/MS-ADD-00433.json

and the same manifest with the last canvas removed so it has an even number of pages and does not show the problem:
https://raw.githubusercontent.com/Jennief/randomstuff/master/MS-ADD-00433-even.json

![screenshot from 2018-10-03 10-21-09](https://user-images.githubusercontent.com/4117072/46402115-c722c800-c6f6-11e8-9387-45500e47dde4.png)

**Comment by Jennief** [comment]
There is a pull request to fix this bug at https://github.com/ProjectMirador/mirador/pull/1550

**Comment by mejackreed** [comment]
Resolved in #1550
