### ISSUE TITLE
How to insert media on Mirador for annotation?

### ISSUE THREAD

**Issue by tyy0402** [ProjectMirador/mirador#1554]
I tried to add a annotation of video on "http://projectmirador.org/demo/". After I input the URL "https://youtu.be/NjTT5_RSkw4?list=RDNjTT5_RSkw4" of my video, I can see it when I edit it, but there's nothing when I save it.
I also tried the code `<iframe width="640" height="360" src="https://www.youtube.com/embed/NjTT5_RSkw4?list=RDNjTT5_RSkw4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>` But I met the same problem.
What's going on?

Thanks a lot!

**Comment by bilz01** [comment]
Did you find a solution? I am also facing the same problem

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations). Please note that attaching media to annotations is not currently supported.
