### ISSUE TITLE
projectmirador.org should accept a manifest param on query string

### ISSUE THREAD

**Issue by tomcrane** [ProjectMirador/mirador#1556]
It would be handy if you could initialise the "official" Mirador demo with your choice of manifest, like this:

http://tomcrane.github.io/scratch/mirador/?manifest=https://wellcomelibrary.org/iiif/b1932795x/manifest

Useful for demos, sharing etc.

**Comment by mejackreed** [comment]
This is available now: https://projectmirador.org/embed/?iiif-content=https://wellcomelibrary.org/iiif/b1932795x/manifest

or https://projectmirador.org/embed/?manifest=https://wellcomelibrary.org/iiif/b1932795x/manifest
