### ISSUE TITLE
preserveManifestOrder not working

### ISSUE THREAD

**Issue by berger-n** [ProjectMirador/mirador#1558]
* when opening Mirador at http://library.bdrc.io/show/bdr:W22084 with `preserveManifestOrder` set to `true`, manifest order is not preserved:

![image](https://user-images.githubusercontent.com/33383857/49078105-666ac400-f23d-11e8-964a-b0f9c2d03174.png)

* It is already at least partially working though as shown when not using that parameter and getting manifests as they are loaded:

![image](https://user-images.githubusercontent.com/33383857/49078250-c9f4f180-f23d-11e8-806d-05bd5f59e403.png)

**Comment by berger-n** [comment]
collection URL is http://iiifpres.bdrc.io/2.1.1/collection/i:bdr:I22084

**Comment by rsinghal** [comment]
`preserveManifestOrder` preserves the order of the individual manifests if they are in the `data` section of the Mirador configuration. Right now, it does not preserve the order of manifests within a collection.

**Comment by eroux** [comment]
could there be a new option for that? or maybe it could even be the default behavior?

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
