### ISSUE TITLE
Annotations: IIIF and/or Endpoint

### ISSUE THREAD

**Issue by jbarth-ubhd** [ProjectMirador/mirador#1560]
Dear reader,
I'm trying to make our annotations visible & editable for mirador.
I found out, mirador is trying to display them from our iiif, but this leads to error »shape.name is null« (after klicking on the »comments« icon - should mirador not always display existing annotations?).
Is there a documentation about the exact format expected?

How does mirador manage annotations which are present in our iiif and via an endpoint (which uses the same annotation database) - is there a way to use »endpoint« only?

Kind regards, J. Barth, Heidelberg University Library

**Comment by jbarth-ubhd** [comment]
> How does mirador manage annotations which are present in our iiif and via an endpoint (which uses the same annotation database) - is there a way to use »endpoint« only?

https://github.com/ProjectMirador/mirador/wiki/Annotation-Layer
»... getAnnotations() populates annotations in two ways:
    1. { urls = _this.manifest.getAnnotationsListUrls(_this.canvasID); }
    2. { if (this.annoEndpointAvailable) ... }«

Lets see what to do if both (Manifest & annoEndpoint) contain the same annos...

**Comment by mejackreed** [comment]
Yes you can [configure an annotation endpoint](https://github.com/ProjectMirador/mirador/wiki/Configuring-Annotations-in-Mirador#enabling-mirador-to-communicate-with-a-backend) which will store them externally

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
