### ISSUE TITLE
Cannot toggle bottom panel after switching window layout

### ISSUE THREAD

**Issue by knabar** [ProjectMirador/mirador#1566]
On window re-initialization, e.g. on layout change, existing events are not unsubscribed, resulting in duplicate event handling. In particular handling the TOGGLE_BOTTOM_PANEL_VISIBILITY event twice (or an even number of times) causes the bottom panel toggling to stop working, since every click will toggle it twice, setting it back to its original state.

Fixed in #1565

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
