### ISSUE TITLE
Setup basic window initialization from config and Mirador instantiation

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1576]
Currently the main Mirador api instantiates without any windows open. We should enable this functionality in the essence of M2.

 - [x] settings / config should be set
 - [x] plugins should be initialized 
 - [x] windows should be opened
 - [x] manifests should be added to store
 - [ ] pattern for initializing other store data.

**Comment by aeschylus** [comment]
We should talk more about this last point here: https://github.com/ProjectMirador/mirador/issues/1695

Will fill that out a bit more later, but there is a lot to cover, as we discussed to some extent today.
