### ISSUE TITLE
Window Sidebar --> Add "CanvasNavigation" information Panel

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1584]
Create a basic canvas navigation component.

![screen shot 2019-01-31 at 3 09 57 pm](https://user-images.githubusercontent.com/5402927/52091770-6dc68a80-256a-11e9-8359-d12fd386098c.png)

**Comment by camillevilla** [comment]
hi @glefi! I checked in with @mejackreed and @jvine to narrow the scope of this ticket. Please note that I've updated the screenshot above to the latest from the interactive designs. 

### Acceptance Criteria
- [ ] includes a list of canvas labels 

### Out of scope
- thumbnails
- select menu / state wiring for displaying different options from the select menu 
- icons (e.g. annotations, layers) 

### Resources
- [Interactive designs: Sidebar panel content & navigation](https://github.com/ProjectMirador/mirador-design/wiki/Mirador-3-Interactive-Designs) 
- ThumbnailNavigation implementation checklist #1661

**Comment by jkeck** [comment]
Closed by #1860
