### ISSUE TITLE
Setup i18n internationalization for strings in project

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1585]
There are several ways of implementing this. Ideally we would like an approach that could have the following traits:

 - [ ] Configured language by the Mirador adopter in the configuration
 - [ ] All locale files shouldn't need to be loaded by every instance (only configured language(s))

Possible SPIKEs to be investigated: 
- [ ] https://github.com/alibaba/react-intl-universal
- [x] https://github.com/i18next/react-i18next (#1796)
- [ ] Roll our own (see globocom/megadraft#214 for possible concerns)

**Comment by bodo22** [comment]
Maybe it's worth considering a more react-independent library for i18n, e.g. https://www.i18next.com/ .
My 2 cents would be that adding, editing and updating i18n should be as easy as possible, e.g. by using an industry standard such as gettext and .po files, or plain old json

**Comment by jkeck** [comment]
We've taken the `react-i18next` approach here (as implemented initially in #1796).
