### ISSUE TITLE
Update Workspace interface to reflect sidebar design

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1586]
## Current "Workspace"
<img width="1156" alt="screen shot 2019-01-13 at 9 13 01 am" src="https://user-images.githubusercontent.com/1656824/51087685-ab768700-1713-11e9-90b8-b12e4afca1c7.png">
## Target "Workspace"
<img width="808" alt="screen shot 2019-01-13 at 9 13 44 am" src="https://user-images.githubusercontent.com/1656824/51087688-b7fadf80-1713-11e9-8abe-ea296c075c77.png">

**Comment by camillevilla** [comment]
Seems like this first pass has mostly been addressed in #1682, with some refactoring in #1725.

Full-screen button functionality addressed by #1702 / #1713

I'm opening another ticket for the menu bar functionality:
![workspace toolbar menu](https://user-images.githubusercontent.com/5402927/51930206-e08b0680-23ae-11e9-9c06-5ebccba6abca.png)
