### ISSUE TITLE
"Add Manifest/Album" button

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1587]
When clicked, this button should open a basic "album selection interface" (which could just be a list of text for right now). When clicking on an album/manifest it should open a new `Window` with the selected manifest.

<img width="780" alt="screen shot 2019-01-13 at 9 16 23 am" src="https://user-images.githubusercontent.com/1656824/51087713-f42e4000-1713-11e9-8168-251124e7bc9c.png">

List of manifests and existing manifest form field should be contained here

@jvine did we come to a consensus on the naming here for the "Album?"

**Comment by camillevilla** [comment]
We now have an add manifest button, but it's a simple text form. 
Moving this to the backlog, as it seems like there are more pre-requisites to this view.

**Comment by camillevilla** [comment]
Adding in a backend detail that this work should address:
The manifest list should also be added to the config. This represents a list of manifests that CAN be added to the windows. Note that this list should be separate from the list of manifests currently displayed by windows. 

I'm including the GIFs below to clarify the concept:

current M3 implementation
![manifest-list](https://user-images.githubusercontent.com/5402927/52296438-3b82a780-2933-11e9-9794-edc96af79f59.gif)

example from M2
![m2-manifest-list](https://user-images.githubusercontent.com/5402927/52296679-d8dddb80-2933-11e9-8c24-b009bb9d1436.gif)

**Comment by ggeisler** [comment]
Below are several tickets that collectively represent a load window plugin that I think could meet the goal of this ticket:

- #1833 - Design for load window plugin (story ticket)
- #1834 - Implement 'List view' of load window plugin
- #1835 - Add 'Layout' option to load window tools menu
- #1836 - Implement 'Card view' of load window plugin

**Comment by camillevilla** [comment]
I've added these to the project board and am going to close this in favor of #1833.
