### ISSUE TITLE
Enable svg icon to render within a component

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1591]
Lay down a pattern for rendering SVG icons in the UI.

**Comment by bitzl** [comment]
React Docs on including SVGs for starting: 
https://facebook.github.io/create-react-app/docs/adding-images-fonts-and-files#adding-svgs

**Comment by bitzl** [comment]
There's an official React implementation for the Material Design icons by Google: https://www.npmjs.com/package/@material-ui/icons

There's also one for the larger, user contributed [Material Design Icons](https://materialdesignicons.com/):
https://www.npmjs.com/package/@mdi/react

**Comment by camillevilla** [comment]
A pattern for this was established in #1967 👏
