### ISSUE TITLE
Include webpack as a development dependency

### ISSUE THREAD

**Issue by jkeck** [ProjectMirador/mirador#1592]

**Comment by bitzl** [comment]
Is this still an issue? `webpack` and `ẁebpack-cli` are already in the  `devDependecies` section of `package.json`:

```
"webpack": "^4.27.1",
"webpack-cli": "^3.1.2"
```

**Comment by mejackreed** [comment]
@ggeisler What version of npm are you using? `npm -v` I think an update of that could resolve your issue

**Comment by ggeisler** [comment]
`6.2.0`

Maybe @aeschylus can answer better about whether this is a real issue or just a local dev setup problem. All I know is I was getting an error when running `npm start` and @aeschylus suggested running `npm install -g webpack webpack-cli` and then `npm install` again and then `npm start` worked.

I have no problem assuming it was just a local dev problem and closing this ticket if you don't think it is something that future developers who are installing Mirador for the first time will run into.

**Comment by mejackreed** [comment]
Ok lets close for now, and then we can see if anyone else runs into it.

Thanks for checking.
