### ISSUE TITLE
Add .prettierrc

### ISSUE THREAD

**Issue by bodo22** [ProjectMirador/mirador#1600]

**Comment by mejackreed** [comment]
Would this respect our eslint configuration? Or would it be similar?

**Comment by bodo22** [comment]
It's integrated into the eslint config, so it will respect that. I've found this to work well as an extension to the  the airbnb config. Maybe it's worth discusssing to add auto-formatting as a precommit hook, for easier reviewing... On the down side there would be a few commits which just lint the whole project

**Comment by mejackreed** [comment]
Closing this now as there aren't current plans on adding prettier.
