### ISSUE TITLE
Redirected requests for resources and the Redux state

### ISSUE THREAD

**Issue by mikeapp** [ProjectMirador/mirador#1621]
When a request for a resource results in a redirect, the object is stored in the Redux store under the request URI and not the `id`.  This can cause problems later if (e.g.) the Manifest is looked up later by the `id` - it will need to be loaded again (and duplicate data stored).

For `info.json` a different `id` may signal that the request has been redirected to a "degraded" version.

URLs for testing:
`http://manifests.britishart.yale.edu/manifest/5000`
`https://manifests.britishart.yale.edu/manifest/5000`

**Comment by mejackreed** [comment]
Yup :) Also relevant are degraded, info.json responses similarly stored.

**Comment by mejackreed** [comment]
This works now!
