### ISSUE TITLE
Explore the flexibility of using Material Design

### ISSUE THREAD

**Issue by sdellis** [ProjectMirador/mirador#1633]
### **Can we import a subset of components from Material Design?**
**Why:** 
For performance purposes, we only want to bundle the components we use in the distribution (not the entire library).
**Example:** 
`import { Button, TextInput } from MaterialDesign;`

### **Can we namespace Material Design for Mirador so we can avoid collisions?**
**Why:** 
We want to be certain Mirador or the containing app doesn't look different, forcing us to use an iframe to embed it.
**Example:** 
_Some app uses Material, but overrides a class and changes how Mirador looks._

**Comment by camillevilla** [comment]
Yes and yes. 
Seems like we've gone way past exploring MUI's flexibility, so I'm going to close this guy 😅
