### ISSUE TITLE
Add zoom level of OpenSeaDragonViewer to redux state for each window

### ISSUE THREAD

**Issue by bodo22** [ProjectMirador/mirador#1644]

**Comment by bitzl** [comment]
Associated WIP-PR: #1645

**Comment by mejackreed** [comment]
Do we need this at the moment? Can we deprioritize can come back to it when needed?

**Comment by camillevilla** [comment]
Could this be a prerequisite for some of the zoom and pan work in #1660?

Is this a requirement for including zoom levels in a Mirador config? 

Either way I've unassigned @bodo22 for now.

**Comment by mejackreed** [comment]
Not sure if this is a prereq for #1660 basic implementation. I think it will maybe become a bit more clear as we move forward.
