### ISSUE TITLE
Develop without failing the build on linting errors

### ISSUE THREAD

**Issue by bodo22** [ProjectMirador/mirador#1647]
While developing, the flow state is interrupted often by minor linting problems.

My suggestion would be to lint the codebase via a precommit hook, making development more flowy and letting devs lint / doc their code when ready to commit, not ealier.

Any opinions on this?

**Comment by bitzl** [comment]
Seems to me like something the IDE should help with (e.g. via auto formatting).

Precommit hooks might be an alternative, but need to be setup individually. To my personal opinion it's not comfortable to have possibly long linting sessions at the end.

**Comment by jkeck** [comment]
I agree w/ @bitzl that this feels more like a personal setup question than a project specific enforcement.

**Comment by mejackreed** [comment]
@cbeer mentioned running `npm start --force` earlier in the session to get around this. Is this something something we should document so more people know about it?

**Comment by bodo22** [comment]
About the pre-commit hooks: there's the possiblity to use a module like https://www.npmjs.com/package/pre-commit to make sure some npm run lint command is always fired before commiting.

For people who don't have auto-linting IDEs, i think it's kind of a burden to manually lint while developing. I'm currently e.g. getting errors like this (when deliberately leaving out a `;` ), making the dev-build fail. Is anyone else experiencing this when not auto-lintiing?

![image](https://user-images.githubusercontent.com/7796697/51351106-c839f400-1a5e-11e9-8834-6ec172c7c0df.png)

**Comment by mejackreed** [comment]
Closing this as pre-commit hooks haven't come up again.
