### ISSUE TITLE
configuaration  webpack

### ISSUE THREAD

**Issue by ericvanderlinden** [ProjectMirador/mirador#1655]
When I build mirador in production I get this:
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
    This can impact web performance.
    Assets: 
      mirador.min.js (734 KiB)
    
    WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
    Entrypoints:
      main (734 KiB)
          mirador.min.js

Searching around the internet (not a tech guy) I end up in a lot of suggestions and none of them work...

Could you config webpack in such a way that it just works... mirador.js will always exceed the standard 244 KiB

**Comment by mejackreed** [comment]
We are looking into ways to reduce our dependencies and overall bundle size. Thanks for filing the issue, but at the moment we are focusing on other priorities. Already Mirador 3 is 20% the size of Mirador 2.

**Comment by ericvanderlinden** [comment]
I actually overlooked the fact that my question is related to the 3.0 version:

> mirador@3.0.0-alpha.0 build /Users/ericvanderlinden/Downloads/mirador-master
> webpack --mode=production

Hash: 077b323ab44a5738537bcdd424ddb8ccdbf4c2ec
Version: webpack 4.28.4
Child
    Hash: 077b323ab44a5738537b
    Time: 37579ms
    Built at: 02/01/2019 3:21:37 PM
            Asset     Size  Chunks             Chunk Names
    m3core.umd.js  194 KiB       0  [emitted]  main
    Entrypoint main = m3core.umd.js
     [0] (webpack)/buildin/global.js 472 bytes {0} [built]
    [30] (webpack)/buildin/harmony-module.js 573 bytes {0} [built]
    [34] util (ignored) 15 bytes {0} [built]
    [36] util (ignored) 15 bytes {0} [built]
    [45] (webpack)/buildin/module.js 497 bytes {0} [built]
    [53] ./src/store.js + 13 modules 14.1 KiB {0} [built]
         | ./src/store.js 755 bytes [built]
         | ./src/reducers/index.js 1.18 KiB [built]
         | ./src/actions/index.js 185 bytes [built]
         | ./src/reducers/workspace.js 1.01 KiB [built]
         | ./src/reducers/windows.js 1.44 KiB [built]
         | ./src/reducers/manifests.js 1.58 KiB [built]
         | ./src/reducers/infoResponses.js 1.53 KiB [built]
         | ./src/reducers/config.js 494 bytes [built]
         | ./src/actions/config.js 408 bytes [built]
         | ./src/actions/window.js 1.57 KiB [built]
         | ./src/actions/manifest.js 1.47 KiB [built]
         | ./src/actions/infoResponse.js 1.44 KiB [built]
         | ./src/actions/canvas.js 435 bytes [built]
         | ./src/action-types.js 671 bytes [built]
        + 48 hidden modules
Child
    Hash: cdd424ddb8ccdbf4c2ec
    Time: 37517ms
    Built at: 02/01/2019 3:21:37 PM
             Asset     Size  Chunks                    Chunk Names
    mirador.min.js  734 KiB       0  [emitted]  [big]  main
    Entrypoint main [big] = mirador.min.js
     [2] (webpack)/buildin/global.js 472 bytes {0} [built]
    [46] (webpack)/buildin/harmony-module.js 573 bytes {0} [built]
    [50] util (ignored) 15 bytes {0} [built]
    [52] util (ignored) 15 bytes {0} [built]
    [61] (webpack)/buildin/module.js 497 bytes {0} [built]
    [69] ./src/styles/index.scss 1.19 KiB {0} [built]
    [70] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/styles/index.scss 1.15 KiB {0} [built]
    [74] ./src/index.js + 53 modules 103 KiB {0} [built]
         | ./src/index.js 85 bytes [built]
         | ./src/init.js 1.52 KiB [built]
         | ./src/reducers/index.js 1.18 KiB [built]
         | ./src/store.js 755 bytes [built]
         | ./src/config/settings.js 26 bytes [built]
         | ./src/reducers/workspace.js 1.01 KiB [built]
         | ./src/reducers/windows.js 1.44 KiB [built]
         | ./src/reducers/manifests.js 1.58 KiB [built]
         | ./src/reducers/infoResponses.js 1.53 KiB [built]
         | ./src/reducers/config.js 494 bytes [built]
         | ./src/actions/index.js 185 bytes [built]
         | ./src/config/css-ns.js 213 bytes [built]
         | ./src/action-types.js 671 bytes [built]
         | ./src/actions/config.js 408 bytes [built]
         | ./src/actions/window.js 1.57 KiB [built]
         |     + 39 hidden modules
        + 67 hidden modules
    
    WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
    This can impact web performance.
    Assets: 
      mirador.min.js (734 KiB)
    
    WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
    Entrypoints:
      main (734 KiB)
          mirador.min.js
    
    
    WARNING in webpack performance recommendations: 
    You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
    For more info visit https://webpack.js.org/guides/code-splitting/
