### ISSUE TITLE
Windowing system selection spike using react-grid-layout

### ISSUE THREAD

**Issue by cbeer** [ProjectMirador/mirador#1658]
See #1594

**Comment by sdellis** [comment]
Does this capture what we want to know to be able to make a decision? If yes, I can break these out into sub-tickets:

- Initialize the workspace with a window maximized to the viewport
	- Initialize multiple windows in specific positions 
- Allow keyboard focus via tabbing (I'm not sure there are additional accessibility concerns at this point.) 
- Close/remove window
- Add Material UI styles 
- Determine if inability to set "infinite" horizontal container is a bug in demo (vertical works)

**Comment by mejackreed** [comment]
I've been approaching this not in spinning off separate tickets, but systematically trying to accomplish each of these (and checking them off when accomplished).

**Comment by sdellis** [comment]
**Maximizing Windows**
We will be able to initialize a workspace with a window maximized to the viewport. What is still unanswered is how additional windows get added to the workspace in such a scenario. Does the new window split the screen in the visible viewport, or does it add something next to it outside the viewport. Also, is the workspace always very large, or can it be updated and "expanded" as users drag windows beyond its current boundaries?

**Grouping Windows**
Probably only resizeable as a group, may be ok. Probably won't be able to do "magnetized grouping" but would require selecting and grouping with another mechanism (Ctrl-G/Workspace menu icon). Probably will require abstraction layer that would create a new window that contained the grouped windows. Iterate through window groups (most will be just a single window).

**Comment by sdellis** [comment]
**Infinite Horizontal Container**
Looking at this a little more, it doesn't seem to be a bug in the demo. It seems like there is a fixed width for the demo. No matter what "compaction type" is used, the user can extend the workspace vertically, but not horizontally.
