### ISSUE TITLE
Responsive analysis and behavior considerations

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1666]
A single maximized window in a mobile viewport

**Comment by christopher-johnson** [comment]
it is possible to add lighthouse to CI. see https://github.com/ebidel/lighthouse-ci

**Comment by ggeisler** [comment]
Possibly related: #1703 and #1706.

From #1703:

> If a workspace containing a maximized window is resized, ideally the window should continue to be maximized within the resized workspace (e.g., if the workspace is made smaller, the maximized window will become smaller, but will still be maximized within the smaller workspace)

**Comment by ggeisler** [comment]
Closing since #1706 seems to answer the questions relevant to this ticket.
