### ISSUE TITLE
Normalize state

### ISSUE THREAD

**Issue by charbugs** [ProjectMirador/mirador#1668]
Redux docs suggest to keep state in a normalized fashion: https://redux.js.org/faq/organizing-state#how-do-i-organize-nested-or-duplicate-data-in-my-state

Therefor each state item should be treated like a database table with rows and ID's (see `window` and `manifests` in the example). A row should only contain primitives and arrays. Related objects should be stored as their own items and referenced by their ID's. Having ID's twice, as object keys and as property values of the respective object, can be convenient in iterations.

This may be an unnecessary overhead if a certain state item is meant to only store a single object/row. So I suggest to treat it in a normal way (see `config` in the example)

```javascript
{
  windows: {
    'window-1': {
      id: 'window-1',
      manifestId: 'http://foo',
      canvasIndex: 0
    },
    'window-2': {
      id: 'window-2',
      manifestId: 'http://bar',
      canvasIndex: 0
    }
  },
  manifests: {
    'http://foo': {
      id: 'http://foo',
      manifestation: '...'
    },
    'http://bar': {
      id: 'http://bar',
      manifestation: '...'
    }
  },
  config: {
    'foo': 'bar'
  }
}
```

**Comment by charbugs** [comment]
This might be also a design decision that should be documented in the wiki.

**Comment by christopher-johnson** [comment]
:+1: 
this is a good idea.  in the absence of GraphQL, it may also be useful to normalize the manifestation as well.

**Comment by jbaiter** [comment]
I think this is the way to go for the store state.

>  this is a good idea. in the absence of GraphQL, it may also be useful to normalize the manifestation as well.

This might also be worth a shot, though the level of normalization should probably be driven by actual use cases in the code. I can image that having top-level `canvas`, `annotations` and `range` keys could be useful.

**Comment by aeschylus** [comment]
I agree with this approach. We've seen that listening to arrays with connect causes frequent re-renders. @jbaiter suggests to incrementally convert the state, and I agree with that approach. I am experimenting with removing the manifestation from the store, as it complicates state serialisation.

**Comment by mejackreed** [comment]
👍 to the incremental approach also.

**Comment by bitzl** [comment]
:+1: to normalize the state and the incremental approach
