### ISSUE TITLE
Understand/Fix codeclimate coverage preferences

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1670]

**Comment by christopher-johnson** [comment]
It might be worthwhile to look at other code coverage tools (e.g. codecov.io).  [example here](https://codecov.io/gh/christopher-johnson/mirador/branch/codeclimate)

I find the codeclimate test coverage PR report to be lacking.

**Comment by mejackreed** [comment]
Great idea @christopher-johnson . I've added CodeCov integration and updated Travis with a `CODECOV_TOKEN` env var. We should be all setup for a PR to switch out codeclimate for CodeCov if someone wants to take that on.
