### ISSUE TITLE
Create list of fixtures needed for work cycle design and development

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#1677]
Refine [draft list of potential fixtures](https://docs.google.com/document/d/14HMy2TmuSz2WNK0sU7o1HX2BeHi0S2VH82DEt5LULvw/edit) to be more descriptive of what fixture data is needed for each distinct use case. 

Goal is to have a list of fixtures needed for the current work cycle (IIIF manifests and related data, such as annotation lists) with clear labels and descriptions so teams participating in work cycle development and others in the IIIF/Mirador community can provide sample data that would fulfill the goal of each use case.

**Comment by ggeisler** [comment]
Thanks @regisrob. I've given you edit access - let me know if it doesn't work.

The current list is pretty general. It was just intended to be a first-pass for discussion purposes at the Mirador 3 kickoff last week. The next step is to refine the list to be more specific about what each fixture should include to match a given use case, and then we'd look for real or semi-real manifests/annos to match each fixture need. I plan to work on refining the list soon but in the meantime if you have ideas for how to make progress on those goals, that would be great and feel free to edit or comment on the document as you see fit.

**Comment by regisrob** [comment]
Thanks @ggeisler for the clarification and for the google doc. I have a few real manifests that could be useful at some point. I will take another look at the doc asap

**Comment by ggeisler** [comment]
Here's a first stab at a wiki page listed needed fixtures: https://github.com/ProjectMirador/mirador/wiki/M3-Fixtures-&-sample-IIIF-data

The idea is we can alert the community to this page and ask them to point us to manifests and associated resources that match the "Example needed" use cases. 

It might be helpful for interested members of the development team to look over the list and edit and/or add new use cases if I missed anything that would be helpful in the current workcycle.

I'm also not clear how the development team wants to incorporate identified examples into the project itself, or if it is sufficient to have external references.
