### ISSUE TITLE
Thumbnail Navigation - review accessibility of carousel

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1690]
https://www.w3.org/WAI/tutorials/carousels/

**Comment by camillevilla** [comment]
Seems like this has been addressed in several tickets? 

- #2101
- #1932 
- [Spikes related to accessibility + lazy-loading performance tradeoffs](https://github.com/ProjectMirador/mirador/projects/1#card-18529655) (#2109)

**Comment by jvine** [comment]
The context of this has changed substantially. Will review the thumbnail grid in its current form in the context of other list controls and create new issues as necessary.
