### ISSUE TITLE
Refactor configuration processing to support various rehydration scenarios

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1695]
This is perhaps another "epic" to try to capture some of what I learned this week while attempting to design the configuration mechanism. Essentially there are three related areas that require some discussion or further research to move forward on. First, we want Mirador adopters to be able to send in a human-readable, easily writable, configuration object when they create a viewer. This object should specify two things: the feature set and behavioural settings of the viewer environment that is created (are annotations available, is there a freeform workspace option, is the collection navigation available to the user, etc.), and its initial state (how many windows are open, which canvases are they displaying, etc.). Second, we need to be able to translate this config into the redux state so the viewer can render it. Lastly, we want to be able to serialise the redux state

### Some combination... ?

**Comment by mejackreed** [comment]
Closing as this doesn't seem actionable and work has been done on this.
