### ISSUE TITLE
Add behavior for window maximize icon

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#1703]
Windows have a maximize icon in their menu bar:

<img width="165" alt="window-workspace-behavior-v_1" src="https://user-images.githubusercontent.com/101482/51776249-ade2c480-20b5-11e9-893a-81866d4662c4.png">

Expected behavior when the user selects the maximize icon:

- The maximized window expands to take the entire workspace viewport but the workspace itself doesn't change in size
- The zoom level of image should stay same when maximized, even though the window itself is larger
- The maximize icon is changed to an un-maximize icon when the window is maximized
- The maximized window should return to previous window size when the user selects the un-maximize icon, the catalog plus icon, or any action in the _workspace_ tools menu (@jvine we didn't discuss this so please comment if you have other thoughts about this)
- If a workspace containing a maximized window is resized, ideally the window should continue to be maximized within the resized workspace (e.g., if the workspace is made smaller, the maximized window will become smaller, but will still be maximized within the smaller workspace)

Examples of maximizing a window at different viewport sizes (click the maximize icon in the window menu bar to see the expected behavior):

- [desktop](https://xd.adobe.com/view/a470e834-eaef-4168-60db-aa90f130c384-d241/screen/52c93ca2-8ad3-46df-b413-52c52ce2d33a/Desktop-workspace-1024px-wide) 
- [tablet](https://xd.adobe.com/view/a470e834-eaef-4168-60db-aa90f130c384-d241/screen/d7ab6a38-aa4b-4e1e-8850-85b950045583/Tablet-workspace-768px-wide) 
- [mobile](https://xd.adobe.com/view/a470e834-eaef-4168-60db-aa90f130c384-d241/screen/9dedb59d-4245-493d-9638-465752f670ef/Mobile-workspace-375px-wide)

When the workspace contains two or more windows, the behavior is the same. The window you maximize goes into maximize mode, which overlays the workspace, so you don’t see other windows until you exit maximize mode. Here's [an example](https://xd.adobe.com/view/a470e834-eaef-4168-60db-aa90f130c384-d241/screen/b3fc7e0c-be85-4acc-ac76-de9583eae023/Desktop-workspace-1024px-wide-2-windows), where you can maximize either of the two windows (and note the van Gogh example is zoomed in, in both the original and maximized window size).

(There is a likely use case where the user wants to show a two-up (or three-up, etc.) with all of the windows as large as possible. That use case is not covered by this ticket; we currently plan for a mode (to be more fully described in future mockups) where designated windows can be grouped/locked together, and once in that mode the window group could be maximized to accomplish that use case goal.)

**Comment by camillevilla** [comment]
Let's discuss this ticket in more detail. We'll want to revisit implementation ideas for this button in Mosaic mode.

**Comment by sdellis** [comment]
Closed by #2053
