### ISSUE TITLE
Add expected behavior for adding one or more windows to a new workspace

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#1704]
We expect that one, or more than one (using the "cart" idea for either manifests or manifest canvases in the catalog mockup), window can be opened in a new, empty workspace. 

This ticket describes the proposed behavior. Obviously, how we end up implementing a windowing system could affect this proposal.

General idea:
- We treat a new workspace as a tiled workspace
- We tile new windows in a row up to the defined max columns for the viewport, then move to a new row
- Each new window added to the workspace is added in a square aspect ratio, regardless of the canvas aspect ratio
- The size of the new, square window depends on the size of user's viewport, in two ways:

1. There is a default number of columns used to place windows in the workspace, depending on the user's viewport. For example:

- Desktop: 3 columns of windows per row
- Tablet: 2 columns of windows per row
- Mobile: 1 column of windows per row

(We will need to define specific breakpoints for those general sizes.) After windows fill the available number of columns, we add the next new window to a new row. For example, here's a Desktop viewport with five new windows added:

<img width="500" alt="window-workspace-behavior-v_1" src="https://user-images.githubusercontent.com/101482/51778129-67916380-20bd-11e9-87ef-99f82cfe3624.png">

2. At any of the above general sizes, we want make the windows are large as possible, so the width of the window is also proportional to the width of the user's viewport. For example, in an 1800px Desktop viewport, each of the 3 columns/windows can be wider than in a 1200px Desktop viewport.

We'll have to work out the details when we think harder about spacing throughout the app, but for sake of example (or a starting point), here's a rough sizing example for a Desktop viewport (assuming an 8px grid based on Material UI defaults):

- workspace side menu bar = 40px
- gutter between each window and between the workspace edges = 32px
- 4 gutters * 32 = 128px
- space required for non-window layout = 40px + 128px = 168px
- so, window size would be calculated at (user's viewport width - 168) / 3 columns

We'd have similar but different (other viewports don't have the 40px workspace side menu, gutters might be a bit smaller on tablet, etc.) calculations to determine window size for tablet and mobile.

The end result would lay out new windows as in these examples: 

- [Desktop](https://xd.adobe.com/view/a470e834-eaef-4168-60db-aa90f130c384-d241/screen/c4194eb2-d613-43a2-9c89-0a2c7442cb2d/Desktop-add-single-window-to-empty-workspace)
- [Tablet](https://xd.adobe.com/view/a470e834-eaef-4168-60db-aa90f130c384-d241/screen/bd7bb23b-04c3-42ce-a75d-6ce33d7b851f/Tablet-add-one-window-to-empty-workspace)
- [Mobile](https://xd.adobe.com/view/a470e834-eaef-4168-60db-aa90f130c384-d241/screen/816d293f-626f-432e-aa03-d32d61e28555/Mobile-add-new-window-to-empty-workspace)

**Comment by jvine** [comment]
This initial design has been superseded by later decisions but we want to save it for possible future implementation.
