### ISSUE TITLE
Add control to switch workspace type in the workspace side panel (?)

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1709]

**Comment by cbeer** [comment]
I'm not sure what you mean by workspace type?

**Comment by ggeisler** [comment]
I think I know what @aeschylus means by workspace type, but I don't think we know yet that we will need workspace types (I certainly hope we can avoid needing them) so it seems premature to say a design is needed to accommodate them. I'd rather we wait to resolve the windowing system decisions before saying workspace types are a requirement that needs to be designed for.

**Comment by jvine** [comment]
Created two tickets to address this one:

Create "Select workspace type" dialog and add to workspace menu #1838
Add workspace type-specific options to workspace menu #1839

**Comment by ggeisler** [comment]
Superseded by #1838
