### ISSUE TITLE
Address using/not using WorkspaceControlPanelButtons

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1723]
In #1682, WorkspaceControlPanelButtons are removed. We should either integrate these back in or figure out what to do with that component.

**Comment by cbeer** [comment]
I've done this in #1713, unless we're committed to throwing it away..  I thought it was a key part of how plugins would inject themselves, but maybe there are other approaches?

**Comment by mejackreed** [comment]
No i think you are right, and should be how Plugins inject.

Maybe we also need a test to make sure that it is rendered?
