### ISSUE TITLE
Investigate snapshot testing in enzyme to speed up development

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1731]
Snapshot testing could potentially replace a lot of the tests we're writing that are based on checking that markup we wrote looks like the markup we wrote. Snapshot testing will also enforce greater immutability sensitivity in our test suite, requiring that the same data always produce the same result.

https://jestjs.io/docs/en/snapshot-testing

In theory, once set up, it would be MUCH faster to write tests of this kind, since you just take a snapshot once everything is confirmed, providing an extra layer of regression assurance.

**Comment by mejackreed** [comment]
Snapshot testing is something I remember looking at initially when we set up Jest, but had some initial reservations about it.

Most of my reservations come from poor experiences with other snapshot testing approaches I've previously encountered. I'd be interested to hear other's thought on this or experience with Jest snapshots. Maybe its better with Jest? The large committed diffs, the minor updates to the failing tests, merge conflicts in snapshots, and false negatives were what drove me away.

I'm all for making the developer experience better, so if snapshots improve it, by all means :) Maybe its worth a spike?

**Comment by charbugs** [comment]
I have only recently come across this topic and I intend to do some research on it in the next few days. The `matchesElement()` function of enzyme is a rather similar approach as you can simply pass a react element tree in it (see [here](https://github.com/ProjectMirador/mirador/blob/master/src/components/CanvasThumbnail.js)). But the documentation about this feature is poor so we need to figure out by experiments.
