### ISSUE TITLE
Document how to enable Collection Tree

### ISSUE THREAD

**Issue by markmatney** [ProjectMirador/mirador#1735]
I went to try out the Collection Tree feature on `release-2.x` today and noticed that in order to learn how to enable it, one would have to find [this comment](https://github.com/ProjectMirador/mirador/pull/1405#issuecomment-330352930). The content there needs to be moved somewhere else (probably to multiple places).

@dicksonlaw583 since you developed this feature, would you like to do this? I would be happy to take a stab at it if you don't have time.

**Comment by dicksonlaw583** [comment]
Done:

- Configuration examples: https://github.com/ProjectMirador/mirador/wiki/Configuration-Guides
- API listings: https://github.com/ProjectMirador/mirador/wiki/Complete-Configuration-API

**Comment by markmatney** [comment]
Thanks @dicksonlaw583 !
