### ISSUE TITLE
IIIF Thumbnails in Mirador 3

### ISSUE THREAD

**Issue by glenrobson** [ProjectMirador/mirador#1736]
I just wanted to flag the work that @tomcrane has done on the most efficient way to get a Thumbnail from a IIIF resource. There is a discussion of this issue with regards to the UV:

https://github.com/UniversalViewer/universalviewer/issues/102

and a Demo:
 * http://tomcrane.github.io/iiif-expts/getthumbnail/
 * http://tomcrane.github.io/wellcome-today/thumbs.html?manifest=http://wellcomelibrary.org/iiif/b28047345/manifest

and Code:

 * https://github.com/tomcrane/iiif-expts/tree/gh-pages/getthumbnail

Relates to #1661.

**Comment by mejackreed** [comment]
Thanks @glenrobson ! Closing this issue now.
