### ISSUE TITLE
Add placeholder state styling to window elements to communicate when the associated manifests are being loaded

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1748]

**Comment by jkeck** [comment]
Something that came up when `media.nga.gov` was timing out, is that an error scenario would be good to build in.  Not sure if that's for this issue, or spun out into another one,  but wanted to make sure it was documented somewhere.

**Comment by aeschylus** [comment]
Pinging @jvine and @ggeisler about this here. It's not obvious why this is a problem necessarily, as computers are the worst, so I'll spell it out here (sorry if this is already understood):

A choice was made to allow the user to open a window containing a manifest that has not yet loaded. This choice could potentially be reversed. Essentially these buttons are rendered, with callbacks enabled, and have their text populated, without yet requesting the manifest:

<img width="398" alt="screenshot 2019-02-05 at 10 17 32 am" src="https://user-images.githubusercontent.com/145874/52295205-0aed3e80-2930-11e9-9332-3adabd79b0c5.png">

The AJAX request shell game can go a few different ways, and there are [technical issues](https://github.com/ProjectMirador/mirador/issues/1620) to deal with separately. Currently, because our manifest picker is rather basic, we don't need to fetch manifests until they are opened, but when we want to provide a more fully-featured catalogue, we will have to start fetching manifests as soon as the application loads (in order to have the data to build thumbnails, titles, and so forth). So, depending on how we implement the catalogue, we may not need a loading state for windows for the same reasons we currently do.

This only partially fixes the problem, however, since then there's the initial loading case. If several windows have been specified to open in the config, then they will try to grab their manifests immediately. We currently have no design to communicate to the user when they are loading, or and no fail state or fallback for when the manifest the window depends on fails to load. Should there be a retry option? What should the text be? Etc.

**Comment by ggeisler** [comment]
@aeschylus @camillevilla Do you think #1963 and #1966 represent the goal of this issue enough that we can close it?
