### ISSUE TITLE
Window sidebar --> Companion window --> implement "popping out" to  right 

### ISSUE THREAD

**Issue by camillevilla** [ProjectMirador/mirador#1752]
This ticket implements toggling the Window sidebar content from the left side of the window to a the right companion window. 

It would be ideal if #1583 is implemented first, but it's not necessarily a blocker. 

![sidebar open, companion window closed](https://user-images.githubusercontent.com/5402927/52002846-df71dc00-2477-11e9-9c0e-e4291cc41548.png)
![sidebar closed, companion window open](https://user-images.githubusercontent.com/5402927/52002908-ff090480-2477-11e9-9c3a-c60059db1b87.png)

### Resources
[Interactive design](https://xd.adobe.com/view/1a628598-6843-4d25-67cb-d9e42eff6617-6c53/screen/4442ab28-e7a0-4ad4-962d-74506597c24d/Companion-right-default)
- Possible architectural consideration: note that an info panel, right companion window, and bottom companion window can be open simultaneously.

### Acceptance criteria
- [ ] The companion window is available for any Window sidebar menu item

Clicking on the companion window button
- [ ] Closes the window sidebar info panel
- [ ] Keeps the window sidebar menu open (i.e. icons showing, but no icon is selected)
- [ ] Opens the right companion window with content
- [ ] ~The image viewing area remains the same size (e.g. image is not clipped); total window area increases to accommodate the companion window~ <-- Technical considerations for this will be split out to another ticket 🎟

The open companion window
- [ ] Has a header area 
- [ ] Has a working close button

### Out of scope
Drag button and behavior / moving content to bottom companion window. Splitting that out to #1754

**Comment by jkeck** [comment]
Question: Should the companion window "track" behavior that's happening in the viewer like the original panel it was "popped out" from does? 

Or another way of asking: If I have the canvas/manifest metadata info panel open, pop it out to a right companion window, then paginate to a different canvas, does the right companion window have the new canvas' metadata or does it show the metadata of the canvas it was popped out from?

**Comment by jkeck** [comment]
Also, is `Companion Window` the intended to be the heading for all companion windows, or is that placeholder text?

**Comment by jvine** [comment]
`Companion window` is placeholder. Heading should match what it is - `Annotations` or `About` or whatever.

> Should the companion window "track" behavior that's happening in the viewer like the original panel it was "popped out" from does?

Yes.
