### ISSUE TITLE
Windowing System(s) Master Ticket

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1757]
We had a longer discussion today about some of the outstanding design, implementation, and sequencing concerns pertaining to the windowing system(s). We uncovered areas of remaining design and implementation fuzziness, as well as sequencing questions. Some aspects were clarified enough to conclude that we should continue with the "roll our own" spike in support of an overlapping windowing system, and leave the react-grid-layout PR open for consideration for now.
## High-level Non-design-specific Requirements
This list represents tasks or scenarios that need to be addressed by the windowing system. They should be stated in such a way that, as far as possible, they make no reference to a particular system or implementation unless the user(s) specifically asked for them in interviews.
- [ ] (a.) Add windows to the workspace
- [ ] (b.) Compare window content to content of other windows
- [ ] (c.) Provide reasonable responsive behaviour ("mobile friendly")
- [ ] (d.) Remove Windows from the workspace
- [ ] (e.) Find a specific open window and focus it
- [ ] (f.) Full-screen a window
- [ ] (g.) Resize windows (note that this can happen in any of the different paradigms we've described, the difference being the behaviour of surrounding windows in response to resizing a window)
- [ ] (h.) Move windows in relation to each other
- [ ] (i.) Synchronize behaviour between selected windows
- [ ] others...
## High-level prioritization
 - [ ] Implementation scenario that handles an embedded view 1-up (relative full workspace "layout")
 - [ ] Implementation scenario that handles an embedded two-up (relative full workspace "layout")
# Existing Tickets and Resources
### Free-form Workspace
**[Spike PR](https://github.com/ProjectMirador/mirador/pull/1759) ([Demo](https://deploy-preview-1759--mirador-dev.netlify.com/__tests__/integration/mirador/))**
- We want some mode that allows arbitrary dragging and resizing of windows
- In free-form, adding a window is well-specified
- Adding multiple windows is well-specified
- There is no change to the layout in response to viewport changes #1706 
### React-grid-layout Affordances
**[Spike PR](https://github.com/ProjectMirador/mirador/pull/1594) ([Demo](https://deploy-preview-1594--mirador-dev.netlify.com/__tests__/integration/mirador/))**
### "Mosaic" mode
**[Spike demo](https://deploy-preview-1777--mirador-dev.netlify.com/__tests__/integration/mirador/)**
### _Slot-based Comparison Builder (? is this just "Mosaic mode behaviour"?)_
# Implementable Plan
# Explicitly Out of Scope (until further review)
Minimizing windows https://github.com/ProjectMirador/mirador-design/issues/36

**Comment by jvine** [comment]
Proposed approach is to provide 3 user-selectable workspace modes:

1. free-form: elastic workspace beyond the Mirador viewport; windows can be overlapped
2. grid: workspace is horizontally constrained but scrolls vertically; windows can be positioned with some flexibility within a grid layout.
3. mosaic: workspace is constrained to the Mirador viewport; windows are tiled to fill the space completely.

<img width="1761" alt="screen shot 2019-02-01 at 12 59 04 pm" src="https://user-images.githubusercontent.com/6945691/52149331-31099a80-2621-11e9-840d-fb0659643979.png">

[Mockup](https://xd.adobe.com/view/f6d0b49c-f2cc-467b-4ee4-fde8f4a6276c-80e1/)

These frameworks will provide the default behaviour in each mode:

1. our own free-form implementation
2. react grid
3. react mosaic

Design tasks:

- [ ] Modify workspace tools menu to provide affordance to select modes and mode-specific features
- [ ] Determine default settings for grid mode
- [ ] Design transitions from one mode to another
