### ISSUE TITLE
Adjust window layout: bottom + right companion windows

### ISSUE THREAD

**Issue by camillevilla** [ProjectMirador/mirador#1760]
Related #1714 / #1715 

This ticket shakes out of a discussion @jkeck and I had with @jvine. I think we could still move ahead with basic implementations of companion windows in #1754 and #1752. This design becomes relevant in cases where we have both a bottom companion window and right companion window open. 

I'm interested in @mejackreed's opinions re: implementation, and am tagging this with @jvine and @ggeisler to confirm this layout change.  

## Currently implemented
![window-layout](https://user-images.githubusercontent.com/5402927/52032808-6bffb700-24d7-11e9-8e48-9efb16cf475b.png)

## Proposed
**Image updated March 4**
![proposed window layout](https://user-images.githubusercontent.com/6945691/53747118-6c34fe80-3e57-11e9-821f-67e234f37696.png)

![screen shot 2019-01-30 at 3 57 52 pm](https://user-images.githubusercontent.com/5402927/52032779-4b376180-24d7-11e9-9da3-8734a396df89.png)

## Resources
- [Interactive designs](https://github.com/ProjectMirador/mirador-design/wiki/Mirador-3-Interactive-Designs) --> Companion window behavior
- #1715: original layout design
- [CSS prototyping codepen](https://codepen.io/mejackreed/pen/MLezVX)

**Comment by jvine** [comment]
Comment above says for both window types:

> can be split **vertically** into multiple companion windows

which isn't accurate. It's hard to be unambiguous about the behaviour in terms of "splitting vertically/horizontally", so let me try it this way:

Companion windows are a specific shape (vertical or horizontal) and can stack within their allocated region.

Primary window = Canvas area, including left side menu and panel. 

Horizontal companion window exists below the primary window, and is the same width as the primary window. Multiple horizontal windows can stack below the primary window, maintaining the same width.

Vertical companion window exists to the right of the primary window and is the same height as the primary window + its horizontal companion windows. Multiple vertical windows can stack beside the primary window, maintaining the same height. 

_Alternative approach: Implement React Mosaic framework within the window, allowing full flexibility in placing and splitting companion windows. :-)_

**Comment by charbugs** [comment]
I added this issue to the [companion window card](https://github.com/ProjectMirador/mirador/projects/1#card-17532968) in the project board because I consider it as a prerequisite for #1754 .

**Comment by aeschylus** [comment]
https://github.com/ProjectMirador/mirador/issues/1760

**Comment by cbeer** [comment]
Fixed by #2045
