### ISSUE TITLE
Remove unused config property from <App/>

### ISSUE THREAD

**Issue by christopher-johnson** [ProjectMirador/mirador#1764]
config is set with the `setConfig` action, so this property can be removed

**Comment by christopher-johnson** [comment]
still an issue
https://github.com/ProjectMirador/mirador/blob/master/src/lib/MiradorViewer.js#L32

**Comment by cbeer** [comment]
👌 ; i figured we were now using config with the theming stuff, but I see it's the config coming from state instead.
