### ISSUE TITLE
Consider refactoring components to be more generic

### ISSUE THREAD

**Issue by glefi** [ProjectMirador/mirador#1768]
Maybe it would useful to make components like buttons etc. more generic, especially renaming them, to increase reusability. E.g. there is a 'WorkspaceMenuButton', but it could be used anywhere else within mirador, as the handlers are passed as properties anyway. So it is not necessarily tied to the workspace.

I also suggest to create subfolders like 'buttons' within the components folder, because there are already a lot of components.

**Comment by cbeer** [comment]
I've been resisting the temptation to refactor and consolidate until we have a clear view of what the common components are. I agree it's certainly something we should do, I'm just not sure now is the best time for it.

**Comment by glefi** [comment]
I had a look on all components, but a lot of refactoring seems the be already done within other issues. I wasn't able to find any component with a great necessity for refactoring at all. @cbeer What do you think?
