### ISSUE TITLE
Communicate to the user when a canvas is blank

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1772]
- [ ] Add a special placeholder in the thumbnail navigation strip
- [ ] Add some sort of visual indication of a lack of images on the canvas

Fixture: https://demos.biblissima.fr/iiif/metadata/florus-dispersus/manifest.json
Context: https://github.com/ProjectMirador/mirador/wiki/M3-Fixtures-&-sample-IIIF-data#canvases-with-no-image-or-any-resources

**Comment by jkeck** [comment]
A few questions/comments:

- @jvine  / @ggeisler do you guys have an idea of what kind of placeholder we want?
  - We own the thumbnail strip, so it will be easy to add something there. We currently have a gray square, is there some other sort of placeholder we should use instead in general?
- What is shown in the OSD canvas area might be a little tricker (and maybe could be split out into a separate issue).
- As of now, manifests like this cause Mirador to error out and give a WSOD, and I'll submit a PR first to  fix that.

**Comment by ggeisler** [comment]
@jkeck Not sure if you've looked at #1972 (for the window canvas) and #1970 (thumbnail strip)?

**Comment by jkeck** [comment]
Hmm, I wonder what the purpose of this ticket is then...

**Comment by jkeck** [comment]
Oh, one question and something that I could potentially fix when addressing the WSOD bug, is should a thumbnail for a canvas w/ no image be "clickable"?  Currently it is not, and one can only get there from using the next/previous canvas navigation.

**Comment by jvine** [comment]
I think there's some value in being able to click directly on a canvas with no image in order to see its companion content.

**Comment by ggeisler** [comment]
Yep, was about to say the same thing.

Also, sorry @jkeck, I didn't realize this ticket existed when I was writing up all the placeholder tickets, otherwise I would've referenced it.

**Comment by jkeck** [comment]
No worries, here is what I think I may do:

This issue will be about fixing the White Screen of Death for these types of manifests, and enabling clicking on the image-less thumbnails, and I'll let the other issues represent the other features (since they are in the Backlog).

Does that sounds good to folks? (cc: @camillevilla / @mejackreed)
