### ISSUE TITLE
CanvasNavigation Panel --> Compact list, implement click + canvas change behavior

### ISSUE THREAD

**Issue by camillevilla** [ProjectMirador/mirador#1773]
This ticket implements behavior for UI elements introduced by #1584 

![list of canvas labels](https://user-images.githubusercontent.com/5402927/52091770-6dc68a80-256a-11e9-8359-d12fd386098c.png)

### Acceptance Criteria
- [x] Clicking on a canvas label opens that window to the appropriate canvas
- [x] `canvasIndex` is updated in the state

### Out of scope
- thumbnails
- select menu / state wiring for displaying different options from the select menu 
- icons (e.g. annotations, layers) 

### Resources
- [Interactive designs: Sidebar panel content & navigation](https://github.com/ProjectMirador/mirador-design/wiki/Mirador-3-Interactive-Designs) 
- ThumbnailNavigation implementation checklist #1661. The `SET_CANVAS` action should be reusable in this context.

**Comment by jkeck** [comment]
Closed by #1913
