### ISSUE TITLE
Display canvas level data in the About this item panel

### ISSUE THREAD

**Issue by jkeck** [ProjectMirador/mirador#1780]
Split out from #1583

<img width="500" alt="canvas-level-md" src="https://user-images.githubusercontent.com/96776/52140723-576f0c00-2608-11e9-9b69-965368327c9b.png">

_Also, see #93 for an older ticket that was also requesting this feature in previous versions_

### Resources
- [Interactive designs](https://github.com/ProjectMirador/mirador-design/wiki/Mirador-3-Interactive-Designs) > Sidebar panel content & navigation

**Comment by jvine** [comment]
My understanding is:

- a canvas should have a label; if it doesn't, we need to create a placeholder ("1", "2"...)
- additional metadata can be provided in label/value pairs

Here's an example manifest that has a little bit of canvas metadata in addition to the label: https://media.nga.gov/public/manifests/nga_highlights.json

which might look like this:

<img width="327" alt="screen shot 2019-02-01 at 10 55 06 am" src="https://user-images.githubusercontent.com/6945691/52143269-e7648400-260f-11e9-9e07-3029d1fcd0fe.png">

(Note that there's still some open design around the "# of n" navigation - there's variation in the mockups that we need to reconcile. https://github.com/ProjectMirador/mirador-design/issues/35)

**Comment by aeschylus** [comment]
The [fixtures ticket](https://github.com/ProjectMirador/mirador/wiki/M3-Fixtures-&-sample-IIIF-data#canvas-level-metadata) @ggeisler put together also has a fixture for canvas-level metadata from @regisrob. Here's my understanding. I think if the following mapping should permit this to be worked on. I'm assuming the dotted pink box is where the "lorem ipsum" text from the first mockup in this thread would come from/go.

<img width="985" alt="screenshot 2019-02-01 at 11 50 32 am" src="https://user-images.githubusercontent.com/145874/52146195-e5062800-2617-11e9-9aae-5856334ce1f5.png">


The other aspect is the "manifest-level metadata". This is the `label`, `description`, and key-value pairs in the metadata field on the top-level node of the manifest tree.

Two design follow-up question I have are:
- How can we make the hierarchical relationship between the manifest and canvas a little clearer. I understand the reasons for having the manifest metadata at the bottom, but is there additional visual encoding we can give to it (or perhaps even contextual text) to make it clear that this pertains to the whole item in the window?
- The fixtures we have don't have too many key-value pairs, but I have seen examples where there are dozens to over a hundred pairs in the metadata fields (I think I remember seeing some Vatican manuscripts like that). Should be plan for a "see more" type collapsible link, or just roll with listing them all out for now?

**Comment by jvine** [comment]
Hah - at a glance, I thought "Description: Painting" was describing the canvas in some kind of IIIF-y way, and not metadata about the canvas. It would just be another label-value pair, with no assumption about it being before or after the metadata "section". I.e. the pink space is just space and additional metadata would follow in the order it appears. 

Yes, agree on the other two questions; we will need a "show more" pattern and some labelling about relationships, but these will need to apply in lots of places. For now, I'd like to just list the complete metadata.

**Comment by camillevilla** [comment]
Removed the design needed label for now. 

We will need design around multi-lingual metadata, but I'm fine with assuming one language for whoever implements this ticket.

**Comment by jkeck** [comment]
Is canvas `description` specified anywhere?  I'm not seeing any references to it in the spec, but haven't looked exhaustively.  There also isn't support for it directly in manifesto for canvases AFAICT, although I can access the property directly if need be.  If we do want to include `description` should it be label-less or should we give it a label like "Description".  The only examples I've seen don't have a label/value pair and is just a descriptive string.

**Comment by cbeer** [comment]
There's a bunch of `MAY`s here: https://iiif.io/api/presentation/2.0/#descriptive-properties. I'm not sure I've seen much of this in the wild though.

**Comment by jkeck** [comment]
Ah, okay, it's more generic.  So yeah, looks like it's either HTML or a plain string, so we'll need to know if we should label it or not.
