### ISSUE TITLE
Creating an integration test with two Miradors embedded in the same page, and making sure they don’t interact

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1782]
Make sure that our styles are not interacting with external parts of a webpage. 

### Acceptance criteria
 - [x] Create an integration test page with two mirador instances and other html content #1782
 - [x] Evaluate and fix any interaction between the mirador instances and the containing pages
 - [x] Use non-fixed sidebar https://github.com/ProjectMirador/mirador/issues/1804 
 - [ ] Spin off any larger chunks of work to additional tickets

**Comment by aeschylus** [comment]
This is under way in https://github.com/ProjectMirador/mirador/pull/1829

Off the bat there seem to be some initialisation problems. Still working through them but would love extra eyes on that at some point.

**Comment by mejackreed** [comment]
Closing this now, I think the acceptance criteria is met.
