### ISSUE TITLE
Making the text in the sidebar themable

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1786]
![screen shot 2019-02-01 at 4 33 42 pm](https://user-images.githubusercontent.com/1656824/52155275-2d850c00-263f-11e9-9122-128e6b6a5db2.png)

**Comment by camillevilla** [comment]
Depends on #1755

**Comment by camillevilla** [comment]
Some resources:
- [Material Design re: accessible colors](https://material.io/design/color/the-color-system.html#color-theme-creation)
- [Apple's Dark Mode guide](https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/dark-mode/)
