### ISSUE TITLE
Workspace sidebar --> Download / export workspace

### ISSUE THREAD

**Issue by camillevilla** [ProjectMirador/mirador#1787]
This ticket adds a simple export of the workspace's config as a JSON object. This Mirador config is not final by any means. Our goal is to have something to share with other M3 devs, plugin authors.

![Menu with "Download/export workspace" option](https://user-images.githubusercontent.com/5402927/52155437-abddb000-2637-11e9-822e-7a2747d1a087.png)

### Acceptance Criteria
- [x] "Download / export workspace" option toggles a dialog box
- [x] Dialog box contains a simple JSON version of the initialization config 
- [ ] JSON includes the following items from state:
  - [x] config
  - [x] windows
  - [ ] Manifest URIs
- [ ] The JSON exported should be simpler than (i.e. not a copy of) the Redux state

### Out of Scope
- importing a config via the UI (design needed)
- URL <--> config mapping #1665 

### Resources
- #1755 implements a sidebar option to fullscreen dialog using MUI components
- [Config currently used in demo](https://github.com/ProjectMirador/mirador/blob/master/__tests__/integration/mirador/index.html#L14-L21)

After further discussion with @mejackreed, we've decided that #1697 is not a blocker.

**Comment by cbeer** [comment]
Do we need manifest URIs separate from the manifestId attribute from each window?

**Comment by camillevilla** [comment]
I believe they're the same? @mejackreed

**Comment by aeschylus** [comment]
The “config” above already includes the manifest uris, or should.

Within the config, it is necessary to have the manifest uris in addition to those that happen to be open in windows, so that users can have the listed manifests available to pick from.

**Comment by camillevilla** [comment]
Noted. I've thrown in this detail about manifest URIs in #1587, where it's more relevant to implementation. 

current M3 implementation
![manifest-list](https://user-images.githubusercontent.com/5402927/52296438-3b82a780-2933-11e9-9794-edc96af79f59.gif)

example from M2
![m2-manifest-list](https://user-images.githubusercontent.com/5402927/52296679-d8dddb80-2933-11e9-8c24-b009bb9d1436.gif)
