### ISSUE TITLE
Create Mosaic workspace mode

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#1788]
### Related
- #1757 (master windowing ticket)
- Spike PR #1777 and [demo](https://deploy-preview-1777--mirador-dev.netlify.com/__tests__/integration/mirador/)
- [React mosaic demo](https://palantir.github.io/react-mosaic/)

<img width="1025" alt="screen shot 2019-02-01 at 9 54 18 am" src="https://user-images.githubusercontent.com/6945691/52155362-2e19a480-2637-11e9-88e9-366edac737fa.png">

### Mosaic mode
- invoked when the user selects it as their workspace preference
- windows are constrained to the visible workspace / "viewport"
- the combination of open windows fills the viewport, with no white-space
- windows can be dragged into new configurations by predictable splitting behaviour
- layout is responsive in terms of window size
- in general, the layout and behaviour of tools and features within windows are consistent with other modes

### Design issues
- [ ] predictable behaviour for adding windows
- [ ] replacing the content of a window
- [ ] identify window behaviours that need to be suppressed or modified in this mode
- [ ] ...

**Comment by ggeisler** [comment]
Closing because the only remaining thing we think we really need is in #2145.
