### ISSUE TITLE
Add some kind of indication to the image view that the zoomable canvas is loading but not yet initialised.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#179]

**Comment by aeschylus** [comment]
In general we don't communicate the loading status and especially failure status of things to the user. Perhaps we should create an overview issue for those kind of things.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
