### ISSUE TITLE
Create free-form workspace

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#1792]
### Related
- #1757 (master windowing ticket)
- #1662  
- Spike PR #1724  and [demo](https://deploy-preview-1724--mirador-dev.netlify.com/__tests__/integration/mirador/)

<img width="1024" alt="screen shot 2019-02-01 at 9 53 22 am" src="https://user-images.githubusercontent.com/6945691/52157179-f3693980-2641-11e9-9d00-0c20f0c47ea8.png">

### Freeform mode
- invoked when the user selects it as their workspace preference
- workspace is elastic both horizontally and vertically around the application viewport
- windows are independently sized and can overlap
- windows can be dragged to any new position
- layout is not responsive - size and placement of windows is retained across devices
- has an exposé feature that allows the user to see all the open windows within the app viewport and select one to focus
- has an "arrange in columns" feature that resizes and reflows windows in columns without applying snap-to-grid
- in general, the layout and behaviour of tools and features within windows are consistent with other modes

### Design issues
- [x] predictable behaviour for adding windows 
   #1705 - adding one or more windows to an existing workspace
   #1704 - adding one or more windows to a new workspace
- [ ] behaviour of exposé feature
- [ ] behaviour of "arrange in columns" feature (and name) 
- [ ] identify window or application behaviours that need to be suppressed or modified in this mode
- [ ] ...

**Comment by ggeisler** [comment]
Closing in favor of individual tickets that exist related to elastic mode.
