### ISSUE TITLE
Add logo to window topbar

### ISSUE THREAD

**Issue by camillevilla** [ProjectMirador/mirador#1794]
![companion_window_behaviour](https://user-images.githubusercontent.com/5402927/52158516-dcc8df80-264d-11e9-8018-33354a92b941.png)

### Acceptance Criteria
- [ ] If no `logo` attribute is provided, logo should be flush left (i.e. no blank divs)
- [ ] If a `logo` is provided in the manifest:
  - [ ] Logo resizes to display in the window topbar. Aspect ratio should be preserved.
  - [ ] only allows valid file extensions to be rendered
- [x] handles single logos ([v2.0](https://iiif.io/api/presentation/2.0/#rights-and-licensing-properties))
- [x] selects the first logo available if provided with an array of strings ([v2.1+](https://iiif.io/api/presentation/2.1/#logo))
- [x] extracts logo if presented with an array of JSON objects ([v3.0](https://iiif.io/api/presentation/3.0/#logo))

**Note:** 
We received a request to make Mirador v2.1 compliant (#1487) in October 2017. [I'm not sure that manifesto handles v2.1+](https://github.com/IIIF-Commons/manifesto/search?q=getLogo&unscoped_q=getLogo), so this may be an opportunity to contribute upstream. If that gets too hairy, feel free to start with the v2.0 case and split the others out.

### Resources
- [Interactive designs](https://github.com/ProjectMirador/mirador-design/wiki/Mirador-3-Interactive-Designs)
- [IIIF Presentation v2.1: logo spec](https://iiif.io/api/presentation/2.1/#logo)
- [IIIF Presentation v3 draft: logo spec](https://iiif.io/api/presentation/3.0/#logo)
- Manifesto docs: getLogo()
  - [Docs](https://iiif-commons.github.io/manifesto/classes/_manifest_.manifesto.manifest.html#getlogo)
  - [Code snippet search](https://github.com/IIIF-Commons/manifesto/search?q=getLogo&unscoped_q=getLogo)
- Fixtures
  - [v2](https://purl.stanford.edu/fr426cg9537/iiif/manifest)
  - v2.1 
  - v3: docs only?

**Comment by cbeer** [comment]
I've started work on this ticket; it's interesting that the two default manifests have logos that aren't... uh.. as nice as the mockups.

When we say aspect ratios should be preserved, we're talking about the aspect ratio of the source image?

Is there more information about what we mean by: 

> only allows valid file extensions to be rendered

**Comment by camillevilla** [comment]
@cbeer 
> only allows valid file extensions to be rendered

I'm talking about whitelisting image formats. e.g. suppose there's a link to a `.pdf` file. I'm hoping no one throws something like that in their manifests, but my experience with brand asset management tells me that, well... anything can happen.

>Two default manifests have logos that aren't... uh.. as nice as the mockups.

Would you mind creating a new ticket with:
- links to the manifests
- screenshots

I know @ggeisler mentioned there's more design work to be done around these cases, so it would be good to provide some fixtures. 

> aspect ratios should be preserved
we should try our best to smush them into the topbar. I'd rather see illegibly tiny logos than weirdly horizontally stretched logos.

**Comment by ggeisler** [comment]
We definitely want to preserve aspect ratio. The question (to me, anyway) is whether we limit horizontal width in some way to prevent horizontally-oriented logos from consuming too much topbar space (and whether we omit display of logos at some viewport or window width to gain as much topbar space as possible where topbar space is limited).

Here are a couple of examples of horizontally-oriented logos from our existing fixture list:

http://beta.biblissima.fr/iiif/manifest/ark:/43093/desc57cb76cd3739a24a9277b6669d95b5f3a590e771

![logo-biblissima-350w](https://user-images.githubusercontent.com/101482/52289325-08d4b100-292b-11e9-9ea6-f912e9af36c6.jpg)


https://gallica.bnf.fr/iiif/ark:/12148/btv1b10022508f/manifest.json

![bnf](https://user-images.githubusercontent.com/101482/52289343-0f632880-292b-11e9-9c33-0fde30636c1f.png)

I believe I've also seen manifests from Harvard Art Museum that have a similarly oriented logo, but can't find an example at the moment.

**Comment by cbeer** [comment]
> I'm talking about whitelisting image formats. e.g. suppose there's a link to a `.pdf` file. I'm hoping no one throws something like that in their manifests, but my experience with brand asset management tells me that, well... anything can happen. If this is something that manifesto already accounts for, then tick this requirement off.

No, manifesto doesn't look or care; I guess maybe the IIIF spec suggests logos should be images, and the HTML `<img>` tag will take care of ensuring it's a renderable image, so maybe no work is required on our part (at least until we get into the business of selecting the best possible `logo` to render...)
