### ISSUE TITLE
Exclude blueprint warning from linter/build system output

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1806]
React Mosaic requires a less-based style framework called blueprint, but can be used without these styles (as we are doing). However, the JS dependency still gets registered, causing this:

<img width="1000" alt="screenshot 2019-02-04 at 4 56 41 pm" src="https://user-images.githubusercontent.com/145874/52247302-3f181f00-289e-11e9-9ba8-8fcb4df12e64.png">

**Comment by sdellis** [comment]
Looks like [the maintainers of react-mosaic are not concerned about this warning](https://github.com/palantir/react-mosaic/pull/92).  

@aeschylus Would suppressing the warning with [this webpack plugin](https://www.npmjs.com/package/webpack-filter-warnings-plugin) be acceptable? If not, it seems like the next step would be fixing and submitting a PR to react-mosaic, no?

**Comment by aeschylus** [comment]
Strange opinion to hear from them. We have a good number of dependencies at this point, and none of them produces any warnings at all.
