### ISSUE TITLE
Generify fetch actions

### ISSUE THREAD

**Issue by christopher-johnson** [ProjectMirador/mirador#1808]
fetch actions are generic.  creating distinct fetch actions by response type is unnecessary and leads to duplication. (e.g. `infoResponse`, `manifest`, etc..).  There are a lot of potential fetch responses, so this pattern will become unwieldy going forward.

propose naming 4 basic fetch action types: `REQUEST, RESOLVE, REJECT, ABORT`.  

A fetch action creator function would look like this:
```javascript
/**
 * resolve - action creator
 *
 * @param id
 * @param  {String} url
 * @param  {Object} json
 */
export function resolve(id, url, json) {
  return {
    type: ActionTypes.RESOLVE + id,
    url,
    json,
  };
}
```
where `id` (a name describing the response e.g. MANIFEST) is provided to the action creator by the specific fetch function (e.g. `fetchManifest()`)

**Comment by cbeer** [comment]
Besides IIIF info responses and manifests, what other fetches are you anticipating?

**Comment by christopher-johnson** [comment]
any IIIF resource can be dereferenced (canvas, annotation, etc.).  also, discovery, search and auth apis.  the list of potential fetch response types is very long.
