### ISSUE TITLE
Reduce overall whitespace in Material UI theme

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1814]
Maybe it's just me (sanity check @jvine, @ggeisler), but the whitespace in the default MUI theme seems extremely excessive to me, and a lot more capacious than the (admittedly, non-visual) designs originally given, likely due to MUI's "mobile-first (a.k.a. Android-first)" design intentions. Is there a way to dial this down through theming?

This is the styleguide affecting the relevant areas: https://material.io/design/layout/spacing-methods.html#spacing. It seems some combination of the `padding` and `vertical spacing` variables should allow us to adjust this. There also seem to be extra margins on all dropdowns coming from somewhere (see the thumbnail options popout menu and the global workspace sidebar.

**Comment by camillevilla** [comment]
This seems a little premature. MUI lets you adjust things through variables, as well as override CSS per component type. 

But without visual design from @jvine and @ggeisler I'm not sure this ticket is actionable. They mentioned forthcoming work on a style guide so I'll look to that for more guidance on this issue.

As far as theming priorities go, I would rather see more engagement re: theming use cases #1649 and making non-MUI coponents themable. And I have yet to see additional review on #1755.

**Comment by jvine** [comment]
Closing this in favour of #2214.
