### ISSUE TITLE
Refactor zoom level redux state to use a IIIF bounds rather than a point

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1818]
This is a problem for state restoration, since a user trying to share a view of something cannot guarantee the size or aspect ratio of the other user's viewport. Maintaining zoom level does not help in this case. Therefore, we should store a bounding box in IIIF coordinate space. Using OSD's "fitBounds" feature can then ensure the shared view is framed and fully visible (Mirador 2 used this method).

This is also the method suggested in the import-to-viewers specification ([content state](https://preview.iiif.io/api/import-to-viewers/api/import/0.1/#content-state), [example](https://preview.iiif.io/api/import-to-viewers/api/import/0.1/#41-a-region-of-a-canvas-in-a-manifest)).

"Zoom level" has no interoperable semantics.

**Comment by mejackreed** [comment]
I'm not sure that we can guarantee the window size will always be the same. Because of this, centerpoint / zoom seems like a sufficient subsitute. Closing this until we have some more data points and someone implements content state initialization with xywh.
