### ISSUE TITLE
thumbnail requests using native.jpg, should it be default.jpg?

### ISSUE THREAD

**Issue by jeffreycwitt** [ProjectMirador/mirador#1831]
As of 2/7/2019, current master branch is requesting thumbnails with "native" quality parameter.
But I think this is an old 1.0 value (see https://iiif.io/api/image/1.0/#4-4-quality) and has been changed to "default" in version 2.0 and later https://iiif.io/api/image/2.1/#quality

**Comment by jeffreycwitt** [comment]
I traced this back to manifesto/Canvas

https://github.com/IIIF-Commons/manifesto/blob/c6c3a59771cd7340bdc85171b019c7a07dc011d7/src/Canvas.ts#L16

But oddly, the quality is "default"

Is Mirador currently using an old version of manifesto/Canvas ???

**Comment by jeffreycwitt** [comment]
I think the native is coming from Manifesto/Canvas here: 
https://github.com/IIIF-Commons/manifesto/blob/3217f1e58418b6e9d8121acba38350cf44ddd941/src/Canvas.ts#L28-L32

The manifest I'm testing with is here: 
https://scta.info/iiif/graciliscommentary/lon/manifest

Which has an image context of 2.0, so I'm not sure why manifesto is returning "native"

**Comment by cbeer** [comment]
It's hitting a later condition:

https://github.com/IIIF-Commons/manifesto/blob/3217f1e58418b6e9d8121acba38350cf44ddd941/src/Canvas.ts#L52

Because, although the `@context` is 2.0, the profile is IIIF 1.x, if I'm reading that right?

**Comment by aeschylus** [comment]
Ah, yeah. The profile is overriding the context. That doesn't seem necessarily correct to me on manifesto's part, but it is fixable in the manifest, which validates. There's nothing in the spec about breaking this tie between context and profile that I could find.

**Comment by jeffreycwitt** [comment]
Oh ok, I really don't understand what "profile" is doing. 
For 2.X manifest and 2.X image service, what SHOULD the profile be?

http://iiif.io/api/image/2/level2.json ??

I can fix that in my manifest. But I agree that manifesto could possible be updated here, since my manifest validates via the IIIF validator. Why does Manifest check the profile at all?

But if that's the problem, you can probably close this issue as it seems like something that needs to be changed in Manifesto and/or my manifest.

**Comment by aeschylus** [comment]
I guess this is the relevant section https://iiif.io/api/image/2.1/compliance/#indicating-compliance

I'll close for now, but I'm glad we resolved it. It will be good to test with the scta corpus.
