### ISSUE TITLE
Responsive behavior: reposition workspace control bar based on viewport aspect ratio

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1837]
Looking at these designs, should we also have this reposition?: https://github.com/ProjectMirador/mirador/issues/1833

**Comment by camillevilla** [comment]
Indeed. I'm a little concerned that this will break Material UI's notion of a drawer. Drawers can open from the top, but this might be a good time for some analysis re: whether a Drawer is the right component for the job. 

https://material-ui.com/demos/drawers/
![topdrawer](https://user-images.githubusercontent.com/5402927/52741885-4e2c5a80-2f8b-11e9-919a-82ce8fdd5e3e.gif)



## Designs
### Mobile
<img width="371" alt="mobile-list-view" src="https://user-images.githubusercontent.com/101482/52449613-34a39280-2af5-11e9-9da7-f9ad9b141085.png">

---


### Tablet
At tablet and larger, the device is wide enough to fit all resource elements in the same row:

<img width="766" alt="tablet-list-view" src="https://user-images.githubusercontent.com/101482/52449623-3d946400-2af5-11e9-8b93-c11420ca9eea.png">

---

### Desktop
<img width="1021" alt="desktop-list-view" src="https://user-images.githubusercontent.com/101482/52449629-438a4500-2af5-11e9-9938-b22e7ee2d3c6.png">
