### ISSUE TITLE
Export store in such a way that instances do not interfere with one another

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1844]
It was discovered in https://github.com/ProjectMirador/mirador/pull/1829/files#diff-440023654038f83a80c9ee8012dde09f that multiple instances of mirador are attempting to access the same initialised store. How should we attach or initialise the store in each instance to avoid this. There's a straightforward solution provided in the PR, but it strikes me that this touches on a few other architectural questions, so I'm posting this here:
https://github.com/ProjectMirador/mirador/pull/1697/files
#1807
#1802

**Comment by aeschylus** [comment]
My impressionistic initial opinion is that we should try to maintain the current abstraction at the instance level, namely, reorganise the createStore function such that it returns a distinct instance at the module level, rather than binding it to the mirador object with `this`.

**Comment by christopher-johnson** [comment]
this can be done by provide [custom context](https://react-redux.js.org/using-react-redux/accessing-store#providing-custom-context).  this would mean adding a "context" property to connected components.  I suspect that this needs to be done to make an implementation providers store be accessible to the vender supplied connected components in` react-redux 6.0.0`  I will test this.
