### ISSUE TITLE
Events needed by real world external app

### ISSUE THREAD

**Issue by rsinghal** [ProjectMirador/mirador#1865]
Here is a list of the events Harvard’s annotation application needs from or sends to Mirador.  
- When a window gets added / updated
- When a call is made to the endpoint / manifest to retrieve annotations
- When that call is successful and gets added to storage and when it fails
- When those stored annotations finish being drawn on screen
- When an annotation viewer is shown/hidden
- When an annotation editor is shown/hidden
- When the selected areas (rectangles, ovals, freeform) get resized/deleted/added/changed
- When an annotation is created
- When an annotation is updated
- When an annotation is removed
- When viewtype or the image in general is changed
- When Mirador gets resized
- When region is clicked/hovered
- When viewport/viewable annotations is changed
- Trigger to zoom to a specific set of images via external means
- Trigger the creation / update / deletion of annotation via external means (i.e. my sidebar or accessibility/keyboard annotations)
- Trigger hiding/showing certain annotations via external means
- Trigger a way to retrieve annotation information (e.g. return all annotations, return only annotations currently visible, etc.)
- Hooks to add/remove contents of viewer/editor (e.g. instead of tinymce choose another WYSIWYG, add colors to tags, add button for other functions that HxAt might include like viewing replies or making a reply)
- Ways to configure turning on/off Mirador features that might be distracting for learners in a HxAT context (e.g. navigation, adding new image, splitting windows, mosaic/grid/free mode, etc.)

**Comment by mejackreed** [comment]
Closing this issue for now. Most of this functionality is now using the redux actions which are subscribable.
