### ISSUE TITLE
Create monorepo and package for publishing Mirador as a React Component

### ISSUE THREAD

**Issue by christopher-johnson** [ProjectMirador/mirador#1866]
closes #1743 , closes #1720 , closes #1802, closes #1825, closes #1827
these are obsoleted since they are implementation decisions.

Mirador could/should be published as a React Component in a separate library package (with its own webpack configuration).  The library would only export the root component <App/>, actions and named reducers.

Mirador Viewer can remain the default implementation published in a separate package.  To manage these packages in a single repository is optimal.  The status quo repository source can thus be symlinked into the component distribution.

Here is how it could be done with `lerna` and `git subtree`
https://github.com/ubl-chj/mirador-monorepo

Note that the monorepo would exist in a new and distinct repository.

**Comment by mejackreed** [comment]
It might be a good idea to hold off on this until we have better defined #1693 and can split that out into concerted prioritized tickets.

**Comment by christopher-johnson** [comment]
#1693 should not affect this.  that is all part of the default implementation.  

The `library component` is just the root React component (i.e. <`App />`, reducers and actions not the initialization, event or configuration APIs. 

The Portal will be a React App and requires the ability to import App from 'mirador'.  This is a blocker.

**Comment by mejackreed** [comment]
Would adding an `App` export to the exports here: https://github.com/ProjectMirador/mirador/blob/master/src/index.js#L3-L6 resolve your issue?

**Comment by christopher-johnson** [comment]
no.  the package needs specific managed dependency versions.  for example, `"react-redux": "5.1.1"`

**Comment by christopher-johnson** [comment]
I believe that it is much easier to manage the library (component) dependency versions separately an implementation.  `react`,`react-dom`, `redux`,`react-redux` should probably be peer dependencies.  

The component should also be regularly published and semantically versioned.  The implementation would have a release version that is completely different from the component version (and on a different cycle).

I cannot yet test whether or not exporting `App` from the implementation build will work.  There are prerequisites (#1862).  I would also need `I18nextProvider` to be refactored from `MiradorViewer` and added to `App`.  

The component import works as a separate package export for sure.  Checkout this [custom implementation](https://github.com/ubl-chj/mirador-monorepo/tree/master/packages/mirador-custom-implementation) (WIP)

**Comment by mejackreed** [comment]
Gotcha, so it sounds like that:

> The Portal will be a React App and requires the ability to import App from 'mirador'. This is a blocker.

Is no longer a blocker because of the need of a monorepo, its more about needing the reducers in a different way and dealing w/ i18n. Is that right?

A big 👍 to moving `react`,`react-dom`, `redux`,`react-redux` to peer dependencies.

The custom implementation is sure interesting. That work will be great to see the benefits of how things work in a different context. However, I'm reluctant to introduce such a dramatic change (monorepo) in the middle of a workcycle where there is a lot of progress being made. The loss of productivity doesn't seem yet to be greater than the yields we would gain, with still yet uncertain and unknown needs.

**Comment by mejackreed** [comment]
Mirador 3 will not be published as a monorepo. Closing this until this discussion reemerges.
