### ISSUE TITLE
Determine best type of layout for book view images with differing aspect ratios

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1869]
Pinging @ggeisler and @jvine on this.

#1867 implements book view. However, for manifests that have canvases that differ wildly in aspect ratio, the view can be a little awkward.

https://deploy-preview-1867--mirador-dev.netlify.com/__tests__/integration/mirador/

Manifest to test: https://media.nga.gov/public/manifests/nga_highlights.json

What is the designed behavior? Everything works ok with more "book like" material

Is this good enough?

![bookviewawkward](https://user-images.githubusercontent.com/1656824/52671273-d81aeb80-2ed7-11e9-8a74-ed0a46542469.gif)

**Comment by jvine** [comment]
It's not just the aspect ratio but the relative size. Not clear why it's not the same as Mirador2?

<img width="984" alt="screen shot 2019-02-12 at 2 52 33 pm" src="https://user-images.githubusercontent.com/6945691/52673541-eff17000-2ed5-11e9-8fdc-a1598c167d68.png">

Is the image size difference reflecting the IRL relative sizes of the objects? That might be informative... (but could also be unusably extreme for some objects).

**Comment by ggeisler** [comment]
It feels like some of the canvases in your example are much smaller than they should be, based on opening the image referenced in the manifest directly. For example, "Watson and the Shark" looks very small in your example (not using horizontal space it appears it could), but when I open the referenced image it is 2048x1624. I guess you're trying to keep the aspect ratios while ensuring two images always completely fit in the window and so you have to shrink a very horizontal image a lot, but a few examples still feels like they aren't using all the space they could. 

It looks like Mirador 2 normalizes adjacent images by height -- they vary in width but not in height. Sometimes this means a very horizontal image takes almost the whole viewport and you don't see much of the adjacent canvas, but to me that's a reasonable approach, versus the approach in your example where it looks like you are always ensuring that two images completely fit within the window. 

I like how Mirador 2 handles book view. Maybe @jvine has other thoughts, though.

**Comment by aeschylus** [comment]
Another consideration, though perhaps for later, is the addition of margins in the top-level zoom-out (this becomes more of a requirement in the "no opaque boxes" theme museums have requested, which is not the way the markup is currently organised). I wrote a library to calculate the layout parameters using these margins some years ago. See [iiif-layout-functions](https://github.com/sul-dlss/iiif-layout-functions), [Demo](http://sul-dlss.github.io/iiif-layout-functions/example/), [context + diagrams](https://github.com/sul-dlss/iiif-layout-functions/issues/1)
