### ISSUE TITLE
CanvasNavigation Panel --> Thumbnail list

### ISSUE THREAD

**Issue by camillevilla** [ProjectMirador/mirador#1872]
See #1584 and #1772

<img width="276" alt="screen shot 2019-02-12 at 8 33 17 pm" src="https://user-images.githubusercontent.com/5402927/52687163-8c7f3680-2f05-11e9-8624-91b23d3b4ce1.png">

### Acceptance Criteria
- [x] canvas thumbnails are lazy loaded (something similar to thumbnail nav)
- [x] canvas label is rendered
- [x] Clicking on thumbnail or title changes `canvasIndex`

### Out of Scope
- annotation, layer icons
- Other canvas navigation menu options
<img width="260" alt="screen shot 2019-02-12 at 8 33 07 pm" src="https://user-images.githubusercontent.com/5402927/52687145-783b3980-2f05-11e9-89b2-dee794f47212.png">

### Resources
- [Interactive designs](https://github.com/ProjectMirador/mirador-design/wiki/Mirador-3-Interactive-Designs) --> Sidebar panel content & navigation 
- thumbnail nav loading tickets: #1689, #1688

**Comment by mejackreed** [comment]
Resolved in #1940 and #1937
