### ISSUE TITLE
i18n locale toggle (workspace) 

### ISSUE THREAD

**Issue by camillevilla** [ProjectMirador/mirador#1876]
We now have a basic i18n implementation, we need to implement a UI element for switching the workspace's locale.

**Comment by jvine** [comment]
This design adds a UI element to switch the language for the workspace. 

Assumption is that the implementer can decide which language(s) to make available for their installation. If there is more than one language available:

- show a `Language` option in the application / workspace menu
- `Language` option opens a secondary menu that allows the user to view and select one of the available languages
- on selecting a language, the sub- and parent menus are closed, and the UI text is replaced with the selected language text

<img width="492" alt="screen shot 2019-02-14 at 4 16 17 pm" src="https://user-images.githubusercontent.com/6945691/52826053-2533c480-3074-11e9-8f25-5d3e3b6acae1.png">

**Caveats**

The screenshot includes some other menu adjustments/features that have not been ticketed yet. These aren't intended to be in scope here; only the Language option.

Design uses the MUI desktop cascading menu. Not clear from their documentation how this will work on mobile - whether the placement of the sub-menu will adjust responsively, or we'll need to separately address mobile menu behaviour.
