### ISSUE TITLE
i18n locale toggle (information panel metadata)

### ISSUE THREAD

**Issue by camillevilla** [ProjectMirador/mirador#1877]
If multiple languages are provided in the manifest metadata, we need to indicate that to the user and provide a way of toggling between the languages. 

Resources:
- [IIIF v3 spec - Language and Property Values](https://iiif.io/api/presentation/3.0/#43-language-of-property-values)

**Comment by jvine** [comment]
Hm. My reading of this bit in the spec was that the application language setting would capture the user's language preference, and the manifest language would respond to that - i.e. if the user selects French at the app level, and an open manifest has French content, that content would display. But the missing piece is when there is no app-level language option for content that exists in one of the manifests in the workspace. (Implementer provides English, Spanish, French; manifest has Japanese.) Hm.

**Comment by eroux** [comment]
related: https://github.com/ProjectMirador/mirador/issues/1959

**Comment by camillevilla** [comment]
Initial backend implementation was added via #2250. Further design work for this feature is in #2477
