### ISSUE TITLE
App crashes while loading canvas thumbnails

### ISSUE THREAD

**Issue by charbugs** [ProjectMirador/mirador#1888]
![mirdor-bug-canvas-thumbnails](https://user-images.githubusercontent.com/11216290/52784532-b6477300-3055-11e9-89f7-e5c4c461efea.gif)

**Comment by mejackreed** [comment]
It seems in this case that the canvas has a width and height of 0 see: https://iiif.bodleian.ox.ac.uk/iiif/manifest/e32a277e-91e2-4a6d-8ba6-cc4bad230410.json

**Comment by glefi** [comment]
fixed in #1990
