### ISSUE TITLE
Update 'light' theme color palette

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#1906]
Here's a first pass at specifying the `light` color palette. We expect to have to make multiple passes at this to get it where we want it, but it'll be easier to fine-tune the palette after getting some fundamental updates incorporated in the app.

There are two parts to this, I believe:

- Specifying a basic color palette for the light theme
- Updating the existing color-category-to-component mapping

### Color palette specifications

```
palette: {
  type: 'light',
  primary: {
    main: '#f5f5f5',
    light: '#ffffff',
    dark: '#eeeeee',
  },
  secondary: {
    main: '#1967d2',
    light: '#64b5f6',
    dark: '#0d47a1',
  }
}
```

For the other palette categories, we can start with what I think are the defaults:

Background: #ffffff
Surface: #ffffff
Surface - dark: #f5f5f5 (not sure this is part of the default palette or not)
Error: #b00020

### Color-category-to-component mapping

There are some components that we want to map to color categories that are different from (the best I can tell) the defaults:

- Application bar: primary - main
- Workspace surface: surface - dark
- Window surface: primary - dark
- Window top bar: primary - light
- Thumbnail strip surface: primary - dark
- Selection controls: secondary
- Buttons: secondary
- FABs: secondary
- Chips: secondary
- Text links: secondary

For other components, such as menu and dialog surfaces, the default (#ffffff) is fine. All of the "on text" defaults and things like text fields will probably be okay (or handled automatically based on our palette).

We'll likely want to adjust some things in the future (e.g., in the final palette, chips probably should not be the secondary color) but we'll be able to make better judgements if we can get these initial palette and mappings in place.

**Comment by camillevilla** [comment]
Closed by #1979 and and #1980

**Comment by mejackreed** [comment]
@ggeisler @camillevilla I had some questions about this.

Specifically: 

> Workspace surface: surface - dark

And similar areas that reference "dark". Is it possible that we should not reference "dark" or "light" for a specific area, but should reference it based off of what theme is available?

**Comment by ggeisler** [comment]
@mejackreed I'm not sure that would produce reliable results. The `light` and `dark` variants are just additional colors added to the color palette so there are more color options available in the palette. Depending on the color palette, trying to automatically calculate `light` based on the primary color, for example, might be fine for palette A but not be the ideal color for palette B, if that makes sense.

That said, there is still more work to do I wanted to do on the color palette stuff, based on what was implemented from this ticket, so I'm not 100% sure of anything yet.

**Comment by mejackreed** [comment]
Ok.. so I just spoke w/ @jvine a bit about this and maybe have a proposal moving forward. I'll see if I can put up a proposal so others can take a look.
