### ISSUE TITLE
[Performance] Use canvas-exit handler for update viewport action 

### ISSUE THREAD

**Issue by christopher-johnson** [ProjectMirador/mirador#1910]
The OSD component currently uses the `viewport-change` handler to snapshot the viewport's x,y and zoom in state.
However, this is costly, since the user may create hundreds of state updates with a single zoom as shown here.  (the red indicates high update frequency)
![2019-02-17 01-02](https://user-images.githubusercontent.com/5990301/52906626-e3f80c00-324f-11e9-9088-48f8f8b75420.gif)

Alternatively, the viewport snapshot action could occur when the user leaves the canvas using the `canvas-exit` handler.

**Comment by mejackreed** [comment]
I noticed this too. That looks like a nice tool you are using to look at renders, what is that?

What do you think about using something like throttle or debounce instead of `canvas-exit`? I'm just thinking about the case where the canvas may not have yet exited.
