### ISSUE TITLE
Spike: Migrate 1 component to a hook/functional component

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1930]
Discussed in post standup on 2/20/2019 functional vs class based components. Rather than move wholesale, someone could do a spike to explore this how it affects one of our existing components and tests.

**Comment by christopher-johnson** [comment]
implemented the OpenSeadragonViewer as a stateless functional component.  it works.

hooks are not supported by enzyme yet.  the test will need to be rewritten.  

here is a possible testing alternative: https://github.com/kentcdodds/react-testing-library.  will experiment with that tomorrow.
