### ISSUE TITLE
ThumbnailNavigation styling, labels, and visual design

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1932]
Our current implementation of ThumbnailNavigation is missing the styles in the mocks.

Needed things:
 - [ ] ~~Effective padding / margins for both single and book view~~
 - [x] Labels added
 - [x] Container areas should work w/ theming

Thumbnails navigation
- [x] use `<nav />` element, add `aria-label="Thumbnail carousel"` (#2101)

**Comment by jkeck** [comment]
I'm going to work on just the canvas labels for the time being (assuming the `design needed` designation is more about the theming/styling of the thumbnails/area)

**Comment by jvine** [comment]
Based on work done in #2073, which adds labels and focusable elements.

This styling will make the images & scrollbar fit within the nav area, and makes the currently-selected outline prettier. 

- [ ] for `.mirador-thumb-navigation .mirador-thumbnail-nav-canvas`
  - change border width to 2px
  - add 2px padding
  - change border colour to secondary theme colour 
- [ ] remove `text-transform: uppercase;` from the button text
- [ ] for the various containers above `.mirador-thumbnail-nav-container`, change the height and/or max-height from 150px to 177px - or rather, the height of the image plus 27px. This will apply if the image size is 100px or 75px etc. 
- [ ] for the `<ul>` element, change `margin: -2px;` to `margin-top: 2px;`
- [ ] on the `<ul>` element `.jss167` has `overflow-y: auto;` which just seems to be causing trouble
- [ ] for `.ReactVirtualized__Grid`, change  `overflow: auto;` to  `overflow: auto hidden;` to get rid of the vertical scrollbar

**Comment by camillevilla** [comment]
The container background areas now correspond to the `primary.dark` as of #1980 @jvine

Any other things that need to plug into theme?
