### ISSUE TITLE
Correct sidebar elevation and relationship with canvas

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#1934]
[UI map for context](https://github.com/ProjectMirador/mirador/wiki/M3---UI-map)

Currently the sidebar is overlapping the canvas, and is at the same elevation as the window header. This seems to be a feature of the drawer component, but is not the intent of the design.

### Current layout
<img width="792" alt="screen shot 2019-02-20 at 11 26 46 am" src="https://user-images.githubusercontent.com/6945691/53119273-f39f7b00-3503-11e9-9928-8af37282a6ca.png">

- sidebar and header are at the same elevation (incorrect); canvas and right panel are at 0 elevation (correct)
- canvas is not centered; canvas navigation is partly obscured (depending on window size)

### Intended layout
<img width="798" alt="screen shot 2019-02-20 at 11 25 40 am" src="https://user-images.githubusercontent.com/6945691/53119274-f4381180-3503-11e9-952f-298f127ee59a.png">

- sidebar, canvas, and panel are all at 0 elevation; header is elevated equally above all three sections
- canvas and canvas navigation are centered; neither the sidebar nor the panel overlaps the canvas area
- there should be no shadows cast by sidebar, canvas, or panel.

**Comment by mejackreed** [comment]
I think the elevation issues here were addressed in #2039 and #2018

**Comment by jvine** [comment]
Looking at the current state of this, just want to point out some details. Apologies if you're already aware.

1. navigation is still at a higher elevation than the content of the sidebar, so the shadow of the window header doesn't extend the full width of the window
2. content panel still has a drop-shadow
3. `overflow-y: auto;` would be better than `overflow-y: scroll;` for the content area, so the scrollbar area isn't reserved when it's not required. 

**Current**
<img width="300" alt="screen shot 2019-03-06 at 1 24 23 pm" src="https://user-images.githubusercontent.com/6945691/53915427-bf07e500-4014-11e9-9e7b-fb73fe76163d.png">

**Should be**
<img width="300" alt="screen shot 2019-03-06 at 1 25 10 pm" src="https://user-images.githubusercontent.com/6945691/53915443-c4652f80-4014-11e9-80e3-b2a69ab357c0.png">
