### ISSUE TITLE
Menu issues: location, behaviour, icons

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#1936]
<img width="782" alt="screen shot 2019-02-20 at 3 34 20 pm" src="https://user-images.githubusercontent.com/6945691/53132604-070f0e00-3525-11e9-937c-ecdc6b362c44.png">

## Location
1. **Menus should appear next to or below, but not covering, the element that generates them**. The `Toggle Menu Grow` style here https://material-ui.com/demos/menus/#menulist-composition seems closest to the intended behaviour, though the keyboard interaction is slightly different than MUI.

- [ ] Align sidebar menus with the top/right (in LTR mode) or top/left (in RTL) of the icon.
- [ ] Align top bar menus with the bottom/right (in LTR mode) or bottom/left (in RTL) of the icon.

(By "icon" I mean the svg element (24px) of the icon button (svg + padding).)

2. **The window menu should be visually contained within the window that generated it**. It should not overlap multiple windows. Its max width should match the window width; menu content can wrap if necessary. 

## Selection
3. **The icon button that generated the menu should remain in "active" state** while the menu is open. Example from gmail:

<img width="290" alt="screen shot 2019-02-20 at 4 11 38 pm" src="https://user-images.githubusercontent.com/6945691/53134078-76d3c780-352a-11e9-91fe-e9d1e7758c18.png">

4. **No menu item should be highlighted by default.** Current behaviour allows for two items to be in hover state, which is inappropriate.

<img width="277" alt="screen shot 2019-02-20 at 2 49 39 pm" src="https://user-images.githubusercontent.com/6945691/53130351-d4621700-351e-11e9-83d4-c9af28934bda.png">

This seems to be a factor of the menu overlaying the icon button, so may be fixed by changing the location of the menu (item 1). Menus should open with no option in focus; user can hover/set focus using the mouse or arrow keys. 

5. **Dividers should not be focusable elements.** 

Current implementation is using `<hr class="whatever" tabindex="-1">` as the divider element. For whatever reason, this element is focusable, but it should not be.

<img width="272" alt="screen shot 2019-02-20 at 4 27 33 pm" src="https://user-images.githubusercontent.com/6945691/53134595-a4217500-352c-11e9-9df2-fa8f43266fe0.png">

MUI documentation shows this as the divider, FWIW:
`<li class="mdc-list-divider" role="separator"></li>`

## Layout & icons

6. To avoid icon proliferation/ransom note effect, and avoid re-used/re-purposed icons, **only selected menu options should have icons**. 

So far these are the options grouped at the bottom of the workspace menu:
- Settings
- Share
- Export

- [ ] In the workspace menu, remove icons from all options except the three listed above.

**Comment by jkeck** [comment]
Closes by #2107
Remaining work outlined in #2115
