### ISSUE TITLE
Check if IntersectionObserver is needed for <ThumbnailNavigation>

### ISSUE THREAD

**Issue by glefi** [ProjectMirador/mirador#1942]
As the GridCells of the Grid are rendered on demand, we can possibly throw out the IntersectionObserver.

**Comment by mejackreed** [comment]
IntersectionObserver is still in `CanvasThumbnail` and I believe is still needed as other long lists may use `CanvasThumbnail`. I'm going to close this for now, reopen if we need to discuss some more.
