### ISSUE TITLE
WindowIcon container not used in ManifestListItem

### ISSUE THREAD

**Issue by christopher-johnson** [ProjectMirador/mirador#1950]
`WindowIcon` when used in `WindowTopBar` gets `manifestLogo` from state.  `WindowIcon` when used in `ManifestListItem` is not connected, however, and gets the prop with inheritance.   The `WindowIcon` container (as an implementation of the component) should be used consistently in all components.   

The key issue seems to be that the `getWindowManifest` selector for the `WindowIcon` container requires a `windowId`, which `ManifestListItem` does not have.  

A proper fix could be to allow manifest value lookups without depending on `windowId`

**Comment by mejackreed** [comment]
`WindowIcon` was removed from `WindowTopBar` I believe. Closing this issue.
