### ISSUE TITLE
When opening and closing the workspace menu the opened windows are moving

### ISSUE THREAD

**Issue by glefi** [ProjectMirador/mirador#1951]
When opening (and closing) the workspace menu or one of the linked dialogues e.g. "settings" or "export workspace" each of the opened windows are moving by a few pixels.

**Comment by christopher-johnson** [comment]
this seems to be a result of `Fullscreen` setting height to 100% which results in a y overflow (and a vertical scrollbar).  This component does not allow injected styles unfortunately.  An ugly workaround could be to override it in css:
```
.FullScreen {
  height: 0 !important;
}
```

**Comment by mejackreed** [comment]
I'm not noticing this happening anymore. Please reopen if its still an issue.
