### ISSUE TITLE
vertical display mode

### ISSUE THREAD

**Issue by eroux** [ProjectMirador/mirador#1957]
I originally reported the issue [here](https://github.com/ProjectMirador/mirador-design/issues/40) before realizing it might no be the right place, one of the two should probably be closed. For a rather large corpus of Asian manuscripts and a few modern editions, it would be a very noticeable improvement (over Mirador2 and UV) to have a mode where all the images are displayed vertically. Diva and the Internet Archive viewer have this feature and it makes reading very smooth, while our ([BDRC](https://www.tbrc.org/)'s) users report a rather poor experience with Mirador and UV.

An example with the Internet Archive viewer:

https://archive.org/details/bdrc-W4CZ57131/page/n7

For an example with Diva go to

http://library.bdrc.io/show/bdr:V22084_I0886

and click on "View images in Diva". That kind of display would be a tremendous help to many Asian users!

**Comment by mejackreed** [comment]
@eroux do you have any manifests with the `scroll` or `top-to-bottom` viewing enabled? This was just worked on and I think may now be resolved.

**Comment by eroux** [comment]
here's a `top-to-bottom` manifest:

https://iiifpres.bdrc.io/vo:bdr:I0886/manifest

I sort of gave up on the `scroll` idea. 

Footnote: we developed some extensions to mirador 2 to have the output we want, for both collections and manifests, see for instance

http://library-dev.bdrc.io/view/bdr:W22084 for the collection view and

http://library-dev.bdrc.io/view/bdr:I4CZ75258 for the manifest view

**Comment by mejackreed** [comment]
Thanks!

**Comment by triplingual** [comment]
I'm thrilled to see Mirador 3 now supporting TTB oriented content! Still — though this may have come up elsewhere before — I wanted to throw in my $0.02 about the navigation UX for a TTB manifest.

https://projectmirador.org/embed/?iiif-content=https://preview.iiif.io/cookbook/0010-book-2-viewing-direction/recipe/0010-book-2-viewing-direction/manifest-ttb.json shows an implicitly paged TTB manifest, but the nav buttons in Mirador remain in a left/right orientation. For this user, I hear static in my brain when I'm navigating a TTB document by moving left and right.
