### ISSUE TITLE
wrong display of multi lingual labels: [object Object, object Object]

### ISSUE THREAD

**Issue by eroux** [ProjectMirador/mirador#1958]
Version is 2.7.2.

When a label is in the multilingual form advised by [the spec](https://iiif.io/api/presentation/2.1/#language-of-property-values), like

```json
"label":[
   {"@language":"en","@value":"a label"},
   {"@language":"fr","@value":"un libellé"}
]
```

Mirador displays the labels as ` [object Object, object Object]`. See [this demo](http://eroux.fr/bugmirador.html). It should display one of the labels (or maybe several of them depending on the cases, the spec goes into some details about that).

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
