### ISSUE TITLE
Remove provider logo image from window top bar

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#1962]
When @jvine and I were working out details of typography and spacing for different components, it became clear that the complications of displaying the manifest provider's logo in the window top bar outweigh the benefits. We recommend removing the logo from the window top bar. So in the current version of the app things would look like this:

<img width="1026" alt="mirador-2" src="https://user-images.githubusercontent.com/101482/53378198-fa722780-3921-11e9-8884-bda8a5575169.png">

**Comment by christopher-johnson** [comment]
:+1: 
the logo is also a visual distraction when juxtaposed against the content.
