### ISSUE TITLE
Add empty state message to workspace

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#1964]
Part of https://github.com/ProjectMirador/mirador/issues/1963

This is a bit different than the other placeholder tickets, because it includes modifying the application bar in addition to showing an empty state message. A workspace could be empty for a couple of reasons:

- The Mirador instance the user is working with has no pre-defined objects to load
- The user has closed all windows in the workspace

In either case, we want to make sure the user understands the current state and has a clear way to get out of it (by adding one or more resources).

<img width="1027" alt="screen shot 2019-02-25 at 5 45 15 pm" src="https://user-images.githubusercontent.com/101482/53379035-25aa4600-3925-11e9-8494-c1a28b4b86b3.png">

So, when the workspace is empty:

- Modify the application bar
a. Widen the plus button to include the words "Start Here" (the button should be styled similar to the "Add Resource" button in the load window)
b. Widen the application bar so it contains the wider "+ Start Here" button
c. Add the "Mirador" and "Version" text above the Mirador logo
d. Center all the above elements in the wider application bar

- Add a "Welcome to Mirador" message centered in the workspace area

Clicking the "Start Here" button triggers the load window just as it does with a non-empty workspace (that is, the application bar goes to its narrower version with the close button, and the load window displays in the main area). See this [simple interactive mockup](https://xd.adobe.com/view/5c678481-d9a7-44d5-6217-7d961d5c07d9-2a56/) if that isn't clear.

**Comment by cbeer** [comment]
What do you want to do with the other workspace buttons?

**Comment by ggeisler** [comment]
Assuming you're referring to the workspace app menu icon buttons, hide them. 

An exception might be the Workspace options menu (which doesn't exist yet, but has been recommended in an [update to the workspace app bar](https://github.com/ProjectMirador/mirador/issues/2376)). It seems reasonable for a user to want to import a workspace from the empty workspace.

I'm experimenting with how to add that affordance to the design but maybe we can just go with no workspace buttons (matching the mockup above) for now, and we can decide later if and how to add the workspace options (and whether settings and full-screen should also be available here).

**Comment by cbeer** [comment]
It seems like #2376 will be reorganizing stuff, so I'm just going to leave them as-is (uh, centered) for this PR.
