### ISSUE TITLE
Fullscreen should be the entire app not just the workspace viewport

### ISSUE THREAD

**Issue by jkeck** [ProjectMirador/mirador#1974]
Currently the Application Bar/WorkspaceMenu are not available in fullscreen but they should be.

See https://github.com/ProjectMirador/mirador/pull/1967#issuecomment-467540566

Note that since the Application Bar/WorkspaceMenu will now be visible in fullscreen we'll need to modify the fullscreen icon so that it changes to `FullscreenExitSharp` when in fullscreen mode.

This also has potential implications for #1785/#1813 (and we may be able to address that issue holistically with this change)

**Comment by cbeer** [comment]
If the whole application is in the screen, is the browser's own built-in full screen button sufficient? Maybe we don't need to roll our own?

**Comment by jkeck** [comment]
It could be useful in an embedded contexts. Although, as mentioned in #1885, it might be common for the workspace sidebar to be hidden in embedded contexts, and then the fullscreen button would be hidden. 🤔
