### ISSUE TITLE
Overflow settings creating inappropriate scrollbars/placeholders

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#1975]
There are three places where the app is incorrectly getting scroll bars or placeholders for scrollbars.

<img width="509" alt="screen shot 2019-02-26 at 10 19 16 am" src="https://user-images.githubusercontent.com/6945691/53436776-d01b7b00-39b0-11e9-8873-ee39b633f4b1.png">

##  1. Workspace in Mosaic mode 
- [x] `.mirador-workspace` has `overflow: scroll;` which is creating an unnecessary scroll-bar sized border around the mosaic workspace. Not sure what the best setting here is, or how Freeform will use this space (do we want scrollbars on Freeform?) - setting it to `overflow: auto;` or removing the setting altogether fixes the issue for Mosaic.

<img width="506" alt="screen shot 2019-02-26 at 10 07 46 am" src="https://user-images.githubusercontent.com/6945691/53437054-7f585200-39b1-11e9-8054-91f522aa5da3.png">

## 2. Thumbstrip has vertical scrollbar
- [ ] Goal is this: 
- companion windows may scroll in both directions when they have non-thumb content
- thumbnail strip may scroll horizontally but should never scroll vertically. Setting `overflow-y: hidden;` on the inner div (`class="ReactVirtualized__Grid"`) seems to work but might not be the most robust solution.

<img width="504" alt="screen shot 2019-02-26 at 10 08 36 am" src="https://user-images.githubusercontent.com/6945691/53438667-330f1100-39b5-11e9-9fac-ae6ddbf17a1f.png">

## 3. Application has vertical scrollbar
- [x] Not clear to me how/why this is happening, but the application as a whole should never have a vertical scroll bar. Elements within the app (menus, workspace, even the app bar etc.) can scroll, but not the app. Currently the app always seems to be ~2x as high as the viewport - it's impossible to stretch the window to eliminate the scrollbar. 

Outcome with all three overflows resolved should look like this:
<img width="509" alt="screen shot 2019-02-26 at 10 09 34 am" src="https://user-images.githubusercontent.com/6945691/53439004-ef68d700-39b5-11e9-9322-602d43764fdf.png">

<img width="508" alt="screen shot 2019-02-26 at 11 06 00 am" src="https://user-images.githubusercontent.com/6945691/53439259-85046680-39b6-11e9-98a9-8e1b9e2735d3.png">

**Comment by mejackreed** [comment]
Third problem described is also related to https://github.com/ProjectMirador/mirador/issues/1929

**Comment by mejackreed** [comment]
Part 2 is likely related to #1932 as discussed in slack.

**Comment by jvine** [comment]
Referencing #1932 for further work on issue 2. Intent is to address the sizing issue holistically as part of the accessibility and completed functionality (labels, resizability) of the thumbnav.

**Comment by camillevilla** [comment]
👍 2 / 3 issues resolved in PR #1997. See #1932 for more on thumbnail nav.
