### ISSUE TITLE
Theming: override input labels default so they use the MUI secondary color

### ISSUE THREAD

**Issue by camillevilla** [ProjectMirador/mirador#1986]
Override text input labels so they use our `secondary` color instead of `primary`? See the light grey color used for this picker's label. Might need to check in with @jvine and @ggeisler about this.
![grey-menu](https://user-images.githubusercontent.com/5402927/53469178-d726a580-3a11-11e9-974e-55293701d62b.gif)

**Comment by ggeisler** [comment]
I don't think we'll want to use the `secondary` color for the label, just a darker gray. I was hoping the `on` text colors would automagically adjust correctly to our color scheme but it looks like that is not the case.

I'll take this into account in the current work I'm doing on extending the color palette and we can revisit this when that work is ready.

**Comment by ggeisler** [comment]
I think this issue has been superseded by other theming related issues, and the specific example above is no longer relevant, so closing this.
