### ISSUE TITLE
Master ticket: non-functional requirements

### ISSUE THREAD

**Issue by charbugs** [ProjectMirador/mirador#1991]
This is a master ticket for architectural/non-functional issues. 

* documentation (#1620)
* bundling and shipping (#1866, #1921, #1798, #1743, #1699, #1693, #1626)
* tooling (#1732, #1602)
* error handling (#1749)
* styling/css patterns
* testing (#1731)
* external API
  * configuration (#1874, #1733, #1697, #1695)
  * plugin system (#1959, #1985, #1693, #1665)
  * event system (#1865, #1693)
* state mangement
  * interdependencies of multiple instance (#1844, #1782)
  * asynchronous state management patterns (#1808, #1620)
  * reducer/action patterns (#1926)
  * manifesto (#1663)

**Comment by eroux** [comment]
maybe https://github.com/ProjectMirador/mirador/issues/1969 could be added too?
