### ISSUE TITLE
configuring availableViews when opening a collection

### ISSUE THREAD

**Issue by berger-n** [ProjectMirador/mirador#1992]
When opening a single manifest one can set `availableViews` menu items, within `windowObjects`.
But when loading a collection? How to set the `availableViews` that will be used for any manifest loaded from the collection? 
I'm using mirador 2.7.2

**Comment by berger-n** [comment]
I'm using mirador 2.7.2

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
