### ISSUE TITLE
Sidepanel behavior when in book view

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1994]
Raised by @jkeck  in https://github.com/ProjectMirador/mirador/pull/1989

**Comment by jkeck** [comment]
We should probably have similar considerations for the annotations panel.

**Comment by camillevilla** [comment]
## About this item
- [ ] Should canvases metadata be displayed one after the other? (Option A) Or something else? (Option B)
### Option A
```
[Current Item Label 1]
[Canvas Metadata 1]
[Current Item Label 2]
[Canvas Metadata 2] 
[Manifest Metadata]
```
### Option B
<img width="1321" alt="Screen Shot 2019-03-19 at 4 54 58 PM" src="https://user-images.githubusercontent.com/5402927/54649635-48350800-4a68-11e9-896b-f19004b1548a.png">

```
[Current Item Label 1]
[Current Item Label 2]
[Canvas Metadata 1]
[Canvas Metadata 2] 
[Manifest Metadata]
```

## Index panel
Right now only a single canvas is highlighted as displayed
![canvas-nav-selection](https://user-images.githubusercontent.com/5402927/54649682-6f8bd500-4a68-11e9-8186-5fbf43e8e67a.gif)

## Annotations
Currently displays all annotations and reflects the correct number of annotations. Might defer defining this behavior until #2135 is implemented

**Comment by jvine** [comment]
### Metadata single

Element | Value
-- | --
Overline | `Item`
Heading4 | Current item label
DefList | Canvas metadata
Overline | `Resource`
Heading4 | Manifest label
DefList | Manifest metadata

<img width="313" alt="single metadata" src="https://user-images.githubusercontent.com/6945691/55517455-5157d480-5625-11e9-9daf-d0acb9e674c0.png">

### Metadata book

Element | Value
-- | --
Overline | `Left`
Heading4 | Current item label 2
DefList | Canvas metadata 2
Overline | `Right`
Heading4 | Current item label 2
DefList | Canvas metadata 2
Overline | `Resource`
Heading4 | Manifest label
DefList | Manifest metadata

<img width="278" alt="book metadata" src="https://user-images.githubusercontent.com/6945691/55515782-46e70c00-5620-11e9-94e5-3e1308af4986.png">

### Annotations single

Element | Value
-- | --
Overline | `Item: [Canvas label]`
List | Annotations

<img width="313" alt="single annotations" src="https://user-images.githubusercontent.com/6945691/55516634-a47c5800-5622-11e9-88ee-65abffb1073e.png">

### Annotations book

Element | Value
-- | --
Overline | `Left: [Canvas label 1]`
List | Annotations
Overline | `Right: [Canvas label 2]`
List | Annotations

<img width="316" alt="book annotations" src="https://user-images.githubusercontent.com/6945691/55516204-67fc2c80-5621-11e9-8635-2ee68747d088.png">

## Changes required

**1. Structure of the overline + h4 combination**

On the metadata panel currently, the overline is a span connected to the H4 by an `aria-labelledby`. This isn't working correctly (my misunderstanding) but I think if we restructure it we can use 

If the overline span is inserted inside the H4 element like so:
<h4><span>Overline</span> Heading value</h4>

on the metadata panel this can be formatted like so:
<img width="207" alt="Screen Shot 2019-04-03 at 3 25 21 PM" src="https://user-images.githubusercontent.com/6945691/55517411-2a999e00-5625-11e9-814b-0a4c24992c99.png">

and on the annotations panel like so:
<img width="208" alt="Screen Shot 2019-04-03 at 3 03 21 PM" src="https://user-images.githubusercontent.com/6945691/55517149-523c3680-5624-11e9-8979-3e5d2fc21037.png">

and in both cases it will read in the same way to a screen reader and in the headings list.

This applies to all the sections in the metadata panel, not just the canvas label.

**2. Separation of annotations into separate lists per canvas.**

Currently the annotations for both canvases are combined into one list; intended outcome is: heading1 + list1; heading2 + list2.

This pattern might be extended in the future to allow continuous paging of annotations and navigation of canvases from this panel. 

(Note that nothing in this ticket is meant to contradict the annotation behaviour and formatting specified in #2383. These mockups don't reflect the separators and highlights etc. in that issue.)

**Comment by cbeer** [comment]
I'm going to take the info panel part of the ticket.

**Comment by jkeck** [comment]
Maybe we can talk about what you'll do there to make sure it doesn't make the work I'm doing for #2435 impossible.

**Comment by jkeck** [comment]
I'm picking up the annotation panel.
