### ISSUE TITLE
Retrieve annotations from an external annotation store (not in manifest), e.g. HTTP or local store

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#2016]

**Comment by jkeck** [comment]
Can we get a little more details about what the expected interaction is here?

How should mirador get an HTTP reference for an annotation list not in the manifest?

WRT local store, do you mean like the browser's localStorage?

**Comment by mejackreed** [comment]
Sure thing. So in Mirador 2, there was the ability to add an "Annotation Endpoint". See https://github.com/ProjectMirador/mirador/wiki/Configuring-Annotations-in-Mirador

This "Generic" endpoint https://github.com/ProjectMirador/mirador/blob/v2.7.0/js/src/annotations/endpoint.js could be adapted to allow for a localstorage strategy and a HTTP restful one. 

This enables adopters to reference manifests with annotations configured to retrieve (or store) somewhere else.

> How should mirador get an HTTP reference for an annotation list not in the manifest?

Mirador 2 did this by using a current canvas id as a parameter to query a configured endpoint. AnnototEndpoint is an example of this configured for our Rails apps. https://github.com/mejackreed/annotot/blob/master/app/assets/javascripts/annotot/annotot_endpoint.js

> WRT local store, do you mean like the browser's localStorage?

Yep. But we don't have to start there (or even go there right now). For reference https://github.com/ProjectMirador/mirador/blob/v2.7.0/js/src/annotations/localStorageEndpoint.js

**Comment by lduarte1991** [comment]
Hey all, it was unclear to me as discussed in the Slack channel whether this was to be a plugin or in core. I took at crack at it as a [simple plugin](https://github.com/HarvardX/catchpy-mirador-plugin) and wanted thoughts. It's very much geared towards HarvardX's backend implementation of an annotation store, but should be translatable.

**Comment by lduarte1991** [comment]
As requested in the call today, here's [a link to a demo of my plugin](https://pedantic-heyrovsky-1f08ba.netlify.com/). Note: 1) it's a big image so zoom a little to see the annotations and 2) our annotations are created by instructors and/or students with a very particular pedagogical lens in mind that's different than the scholarly work more commonly seen in the fixtures attached to this project and in manifest annotations.

**Comment by mejackreed** [comment]
I'm going to close this ticket for now. We have two demos of plugins doing this:

https://pedantic-heyrovsky-1f08ba.netlify.com/

and 

https://github.com/ProjectMirador/mirador-annotot-endpoint-plugin
