### ISSUE TITLE
Menu dividers should not be focusable

### ISSUE THREAD

**Issue by sdellis** [ProjectMirador/mirador#2021]
Dividers help group items logically, but should not be focusable when tabbing through menus.

<img width="283" alt="screen shot 2019-03-01 at 4 04 42 pm" src="https://user-images.githubusercontent.com/609368/53666435-17696c00-3c3c-11e9-95f8-3378c7a4eae4.png">

**Comment by jkeck** [comment]
`ListItem` component has a `divider` prop that will apply a `border-bottom` to the item (having the same visual effect).

Removed the `<Divider />`s in the existing menus in #2107
