### ISSUE TITLE
Add accessibility landmarks

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2033]
Use HTML5 sectioning elements and aria-labels to communicate the application structure to assistive technology. 

The goal is a landmarks list that looks something like this:

1. Workspace navigation
2. Workspace main
3. Window: [Manifest title] region
4. Window banner
5. [Panel title] complementary
6. Item: [Canvas label] main
7. Thumbnail carousel navigation
8. Window: ... [repeat from # 3 for each open window]

This is a very explicit list, and may need to be culled, but we'd like to start here and test.

**1. Workspace navigation**
`<header class="mirador-workspace-control-panel">`
use `<nav>` element, add `aria-label="Workspace"`

**2. Workspace main**
`<div class="mirador-viewer">`
use `<main>` element, add `aria-label="Workspace"`

**3. Window: [Manifest title] region**
not sure of the exact element - in Mosaic mode it looks like 
`<div class="mosaic-tile">`
use `<section>` element, add `aria-label="Window: [Manifest label]"` 

Possible issues around using manifest content in the HTML structure...? 

**4. Window banner**
`<div class="mirador-window-toolbar">`
use `<header>` element, add `aria-label="Window"`

**5. [Panel title] complementary**
For both the sidebar and complementary windows, apply to the `<div>` that contains the panel content
use `<aside>` element, add `aria-label="[Panel title]"`

**6. Item: [Canvas label] main**
<div class="mirador-osd-container">
use `<section>` element, add `aria-label="Item: (Canvas label)"`

Same possible issue as # 3

**7. Thumbnails navigation**
<div class="mirador-thumb-navigation">
use `<nav>` element, add `aria-label="Thumbnail carousel"`

**Comment by cbeer** [comment]
In #2070, for point 3, I've put the `<section>` element on our window component, which is the common component for all windowing modes. Let me know if that's a problem (and, doing it with the mosaic element is going to be tricky because it's generated by the mosaic library, not our code...)
