### ISSUE TITLE
Sidebar structure is not ideal for keyboard support

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2034]
Slightly overlaps #1853 
Related to #1934 

Keyboard navigation of the sidebar should follow [WAI ARIA Practices for tab navigation](https://www.w3.org/TR/wai-aria-practices/#tabpanel) ([w3c demo](https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-2/tabs.html) | [material-design demo]( https://material-components.github.io/material-components-web-catalog/#/component/tabs) )

**Comment by camillevilla** [comment]
Hoping that #2018 will address some of this by removing drawers from the equation.

**Comment by jkeck** [comment]
Potentially useful code in MUI:
- https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/Menu/Menu.js
- https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/MenuList/MenuList.js

**Comment by glefi** [comment]
I've added the key handlers for the arrow keys. It's working like described in the WAI ARIA practices. There's still a problem with the optional behavior for the _home_ and _end_ key. But it's working for the provided w3c example. I'm going to check what's the difference to fix it.
