### ISSUE TITLE
Outcome of "Add resource" is hidden by the form

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2038]
Depending on the side of the viewport and length of the resource list, the Add resource panel may cover the placeholder and resolution (success or failure) of the Add, so the user has no visible feedback.

**Comment by ggeisler** [comment]
If we close the Add resource panel close after the users selects "Add," would this eliminate the problem?

The downside is if the user intends to add several resources consecutively they'd have to reselect the Add resource button each time. But it feels cleaner to me for the panel to close after selecting "Add" and I think that would eliminate the potential problem.

**Comment by jvine** [comment]
I think there's something more complicated going on, actually - the list as a whole doesn't scroll if the viewport isn't long enough to display all of it. So if that is fixed, it might be reasonable to scroll the list to the position where the new item was added. Or let the Add panel push the list up rather than overlay it.

**Comment by ggeisler** [comment]
@jvine @jkeck I think #2048 fixed this? Or is there something else that prevents us from closing this issue?

**Comment by jvine** [comment]
I agree this issue is fixed, and #2126 covers the behaviour change mentioned in the comments above.
