### ISSUE TITLE
Add static section labels to the metadata panel

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2058]
In response to user feedback.

For each section of the "About" panel, add a label:

1. **`Current item`**
   - Canvas level metadata
   - If there is no selected canvas(es) - e.g. can happen in gallery view - then suppress the label as well as the metadata.
   - Can potentially show metadata for 2 canvases (e.g. book view), but the label should appear only once.
2. **`Resource`**
   - Manifest metadata
3. **`Collection`**
   - If there is collection metadata

Will end up looking something like this:

<img width="197" alt="screen shot 2019-03-04 at 2 02 38 pm" src="https://user-images.githubusercontent.com/6945691/53843021-024f4e80-3f56-11e9-8071-61e362aafe92.png">

**Comment by cbeer** [comment]
What HTML element should the new labels have?

**Comment by jvine** [comment]
`<p>` classed as `overline`

Would be nice to add an aria-labelledby association with the heading(s) in the section:

```
<p id="currentItem">Current item</p>
<h4 aria-labelledby="currentItem">Canvas label</h4>
```
