### ISSUE TITLE
Add Table of contents to Index panel

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2068]
Add Ranges structure to the index panel as a hierarchical list navigation. 

The ToC is an alternative to the canvas thumbs navigation, and should be the **primary** navigation where it exists. Complete feature will also require a dropdown menu to select alternate Index options.

**Mockup**
<img width="284" alt="screen shot 2019-03-06 at 10 58 06 am" src="https://user-images.githubusercontent.com/6945691/53906047-d20fba80-3ffe-11e9-9d13-497cbb37e4ff.png">

**Fixtures**
https://github.com/ProjectMirador/mirador/wiki/M3-Fixtures-&-sample-IIIF-data#table-of-contents-and-sequences

**Implementation**
The sidebar menu on the Material Design sidebar is a nice example of an expanding hierarchical list.
https://material.io/design/foundation-overview/

**Comment by mejackreed** [comment]
I'm not sure I can find the referenced Sidebar. Could you screenshot that? @jvine

**Comment by jvine** [comment]
Sorry, I had the browser maximized and forgot the menu would collapse. 

![menu4](https://user-images.githubusercontent.com/6945691/53910999-1e142c80-400a-11e9-92b6-32a5023be74a.gif)

**Comment by mejackreed** [comment]
Oh!!!!! Got it thanks!

**Comment by cbeer** [comment]
What data is supposed to go into the table of contents (jus stuff in `structures`?)

**Comment by jvine** [comment]
Yes, stuff in `structures`.

**Comment by camillevilla** [comment]
See [comment in #2158](https://github.com/ProjectMirador/mirador/pull/2158#issuecomment-472223636) re: design questions

**Comment by cbeer** [comment]
I don't know where to raise this, so feel free to copy into whatever repo is appropriate:

If we're not showing the canvases (or canvas segments) that belong to the range in the table of contents, are there any affordances for navigating through the parts of a range? In particular, I'm thinking about the newspaper example where a single article may be scattered across non-contiguous pages.

**Comment by aeschylus** [comment]
Just to record some more considerations here, for newspapers, ideally the ranges provided would order the sections appropriately to read the article across pages, such that navigating the table of contents/ranges would step through the appropriate image areas.

**Comment by aeschylus** [comment]
Typography and style input needed for following interaction states:

Use the sidebar styling as reference for interaction states (https://github.com/ProjectMirador/mirador/issues/2282)

**Comment by mejackreed** [comment]
Resolved already.

**Comment by JeremyJensenCOB** [comment]
How do you take advantage of this feature. I'm using Mirador for the first time, and I think my manifests are formatted correctly, but only the range names display, not the canvases underneath them. I looked for a setting that would show them as well, but couldn't find it. This issue appears to have been resolved five years ago, so hoping there's a way to do what I need it to do.

![Image](https://github.com/user-attachments/assets/c8f93f14-1c02-4506-bd6e-cf27d78c336e)
