### ISSUE TITLE
thumbnail strip stump makes companion window look weird

### ISSUE THREAD

**Issue by charbugs** [ProjectMirador/mirador#2079]
![thumbnail-companion](https://user-images.githubusercontent.com/11216290/53941908-af8ea780-40b9-11e9-80a0-a26c47bdf901.png)

**Comment by ggeisler** [comment]
- [ ] Make thumbnail strip background `#ffffff` (white) in the light palette 

This is mentioned in #2479 but can be done independently and should take care of the weirdness seen the screenshot above.

**Comment by cbeer** [comment]
Instead of setting the background directly, what about wrapping it in `Paper` for consistency with the other windows?
