### ISSUE TITLE
Diffferent repos for different packaging requirements

### ISSUE THREAD

**Issue by charbugs** [ProjectMirador/mirador#2081]
As you know we have the two packacking requirements a) Mirador as a react application and b) Mirador as an embedded script. Probably there will be more in the future (or are there already more?).

I think it is actually easy to accomblish that if we follow a react first approach. That is, in our **ProjectMirador/mirador** repo we have the pure react application without configuration for script embedding. Here we ship Mirador as a react application to npm. Than we should have a **ProjectMirador/mirador-as-script** repo that pulls the Mirador react app from npm and configure it in order to use Mirador as a script in a web site.

For me this appears a clean solution as we wouldn't pollute the main app with configuration stuff for different use cases. I haven't so much experience with packaging and shipping on npm. So do you folks think this is possible?

**Comment by mejackreed** [comment]
I would prefer not to separate out repositories based solely on packaging requirements. We can (and will) ship different distributions of Mirador from a single repository. 

To me, the reason to start splitting out a repository or different package would mainly depend on either:
 - a natural separation of independent API's that no longer make sense to keep together

or
 - ease of installation of only necessary packages

I'm not sure I see significant evidence of either yet to make this necessary change.

What if someone could import Mirador React components directly from a distribution from a single repository?

**Comment by charbugs** [comment]
As far as I can see the mirador npm package that was shipped recently provides no possibility to use it in a react application, right? I mean I can not grab the root component of M3 and put it somewhere in my application. When and how do we want to enable this feature?

**Comment by mejackreed** [comment]
Correct.

Let's enable it now!

What is the starting point you need for HSP?

**Comment by aeschylus** [comment]
I've ticketed this in #2082 to get us started, and created a [ticket](https://github.com/ProjectMirador/mirador/issues/2083) for figuring out how/where we want to make this export in the API surface area.

For more context, have a look at the [developer api ticket](https://github.com/ProjectMirador/mirador/issues/1693); that would be a good place to continue any more contextual discussion.

**Comment by mejackreed** [comment]
I think this is now resolved as we provide umd, cjs, and es in our npm package.
