### ISSUE TITLE
Export the top-level react component for parent react applications

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#2083]
see: https://github.com/ProjectMirador/mirador/issues/1693

`import miradorComponent from 'mirador'` (or something similar), should provide the top level react component.

**Comment by mejackreed** [comment]
A few things I have found in researching and implementing this issue:
 - lets move locales to `src`
 - we can export `es` modules that babel converts in our package without needing to change much of anything
 - we need to move `react` and `react-dom` to peerDependencies
 - ...

**Comment by aeschylus** [comment]
Ack! I knew the css strategy was going to pose an issue. 
https://blog.bitsrc.io/5-ways-to-style-react-components-in-2019-30f1ccc2b5b?gi=fc0ddca5bf3f
So much... choice!

**Comment by aeschylus** [comment]
I think a lot of this issue is just deciding how we want to wrap the things code-wise. I don't think we need to change a whole bunch in the toolchain, though styles makes sense.

**Comment by mejackreed** [comment]
Yep so far haven't seen a big change needed in toolchain. Though there are some oddities that I will try and wrap up into individual documented PR's so that the knowledge can be shared.

**Comment by aeschylus** [comment]
See https://github.com/ProjectMirador/mirador/issues/2197, #2173 for more context.
