### ISSUE TITLE
Provide a way of passing plugins into the configuration that doesn't rely on the global object

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#2085]
This has been requested in a number of places out of the context of the general API concerns, but I want to capture it as a need so we can suss out the requirements in a sharable way.

We need a way for posting script tags on a host webpage to add plugins, which currently works, but we don't want this to interfere with adding plugins in other ways for other users, especially those embedding mirador in react applications or inside other JS applications who need finer-grained control of when and how plugins are added.

**Comment by mejackreed** [comment]
Resolved in changes to the plugin system by @charbugs
