### ISSUE TITLE
Add a visual indicator for a window that has focus

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2095]
To visually indicate when a window has focus we want to add a 2px border to the top of all window top bars and then change the border color of a window when it gets focus. The result would look like this, where the second window is the one that has focus:

<img width="1037" alt="screen shot 2019-03-07 at 5 16 38 pm" src="https://user-images.githubusercontent.com/101482/53998684-d5d63680-40fd-11e9-9e4a-f96495571ff7.png">

---

And in mosaic:

<img width="1037" alt="screen shot 2019-03-07 at 5 11 05 pm" src="https://user-images.githubusercontent.com/101482/53999061-45005a80-40ff-11e9-92d8-83f6f25a8fe2.png">

---

I believe the updates involved are:

- Add the top border to the window top bar (`<header />`) of all windows:

`border-top: 2px solid #ffffff;` 

where `#ffffff;` is the same color palette specification as the window top bar (I think this is currently "primary - light"); that is, we want the border to exist on all windows but be invisible unless the window is in focus (and using `transparent` doesn't have the same effect).

- When a window gains focus, change the border color of the `<header />` element to the color palette's secondary color:

`border-color: #1967d2;` # or whatever the color palette's secondary color might be

- When a window loses focus, remove the class that added the focus border color (or whatever is the appropriate way to change the unfocused window's top border back to the color specified for the window top bar).

**Comment by cbeer** [comment]
What does it mean for a window to have focus?

**Comment by ggeisler** [comment]
I believe so. When the user has navigated (keyboard or mouse) into any window element, the window has focus.
