### ISSUE TITLE
Address Initial Menu Selection/Focus Issue

### ISSUE THREAD

**Issue by jkeck** [ProjectMirador/mirador#2115]
Currently the first item in the menu when popped up is focussed.  This is intentionally done by MUI (see mui-org/material-ui#5186 for more context).  There are three states (4 really, but `disabled` is not used in this particular menu), `focus`, `selected`, `hover`. The first item has the `focus` state (I believe so that it can be keyboard navigable using the arrows).  `focus` and `hover` look identical which causes the issue described in #1936.

A few options that came out of discussion during #1936/#2107 would be to update the styling so that the `focus` and `hover` state or more visually distinct or to use something like [MenuList composition](https://material-ui.com/demos/menus/#menulist-composition) which can give us the desired outcome visually but may have sub-optimal keyboard interactions.

**Comment by jvine** [comment]
Focus state for menu items should be applied to the text element inside the `<li>`:

```
    font-weight: 500;
    letter-spacing: -0.006em;
```

Note that this is going to cause a slight problem for the Window options menu with the inline options but we will address that separately.

**Comment by jkeck** [comment]
I'm not sure if the intention is to style the text element inside the `<li>` as mentioned above, but if you mean what the element the browser's focus is on, that may cause some issues.  The menu focus implementation comes from MUI and it focuses on the `<li>` explicitly.  We can style something w/o the focussed `<li>` using a pseudo selector, but actually changing the focus implementation to focus on an entirely different element in the DOM, that's going to take a quite a bit more work.

**Comment by camillevilla** [comment]
![Screen Shot 2019-04-10 at 4 33 21 PM](https://user-images.githubusercontent.com/5402927/55920672-8e384400-5bae-11e9-836d-1fb48e5ea829.png)

Popping an example of this in here, which I ran into while reviewing the WindowList menu in #2449

**Comment by jvine** [comment]
Currently working on a separate ticket that coordinates hover/focus/selected states across components.
