### ISSUE TITLE
Update behavior when adding resource in load window

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2126]
A few behavior refinements to the Add resource/load window:

- [x] Close the Add resource panel after the user submits using Add
- [x] Clear the Resource location field in the panel when the users submits using Add, or closes the panel via Cancel
- [x] When the user clicks Add, the new row for the resource should be added to the top of the resource list, rather than the bottom as it currently is

This one might need to wait until we figure out how to structure the list of resources to provide the necessary keyboard accessibility but ideally:

- When the new row for an added resource is added to the top of the resource list it should get current item focus and related current item highlighting (to make it more clear to the user that it was added to the list)

**Comment by mprove** [comment]
Without spending a thought I would add the new resource to the end of the list, scroll down and provide a visual cue. I know that there is no select mode. But a pulsing background might do. It is also feasible to slow things down (2 secs) to be in the range of the human perception.

**Comment by mprove** [comment]
The issue –add to top or bottom– is not of high severity.  "Usually" people will start with an instance populated with very few menifesti – no scrollbar needed. Once they add more and more they will learn wether new IIIF references are added at the top or the bottom.
