### ISSUE TITLE
UpdateViewport could be debounced by redux 

### ISSUE THREAD

**Issue by christopher-johnson** [ProjectMirador/mirador#2129]
In testing the new minimize and maximize actions, it appears that using lodash to debounce the `onViewportChange` function that dispatches `UpdateViewport` does not work properly if another action is fired before the lodash debounce is invoked. 
 
![Peek 2019-03-09 14-02](https://user-images.githubusercontent.com/5990301/54071982-c4636a80-4274-11e9-8a6d-406a266e1b07.gif)

I ran a few tests with [redux-debounced](https://github.com/ryanseddon/redux-debounced), and it appears to improve this since a redux debounced action will always execute at least once even if another action is fired.

**Comment by aeschylus** [comment]
I agree this needs to be addressed. Related to implementation of https://github.com/ProjectMirador/mirador/issues/1976
