### ISSUE TITLE
Implement annotation selection from WindowSidebarAnnotationsPanel

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#2134]
Per designs, when clicking on an annotation in WindowSidebarAnnotationsPanel show that annotation on the canvas.

![Screen Shot 2019-03-11 at 12 18 18 PM](https://user-images.githubusercontent.com/1656824/54147529-fe10ae80-43f7-11e9-82da-53cb5076d63b.png)

Basic canvas annotations showing all implemented in #2132, this enhancement only shows the "selected" annotations for a given `Window`.

## Mocks
https://xd.adobe.com/view/f2440f29-045b-4d8d-7b61-0d5c8ece8104-8475/screen/dc313c49-498d-4a64-a406-fedf73d3484b/Side-panel-open-Annotations-available-288r

**Comment by jkeck** [comment]
Closed by #2198
