### ISSUE TITLE
Typography review & adjustments

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2138]
- [x] thumbnail nav caption letter-spacing decimal point in the wrong place (fixed by #2159)
- remaining details in comment

**Comment by jvine** [comment]
## Side panels
- [ ] `WindowSideBarInfoPanel `
    - change `canvasDescription` to `body1` 
    - `windowSideBarHeading` should not have `windowSideBarHeading: theme.typography.h6,` override - default `h4` style is appropriate
- [ ] `WindowSideBarCanvasPanel`
   - give canvas labels variant `body1`
- [ ] `WindowSideBarAnnotationsPanel`
   - give `showingNumAnnotations` variant `subtitle2`

## Menus
All menu options should be `body1`. Currently the following menu options are displaying a larger font size that isn't specified in the supplied typography. 

- [ ] `WorkspaceMenu` - `listAllOpenWindows`
- [ ] `LanguageSettings`

## Inputs

- [ ] `ManifestForm` :  Add resource `TextField` - `body1`
- [ ] `WindowSideBarCanvasPanel`:  `Select` input and `MenuItem`s in  - `body2` (also I don't think we want autoWidth for this control.)

## Load window

- [ ] `<h2 class="jss2 jss15 jss31 jss28 jss194">Add resource</h2>` - should have `<h2> styling but is getting a font-size override from `jss194`.
- [ ] `ManifestListItem` 
    - give the manifest title `h6` (currently `subtitle1`) and remove its color setting. 
    - the provider and number info appears to have the desired `body2` typography but I can't see it explicitly

**Comment by cbeer** [comment]
For:

> ManifestForm : Add resource TextField - body1

What aspect of the `TextField` do you want to be `body1`?

**Comment by jvine** [comment]
Not sure how it's broken down in the component, but this is what's intended:

<img width="213" alt="Screen Shot 2019-03-13 at 9 57 09 AM" src="https://user-images.githubusercontent.com/6945691/54298659-64bbd680-4576-11e9-950a-a41153200bcc.png">
<img width="225" alt="Screen Shot 2019-03-13 at 9 56 03 AM" src="https://user-images.githubusercontent.com/6945691/54298660-65546d00-4576-11e9-996b-c6fb250afb86.png">

(Secondarily, the input in the Add resource panel was specified to have a static label (#1857 ) without the animation.)
<img width="470" alt="Screen Shot 2019-03-13 at 9 58 23 AM" src="https://user-images.githubusercontent.com/6945691/54298732-903ec100-4576-11e9-851f-c4052a5bf8eb.png">
