### ISSUE TITLE
Thumbnail navigation styling

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2142]
This issue is about the visual styling and theming flexibility of the thumbnail navigation strip.

Currently, a lot of absolute position calculation is causing overlap of elements. Goals are:

1. possibility for user selection of smaller/larger thumbnails (initially designed as a size/border drag handle on the companion window)
2. consistent, potentially customizable/theme-able, margins/sizes for the container, the images, and their borders
3. accommodation for a long-side scrollbar in the container so it doesn't obscure content
4. elimination of the short-side scrollbar
    - `<div class="ReactVirtualized__Grid">` has an inline style of `overflow: auto;` which is allowing scrollbars in both directions. This may be okay if the container height is calculated to allow for all content (see below) but it might be safer to specify `overflow: auto hidden;` for the horizontal nav and `overflow: hidden auto;` for the vertical.

I don't know if the grid component supports this, but it seems like this control would be much more flexible if the positioning and sizing were relative rather than absolute. 

<img width="584" alt="Screen Shot 2019-03-11 at 3 12 29 PM" src="https://user-images.githubusercontent.com/6945691/54168349-3bdafa80-442b-11e9-8236-c3e4b3c7ece0.png">

- Container: 
  - has a theme-able background
  - 2px padding on all sides
  - additional 14 px on the long outside (right or bottom, depending)
- Images have:
  - 2px padding
  - 2px border
    - unselected items have transparent border
    - selected item has secondary-colour border
  - 2px margin

<img width="631" alt="thumb nav horizontal" src="https://user-images.githubusercontent.com/6945691/54169268-3a133600-442f-11e9-9bd1-7bf49056e533.png">

<img width="552" alt="thumb nav vertical" src="https://user-images.githubusercontent.com/6945691/54169277-40091700-442f-11e9-8851-ac5d5491581d.png">

**Comment by jkeck** [comment]
Potentially useful info re: scroll-bar sizes: https://codepen.io/sambible/post/browser-scrollbar-widths
