### ISSUE TITLE
thumbnails can be requested at a width larger than the original (overscaling)

### ISSUE THREAD

**Issue by eroux** [ProjectMirador/mirador#2152]
Mirador can sometimes request thumbnails in size larger than the one advertised in the image service, which causes the thumbnail requests to receive http 400 errors from a server that doesn't support overscaling.

We fixed it in our fork in [this commit](https://github.com/buda-base/mirador/commit/cb3067158c2c71cf56b07ac48fba0a229261f4ca), in case the 2.7 branch is still maintained.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
