### ISSUE TITLE
thumbnails requested at various sizes even when compliance level is 0

### ISSUE THREAD

**Issue by eroux** [ProjectMirador/mirador#2153]
when compliance level is 0, thumbnails should always be requested at the max size, they are currently requested at various other sizes depending on the browser window

**Comment by eroux** [comment]
here's a patch we applied on 2.7 to fix that:

https://github.com/buda-base/mirador/commit/9b8c19ca10d1bf327c3ea8c50368dd12460afd28

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets. Level 0 is now supported in Mirador 3, so it would be great to have your feedback.
