### ISSUE TITLE
Dismiss window view menu when an item is chosen (?)

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#2156]
Currently, when a view is chosen from the window settings menu, the menu hangs around even after the mouse leaves.

I can see some reason in keeping it around after an item is clicked, but the mouse is still within the menu, but perhaps that should only happen when choosing thumbnail options. I sort of expect the menu to dismiss itself when choosing a view.

**Comment by jvine** [comment]
This is discussed/spec'd in #2029.

**Comment by aeschylus** [comment]
Ah, thanks. Closing.
