### ISSUE TITLE
Change app bar menu items with dialogs to inline menu items

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2171]
In the app bar menu, we currently include "Set workspace type" and "Settings." When selected, each of these opens a dialog window from which the user makes a selection. Because both of these dialogs only include two options, we think it would be more efficient to change the behavior to make these menu item options inline, similar to how the Language menu item currently works (i.e., selecting Language expands within the menu to show the two options nested within).

- [ ] Change label and behavior of "Settings" menu item

- [ ] Change label and behavior of "Select workspace type" menu item

Here's how the menu should look after making the changes (ignore the dividers in the menu; we will worry about those in a separate ticket if necessary, based on discussion with @jvine and @jkeck):

<img width="369" alt="closed" src="https://user-images.githubusercontent.com/101482/54303142-971e0180-457f-11e9-9a78-460aa6a9a3ff.png">

---

And when one of the updated menu items is selected:

<img width="369" alt="two-borders" src="https://user-images.githubusercontent.com/101482/54303266-d64c5280-457f-11e9-9064-87b1906e2b07.png">

---

Relevant changes:
- Change current label "Select workspace type" to "Workspace type"
- Instead of opening a dialog when selecting "Workspace type," expand to show its options (the way the Language menu expands), which are "Elastic" and "Mosaic"
- Change current label "Settings" to "Theme" and remove gear icon
- Instead of opening a dialog when selecting "Theme," expand to show its options, which are "Light" and "Dark"

**Comment by cbeer** [comment]
Are we not going to implement https://github.com/ProjectMirador/mirador/issues/1838? If we are, I don't think changing all the elements to do an inline menu, and then changing them back to a modal is a good idea.

For the settings panel, are we not anticipating any other settings that might go there (including potential settings from plugins)? Again, I'd hate for us to do all the work to remove the modal and then undo it all in the not-distant future.

**Comment by ggeisler** [comment]
I'll bring @jvine into this because we discussed the drawback of changing things and then having to change back. I believe the reasoning was that 1) it'll probably be quite a while before we have the grid workspace option available and it felt unreasonable to make the user do the extra work of interacting with a dialog that had only two options and 2) we actually don't know of any user "settings" other than theme that would justify the Settings dialog.

@jvine might have additional thoughts.

**Comment by ggeisler** [comment]
I'll add that I do think that even if we don't currently know of anything besides theme that would go in Settings, @cbeer's point about future plugins possibly needing it is a good one. Earlier today I mentioned to @jvine in passing (for a different reason) the possibility of keeping Settings in the menu but disabling it. That way we could leave the associated Settings dialog for future use but not make the user use it just to change the theme.

**Comment by jvine** [comment]
... but then when we do have other Settings that need to be in that dialog, we'd need to move Theme back out of the menu. I don't think we should have Setting-like things in the menu, outside of the dialog, as well as representing a non-functional Settings feature. As much as I like the idea of putting these options directly in the menu (and I do) maybe we need to just go ahead and make the dialog usable and extensible. ...?

**Comment by ggeisler** [comment]
Okay. Hopefully you haven't done any work on this yet, @cbeer. I'll close it and we can work on the "improv the dialog windows" ticket soon.
