### ISSUE TITLE
Update styling of TOC select menu

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2181]
Given the MUI/React components are not ideal, we're hoping we can improve the styling of the select menu used in the TOC panel. Currently it looks like this:

<img width="281" alt="select-current" src="https://user-images.githubusercontent.com/101482/54323343-13cbd280-45b6-11e9-9390-279e8d23ca25.png">

It appears that it is using a variant of the select component that includes space for a label? In any case, I think we want to use the variant that is called "Without label" in the [documentation](https://material-ui.com/demos/selects/):

<img width="515" alt="select-example" src="https://user-images.githubusercontent.com/101482/54323553-24307d00-45b7-11e9-83f5-2a1c0894c1a5.png">

In addition, I think we're going to have to make some CSS adjustments if we want it to look decent in the panel header context. I don't really know how much flexibility we have in terms of fine-tuning the component-related CSS, or how to be more specific about what we need to update, but this is what we are after (I adjusted the background color and some padding values on various divs to get this):

<img width="281" alt="select-goal" src="https://user-images.githubusercontent.com/101482/54323496-e29fd200-45b6-11e9-88d8-94aecdfe3641.png">

I'm happy to work with a developer on this if it makes sense to discuss what is possible, CSS-wise.

**Comment by christopher-johnson** [comment]
This selector could be a switch since it is a boolean.  (or are there future plans for this?)

An additional issue with the selector styling is if the companion window width is increased, then it will appear horizontally inline with the title, and selectors next to labels do not horizontally align. The placement below is only because it does not fit.   

![Peek 2019-03-14 06-13](https://user-images.githubusercontent.com/5990301/54332865-680b9c80-4620-11e9-8281-12f291bf889c.gif)

**Comment by ggeisler** [comment]
Thanks @christopher-johnson. The switch is definitely a better control when there are only two options (and I think we've identified some other places in our designs where we intend to switch a radio button group to a switch).

But in this case I believe we have to allow for more than two options, so a switch wouldn't work. Here's a mockup that shows the potential for more options:

<img width="356" alt="Screen Shot 2019-03-14 at 9 22 11 AM" src="https://user-images.githubusercontent.com/101482/54374323-20930980-463c-11e9-9b31-b15b2eb99d9d.png">
