### ISSUE TITLE
Add a top-level export to the mirador codebase that provides a whole-viewer react component to a containing app.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#2197]
Spun out of #2083 and #2173.

**Comment by aeschylus** [comment]
This should also be available in the UMD build.

**Comment by aeschylus** [comment]
For an example of how I think we will want to make the viewer available, see https://codesandbox.io/s/wkyw556xp7

**Comment by cbeer** [comment]
Maybe done well enough with #3429
