### ISSUE TITLE
Truncate the canvas title when necessary

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2212]
Issue #2113 was closed but one aspect of that ticket that doesn't seem to have been captured in any of the spinoff tickets is this part: "Labels longer than can fit in the current canvas width should be truncated so the label always uses one line only." Long labels currently look like this:

<img width="276" alt="caption-current" src="https://user-images.githubusercontent.com/101482/54467676-f3318300-4743-11e9-86a2-d23d2e7502bd.png">

We want to minimize the height necessary for the canvas controls/label container and it isn't absolutely critical that the user see the entire title of the canvas (it is always available in full in the About sidepanel), so it would be better to truncate it to always keep it to one line.

As with #2167, I guess we will need to monitor the canvas width to ensure it is always truncated as necessary (unless there is a better way to do it). So the above canvas might look like this to start:

<img width="824" alt="Screen Shot 2019-03-15 at 3 16 01 PM" src="https://user-images.githubusercontent.com/101482/54467745-5cb19180-4744-11e9-93e9-caf6a709644e.png">

and like this when the sidepanel is opened, reducing the width of the canvas:

<img width="513" alt="controls-sm" src="https://user-images.githubusercontent.com/101482/54467729-40adf000-4744-11e9-8414-7ab200202a25.png">

**Comment by cbeer** [comment]
I think this was a regression when the canvas info was added; easy enough to fix up.
