### ISSUE TITLE
Manifests are not persistently added to "data": [] when using "Add new object from URL"

### ISSUE THREAD

**Issue by lguariento** [ProjectMirador/mirador#2220]
Hello, how can I persistently add a manifest to my "data": [] array? I have cloned the repository and I am serving my Mirador instance via `grunt serve` (just testing it). When inputting a (remote) manifest.json file in the "Add new object from URL" field I can see it in the list of my repositories. Nevertheless, upon refreshing the page it just disappears. In order to make it persistent I need to add it directly to my "data": [] array by hand. Is there a way to make the loading from the user interface permanent?

Thanks

**Comment by mejackreed** [comment]
Not by default. You would need to do some customization with Mirador  2 and persist figure out a data syncing mechanism to keep the state in sync.
