### ISSUE TITLE
Couple of tooltip display issues

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2233]
1. Tooltips for the expand/collapse toggle appear in the upper left of the window rather than associated with the icon.
<img width="390" alt="Screen Shot 2019-03-18 at 1 40 02 PM" src="https://user-images.githubusercontent.com/6945691/54562080-7391f700-4983-11e9-91cd-0ac538c076c4.png">
<img width="230" alt="Screen Shot 2019-03-18 at 1 41 40 PM" src="https://user-images.githubusercontent.com/6945691/54562137-94f2e300-4983-11e9-9d5f-7053050d064d.png">

2. The "Exit full screen" tooltip seems to be associated with the "Full screen" icon. I can't capture this in a gif. Try this:
- hover over Full screen icon - "Full screen" tooltip appears
- click Full screen icon - tooltip quickly changes to "Exit full screen" then disappears
- hover over Exit full screen icon - no tooltip

**Comment by jkeck** [comment]
FWIW, I believe there is an issue w/ all tooltips in Fullscreen mode.

**Comment by jvine** [comment]
Ah totally right, they are all missing. I was distracted by the ghost of the text appearing briefly.
