### ISSUE TITLE
Redundant titles in span-wrapped buttons are read twice by screenreader

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2234]
I've been noticing this pattern in the HTML:

```
<span class="" title="Toggle window sidebar">
<button ... aria-label="Toggle window sidebar">
```

Is there a reason for the title attribute on the `<span>` element? It causes VoiceOver to announce "Toggle window sidebar" twice. I know not all AT will behave the same way, but I can't see any reason for the user to be aware of the wrapping element.

**Comment by cbeer** [comment]
How important is it for disabled buttons to have tooltips? I think the span was added as a work-around to make sure they appear in all cases.

**Comment by jvine** [comment]
My initial reaction is if this is the cost of disabled button tooltips, I'd rather not have disabled button tooltips. @sdellis do you agree?

**Comment by cbeer** [comment]
I wouldn't call it the cost of disabled button tooltips, but if it was important, it would be a significant amount of effort to figure out an appropriate work-around that works everywhere.
