### ISSUE TITLE
"Close all other slots" option

### ISSUE THREAD

**Issue by rsinghal** [ProjectMirador/mirador#224]
- [x] switch to compare mode from single object and keep current object open in one of the slots
- [ ] switch from compare to single object on selected object

**Comment by rsinghal** [comment]
Should add a "close all other slots" in the slot creation drop down.  Right now, a user has to close the slots they don't want to look at.

**Comment by aeschylus** [comment]
I think this is out of scope for 2.1. We need clearer use cases and design still. I think to a large extent the use cases we have discussed about this are handled by fullscreen mode, though I do think there is a need to add some kind of quick (duplicate this to compare) type option that spawns an adjacent slot.

**Comment by mejackreed** [comment]
Closing this Mirador 2 issue where design is not focused.
