### ISSUE TITLE
Stanford use case for IIIF Auth

### ISSUE THREAD

**Issue by camillevilla** [ProjectMirador/mirador#2240]
Note: We'll probably need to split this up into multiple tickets / PRs.

- Figure out if an info request has an available auth service.
- Do I get redirected to a degraded version of the image? 
- Display a login button for the service
- Clicking the button uses the service to authenticate
- Image information requests get resent 

![IIIF auth workflow diagram](https://iiif.io/api/auth/1.0/img/auth-flow-client.png)

### Resources
- [Spec: IIIF Auth 1.0](https://iiif.io/api/auth/1.0/)
  - [workflow diagram](https://iiif.io/api/auth/1.0/#workflow-from-the-browser-client-perspective
- Fixtures: https://github.com/ProjectMirador/mirador/wiki/M3-Fixtures-&-sample-IIIF-data#auth

**Comment by mejackreed** [comment]
Resolved in #2367 . Closing for now until we uncover any needed next steps
