### ISSUE TITLE
Whitespace details for Add resource / Load window

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2252]
### Main window

**`.mirador-workspace-add`**

- padding-top: 68px;
- padding-left: 0;
- padding-right: 0;
- overflow: hidden auto;

**`@media (min-width: 600px) .mirador-workspace-add`**

- padding-top 0;
- padding-left 68;

**`<ul>`**

- box-shadow: 0px 1px 3px 0px rgba(0,0,0,0.2), 0px 1px 1px 0px rgba(0,0,0,0.14), 0px 2px 1px -1px rgba(0,0,0,0.12);
- border-radius: 4px;
- background-color: #fff;
- margin: 16px;

### Add resource panel

**absolute-positioned `<div>`**

- set border-top to none
- for mobile: set left and right to 0px
- @media (min-width: 600px): set left to 65px and right to 15px

`<header>`
- set height and min-height to 48px and adjust parent's top margin to match

**mobile adjustments** (no change for 600px+)

- right-align buttons 
- set field width to 100% 

<img width="978" alt="layout - load window desktop" src="https://user-images.githubusercontent.com/6945691/54647675-a3fb9300-4a60-11e9-8c5c-f1dda1b518a0.png">

<img width="327" alt="layout - load window mobile" src="https://user-images.githubusercontent.com/6945691/54647676-a3fb9300-4a60-11e9-8bcb-ffd0f3de9cf8.png">

**Comment by jkeck** [comment]
This may be my naiveté, but should the `<ul>` be wrapped in a `Paper` to get the box-shadow/rounded corner effect we're looking for?

**Comment by jvine** [comment]
That would probably be more correct, though I don't know if it has side effects. <- my own naiveté.

**Comment by jkeck** [comment]
I'll give it a try and take screenshots of both.
