### ISSUE TITLE
Typography corrections: Language menu, canvas description

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2253]
1. "Language" option in Workspace menu - sub-items were fixed, but  now the parent is too small. Should be body1, 1em like all the other options.

<img width="277" alt="typography - language" src="https://user-images.githubusercontent.com/6945691/54648419-677d6680-4a63-11e9-8e15-bee6e51751c4.png">

2. Canvas description. Marked as fixed in #2138 but still displaying as body2 rather than body1.

<img width="185" alt="typography - description" src="https://user-images.githubusercontent.com/6945691/54648424-6a785700-4a63-11e9-84eb-7154884200f6.png">

**Comment by cbeer** [comment]
For #2, you've circled the manifest description; I assume you want that to also be `body1`?

**Comment by jvine** [comment]
Oh well that explains it. Yes, please.
