### ISSUE TITLE
Annotation region stroke widths do not remain constant when zooming

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#2279]
![annotation stroke widths](https://user-images.githubusercontent.com/145874/54776483-7849eb80-4bcd-11e9-8a91-72ccd6efa93c.gif)

https://github.com/ProjectMirador/mirador/blob/07e1544f7273cc8ace844637057b338b94e3fba2/src/components/OpenSeadragonViewer.js#L143

We'll need to both make the stroke width a function as well as cause that function to be called during the OSD `animation`([OSD docs](https://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#.event:animation)) callback.

**Comment by ggeisler** [comment]
Also, independent of the zooming issue, the current stroke width seems a bit too wide, especially when there are lots of annotations immediately adjacent to each other (e.g., a manuscript with line-by-line annotations).

Could we get a width closer to what was used in Mirador 2?

<img width="375" alt="Screen Shot 2019-03-22 at 1 58 47 PM" src="https://user-images.githubusercontent.com/101482/54852721-ec0df600-4caa-11e9-87c6-0e7207042b3c.png">

Granted, the Mirador 2 width is borderline too narrow, especially when the image background color doesn't have a lot of contrast with the annotation border color, but something closer to the Mirador 2 width than the current Mirador 3 width seems worth trying.
