### ISSUE TITLE
Update the "Download/Export" dialog

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2289]
Related to #2286

The title of this dialog is currently "Download/Export workspace" but since it seems that the only way it can be used is to copy the configuration presented, we suggest simplifying the title to "Export workspace" Also, the dialog currently does not have any buttons. Buttons should be added, following the approach used in [form dialogs](https://material-ui.com/demos/dialogs/#form-dialogs).

- Change the label of the workspace menu item that triggers this dialog to "Export workspace"
- Change the dialog heading to "Export workspace"
- Add [text button](https://material-ui.com/demos/buttons/#text-buttons) labeled "Cancel"
- Add a [contained button](https://material-ui.com/demos/buttons/#contained-buttons) labeled "Copy"
- Use the `scroll=paper` [long content option](https://material-ui.com/demos/dialogs/#scrolling-long-content) so users don't have to scroll through entire view of the code if they just want to copy it

The updated dialog would look similar to this:

<img width="541" alt="export" src="https://user-images.githubusercontent.com/101482/54790687-31232100-4bf4-11e9-9aed-fc74f5be6bf9.png">

**Comment by glefi** [comment]
@ggeisler should the dialog be closed after clicking the `Copy` button?

**Comment by ggeisler** [comment]
@glefi Yes. We might need to think about adding a confirmation message ([snackbar component](https://material.io/design/components/snackbars.html#)) after the dialog closes, but let's do that separately after we see how this works.
