### ISSUE TITLE
Plugin hook in window menu

### ISSUE THREAD

**Issue by charbugs** [ProjectMirador/mirador#2298]
There should be a place in the window menu for plugin components. This place should only show up if a plugin wants to render a component there, otherwise it's not visible. I know there is design needed and generally we should come up with a concept for plugin UX stuff. But to move the plugin system forward and be able to demo it, it would be nice to have this simple plugin playground.

**Comment by aeschylus** [comment]
I have a question about the title of these sections. In a related PR for the window button menu, the title of the section was "plugins". Is this desirable? Do we even want a section? @jvine @ggeisler

**Comment by jvine** [comment]
I'm working on the design for this now. We don't necessarily want a visible-to-the-user section title but a defined location in the menu is appropriate. (And I think we want text-only or icon+text options, but not icon-only. I'm just trying to think through these options, and I'll post the design as soon as it's done.)
