### ISSUE TITLE
Fix hide sidepanel toggle 

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2304]
Not sure if for some reason it is just me, but I can no longer hide the sidepanel because the tooltip for it obscures the hit target of the toggle:

<img width="362" alt="Screen Shot 2019-03-22 at 9 09 46 AM" src="https://user-images.githubusercontent.com/101482/54836978-902f7700-4c82-11e9-8008-b6fec23fe7a4.png">

**Comment by camillevilla** [comment]
Ideal behavior: something like Google Maps
<img width="215" alt="Screen Shot 2019-03-22 at 9 22 01 AM" src="https://user-images.githubusercontent.com/5402927/54837580-fcf74100-4c83-11e9-95a9-3f2659aacbcc.png">

**Comment by jkeck** [comment]
I _think_ this is closed now by #2321/#2318.  The placement isn't perfect (due to absolute positioning I believe).  We can re-open or create a new ticket if this needs more work.
