### ISSUE TITLE
Remove the "water droplet" animations

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2306]
We're not fans of the MUI water droplet animation you see on activating various elements. Discussed with @aeschylus and I think he knows how to remove.

**Comment by camillevilla** [comment]
Ok, so I think ripples (their terminology) can definitely be disabled on MUI elements. 
https://material-ui.com/api/button-base/#props

Is an alternative hover style defined yet?

**Comment by jvine** [comment]
Depends whether ripple the only thing that's giving the buttons hover/focus/active state. Without ripple I would expect a solid background colour change - light grey for hover/focus, darker grey for active - see #2282.

**Comment by aeschylus** [comment]
MUI calls this the "touch ripple" and "focus ripple". Sadly, it looks like it needs to be individually disabled on every single component that uses it.

[this method](https://stackoverflow.com/questions/42211994/how-to-disable-ripple-in-material-design-react) doesn't work. Will try https://github.com/mui-org/material-ui/issues/240#issuecomment-435303327 next
