### ISSUE TITLE
Add hover state to thumbnail nav items

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#2311]

**Comment by jkeck** [comment]
Should this be the same hover state that's used for currently selected canvases (same as we do in gallery view)?

**Comment by mejackreed** [comment]
I'd like to check with @jvine to get some direction about this. I can't recall hover state being discussed.

**Comment by jvine** [comment]
Thumbnail nav does need a hover state; but we think we have multiple hover states currently, and some confusion between hover, focus, and selected states. This is on our radar to resolve soon. I slapped a design-needed on this and we will prioritize coming up with a consistent pattern.

**Comment by jvine** [comment]
See #2479

**Comment by ggeisler** [comment]
Superseded by #2479
