### ISSUE TITLE
Fix Gallery View Item layout styling

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#2312]
- [x] items should have a fixed height
- [x] item captions should have a fixed height area in which to render, providing 2 lines of text
- [x] ~~item captions should break words in order to fit more text on both lines~~
- [x] item captions should use ellipses if they are too long
- [x] it images are too skinny, there should be a minimum width of 60px for the total item layout box so that captions are still legible

**Comment by jvine** [comment]
Note that these specs came out of a paired design session including me & @ggeisler. Let us know if mockups are required.
