### ISSUE TITLE
Move focus to input field when selecting Add resource button 

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2314]
Since adding a resource URL is the only action available after the Add resource button is selected, we should put the cursor focus in the Resource location input when opening the Add resource panel so the user doesn't have to click in the input to manually move the focus before adding the URL.

<img width="928" alt="Screen Shot 2019-03-22 at 2 40 25 PM" src="https://user-images.githubusercontent.com/101482/54854547-858bd680-4cb0-11e9-9f34-61f170a484d4.png">

**Comment by camillevilla** [comment]
Closed by #2334
