### ISSUE TITLE
Manifesto output not as expected for all fixtures

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#2315]
## v2 manifests have no hierarchy
see: [Richardson 7 in UV](https://universalviewer.io/examples/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Fiiif.lib.harvard.edu%2Fmanifests%2Fdrs%3A5981093&xywh=-1549%2C-787%2C5665%2C5114)
Versus in Mirador at projectmirador.org/demo (filter-search from list)
## v3 manifests have no canvases (might be a method for this?
@sdellis 
I'm not sure I'm doing it quite right, but some ranges have canvases in the included __jsonld
No way to reliably get canvases from rangeIds in manifesto.

**Comment by mejackreed** [comment]
This has now been resolved.
