### ISSUE TITLE
Some fixtures don't validate

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#2316]
https://iiif.lib.harvard.edu/manifests/drs:5981093

SCTA, quarrachi 1928, Summa Halensis of Alexander Hales with Detailed TOC (8-12 levels deep) (currently fails in Mirador 2, Maximum Call Stack Size exceeded, but it validates as a 2.1 manifest) https://gist.githubusercontent.com/jeffreycwitt/90b33c1c4e119e7a48b7a66ea41a48c1/raw/522b132409d6c67a78f8f26b0ceb7346a52cfe62/test-manifest-with-complicated-toc.json - also crashes UV, seems to produce a range lookup error. Could some ranges be pointing to themselves or something?
<img width="434" alt="Screenshot 2019-03-22 at 3 32 37 PM" src="https://user-images.githubusercontent.com/145874/54856438-be7b7980-4cb7-11e9-97c9-71e1f3faecd1.png">

Same error for the other scta manifest, yet it still loads and produces beautiful ranges.

**Comment by mejackreed** [comment]
The Harvard manifest is loading correctly now. The SCTA has some validation issues. Closing this issue now, please reopen or create a new issue if there are additional TOC error.s
