### ISSUE TITLE
Maximize window button regression

### ISSUE THREAD

**Issue by camillevilla** [ProjectMirador/mirador#2317]
The maximize window button is no longer popping things up to full screen. Something weird is going on with the window state, because they seem to be loading with minimize buttons by default.
![Screen Shot 2019-03-22 at 5 46 59 PM](https://user-images.githubusercontent.com/5402927/54859517-53d43900-4ccb-11e9-990a-0fd332954424.png)

**Comment by jkeck** [comment]
Closed by #2320
