### ISSUE TITLE
Profile all our things

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#2330]
I've been noticing some slowness in the window sidePanel while working on the table of contents features. There are probably some problems specific to that, which seem to be blocking the user thread, but in general we should do some performance checking at some point to make sure we haven't made an architectural mistake on this front. In particular, I wonder if our selectors are actually memoizing things as we expect, and if perhaps there are some simple react mistakes we may be making that affect performance. I'm just going to gather some links here for us to look at together:

- [React Performance Debugging Examples](https://marmelab.com/blog/2017/02/06/react-is-slow-react-is-fast.html)
- [relationship between reselect memoization and state change function signatures](https://github.com/reduxjs/reselect#faq)
- [using the `recomputations` method to check whether a selector is actually memoizing](https://github.com/reduxjs/reselect#q-how-do-i-test-a-selector)
- [reselect dev tools](https://github.com/skortchmark9/reselect-tools)

**Comment by charbugs** [comment]
According to the docs a reselect selector only stores the latest result of an invokation and returns this saved value if the arguments in the next call doesn't change. But in many cases we invoke selectors with different arguments each time, for example if we want to get state pieces for different windows. So in this cases we do not benefit from the memoization capabillities of reselect.

Another thing with reselect selectors is that they are only useful if there are computations in play. Take for example the code from https://github.com/ProjectMirador/mirador/blob/master/src/state/selectors/config.js:

```javascript
export const getShowZoomControlsConfig = createSelector(
  [state => state.workspace],
  workspace => workspace.showZoomControls,
);
```

Here we only access a state property and reselect may be performance overhead. This could also be done with:

```javascript
export const getShowZoomControlsConfig = (state) => state.workspace.showZoomControls;
```

The function below in turn might be useful as there is a computation:

```javascript
export const getLanguagesFromConfigWithCurrent = createSelector(
  [getConfig],
  ({ availableLanguages, language }) => Object.keys(availableLanguages).map(key => ({
    current: key === language,
    label: availableLanguages[key],
    locale: key,
  })),
);
```

**Comment by mejackreed** [comment]
I've been looking at component re-renders also. I've looked a little into using `isEqual` and `memoize` from lodash in `createSelector` with no re-render perf improvement thus far. Using https://github.com/welldone-software/why-did-you-render to calculate re-renders

**Comment by mejackreed** [comment]
Also, I've found this document has some addition helpful information related to `mapStateToProps`: 

https://github.com/reduxjs/react-redux/blob/master/docs/using-react-redux/connect-extracting-data-with-mapStateToProps.md

**Comment by mejackreed** [comment]
I've created a wiki page to start documenting approaches for different profiling: https://github.com/ProjectMirador/mirador/wiki/M3---Performance-and-Profiling
