### ISSUE TITLE
Enable application full-screen icon to cancel full-screen mode

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2342]
The app bar full-screen icon puts the app into full-screen mode, but selecting the full-screen icon when in full-screen mode doesn't do anything; you have to use the ESC key to get out of full-screen mode.

The app bar full-screen icon should enable getting out of full-screen mode the same way as the ESC key does.

**Comment by jkeck** [comment]
I _believe_ this was fixed by #2349.  @ggeisler can you confirm?

**Comment by ggeisler** [comment]
Yep, I think #2349 fixed both #2343 and this ticket but only #2343 was connected to the fix. Good catch.
