### ISSUE TITLE
Annotations icon/panel should not be available when there are no object annos

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2344]
If an object has no annotations at all (no canvas in it has annotations), we should not show the annotations icon in the window sidebar. For example, no canvas in the NGA fixture has annotations so we shouldn't show the annotations icon and enable the user to access a side panel that won't ever have content:

<img width="414" alt="Screen Shot 2019-03-29 at 11 47 50 AM" src="https://user-images.githubusercontent.com/101482/55255874-dce1f780-5218-11e9-9047-58aeba9e4d19.png">

We should only see the metadata and index sidebar icons for an annotation-less object like this one.

**Comment by mejackreed** [comment]
@ggeisler I'm not sure we have a way to know if no annotations are available for an entire object. We only check annotation availability when we navigate to a specific canvas. Without doing it this way, we would need to check every canvas which could bog things down. This pattern might also break when an external annotation store is configured. In this case it may appear kind of jittery, adding the anno panel back.

Could an alternative to be to make this panel configurable? So an adopter who knew there would never be any annotations could just turn it off?

**Comment by ggeisler** [comment]
@mejackreed Bummer, but makes sense. Pre-checking every canvas of a large manifest doesn't seem very feasible.

I think the configuration idea makes sense. It does seem like there could be cases where an implementor knows their Mirador implementation won't include manifests with annotations, and therefore being able to suppress the annotation icon would keep the window sidebar nav cleaner in their implementation.

I guess a potential problem with that is if that implementor suppressed the annotation menu but their users are still able to use the load window to add IIIF manifests directly, a user could add a manifest with annotations and have no way to view them. But perhaps that is just part of the considerations the implementor should make when deciding to turn off annotations.

@jvine Do you have thoughts about how we should handle this?

**Comment by jvine** [comment]
Sad face. One of our early design goals was to avoid displaying tabs with no possible content, à la Mirador2. Is this going to be true for layers as well? 

I mean... I can imagine an implementor wanting to turn off annotations for various reasons, and we should allow that configuration. But the intent was that the presence of the annotations icon would indicate that there **are** annos in this manifest. It's information that's useful to the user, and it's a loss that we can't present it. 

I don't know what to suggest.

**Comment by mejackreed** [comment]
It may be more feasible for layers, but I haven't really done analysis on it yet. Happy to chat through more of this if it makes sense on a call to work through.

**Comment by ggeisler** [comment]
I created a new ticket #2478 to add a config setting that would enable annotations to be turned off and am closing this ticket. Hopefully we can figure out a way to hide the annotations icon/panel automatically as described in this ticket sometime in the future, but #2478 would partially mitigate the problem.
