### ISSUE TITLE
Make default state of thumbnail strip OFF

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2346]
It looks like the current default value for the thumbnail strip is `Bottom` (when opening a new window, the thumbnail strip is always open and placed at the bottom of the window).

We should make the default value for the thumbnail strip to be `Off`. This will make new windows look less cluttered and not give the user more information than she might want.

**Comment by camillevilla** [comment]
@mejackreed see my comment in your PR: 
https://github.com/ProjectMirador/mirador/pull/2350#issuecomment-478407461
