### ISSUE TITLE
Mirador3 breaks with multi-part collections

### ISSUE THREAD

**Issue by sdellis** [ProjectMirador/mirador#2354]
Mult-volume works should be viewable in Mirador. 

[Example manifest](https://figgy.princeton.edu/concern/scanned_resources/4802a8cb-70a0-4021-81e4-1d6a10b83249/manifest) for testing.

**Comment by ggeisler** [comment]
There's another example of the load failure with multi-part works (in case it's helpful for development) in the default set of load window resources: [The biological basis of medicine](https://wellcomelibrary.org/iiif/collection/b18031511)

**Comment by sdellis** [comment]
One assumption is that we will want most components to handle both Manifests and MVWs (Multi-part Collections) using the same (or almost the same) UI views. Thoughts @ggeisler and @jvine?  

For instance, the Thumbnail strip will display the thumbnails of the manifests rather than thumbnails of the canvases, at least until the user clicks through to a volume (i.e. Manifest) via the TOC. 

There will be slight differences, like no book-view for MVWs until we drill down to the manifests. And of course the TOC will behave slightly differently for MVWs because there will be at least one level in the hierarchy before we actually get to any manifests, and probably don't want to load all the manifests until needed. 

We could do this via a Facade pattern to organize the backend code. For example, a selector like `getFirstCanvasThumbnail()` could be abstracted to `getFirstThumbnail()` and depending on whether it's a Manifest or Multi-part Collection, we would deliver what is expected (either Canvas thumbnail or Manifest thumbnail) through the same function call, despite working with different data structures. @mejackreed @aeschylus What do you think? Perhaps something we should discuss with the group?

**Comment by sdellis** [comment]
MVW wireframe designs are [here](https://xd.adobe.com/view/2b634206-c940-4835-5f00-30be1edfd7a3-5d52/screen/4bc3b066-61fd-4b92-8af9-c4ffa3441dc4/index-MVW1/).

**Comment by sdellis** [comment]
One issue is that the `manifestId` associated with a Window may change based on the volume selected. When a new volume is selected, we will need to update both the lookup id in the Redux `manifests` list as well as the id associated with the Window.

**Comment by mejackreed** [comment]
This has now been resolved and collections and MVW are fully supported in Mirador 3.
