### ISSUE TITLE
Expose manifest URL somewhere in the UI

### ISSUE THREAD

**Issue by camillevilla** [ProjectMirador/mirador#2357]
## Mirador 2
<img width="701" alt="Screen Shot 2019-04-01 at 3 26 31 PM" src="https://user-images.githubusercontent.com/5402927/55363698-c21ab780-5492-11e9-8639-c3a733e7b6bd.png">

## UniversalViewer
<img width="844" alt="Screen Shot 2019-04-01 at 3 27 43 PM" src="https://user-images.githubusercontent.com/5402927/55363686-ba5b1300-5492-11e9-8437-b18ed8cef892.png">

**Comment by ggeisler** [comment]
👍 We have a plan for this... hopefully in a ticket to come this week.

**Comment by camillevilla** [comment]
Great! Closing this in favor of #2373.
