### ISSUE TITLE
Flatten annotation state

### ISSUE THREAD

**Issue by charbugs** [ProjectMirador/mirador#2363]
Currently annotation objects are grouped by canvases in the state. As far as I understand the canvas id is already part of the annotation. Is it possible to flatten the annotation state? That would the annotation reducers simpler and similar to other reducers, so generic utility function can be applied.

A similar problem is in the windows state with `selectedAnnotations`. Is it possible that this prop only refers to annotation IDs?

**Comment by mejackreed** [comment]
Do we still need to do this @charbugs ?
