### ISSUE TITLE
Revise panel header layout

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2370]
Panel header needs adjustment to support longer panel titles (e.g. german) without moving buttons; better/smaller drag/move affordance; consistency.

**Comment by jvine** [comment]
Rationale/background for this issue:

- current layout allows elements that should be consistently placed change location based on the length of the title
- longer (e.g. translated) titles don't wrap consistently and cause other elements to move
- the current icons don't (and weren't meant to) work in this context
- current DOM order implies something about the header that isn't quite accurate, and places the move and close buttons between the dropdown selector and the list it controls
- we have one panel (Annotations) where the panel control ("Highlight all") was placed outside of the header, for reasons. For consistency, we'd like it to be moved into the header. 

<img width="247" alt="long title wraps close" src="https://user-images.githubusercontent.com/6945691/55831349-bbf68d80-5ac7-11e9-9c4e-d40c69376ee0.png">
<img width="736" alt="inconsistent placement of controls" src="https://user-images.githubusercontent.com/6945691/55831350-bbf68d80-5ac7-11e9-800f-2917c28dc3bb.png">


### Preferred DOM order
```
<div class="mirador-companion-window-header">
  <h3>
  <button>[move]
  <button>[close]
  <div class="mirador-companion-window-title-controls">
</div>
```

### Layout
![header-layout](https://user-images.githubusercontent.com/6945691/55830785-8d2be780-5ac6-11e9-90b3-ab2af4f3bc2e.png)

<img width="252" alt="long title wrap" src="https://user-images.githubusercontent.com/6945691/55831371-c7e24f80-5ac7-11e9-8b55-00ce0076b3b0.png">

- `.mirador-companion-window-header` needs padding-left:16px. Currently this is only applied in the left sidebar. (Blame: me.)
- "move" icon should use `sharp-drag_indicator` for both locations. 
- "move" button has `width:24px; margin-left:-16px`
- `.mirador-companion-window-header` needs `align-items: flex-start;` to keep the move and close buttons top-aligned when the title wraps (this needs to override the general `align-items: center;` that affects just about everything everywhere)
- `.mirador-companion-window-header` needs `justify-content: space-between;` to keep the close button in the far right without absolutely positioning it
- `<h3>` needs `align-self: center;` to keep it nicely aligned when it doesn't need to wrap.
- `.mirador-companion-window-title-controls` seems to need a set height and its own flex attributes to make the control align nicely in both side and bottom locations: `min-height: 48px; display: flex; align-items: center;`
- the only way I've been able to keep the controls from ever wrapping up to the top row in the side panels, AND prevent the title from breaking the layout when it wraps, is to give the title `width:160px`. I don't think this is a great solution, but... it sort of works. Better solution welcome.

### Side vs bottom
The window controls are meant to appear inline between the title and close button on the bottom panel. However, it's possible for even the horizontal panel to be narrow enough that the controls need to wrap below the title, and the close button needs to remain in the upper right. As far as I can tell, this means the bottom panel needs some awareness of its width, so it can switch between the wrapped and extended layouts. 

### Outcomes
<img width="695" alt="Screen Shot 2019-04-09 at 11 12 33 AM" src="https://user-images.githubusercontent.com/6945691/55827183-741f3880-5abe-11e9-9184-cfd228b4809f.png">
<img width="695" alt="Screen Shot 2019-04-09 at 11 11 17 AM" src="https://user-images.githubusercontent.com/6945691/55827185-741f3880-5abe-11e9-99f0-532c1513f56e.png">
<img width="727" alt="Screen Shot 2019-04-09 at 9 51 28 AM" src="https://user-images.githubusercontent.com/6945691/55827187-741f3880-5abe-11e9-87aa-ec1ac1ca216e.png">

**Comment by cbeer** [comment]
Do you want sharp-drag_indicator, even if we don't have drag-and-drop functionality?

**Comment by jvine** [comment]
Yes. It's a tradeoff. It's not the perfect icon for the current behaviour, but it does convey "move", and we still intend for the panels to be drag-and-droppable someday. It doesn't seem like a good candidate for a custom icon. So... yes.

**Comment by jvine** [comment]
Close button is not staying in the upper right corner when there are controls present. (Also the Highlight all control has some extra left padding.)

**Currently in master**

<img width="248" alt="master index" src="https://user-images.githubusercontent.com/6945691/55912837-152df200-5b98-11e9-9de7-6f07baf64e4f.png">

<img width="253" alt="master annos" src="https://user-images.githubusercontent.com/6945691/55912836-152df200-5b98-11e9-8aaa-c431b0c99fdf.png">

**Specified above**

<img width="236" alt="spec index" src="https://user-images.githubusercontent.com/6945691/55912834-152df200-5b98-11e9-8f14-86e56d9fcab3.png">

<img width="248" alt="spec annos" src="https://user-images.githubusercontent.com/6945691/55912835-152df200-5b98-11e9-97e7-34afd7ad4caf.png">
