### ISSUE TITLE
Decrease height of thumbnails in thumbnail grid

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2371]
Already discussed with @mejackreed and @jvine, but in case you want a ticket as a reminder Jack:

- Decrease height of thumbnails in thumbnail grid so they are about 95-100px. The height of the grid itself should be taller than that ~130px?); 95-100px is just for the resulting height of the thumbnails.

**Comment by mejackreed** [comment]
Already implemented in #2368 cbe22b1
