### ISSUE TITLE
Add Attribution / License to side panel

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2372]
In order to meet the requirement to display the rights/requiredStatement info, we want to add a panel to the sidebar that contains only this information. Intent is that an institution may choose to open windows with the Rights panel open by default; even potentially in a companion window position. If the panel is open, the user can close it; if it's not open, they can easily see that it's present and access it.

<img width="289" alt="required attrib license logo" src="https://user-images.githubusercontent.com/6945691/55498303-230fd000-55f8-11e9-81d6-70e3f998db15.png">

### Create the panel
- [x] 1. Add a button between Info and Index, using the [sharp-copyright](https://material.io/tools/icons/?search=copy&icon=copyright&style=sharp) icon 
- [x] 2. Panel title is `Rights`
3. Panel has 2 sections, each wrapped in a div as on the metadata panel (to provide the margins and divider)
   - [x] a. label/value pairs
   - [x] b. logo
4. - [x] If there is no content in the manifest for either section, do not display the Rights button in the sidebar. 

### Section a. Label/value pairs
Use `<dt>` `<dd>` to display the following information:
- 2.x:
  - [x] `attribution` - English label "Attribution"
  - [x] `license` - English label "License"
- 3.0
  - [x] `requiredStatement` - labels and values as provided
  - [x] `rights` - English label "License"

- [ ] If there is more than one license link, use a separate `<dd>` for each.

**Bonus**
For Creative Commons and Rights Statements urls, it would be nice to display the associated image as we do in [PURL/SULembed](https://purl.stanford.edu/zc861vv5769)  
^-- split out to #2431

### Section b. Logo

- [x] Display the image provided, with `max-width: 100%` so larger images don't overflow the panel. 

## Examples

**License and logo**
<img width="289" alt="required license logo" src="https://user-images.githubusercontent.com/6945691/55500420-235e9a00-55fd-11e9-9e7f-6e86323e2422.png">

**Attribution & logo**
<img width="284" alt="required attrib logo" src="https://user-images.githubusercontent.com/6945691/55500423-23f73080-55fd-11e9-9db6-f7496bd6e4d7.png">

**Attribution only**
<img width="285" alt="required attrib" src="https://user-images.githubusercontent.com/6945691/55500422-23f73080-55fd-11e9-9fa7-729261aca22b.png">

**Logo only**
<img width="288" alt="required logo only" src="https://user-images.githubusercontent.com/6945691/55500985-5a817b00-55fe-11e9-8b58-d31242193285.png">

**Attribution & 2 licenses**
<img width="285" alt="required attrib license" src="https://user-images.githubusercontent.com/6945691/55500424-23f73080-55fd-11e9-8954-bed3de333365.png">

**Comment by cbeer** [comment]
> Intent is that an institution may choose to open windows with the Rights panel open by default

I'm not sure what you mean; are you describing the default behavior for mirador or some possible configuration of mirador, but not the one we'll ship?

**Comment by camillevilla** [comment]
^-- Would that be a consideration for #2378?

**Comment by ggeisler** [comment]
@cbeer 

> I'm not sure what you mean; are you describing the default behavior for mirador or some possible configuration of mirador, but not the one we'll ship?

Some possible configuration of mirador, but not the one we'll ship. 

I believe @jvine was just pointing out that a benefit of creating this separate panel for the attribution/license info is that an implementor could potentially configure their implementation to display the Attribution panel as the one to display when opening the side panel (as opposed to the About panel). For example, institutions that are especially concerned that users see the attribution info for the object.

@camillevilla Sure, that could definitely come into play when thinking about an embedded configuration. @jvine and I plan to work on #2378 next week.

**Comment by cbeer** [comment]
Ok; so for the purposes of this ticket, maybe we can scope it to just "there's a rights panel" as described?

**Comment by ggeisler** [comment]
Yes, that's really what I meant to say. The potential for the panel to be the default panel is not relevant for this ticket (although if it isn't currently possible for an implementor to change the default panel, we probably should make a ticket for that).

**Comment by cbeer** [comment]
Yeah, let's ticket that separately.. that's going to get very tricky with the "sometimes there's rights, sometime's there's not" stuff.

**Comment by ggeisler** [comment]
Ah, yeah. We had some discussion about whether we should show a "No attribution provided" message when there's no rights info provided but decided against it. But we might need to revisit that so we can guarantee there is a panel if it is configured as the default.

I'll create the ticket.

**Comment by camillevilla** [comment]
FYI split out issues are in:
- Display multivalued metadata #2438
- Parse creativecommons and rightsstatement.org licenses to human-friendly versions #2431
