### ISSUE TITLE
Zoom level is being reset/updated on clicking various buttons around the app

### ISSUE THREAD

**Issue by jkeck** [ProjectMirador/mirador#2400]
### Clicking Menus
![weirdScroll](https://user-images.githubusercontent.com/96776/55642035-3d76b480-5784-11e9-8885-420b4bb79aa3.gif)

### Selecting Annotations
![weirdAnnoSelection](https://user-images.githubusercontent.com/96776/55641889-d35e0f80-5783-11e9-8741-3ba19c693a9c.gif)

**Comment by cbeer** [comment]
Fixed by #2399, I think.
