### ISSUE TITLE
Enable configuration of default state of window side panel

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2402]
Related to #2372.

Currently, the About/Metadata panel is the panel that is shown when a window side panel is initially opened. 

However, an implementor might instead want the Rights panel to be the default panel displayed, because they are especially concerned that users see the rights/attribution info for the object. 

Issues to resolve:
- It is possible that an object manifest not include any rights/attribution info, in which case we intend that the Rights panel not be represented in the sidebar nav. But if an implementor configures the Rights panel to be the default, what happens when a user opens an object with no rights/attribution info (and thus there is no Rights panel to display)?

- For the use case where the implementor wants to configure the Rights panel as the default because they are especially concerned that users see the rights/attribution info for the object, is it enough to make the Rights panel the default when the sidebar is explicitly opened by the user, or do we also need to enable the implementor to indicate that the sidebar for a newly-opened window should be **open** by default?

Windows currently open with the sidebar closed, so even if the Rights panel is the default, there is no guarantee that the user will see the rights/attribution info, because they have to deliberately choose to open the sidebar to see it.

**Comment by jvine** [comment]
My intent was that the implementor should be able to specify that the Rights panel be open by default. For some institutions it will not be sufficient that the Rights info display can be initiated by the user. This may be a requirement for Stanford, for example, for the instances where we are not permitted to suppress the Attribution overlay currently.

**Comment by ggeisler** [comment]
We'd like to see two new Window configuration options, which are related but independent.

The goal for these is to enable an implementor to 1) configure default windows to have the sidebar panel open when the window is loaded, and 2) change the panel initially visible when the sidebar panel is opened. Combined, this would enable a scenario, for example, where the implementor could configure windows to have their sidebar panels open to the Rights panel when loaded.

(Names used below are just examples; obviously developers should use whatever names make the most sense.)

- defaultPanel:  {"information"} where the other options are: {rights | index | annotations} (and eventually layers and search). So the default state remains as it is, where opening the side panel in a window shows the information panel, but the configuration option enables the implementor to choose a different panel to be the one seen first when the side panel is opened.

- defaultPanelState: {"closed"} where the other option is "open". Again, the default state is unchanged from how things are now, but the configuration option enables the implementor to choose to have the side panel open when a window is loaded into the workspace.
