### ISSUE TITLE
Parse creativecommons and rightsstatement.org licenses to human-friendly versions

### ISSUE THREAD

**Issue by cbeer** [ProjectMirador/mirador#2431]
Split out a bonus task from https://github.com/ProjectMirador/mirador/issues/2372

> For Creative Commons and Rights Statements urls, it would be nice to display the associated image as we do in [PURL/SULembed](https://purl.stanford.edu/zc861vv5769) 

<img width="752" alt="Screen Shot 2019-04-09 at 12 17 46" src="https://user-images.githubusercontent.com/111218/55828563-8d75b400-5ac1-11e9-8e53-dd68696ce549.png">

**Comment by camillevilla** [comment]
If someone has the interest, it would be nice to extract this to an npm package for wider reuse!
