### ISSUE TITLE
Non-svg images are not being loaded in a plugin

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#2458]
![Screen Shot 2019-04-10 at 5 49 47 PM](https://user-images.githubusercontent.com/1656824/55921223-1d4a5980-5bb9-11e9-90fb-7b1329eb859c.png)
![Screen Shot 2019-04-10 at 5 49 41 PM](https://user-images.githubusercontent.com/1656824/55921224-1d4a5980-5bb9-11e9-9e88-bd6238ebee35.png)

**Comment by charbugs** [comment]
Can you give more context please. How is it related to plugins?

**Comment by mejackreed** [comment]
Images referenced in Workspace type selection are referenced by relative url path https://github.com/ProjectMirador/mirador/blob/master/src/components/WorkspaceSelectionDialog.js#L59 

So when used outside of our current build location these will not be found.

**Comment by jkeck** [comment]
```bash
$ sudo cat-pic-to-svg
```

**Comment by glefi** [comment]
The two images in the workspace type selection dialog are replaced anyway. This wip was merged accidentaly into master. They will be replaced when the pr for [#2288 ](https://github.com/ProjectMirador/mirador/pull/2352)is merged.

**Comment by mejackreed** [comment]
Nice! thanks.. I guess we can close this. ++ @glefi
