### ISSUE TITLE
Review IIIF manifest parsing approaches

### ISSUE THREAD

**Issue by cbeer** [ProjectMirador/mirador#2461]
## Manifesto
Pros:
- widely used, with known bugs that plague UV/M2/etc.
- already in place
- multilingual metadata handling logic

Cons:
- no support for multivalued metadata (for anything that goes through the multilingual methods, which is basically all human-readable text) (see #2438)
- auth support isn't that great; we jump through weird hoops to handle manifest auth info vs info.json auth info (see #2367)
- we're already rolling our own logic around canvases to get thumbnail uris, dimensions, etc (see [ManifestoCanvas](https://github.com/ProjectMirador/mirador/blob/master/src/lib/ManifestoCanvas.js))
- uneven IIIF v3 support; sometimes methods exist for v3 access, sometimes they don't, sometimes they fallback to v2 patterns, sometimes they throw deprecation warnings for v2 access that is completely outside our control.
- inconsistent returns (sometimes an array, sometimes a string, etc)
- reparsing the entire manifest to get metadata in non-locale languages.

Another framing, what are we using from Manifesto?

- `id`: I guess it removed hash-like access for `@id`?
- `getLogo`: handy way to drill down to the manifest's logo
- `getMetadata`: kinda handy way to parse the IIIF `metadata` structure into something easy to iterate over, with multilingual support.
- `get*` accessors: great when they work, which unfortunately is when access is the simplest. They fall down in multivalued access, IIIF v2/v3 uniformity, etc 
- `getProperty`: returns low-level data structures; pretty much raw JSON access with a little JSONLD logic.
- `Utils.getService`: for digging around the `service` structure to get auth services, with support for manifests or info.json docs
- `LanguageMap`: used for handling the `getProperty` responses where the high-level API isn't useful
- `getCanvases` / `getCanvasById` / `getCanvasByIndex`: pretty trivial implementation-wise.
## Rolling our own
Pros:
- most access to manifesto methods is through selectors, so it should be possible to replace manifesto without hunting through components
- opportunity to align better with our selector patterns
- producing usable, consistent data structures from IIIF documents
- a place to put some of the IIIF parsing logic that isn't react-centric (like: get me a thumbnail, any thumbnail; what languages are used in a given manifest) 

Cons:
- bespoke implementation that we have to maintain
- implementing consistent access through the IIIF internationalization rules is non-trivial

## IIIF-Redux
Pros:
- React-based

Cons:
- feature-heavy
- uncertain future (something about moving to Hyperion?) 

## Other?

**Comment by sdellis** [comment]
I anticipate leaning on Manifesto to handle some of the changes between the 2.1 and 3.0 multi-part Collections (Multi-volume works and Archival Collections). There's an optional `members` property in 2.1 (with associated logic) and no longer `collections` or `manifests` properties in 3.0. I'm not sure how Manifesto actually deals with this based on the [docs](https://iiif-commons.github.io/manifesto/classes/_collection_.manifesto.collection.html)
