### ISSUE TITLE
Adding Plugins to Workspace Menus

### ISSUE THREAD

**Issue by jkeck** [ProjectMirador/mirador#2474]
There are currently two workspace menus that are called out to have an area at the bottom for plugins.  When splitting out the menus I wasn't 100% sure what our current plugin pattern is for that sort of thing, so they are not currently hooked up to be pluggable.

See #2376 for more context about the described menus and plugin areas.

**Comment by mejackreed** [comment]
I think that our plugin pattern here will be to add a `PluginHook` in the appropriate components that should take these `add` plugins.

So both of these places will need something similar to this: https://github.com/ProjectMirador/mirador/blob/master/src/components/WorkspaceControlPanelButtons.js#L9-L16

Or this if there is design needed around how these are shown:

https://github.com/ProjectMirador/mirador/blob/92a955a636ce37c3dacffe7bdb344521e5962b18/src/components/WindowTopMenu.js#L10-L22
