### ISSUE TITLE
Debounce state changing events, throttle ui refreshes.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#249]
Interface refreshes should be _throttled_ at a very small interval (<100ms), so that they are as slowly fired as not noticeable to the user's eye. 

Events affecting interior state changes, however, should be _debounced_ on a longer interval, so that they only update when the property changes have reached their final resting place.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
