### ISSUE TITLE
Import of package.json fails to resolve for the ES build

### ISSUE THREAD

**Issue by gigamorph** [ProjectMirador/mirador#2497]
As of v3.0.0-alpha.4,` components/Branding js` tries to import from `../../package.json`.  It works when building the umd distribution, but breaks when a parent React application tries to import the `App` component directly from `node_modules/mirador/dist/es/src`, because package.json is in `node_modules/mirador`, not `node_modules/mirador/dist/es`.

**Comment by mejackreed** [comment]
@ggeisler is it possible to remove the Mirador version info from this area?

![Screen Shot 2019-04-15 at 5 40 08 PM](https://user-images.githubusercontent.com/1656824/56172187-88bf6d00-5fa5-11e9-89fb-e8d9b6d8c6f8.png)

It is causing some issues with how one package type is being imported.

**Comment by ggeisler** [comment]
@mejackreed Sure, it was just an idea since we had space to display it and I thought would clarify for anyone used to Mirador 2. But certainly isn't critical.
