### ISSUE TITLE
Theming the ToC

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2499]
Based on the in-progress version: there are some issues with the typography, borders, and padding/indenting, and some of the styles are attached to the `<h6>` element that needs to be replaced. Here is some simple styling that is consistent with our theme & typography and resolves the problem of indented text being cut off by the scrollbar.

To start:
- [ ] Replace the `<h6>` element with `<p>` (or `<span>`) and give it **body2** typography.
- [ ] Remove all existing padding and border settings 
- [ ] Remove the text-shadow on hover

Restyle:

- [ ] all items get a 2px border placeholder. padding creates space between elements and gives an appropriate mouse target size. expandable items are bold. 
```
.mirador-toc-item .mirador-toc-heading {
    font-weight: 500;
    border-left: 2px solid transparent;
    border-bottom: 0.5px solid rgba(0, 0, 0, 0.12);
    padding: 8px 0 8px 8px;
}
```
- [ ] but leaf nodes are not bold
```
.mirador-toc-item .mirador-toc-heading.leaf {
    font-weight: 400;
}
```
- [ ] child items get indented; top parents do not. (margin instead of padding here prevents the separators from extending beyond the item)
```
.mirador-toc-item .mirador-toc-item {
    margin-left: 12px;
}
```
- [ ] when a parent is selected, add colour to the left border. Use the theme blue (secondary) colour.
```
.mirador-toc-item.selected > .mirador-toc-heading {
    border-left: 2px solid #1967d2; 
}
```
- [ ] when a leaf is selected, add colour to the left border and give it the "dark" transparent background (theme colour, I think?)
```
.mirador-toc-item.selected > .mirador-toc-heading.leaf {
    border-left: 2px solid #1967d2; [theme secondary colour]
    background: rgba(0,0,0,0.14)  
}
```
- [ ] hover also uses light transparent background rather than a fixed colour
```
.mirador-toc-item .mirador-toc-heading:hover {
    background: rgba(0,0,0,0.08)  
}
```

Outcome looks like this:

![ToCstyle](https://user-images.githubusercontent.com/6945691/56067275-66241e80-5d2f-11e9-96d1-b9a7c5d3ac4a.gif)

Note that the example shows the title removed from the panel and displayed in the dropdown in the header - this will be a secondary ticket.

**Comment by camillevilla** [comment]
Closing this ticket, which was linked to #2392. #2392 was closed in favor of a later implementation attempt which received several rounds of design review.
