### ISSUE TITLE
Performance degradation with new plugin system

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#2507]
@charbugs we are noticing some performance rerendering issues with the new plugins.

For instance using `why-did-you-render` we notice a significant increase in number of renders from just returning `TargetComponent` 
 

using current plugins | 1559 
returning `TargetComponent` | 1180

Are there ways we can reduce this?

**Comment by charbugs** [comment]
Is this with the approach introduced in #2411 ?

**Comment by mejackreed** [comment]
Yes

**Comment by charbugs** [comment]
I think, I need more information to address that. How can I reproduce this and what is the acceptable number rerenderings in this scenario?
