### ISSUE TITLE
Load Roboto font

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2527]
We are using Roboto font in the typography, but we don't seem to be loading it. If a user doesn't have Roboto locally installed, they will see one of the secondary fonts. (Have seen this on screenshares with devs who don't have it installed.) I think we should be loading the font we specify.

**Comment by mejackreed** [comment]
Could we provide some guidance around this in theming documentation and maybe update the demo pages instead?

I think bundling directly could result with some extra large bundles.

**Comment by jvine** [comment]
I only mean something like this in the HTML
`<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700%7CCrimson+Text:400" media="all">`
like we do in SearchWorks - is that possible in React?

**Comment by mejackreed** [comment]
I think its more suited to provide documentation about this and show it in our examples. We can definitely do that.
