### ISSUE TITLE
Some hover and selected state indicators now ovals

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2568]
At some point recently it looks like the hover/selected state indicators for some buttons became ovals:

<img width="173" alt="Screen Shot 2019-04-18 at 12 48 23 PM" src="https://user-images.githubusercontent.com/101482/56387366-fa333180-61d8-11e9-985f-87bc238fad20.png">

That example is from the wider empty workspace version of the app bar, but it occurs in the regular app bar as well. Seems to just be the Workspace options and Jump to window buttons.

If it helps, when I noticed this I happened to be running locally with the branch for a [relatively recent PR](https://github.com/ProjectMirador/mirador/tree/2560-workspace-dialog-dark-theme) and it does **not** occur there, so I guess that might indicate the problem was introduced by a commit more recent than what that branch has.

**Comment by camillevilla** [comment]
Closed by #2570
