### ISSUE TITLE
Dynamic, zoomable scroll view

### ISSUE THREAD

**Issue by snydman** [ProjectMirador/mirador#259]
With OSD collection mode, can we now have a fully zoomable scroll view?

**Comment by rsinghal** [comment]
part of #339

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

**Comment by snydman** [comment]
Bravo Mirador 3!  Thanks @camillevilla and team.
