### ISSUE TITLE
Metadata panel does not render metadata with multiple values properly

### ISSUE THREAD

**Issue by regisrob** [ProjectMirador/mirador#2591]
Considering this fixture Manifest with canvas-level metadata: http://beta.biblissima.fr/iiif/manifest/ark:/43093/desc57cb76cd3739a24a9277b6669d95b5f3a590e771. M3 only displays the first value of an array of values from `metadata`, e.g. for the first canvas there is only one link associated with the "Descripteurs" label (there should be 7, as listed in the Manifest):

<img width="348" alt="Capture d’écran 2019-04-24 à 11 36 27" src="https://user-images.githubusercontent.com/402117/56651112-a5843080-6688-11e9-8faa-76581e28736c.png">

```
{
  "value": [
    "<a href=\"http://beta.biblissima.fr//ark:/43093/desc4029aaec9af3ff426a159f956f7a20689b56f2d2\">Lances</a>",
    "<a href=\"http://beta.biblissima.fr//ark:/43093/desc98ecb295b467f7c35070d9ebb076892e297a92b8\">Coiffes</a>",
    "<a href=\"http://beta.biblissima.fr//ark:/43093/desc78ec63596ada325e05f7b5d0bb2bc0598223cf69\">Combat</a>",
    "<a href=\"http://beta.biblissima.fr//ark:/43093/desc7e1644ea589418163cc71f41d158446c29c82628\">Arcs</a>",
    "<a href=\"http://beta.biblissima.fr//ark:/43093/desc02c69ac510a1ade350f688f9100fb94a12625dd4\">Groupes ethniques</a>",
    "<a href=\"http://beta.biblissima.fr//ark:/43093/desc905495aa17391ff09b1fae50937c4522d3d6f77d\">Homme sauvage</a>",
    "<a href=\"http://beta.biblissima.fr//ark:/43093/desc57cb76cd3739a24a9277b6669d95b5f3a590e771\">Centaures</a>"
  ],
  "label": "Descripteurs"
}
```

Another fixture with the same issue: https://data.ucd.ie/api/img/manifests/ucdlib:33064. M3 only displays one "topic-LCSH" out of the two listed in the Manifest `metadata`.

A third fixture for a similar case is https://iiif.io/api/presentation/2.1/example/fixtures/4/manifest.json ("Test 4 Manifest: Metadata Pairs with Multiple Values in same Language"), which seems to break M3 (maybe because there is no `service` for the image?)

**Comment by camillevilla** [comment]
Hi @regisrob! Thanks for including fixtures. We are aware of the problem. Unfortunately, this is an issue that will need to be resolved upstream in [IIIF-Commons/manifesto](https://github.com/IIIF-Commons/manifesto).

The other option would be to stop using manifesto, but writing our own utilities for Mirador would be a larger undertaking.

**Comment by regisrob** [comment]
I understand, thanks @camillevilla. Indeed it would be better to fix this in Manifesto, but I guess there are other issues at stake with this library

**Comment by regisrob** [comment]
I've just checked with the latest master branch of Manifesto which includes @mejackreed 's fix ([#60](https://github.com/IIIF-Commons/manifesto/pull/60)), but it does not seem to solve the problem, at least for [this Manifest](https://portail.biblissima.fr/iiif/manifest/ark:/43093/desc57cb76cd3739a24a9277b6669d95b5f3a590e771) (that has canvas-level metadata with an array of values in one of the key/value pairs). Am I missing something?

**Comment by mejackreed** [comment]
@regisrob , once manifesto releases a new version we can update this method to `getValues()` which should resolve this issue.

**Comment by regisrob** [comment]
Ok i see, there is still some work to do on the Mirador side then. Thanks @mejackreed
