### ISSUE TITLE
react-iframe-comm has production dependency to react

### ISSUE THREAD

**Issue by charbugs** [ProjectMirador/mirador#2592]
As a result, installing Mirador also installs a react and react-dom (version 15.6.2.)

**Comment by mejackreed** [comment]
Should we file this issue upstream?

**Comment by charbugs** [comment]
Good idea, I will do so.

**Comment by charbugs** [comment]
https://github.com/pbojinov/react-iframe-comm/issues/13

**Comment by mejackreed** [comment]
Resolved in #2861
