### ISSUE TITLE
Links in Rights panel should open in new window

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2594]
The License & other links in the Rights panel currently open in the same window and lose all your lovely Mirador work. They should open in a new window, like the links in the Metadata panel.

**Comment by cbeer** [comment]
Do you have an example manifest for this?

**Comment by ggeisler** [comment]
https://wellcomelibrary.org/iiif/b18035723/manifest has a link for the license in the Rights panel, though it seems to already do the right thing and open in a new tab. Not sure if @jvine has another example with links other than license where it doesn't work as desired, or if this was fixed at some point.
