### ISSUE TITLE
Switch out next/previous behaviour and focus view to use a single OSD collection mode canvas.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#260]
This addresses some hacky code as well as some performance and experience improvements. We currently create and destroy an openSeadragon instance every time we need a canvas (opening single image or book view from thumbnail view, navigating to a new page once already inside those views, etc.). This is obviously not ideal. By creating one OSD instance when the window is created, and adding all or at least some of the tileSources upfront, we can greatly improve the performance and experience of each of the different view types.
## Single Image View

Even if we can't put all the pages on the canvas at once, we can dynamically add and remove tileSources so that next/previous smoothly pan over to the next page (or perhaps using a transition such as the . There will be some math involved to space them sensitively with respect to the viewport (the spacing may need to be adjusted on resize, for instance, which may have performance implications). 

Constraints will need to be automatically adjusted to prevent the user from panning or zooming outside of the intended zone of one page.
## Book View

The same goes for book view as goes for single image view. The only difference will be that openings have spacing that allows them both to be visible in the viewport. The same concerns about managing the constraints of panning and zooming apply.

When animating the position of tileSource frames is supported, the user could nicely enter book view from single-image or scroll view by having the spacing dynamically adjust as the viewport slowly grows to contain the transforming coordinate space. C.f.: [http://bost.ocks.org/mike/fisheye/]
## Scroll View

There will be no difference between single image view and scroll view except for the spacing. In this case, the constraints are merely expanded horizontally, and the spacing between tileSources reduced, to allow movement across the entire linear arrangement.

**Comment by rsinghal** [comment]
related to #339

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
