### ISSUE TITLE
pluginMap is undefined when Mirador3 is instantiated using the ES build

### ISSUE THREAD

**Issue by gigamorph** [ProjectMirador/mirador#2600]
Mirador3 crashes when embedded in another react/redux app. The parent app is importing Mirador modules from `node_modules/mirador/dist/es/src`. The Mirador version used was `3.0.0-alpha.6`. 

Screenshot:
![image](https://user-images.githubusercontent.com/86015/57103950-2086c000-6cf5-11e9-82a5-9d570aa2adb5.png)

The direct cause is: in `extend/withPlugins.js`, in function PluginHoc, pluginMap is set to `undefined`. If I run the Mirador code on its own (`npm start`), I can see that pluginMap is set to `{}`. I wonder why the behavior is different.

If I modify the line to
```javascript
const pluginMap = useContext(PluginContext) || {};
```
it works for the embedded situation too.

You should be able to reproduce the problem with https://gitlab.com/gmorph2/iiif/react-mirador3-experiment (tag: mirador-alpha6).

**Comment by charbugs** [comment]
Currently the only recommended way to embbed M3 in your page is to use the `Mirador.viewer()` init function. Here is an expample how to do that in a react app: https://codesandbox.io/s/4x4vn4o4m4.

The usage of the exported es modules is experimental and there is no defined way to use it. Nevertheless, the problem with your code is that you do not wrap `MiradorApp` in a `PluginProvider`. See [here](https://github.com/ProjectMirador/mirador/blob/master/src/lib/MiradorViewer.js#L29) how this is done during the initialization of M3.

**Comment by mejackreed** [comment]
@gigamorph have you been able to get past this yet? There should be alternative ways now to effectively use the ES package. Closing this now, feel free to reopen.
