### ISSUE TITLE
Refactoring: group components semantically in folders

### ISSUE THREAD

**Issue by charbugs** [ProjectMirador/mirador#2604]
Currently we keep all ~80 components (and the related containers) in a flat list under `src/`. This way, it is hard to see the structure of the app and refactorings are difficult. I suggest to semantically group related components in different folders. 

* Each folder should store the presentational components as well as the container components.
* Ideally each folder should export a single root component.

![tree-dot](https://user-images.githubusercontent.com/11216290/57373862-bd37da80-7199-11e9-9f79-1a92166b96af.png)

Based on this graph of the current component tree I came up with the following packages:

* attribution-panel
* authentication
* common (shared components like LabelValueMap)
* companion-window (only the logic, no concrete companion windows like info panel)
* galery-view
* thumbnail-navigation
* top-bar
* window (window layout)
* window-side-bar
* window-side-bar-annotations-panel
* window-side-bar-canvas-panel
* window-side-bar-info-panel
* window-viewer
* workspace (workspace setup, e.g. window manager)
* workspace-add
* workspace-control-panel
* workspace-options-menu
* workspace-menu

Having this grouping it's possible to see the dependencies on a higher level (note that interdependency between the companion window package and the different resource panels:

![packages](https://user-images.githubusercontent.com/11216290/57376020-41d92780-719f-11e9-9606-51cd202b404f.png)

Here is the complete directory structure of my suggestion:

* /attribution-panel
  * /components
    * AttributionPanel
  * /containers
    *  AttributionPanel (export)
* /authentication
  * /components
    * AccessTokenSender
    * AuthenticationSender
    * WindowAuthenticationControl
  * /containers
    * AccessTokenSender (export)
    * AuthenticationSender (export)
    * WindowAuthenticationControl (export)
* /common
  * /components
    * CanvasThumbnail (export)
    * CollapsibleSection
    * ErrorDialog
    * LabelValueMetadata (export)
    * MiradorMenuButton
    * PluginHook (export)
    * SanitizeHtml (export)
  * /containers
    * CollapsibleSection (export)
    * ErrorDialog (export)
    * MiradorMenuButton (export)
* /companion-window
  * /components
    * CompanionArea
    * CompanionWindow
    * CompanionWindowFactory
  * /containers
    * CompanionArea (export)
    * CompanionWindow (export)
    * CompanionWindowFactory
* /galery-view
  * /components
    * GaleryView
    * GaleryViewThumbnail
  * /containers
    * GaleryView (export)
    * GaleryViewThumbnail
* /thumbnail-navigation
  * /components
    * CaptionedCanvasThumbnail
    * ThumbnailCanvasGrouping
    * ThumbnailNavigation
  * /containers
    * CaptionedCanvasThumbnail
    * ThumbnailCanvasGrouping
    * ThumbnailNavigation (export)
* /top-bar
  * /components
    * WindowTopBar
    * WindowTopBarButtons
    * WindowTopMenu
    * WindowTopMenuButton
    * WindowThumbnailSettings
    * WindowViewSettings
  * /containers
    * WindowTopBar (export)
    * WindowTopBarButtons
    * WindowTopMenu
    * WindowTopMenuButton
    * WindowThumbnailSettings
    * WindowViewSettings
* /window
  * /components
    * PrimaryWindow
    * Window
  * /containers
    * PrimaryWindow
    * Window (export)
* /window-side-bar
  * /components
    * WindowSideBar
    * WindowSideBarButtons
  * /containers
    * WindowSideBar (export)
    * WindowSideBarButtons
* /window-side-bar-annotations-panel
  * /components
    * AnnotationSettings
    * CanvasAnnotations
    * WindowSideBarAnnotationsPanel
  * /containers
    * AnnotationSettings
    * CanvasAnnotations
    * WindowSideBarAnnotationsPanel (export)
* /window-side-bar-canvas-panel
  * /components
    * WindowSideBarCanvasPanel
  * /containers
    * WindowSideBarCanvasPanel (export)
* /window-side-bar-info-panel
  * /components
    * CanvasInfo
    * LocalPicker
    * ManifestInfo
    * ManifestRelatedLinks
    * WindowSideBarInfoPanel
  * /containers
    * CanvasInfo
    * LocalPicker
    * ManifestInfo
    * ManifestRelatedLinks
    * WindowSideBarInfoPanel (export)
* /window-viewer
  * /components
    * OpenSeadragonViewer
    * ViewerInfo
    * ViewerNavigation
    * WindowCanvasNavigationControls
    * WindowViewer
    * ZoomControls
  * /containers
    * OpenSeadragonViewer
    * ViewerInfo
    * ViewerNavigation
    * WindowCanvasNavigationControls
    * WindowViewer (export)
    * ZoomControls
* /workspace
  * /components
    * MosaicRenderPreview
    * Workspace
    * WorkspaceArea
    * WorkspaceElastic
    * WorkspaceElasticWindow
    * WorkspaceMosaic
  * /containers
    * MosaicRenderPreview
    * Workspace
    * WorkspaceArea (export)
    * WorkspaceElastic
    * WorkspaceElasticWindow
    * WorkspaceMosaic
* /workspace-add
  * /components
    * ManifestForm
    * ManifestListItem
    * ManifestListItemError
    * WorkspaceAdd
  * /containers
    * ManifestForm
    * ManifestListItem
    * ManifestListItemError
    * WorkspaceAdd (export)
* /workspace-control-panel
  * /components
    *Branding
    * WindowList
    * WindowListButton
    * WorkspaceAddButton
    * WorkspaceControlPanel
    * WorkspaceControlPanelButtons
    * WorkspaceFullScreenButton
    * WorkspaceMenuButton
    * WorkspaceOptionsButton
  * /containers
    * WindowList
    * WindowListButton
    * WorkspaceAddButton
    * WorkspaceControlPanel (export)
    * WorkspaceControlPanelButtons
    * WorkspaceFullScreenButton
    * WorkspaceMenuButton
    * WorkspaceOptionsButton
* /workspace-options-menu
  * /components
    * WorkspaceExport
    * WorkspaceImport
    * WorkspaceOptionsMenu
  * /containers
    * WorkspaceExport
    * WorkspaceImport
    * WorkspaceOptionsMenu (export)
* /workspace-menu
  * /components
    * ChangeThemeDialog
    * LanguageSettings
    * WorkspaceMenu
    * WorkspaceSelectionDialog
  * /containers
    * ChangeThemeDialog
    * LanguageSettings
    * WorkspaceMenu (export)
    * WorkspaceSelectionDialog

**Comment by mejackreed** [comment]
It might be worth figuring out a way to discuss the implications of this for the ES module usage externally. Are there technical implications of this approach, or is this purely an organizational construct?

**Comment by cbeer** [comment]
Noted on https://github.com/ProjectMirador/mirador/discussions/3457.
