### ISSUE TITLE
Add layers menu icon

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2608]
Part of #2607. See callout A of this mockup:

<img width="422" alt="layers-panel-with-notes" src="https://user-images.githubusercontent.com/101482/57407723-b65c9800-7198-11e9-9e20-0a1cda20cf67.png">

- [x] If technically feasible, the layers menu icon should be shown only if the object contains one or more canvases with multiple layers.
- [x] If the current canvas has multiple layers, show the notification icon (same pattern currently used in the annotations panel).
- [x] Icon: `layers`, the sharp version (@material-ui/icons/LayersSharp). Note that this is a different icon than in the mockups.
- [x] Tooltip: "Layers"
- [x] Icon placement: Below the annotations icon (last in the list). Note that this is a different placement than in the mockups.

**Comment by mejackreed** [comment]
Resolved in #2855
