### ISSUE TITLE
Enable drag and drop of layers

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2609]
Part of #2607. See callout B of this mockup:

<img width="422" alt="layers-panel-with-notes" src="https://user-images.githubusercontent.com/101482/57407865-09364f80-7199-11e9-83ef-c4a8dd3302e8.png">

Although other side panels use the same approach of displaying items as a list with a divider between each item, enabling the user to move items around in the list is a new pattern.

- [x] Drag handle container: extending the full height of the layer list item and 24px wide, with the drag handle icon centered both vertically and horizontally within it.
- [x] Icon: `drag_handle`, the `sharp` version (@material-ui/icons/DragHandleSharp)
- [x] Tooltip: "Move layer"
- [x] Drag handle container background color: `shades.light` (`#f5f5f5` in the light theme)
- [x] When hovered (see [this ticket](https://github.com/ProjectMirador/mirador/issues/2479) for definitions), background changes to the `light` indicator background color (`rgba(0,0,0,0.08)`)
- [x] When focused, background changes to the `dark` indicator background color (`rgba(0,0,0,0.14)`). Here's an example where a layer is being dragged, thus is in focus:

![layers-dragging](https://user-images.githubusercontent.com/101482/57407910-29660e80-7199-11e9-8f9b-52f5a161a9bf.png)

---

- [ ] Keyboard accessibility support: A user should be able to move a layer to any new location using only a keyboard. Here's a good example that might be a useful model: https://salesforce-ux.github.io/dnd-a11y-patterns/#/sortA?_k=fif8g1
- [ ] Screenreader accessibility support: The example above also works well with a screenreader, so again it could serve as a model for what we're aiming for.

**Comment by mejackreed** [comment]
Resolved in #2855
