### ISSUE TITLE
Add layer thumbnail and label

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2610]
Part of #2607. See callout C of this mockup:

<img width="422" alt="layers-panel-with-notes" src="https://user-images.githubusercontent.com/101482/57408135-b27d4580-7199-11e9-9a6a-61d323b631b8.png">

At least as a first step, I suggest we follow the pattern used in the Table of Contents panel with the Thumbnail list view active, which includes both a thumbnail and a label:

- [x] Thumbnail: `50px` wide; use a placeholder as we do elsewhere when a thumbnail image is not available.
- [x] Label: `Body 1` typographical class.

**Comment by mejackreed** [comment]
Resolved in #2855
