### ISSUE TITLE
Enable toggling layer visibility

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2611]
Part of #2607. See callout D of this mockup:

<img width="422" alt="layers-panel-with-notes" src="https://user-images.githubusercontent.com/101482/57408272-0daf3800-719a-11e9-88b6-6fc0141bce09.png">

The visibility icon controls whether the layer is visible on the canvas, independent of that layer's opacity setting. This should work the same as in Mirador 2, although we're suggesting an icon rather than a checkbox control.

- [x] The `visibility` icon should be aligned so that it is always vertically aligned with the left side of the layer label (i.e., it should never float to the left edge of the panel below the thumbnail) so that the icons are in the same place within every layer item.
- [x] Selecting the icon should toggle it between the `visibility` and `visibility_off` versions (@material-ui/icons/VisibilitySharp and @material-ui/icons/VisibilityOffSharp)
- [x] Tooltip for `visibility` icon: "Hide layer"
- [x] Tooltip for `visibility_off` icon: "Show layer"
- [x] When the icon is in the `visibility` state, the opacity controls should all be enabled, and the canvas image corresponding to the layer should have an opacity matching the value in the opacity control.
- [x] When the icon is in the `visibility_off` state, the layer's opacity icon, input field, and slider should all be changed to the **disabled** state, and the canvas image corresponding to the layer should have no visibility (opacity = 0). The disabled opacity controls should look something like this (topmost layer):

![layers-opacity-disabled](https://user-images.githubusercontent.com/101482/57408368-5bc43b80-719a-11e9-81ce-bac9d14b625a.png)

**Comment by mejackreed** [comment]
Resolved in #2855
