### ISSUE TITLE
Add move-to-top action for layers

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2612]
Part of #2607. See callout E of this mockup:

<img width="422" alt="layers-panel-with-notes" src="https://user-images.githubusercontent.com/101482/57408531-b9588800-719a-11e9-813f-3a3e2d7555cd.png">

The move-layer-to-top icon provides an alternative to drag and dropping a layer when the user wants to move a layer to the top of the layer stack (could be especially useful when there are many layers in the object).

- [x] Icon: `vertical_align_top` (@material-ui/icons/VerticalAlignTopSharp). Note that this icon should not be shown in the topmost layer in the list.
- [x] Tooltip: "Move layer to top"
- [x] When the user selects this icon, the associated layer should be moved to the top of the layer list.
- [x] When a layer is moved to the top of the layer list, the move-layer-to-top icon should immediately be removed from that layer, and added to the layer that was previously the topmost layer.

**Comment by mejackreed** [comment]
Resolved in #2855
