### ISSUE TITLE
Add layer opacity controls

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2613]
Part of #2607. See callout F of this mockup:

<img width="422" alt="layers-panel-with-notes" src="https://user-images.githubusercontent.com/101482/57408688-2409c380-719b-11e9-8875-17ae59e4c1ba.png">

Each layer has an opacity control, consisting of three elements: an icon, an input field, and a slider. The input and slider should be linked such that changing the opacity value using one of the controls automatically updates the other so that they always reflect the same value.

- [x] Icon: `opacity` (@material-ui/icons/OpacitySharp), left-aligned below the thumbnail image. Note that the icon is decorative only and not clickable/selectable. Also note that the `opacity` icon is different from the one shown in the mockup.
- [x] Tooltip: "Layer opacity"
- [x] Input: This should be a narrow textfield, with no visible label, and an suffixed `InputAdornment` of a `%` sign. The textfield just needs to be wide enough to contain 3 digits and the percent sign. The ["Weight" example here](https://material-ui.com/demos/text-fields/#input-adornments) is sort of what we want, just narrower and with no label or hint text, since the input will always contain a value. 
- [x] Screenreader-only label: the  input should have a screenreader-only label of "Layer opacity".
- [x] Slider: The opacity slider should take up all of the available horizontal space between the opacity textfield and the right edge of the panel, with `16px` left and right padding. I don't see a Material UI React slider component, but what we want is something like [the one shown in the Material UI components documentation](https://material-components.github.io/material-components-web-catalog/#/component/slider). The opacity textfield should update in realtime as the user moves the slider, so the user always knows what opacity value the slider is at.

**Comment by mejackreed** [comment]
Resolved in #2855
