### ISSUE TITLE
Add layer section divider

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2614]
Part of #2607. See callout G of this mockup:

<img width="422" alt="layers-panel-with-notes" src="https://user-images.githubusercontent.com/101482/57408907-c5911500-719b-11e9-8043-bc32a4fce925.png">

- [x] Each layer list item should have a bottom border, identical to that used in the annotation and ToC panels.

**Comment by mejackreed** [comment]
Resolved in #2855
