### ISSUE TITLE
Can we make a list on the Wiki about which components support plugin mode "add"

### ISSUE THREAD

**Issue by jeffreycwitt** [ProjectMirador/mirador#2619]
Can we make a list on the Wiki about which components support plugin mode "add"

It's dawned on me that not all components allow a component to be dropped in with the "add" mode. 

Is there a list somewhere of which components allow add? 

Even if someone could just paste it in here. I'd be glad to add it to the wiki.

**Comment by mejackreed** [comment]
Fixed in https://github.com/ProjectMirador/mirador/wiki/M3---Creating-a-Mirador-plugin/f97690d21c7ad3263e52a884b6fe3f0fbfc67e77

cc @jkeck
