### ISSUE TITLE
translation.json files not found when using M3 alpha npm module in React app

### ISSUE THREAD

**Issue by broadwell** [ProjectMirador/mirador#2621]
Embedding Mirador 3 as a component in a React app by including the v3.0.0-alpha.7 npm module leads to a non-breaking webpack error:

`ERROR in [copy-webpack-plugin] unable to locate 'node_modules/mirador/dist/locales/en/translation.json' at '[path_to_app]/node_modules/mirador/dist/locales/en/translation.json'`

This can be resolved by symlinking `node_modules/mirador/dist/es/src/locales/` to `node_modules/mirador/dist/locales/`, but symlinks aren't practical for distribution.

Another option is to change the line 

`"build:es": "mkdir -p dist/es && cp -r src dist/es && babel dist/es -d dist/es",`

in `package.json` to

`"build:es": "mkdir -p dist/es && cp -r src dist/es && mkdir dist/locales && cp -r dist/es/src/locales dist/locales && babel dist/es -d dist/es",`

This option seems rather cumbersome, however. Perhaps there's another way to fix this in the package configuration, but a larger question might be whether it's a good idea to use `es` to identify the embedded build option, given that the `es/` folder is usually reserved for Spanish-language localization files in most software distributions.

**Comment by mejackreed** [comment]
This should be resolved now in Mirador 3. Thanks for reporting @broadwell if you run into this again please reopen.
