### ISSUE TITLE
Rights side panel doesn't display when it is the default panel

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2622]
If you choose `rights` as the default sidebar panel in `settings.js`:

```
defaultSideBarPanel: 'rights', // Configure which sidebar is selected by default. Options: info, rights, canvas, annotations
```

The Rights panel is not displayed. You have to choose another panel and come back to open the Rights panel again to see it displayed.

<img width="340" alt="Screen Shot 2019-05-17 at 9 53 33 AM" src="https://user-images.githubusercontent.com/101482/57943777-cd327700-7889-11e9-9e0d-2004b468c3ee.png">

This happens whether or not the side panel is set to display by default or not using `sideBarOpenByDefault`. Here I've turned it off by default and am opening the side panel:

![rights-default-sidebar-panel](https://user-images.githubusercontent.com/101482/57943835-f3581700-7889-11e9-90d5-df8da772fc69.gif)

**Comment by cbeer** [comment]
I think the comment is wrong -- it should be `attribution`, not `rights`.
