### ISSUE TITLE
Add configuration setting to hide window title

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2623]
A common scenario is to embed the viewer in a larger application, such as a library catalog show page. In those contexts, the title of the object in the viewer is usually prominently displayed elsewhere on the page so showing it again the M3 viewer title bar is redundant. As an example (this is M2 but same scenario would currently occur with M3), here's a show page from a Spotlight exhibit:

<img width="805" alt="Screen Shot 2019-05-17 at 12 39 45 PM" src="https://user-images.githubusercontent.com/101482/57952258-7cc71380-78a1-11e9-9b00-29c85253b77e.png">

Adding a `window` setting to control the display of the window title would help the implementor control embed scenarios better. Something like this:

```
 window: {
   hideWindowTitle: false, // Configure if the window title is shown in the window title bar or not
}
```

**Comment by mejackreed** [comment]
@ggeisler Should the buttons be pulled right after the title is removed?

**Comment by ggeisler** [comment]
@mejackreed They shouldn't be moved, so they would stay on the right.

This will leave a bunch of whitespace in the title bar, but that'll be the case no matter what and I think the buttons should be right-aligned as they are when there is a title.
