### ISSUE TITLE
Update link color in dark theme

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2624]
When in dark theme, the color of links remains the same blue color it is in the light theme:

<img width="351" alt="Screen Shot 2019-05-17 at 4 44 11 PM" src="https://user-images.githubusercontent.com/101482/57961376-6631b400-78c3-11e9-9833-a6acb013afc8.png">

We need to make sure that when in dark theme, the `color` property of links is something with better contrast. I suggest using `rgba(255,255,255,0.7)` which is far enough from the white used in the headings and body text in the panel to stand out a bit, while having sufficient contrast for accessibility (it's also the same color used for the icons in the window sidepanel menu):

<img width="351" alt="Screen Shot 2019-05-17 at 4 45 01 PM" src="https://user-images.githubusercontent.com/101482/57961437-d8a29400-78c3-11e9-854c-b5d06b2b7366.png">

**Comment by regisrob** [comment]
+1
