### ISSUE TITLE
Change Primary Theme Color

### ISSUE THREAD

**Issue by surreal8** [ProjectMirador/mirador#2625]
Following the theming documentation (https://github.com/ProjectMirador/mirador/wiki/M3-Theming-Mirador) I'm unable to update the theme's primary color. Here's what I have in my index.html file:
```
var miradorInstance = Mirador.viewer({
       id: 'mirador',
       selectedTheme: 'dark',
       theme: {
        palette: {
          primary: {
            main: '#80104E',
          },
        },
      },
```
@camillevilla

**Comment by regisrob** [comment]
I have the same issue, with the same configuration options. The only way I managed to customized the main/secondary colors was to edit settings.js (in `themes.dark.palette`).

Then I tried to tweak settings.js by moving the dark palette in `theme` and leaving only this in `themes`:
```
themes: {
    dark: {
      palette: {
        type: 'dark',
      }
    },
    light: {
      palette: {
        type: 'light',
      }
    }
  }
```
This enables the theme customization through the config options in index.html, but switching to the light theme using the option in the sidebar does not work fine: the light theme inherits some background colors of the dark theme

<img width="535" alt="Capture d’écran 2019-05-20 à 19 14 21" src="https://user-images.githubusercontent.com/402117/58039612-85cf1380-7b33-11e9-8491-e20486126ed2.png">

**Comment by camillevilla** [comment]
@surreal8 @regisrob alrighty! This is definitely a case of the docs being out of sync with the code 😅

You'll want to update your config to the following in your `index.html`.
```javascript
var miradorInstance = Mirador.viewer({
  id: 'mirador',
  selectedTheme: 'dark',
  themes: {
    dark: {
      palette: {
        type: 'dark',
        primary: {
          main: '#80104E',
        },
      },
    },
  },
})
```
In the example above, I've ONLY overwritten the [default dark theme palette](https://github.com/ProjectMirador/mirador/blob/3582bcbe530af423017913b2ed7d896efa6f0948/src/config/settings.js#L8-L22). You'll notice that if you switch back to the light theme, it's using Mirador's default colors. See my demo here: https://codepen.io/cazilla11/pen/QRjavE

If you want to override the BOTH the light theme and dark theme colors, I would recommend doing it like this:
```javascript
var miradorInstance = Mirador.viewer({
  id: 'mirador',
  selectedTheme: 'dark',
  themes: {
    dark: {
      palette: {
        type: 'dark',
        primary: {
          main: '#80104E',
        },
      },
    },
	light: {
      palette: {
        type: 'light',
        primary: {
          main: '#80104E',
        },
      },
    },
  },
})
```

I will keep this ticket open until I have updated the wiki page. But I would appreciate any additional examples you'd like to post here! I would appreciate an example of the background colors inheritance issue @regisrob.

**Comment by camillevilla** [comment]
@surreal8 @regisrob I've updated the theming page on the wiki:
- corrected syntax on [changing primary and secondary colors](https://github.com/ProjectMirador/mirador/wiki/M3-Theming-Mirador#example-changing-primary--secondary-colors)
- added [an example with a third theme](https://github.com/ProjectMirador/mirador/wiki/M3-Theming-Mirador#creating-a-theme), which I hope illustrates the difference between `theme` and `themeS` a little better.

Please let me know if that helps.

**Comment by regisrob** [comment]
Many thanks for this, that's helpful. Everything seems to be ok with this configuration.

The bug I had with the background colors was just because I was doing something wrong in settings.js!

**Comment by surreal8** [comment]
Works great @camillevilla! Thanks!
