### ISSUE TITLE
Customize auth details for Kiosk and External patterns

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2639]
Related to #2636.

If the manifest auth `profile` value indicates the object should use either the [`kiosk`](https://iiif.io/api/auth/1.0/#kiosk-interaction-pattern) or [`external`](https://iiif.io/api/auth/1.0/#external-interaction-pattern) interaction patterns, there will be no auth-related user interaction, but a failure message might need to be displayed.

The differences from the `login` pattern are the same for these two interaction patterns, I believe:

- [x] If after processing the manifest the auth service successfully obtains the access cookie/token, the object is displayed normally and no auth `div` should be displayed.
- [x] If the auth service fails to obtain the access cookie or token, display the auth `div` in the failure state.
- [x] Keep the lock icon but omit the action buttons.
- [x] If provided, display the `failureHeader` and `failureDescription` values as in #2636.
- [x] If a `failureHeader` is not provided, use the fallback string `Authentication failed`.
- [x] If a `failureDescription` is not provided, omit it.

Here's an example of a failure message for the `kiosk` interaction pattern, where the `failureHeader` and `failureDescription` values are provided (using the [spec example](https://iiif.io/api/auth/1.0/#kiosk-interaction-pattern)):

<img width="734" alt="kiosk" src="https://user-images.githubusercontent.com/101482/58724805-62f1fa00-8392-11e9-8560-4cab3577a6c0.png">

And here's an example of a failure message for the `external` interaction pattern, where the `failureHeader` and `failureDescription` values are provided (using the [spec example](https://iiif.io/api/auth/1.0/#external-interaction-pattern)):

<img width="734" alt="external" src="https://user-images.githubusercontent.com/101482/58724827-70a77f80-8392-11e9-9cec-3d72342a0812.png">

**Comment by cbeer** [comment]
Should we have a way to hide/minimize/dismiss this failure (because there's nothing the user can do about it anyway...), like bringing over the cancel button from the interactive auth patterns?

**Comment by ggeisler** [comment]
My understanding of these scenarios (not necessarily complete or correct) is that if there is a failure message, the user won't be able to access the object. So the two actions that seem appropriate for the user are 1) close the window and 2) report the issue to someone else (e.g., call Bob; show the error to a librarian and ask why the object is restricted).

For the first action there's the close button. For the second it seems important to keep the failure message visible and attached to the object. 

So offering a way to cancel or hide the failure message seems like it would only result in a situation where the user has an object with an empty canvas, and unlike the login/clickthrough patterns, there's no potential for retrying the auth and succeeding. And now there's no visible failure message to show to the librarian or whatever.

I guess it's not that different from the interactive patterns, but there's just something about the fact that the auth failed for reasons not under control of the user that makes me reluctant to give the user control over hiding the failure message. Maybe that isn't a rational feeling though. @jvine do you have thoughts on this?

**Comment by jvine** [comment]
My thoughts are the same as yours, @ggeisler, with the added note that a user can walk away from a kiosk and leave it in a state that someone else has to figure out. So retaining the error message seems like the right thing. If we learn otherwise, we can revisit.

**Comment by cbeer** [comment]
>  if there is a failure message, the user won't be able to access the object.

It's also possible the message is displayed if access to the resource is only degraded in some way (like, a maximum resolution).

**Comment by ggeisler** [comment]
> It's also possible the message is displayed if access to the resource is only degraded in some way (like, a maximum resolution).

That's a good point. However, I still think we wouldn't want the user to be able to dismiss the message entirely (for the interactive patterns we don't; the user can cancel to put the message back to the collapsed, single-line version, but not dismiss entirely), just because that creates a state where access is degraded but that degraded state is not explicit to the user (or, as in @jvine's example, the next user who wanders up to the kiosk).

We could follow the model of the interactive patterns and provide a Cancel button to put the message into a collapsed state, but then we'd need to add the "Continue" button so the user could expand it, and at least in cases where the `failureDescription` message is a similar length to the spec examples, we're probably only reducing the height of the div by one line or so. 

So I guess I feel fairly strongly that we shouldn't enable dismissing the message entirely, but am not opposed to adding a Cancel button that collapses the div to show just the `failureHeader` message and "Continue" button for expanding. That would have some benefit for a scenario where 1) the object is degraded but accessible and 2) the failure description is long enough that it wraps beyond a single line and makes the height of the div take up significant height in the window.
