### ISSUE TITLE
drawing the rectangle and measurements

### ISSUE THREAD

**Issue by ericvanderlinden** [ProjectMirador/mirador#2642]
Is there some documentation on how Mirador draws the rectangles on the annotation layer.
It seems to use an own internal measure and not real pixels.

**Comment by mejackreed** [comment]
Mirador 3 draws annotations using the size of the annotation in the xy space of the IIIF Presentation Canvas.

**Comment by ericvanderlinden** [comment]
Sorry, Tuesday, when I was working on my image project I discovered through a process of elimination that the error was that the script that generates the manifest and canvas JSON did not put in the correct height of the image and canvas. The result was annotation area's looked way to big for the image.

Maybe some feedback in console or the details overlay on how bog "Mirador" thinks the canvas and image is would be helpful.
