### ISSUE TITLE
Update Mirador version

### ISSUE THREAD

**Issue by lguariento** [ProjectMirador/mirador#2655]
Hello,

this is not a proper issue, more a general how-to question.

Is there a tested method to update Mirador from, say, 2.6.1 to 2.7, without losing configurations/customisations?

Best,
Luca

**Comment by mejackreed** [comment]
I'm not sure there is the documentation available unfortunately. The release notes might be of some help: https://github.com/ProjectMirador/mirador/releases/tag/v2.7.0

I don't see large scale changes here in this version update.

For future updates, Mirador 3 and beyond, Mirador will be using semantic versioning which will hopefully aid in these types of upgrades.
