### ISSUE TITLE
Image browse icon in sidebar is confusing

### ISSUE THREAD

**Issue by ahankinson** [ProjectMirador/mirador#2661]
The icon for browsing the images in the sidebar seems to have appropriated the same icon in text editors for 'Right-align text"

![image](https://user-images.githubusercontent.com/163183/59188614-f0420500-8b6f-11e9-8be9-f571fccc7cdb.png)

This makes it difficult to tell which item to click to see the other images in a manifest, since the image browse functionality is not immediately obvious.

**Comment by ggeisler** [comment]
@ahankinson The window sidebar category you're referring to is called "Index" (see the icon tooltip). Its purpose is to show structures defined in the IIIF manifest; it's not intended to specifically be an image browse category, that's what the thumbnail grid/panel available from the Window options menu is intended for. 

Work to add a more text-oriented table of contents to this category is still in progress (see https://github.com/ProjectMirador/mirador/issues/2068 for some design links) but when that work is done it should be more clear that this category is more of a way to navigate the object by the different defined structures than by thumbnail images. And the text-oriented table of contents, when it exists, will be the default view of this panel, so the text-oriented icon should feel more appropriate then.

**Comment by jvine** [comment]
@ahankinson More specifically about the icon itself: It's not _actually_ the right-align text icon, but it's definitely close. It was difficult to find/create an icon for this category that wasn't a bulleted list or easily confused with the hamburger menu. This version was meant to express a hint of hierarchy (as in the text Table of Contents @ggeisler refers to) but seems to have just made it confusing in a different way. We're open to alternate suggestions...

**Comment by ahankinson** [comment]
Ah, ok. I guess I was confused because (for some reason) when I load a manifest with multiple pages in the viewer, it defaults to not showing the image navigation bar. You have to click around in (to me) non-obvious places to actually show it.

Loading the Durham University manifest on the sneak peek (https://mirador-dev.netlify.com/__tests__/integration/mirador/) exhibits this behaviour for me now. I have to go to the three vertical dots and turn on 'Show thumbnails'. 

Otherwise, the only default document navigation options visible are clicking through the images one-by-one with little tiny buttons.

**Comment by ggeisler** [comment]
@ahankinson 

> I don't know if not showing the thumbnails by default is a bug or a feature?

The thumbnail display is a configuration option, so it is up to the implementer to decide whether it makes sense to show or hide the thumbnails by default:

```
  thumbnailNavigation: {
    defaultPosition: 'off', // Which position for the thumbnail navigation to be be displayed. Other possible values are "far-bottom" or "far-right"
    height: 130, // height of entire ThumbnailNavigation area when position is "far-bottom"
    width: 100, // width of one canvas (doubled for book view) in ThumbnailNavigation area when position is "far-right"
  },
```

I suggest we close this ticket, since it sounds like your original concern transitioned to a concern about the thumbnails being off by default, and as mentioned above, that is easily controlled by the Mirador 3 implementer.
