### ISSUE TITLE
Add before/after content and truncation behavior

### ISSUE THREAD

**Issue by jkeck** [ProjectMirador/mirador#2671]
The "truncation" renders the full snippet (before/after) in the panel by itself w/ a link that will go back to the Annotation list.

(Edit by @ggeisler below with some details)
We'll have to pick some character or word limit to trigger truncation. This will probably be easy to adjust so as a starting point I'll suggest `200 characters`, which would produce something like this result:

<img width="337" alt="Screen Shot 2019-06-12 at 11 43 42 AM" src="https://user-images.githubusercontent.com/101482/59377725-aee45d80-8d07-11e9-9be3-54ad0e04e614.png">

~When the user selects the "more ..." link, that should take them to the detail result view panel described in #2688.~

**Comment by cbeer** [comment]
I'm going to take the more link behavior over to #2688.
