### ISSUE TITLE
Should / can we balance the before/after truncation?

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#2698]
I’ve been thinking about the very long “before” “after” that we provide, which is not always relevant. Could we provide a truncation algorithm to make that more digestible like this:

*Pseudo code not sure if it works*
```
TOTAL_CHARS = 200

resultingChars = (TOTAL_CHARS - match.length) / 2;
measured = [before.length, after.length].filter(length => length > 0)
charsOnSide = Math.min(resultingChars, ...measured)
display = before.substring(before.length - charsOnSide, before.length);
display += match
display += after.substring(0, Math.min(after.length, charsOnSide))
```

Would turn this:

![Screen Shot 2019-06-13 at 11 07 23 AM](https://user-images.githubusercontent.com/1656824/59452756-aa817880-8dcb-11e9-832e-e2a9f9b8ecab.png)

Into this:

![Screen Shot 2019-06-13 at 11 08 01 AM](https://user-images.githubusercontent.com/1656824/59452764-afdec300-8dcb-11e9-8df7-f7543ba4cc5a.png)

**Comment by ggeisler** [comment]
Just from a UX point of view, I think that looks like what we want. Basically, 200 characters with the search term more or less in the middle of the before and after text.
