### ISSUE TITLE
Screen-reader accessibility of search results navigation

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2717]
Currently, the Next/Previous navigation is keyboard accessible, but not for screen readers. The SR hears the label, and knows it's a button, and can click it; but no change is perceived. I think the correct way to address this is with an `aria-live` region. 

It seems like it should work to dynamically attach `<aria-live="assertive">` to the `<li>` of the current result on button press. User tabs to button, clicks it, SR reads the contents of the list item. It does work in Chrome on VO, but only the first time the button is pressed (maybe the SR doesn't perceive it as a "change" if you go back). Having trouble with other browsers. 

Anyone have other ideas on this? Goal is to have the content of the result read when the user clicks the button, without changing the focus to that content (and away from the button).

**Comment by jkeck** [comment]
Closed by #2829
