### ISSUE TITLE
"More" links should give specific context (plus styling)

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2726]
1.  Concern: The "more..." option is not technically a button-within-a-button in the HTML, but it is still reading as such to a screenreader, because the parent item has `role="button"`. I don't know if this is illegal, but it's disconcerting. I don't know what to do about this. 

2. Actionable: When the "more..." link exists, it should include some context for the screenreader. Can do this with `<button aria-describedby="resultLabelID">` which should read something like "more [pause] Page 6". _(edited)_

3. Actionable: The mockups #2683 show lower-case "m" and an underline (I think the expectation was that this would be rendered as a link, not a button). The underline with the expanded letter-spacing of the button looks awkward to me. @ggeisler?

**Current**
<img width="209" alt="Screen Shot 2019-06-14 at 3 55 50 PM" src="https://user-images.githubusercontent.com/6945691/59542858-e8aa9500-8ebc-11e9-873e-321385200bfc.png">
**Proposed**
<img width="208" alt="Screen Shot 2019-06-14 at 3 50 41 PM" src="https://user-images.githubusercontent.com/6945691/59542725-2eb32900-8ebc-11e9-8971-dc940a31b87a.png">
  - remove the underline
  - force the height of `<span class="MuiButton-label">` to `1.5em` so it doesn't make the last line of text hang lower than it's meant to
  - lower-case the "m"

**Comment by ggeisler** [comment]
> The underline with the expanded letter-spacing of the button looks awkward to me.

Agreed, the wider letter-spacing makes it look odd, like it is unintentional. I didn't expect it to be a button (didn't understand the whole everything-is-a-button thing) so in my mockup just styled it like a regular link.  I've no problem with removing the underline and your other suggestions.

**Comment by camillevilla** [comment]
I've addressed items 2 and 3 in #2374. Should we split out item 1 to a different ticket, or do you want to compile stuff into a single ticket for the next accessibility audit @jvine?

**Comment by jvine** [comment]
Split issue 1 into #2755.
