### ISSUE TITLE
Multiple "selected" search hits displayed

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2733]
I know the team is still working on content search so ignore if this is a known issue being worked on, but the version on `master` has a pretty significant bug where, when I select my first hit, the panel shows what looks like a duplicate hit as the third one:

<img width="405" alt="Screen Shot 2019-06-17 at 4 31 06 PM" src="https://user-images.githubusercontent.com/101482/59643531-e6934100-911d-11e9-8a4a-00d4aa66562c.png">

If I navigate to the second hit, it looks like this:

<img width="405" alt="Screen Shot 2019-06-17 at 4 31 30 PM" src="https://user-images.githubusercontent.com/101482/59643549-f6128a00-911d-11e9-88e4-18e9fba9b381.png">

And if I use the "next result" icon to try to move through the hits I get into a loop where I go back to hit 1, then to hit 2, back to hit 1, etc.

My example was searching for "flower" in https://purl.stanford.edu/zx429wp8334/iiif/manifest

**Comment by cbeer** [comment]
This is happening because the content search is returning two results for the same annotation, so I'm going to move this ticket over there.
