### ISSUE TITLE
Search panel results should scroll in sync with canvas

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2741]
When you get search results and use the hit navigation to move through them, the canvas is correctly updated to show both the currently selected hit and the correct canvas, when you move to a hit that is on another canvas.

However, the search results display never moves, so after navigating through a handful of hits you have a state where the displayed results in the panel are not the ones shown on the canvas:

<img width="508" alt="Screen Shot 2019-06-18 at 1 48 30 PM" src="https://user-images.githubusercontent.com/101482/59719079-6c6fc480-91d0-11e9-8235-ad4cbcf62c5d.png">

Ideally, as the user uses the hit navigation to move through the search result hits, the panel will scroll such that the currently selected hit (the yellow highlighted one) will visible in the panel. Most ideally, perhaps, the currently selected hit should always be the hit item aligned at the top of the search panel body:

<img width="855" alt="Screen Shot 2019-06-18 at 1 56 53 PM" src="https://user-images.githubusercontent.com/101482/59719320-f4ee6500-91d0-11e9-8aef-cbdf62aa9fc0.png">

**Comment by cbeer** [comment]
I'm a little worried about our ability to pull off a good + consistent implementation here, particularly once you get into paginated responses or with multiple search companion windows open. It also seems to presume that search hits will be returned in canvas order.

**Comment by ggeisler** [comment]
I'm not sure I understand how canvas order complicates doing this; at least, I wasn't presuming hits are in canvas order (though that would be ideal). 

With multiple search companion windows open we still have only one result item as the selected item at any one time, I think? So if you select an item in Companion Window A, the canvas highlights that hit (changing canvases if necessary) and (what we would also like) Companion Window A's panel scrolls as necessary to make sure that selected hit is visible in the panel.

If the user then selects a hit from Companion Window B's panel, the same thing happens: canvas is updated, Companion Window B's panel scrolls as necessary to to ensure the selected hit is visible in Companion Window B's panel.

So from the UI perspective at least, I think the interaction can be intelligible. And better than having a selected search hit that isn't visible in the panel.

If your concern is with the challenge in implementing something that works as I described above, sure, I take your word for it, just want to make sure it's clear this is a non-trivial UX issue.
