### ISSUE TITLE
Highlight of Window options choices is not correct

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2764]
At some point (I think recently, but not sure) the highlight for the options in the Window options menu changed so that it doesn't reflect the shape of the underlying icon/text of the option being highighted:

<img width="382" alt="Screen Shot 2019-06-20 at 10 29 48 AM" src="https://user-images.githubusercontent.com/101482/59868853-bc709780-9346-11e9-8bac-fb0f438556e6.png">

**Comment by mejackreed** [comment]
This happened w/ the MUI 4.x upgrade

**Comment by ggeisler** [comment]
I'll add another one that might also be due to the MUI upgrade and perhaps could be fixed at the same time as the issue above. The highlight for the workspace fullscreen icon is oval instead of round:

<img width="122" alt="Screen Shot 2019-06-21 at 9 51 53 AM" src="https://user-images.githubusercontent.com/101482/59938619-62390a80-940a-11e9-93ad-590425868dc6.png">
