### ISSUE TITLE
Add search result details to gallery view

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2765]
If a user is in gallery view when conducting a search, we want to provide an overview of the results in as much detail as we can. The recommendation below simplifies that idea a bit but still tries to provide the user with an indicator of each page in the document that contains search results (gray border around page).

### Interactive mockup
To get a feel for how the proposed interaction would work, see: https://xd.adobe.com/view/bf6a7518-d18a-4782-49e9-18c41b79fcb2-c95b/

use the hit navigator (the "1 of 33" thingy) to move through the different mockup pages.

### Gallery view display area - page borders

<img width="993" alt="Screen Shot 2019-06-20 at 12 04 11 PM" src="https://user-images.githubusercontent.com/101482/59874778-f6946600-9353-11e9-8fba-127797e891a9.png">

---

- [x] For each page that has hits, show a gray border around the page item in the view display area (callout B in mockup above). Use the same border styling used to indicate the selected page in normal gallery view, just with `border-color: rgba(0,0,0,0.14);`, which I believe is the same color we use for the background of a selected annotation in the Annotations panel, for example.

- [x] As the user navigates through hits, either with the hit navigator in the search panel header, or by manually selecting an item from the results list in the panel body, the page item containing the currently selected search result hit should get the selected border color (callout A; using the secondary theme color, I believe), same as in normal gallery view.

- [x] "Plus more" hits indicator: show a special indicator with a larger dot and a count of how many hits the page contains. 

- [x] "Plus more" hits indicator styling: The example in the mockup above is based on the chip component. The background and text colors are the same as used in the search panel results list for the gray hit counter background/text (`#bdbdbd` and `rgba(0, 0, 0, 0.87)`,  I believe). (This was changed to use the default chip grey as the background, and `#bdbdbd` as a avatar color)

- [x] Plus more" hits indicator dot styling: The bigger dot in the "plus more" chip is about `24px`. Background color is grey when no annotations on that canvas are selected. If an annotation on the page is seleected, the background color for the chip dot becomes yellow (as in mockup below), to indicate that the user has currently selected a hit belonging to the group. So it stays yellow until the user navigates to another results page.

- [x] "Plus more" hits indicator font styling: The typography of the "+19" in the mockup above is the same `Caption` typography used for the canvas label below the page image (`MuiTypography-caption`).

### Search panel header and body
- [x] As the user navigates through hits, either with the hit navigator in the search panel header, or by manually selecting a page in the gallery view, the search panel body should scroll as necessary to keep the selected hit in view.

- [x] If the user manually selects a page from the gallery view, the search hit navigator and the result list in the panel body should update as needed to show **the first hit** on that page as the selected hit.

**Comment by cbeer** [comment]
I've extracted the hit indicators to #2787 and rewritten the ticket to describe the approach @jvine and I discussed (and the original text is still in #2787).
