### ISSUE TITLE
Sidebar tab buttons no longer open collapsed sidebar

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2773]
Open the sidebar.
Collapse it with the collapse control.
Click one of the sidebar icons - Index, Rights, whatever.
The selection highlight moves but the panel doesn't open.

![sidebar](https://user-images.githubusercontent.com/6945691/59950211-14cc9580-942a-11e9-919d-aa3a510d9661.gif)

Clicking a sidebar icon is meant to re-open the sidebar, and used to. Wha happen?

(Reported by PSM tester.)

**Comment by camillevilla** [comment]
I think we changed this sidebar behavior a while back: 
https://github.com/ProjectMirador/mirador/pull/2092
https://github.com/ProjectMirador/mirador/issues/1853
