### ISSUE TITLE
Invisible scrollbars causing usability issues

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2774]
Some things just need to scroll, like a complex dialog in a very small window. 

If a user has their scrollbars set to show only when scrolling... they don't see any affordance for scrolling in the dialog and don't realize there are more options available. 

Is there a way to force the display of scrollbars inside dialogs? Found this but it doesn't seem robust:
https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

**Comment by jvine** [comment]
Decision is to use shadow to indicate when there is content that is not displayed. Not convinced this will be 100% effective, but forcing the scrollbar seems like a no-go.

Goal is for the shadow to appear only if there is overflow content below the visible content, above it, or both.

**Start state: Shadow at the bottom**
<img width="454" alt="shadow bottom" src="https://user-images.githubusercontent.com/6945691/60058371-ff12d680-969c-11e9-9a28-b9dd7467232d.png">

**User scrolls down, shadow also appears at the top**
<img width="450" alt="shadow scroll" src="https://user-images.githubusercontent.com/6945691/60058748-7bf28000-969e-11e9-966c-66f88b0c5e6f.png">

**User reaches the bottom, shadow only at the top**
<img width="456" alt="shadow top" src="https://user-images.githubusercontent.com/6945691/60058374-ff12d680-969c-11e9-8de2-3f5ebf867d9d.png">

**No shadow needed, all content is displayed**
<img width="457" alt="shadow not needed" src="https://user-images.githubusercontent.com/6945691/60058431-38e3dd00-969d-11e9-9d56-65f865ab0c74.png">

For the header, I used `MuiPaper-elevation4` which is 
`0 2px 4px -1px rgba(0,0,0,.2), 0 4px 5px 0 rgba(0,0,0,.14), 0 1px 10px 0 rgba(0,0,0,.12)`, 
but for the footer it needs to be inverted to: 
`0 -2px 4px -1px rgba(0,0,0,.2), 0 -4px 5px 0 rgba(0,0,0,.14), 0 -1px 10px 0 rgba(0,0,0,.12)`

**Comment by jkeck** [comment]
@jvine should this behavior only apply to modal dialogs?
