### ISSUE TITLE
Start canvas issue 

### ISSUE THREAD

**Issue by NSV1991** [ProjectMirador/mirador#2791]
`"sequences":[{`
` "@id":"http://23a337ad-76b9-4c5f-be47-50f1f5094ff0",`
 `"@type":"sc:Sequence",`
` "label":[{
  "@value":"Normal Sequence",
  "@language":"en"
 }],`
` "canvases":[],`
 `"start":{
"id":"https://iiif.durham.ac.uk/manifests/trifle/32150/t1/m4/x5/t1m4x51hj08c/canvas/t1thq37vq07f",`
` "type":"Canvas"`
` }}]`

`"sequences":[{`
 `"@id":"http://23a337ad-76b9-4c5f-be47-50f1f5094ff0",`
 `"@type":"sc:Sequence",`
` "label":[{
  "@value":"Normal Sequence",
  "@language":"en"
 }],`
` "canvases":[],
}],`
`"start":{
"id":"https://iiif.durham.ac.uk/manifests/trifle/32150/t1/m4/x5/t1m4x51hj08c/canvas/t1t0k225c71s",
"type":"Canvas"
},`

I have tried to add "start" property in manifest data in above following ways (one at a time):
1. added 'start' property inside sequences beside Canvas array
2. added 'start' property inside manifest data beside sequences

On clicking first canvas thumbnail, it loads canvas defined in start property.

![NewGIF](https://user-images.githubusercontent.com/37620010/60099470-571d0c00-9775-11e9-88b6-657f0924fe51.gif)

Please provide appropriate guidance or solution

**Comment by mejackreed** [comment]
Is it possible to provide a live manifest where this is happening?

I'm noticing that this manifest: https://api.bl.uk/metadata/iiif/ark:/81055/vdc_000000035B1A/manifest.json

seems to work ok for me at least.

<img width="876" alt="Screen Shot 2019-06-27 at 11 27 38 AM" src="https://user-images.githubusercontent.com/1656824/60254655-9b6fef80-98ce-11e9-83c0-04de857139d8.png">

**Comment by NSV1991** [comment]
Today again I have rebase my forked branch and now it's wroking. I don't no what changed but it's working now for property "start" according to [v3.0](https://iiif.io/api/presentation/3.0/#332-internal-links) and "startCanvas" according to [v2.1](https://iiif.io/api/presentation/2.1/#sequence).

**Comment by mejackreed** [comment]
That's great to here! I'll wait to hear from @cbeer before closing
