### ISSUE TITLE
Keyboard access issue in Index list

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2812]
Tested on this manifest: https://purl.stanford.edu/zx429wp8334/iiif/manifest

Behaviour is slightly different in single vs book view.

Single view:

1. place focus on the Page 1 in the list
2. tab to Page 2 - 2 tabs are required to place focus on Page 2
3. press Enter to select Page 2 - image changes
4. tab to Page 3... focus moves to Page 1, then Page 2, then Page 3. That is 3 tabs to move the focus to the next item in the list. Enter to select that item, then rinse, repeat.

Book view:

1. place focus on the Page 1 in the list
2. tab to Page 2 - 2 tabs are required
3. press Enter to select Pages 2&3 - images change
4. tab to Page 4... focus moves to Page 1, 2, 3, 4.
5. press Enter to select page 4
6. tab to Page 5... focus moves to Page 2, 3, 4, 5, 6.  That's **5 tabs** to move focus to the next item. 

![tabbing issue - single view](https://user-images.githubusercontent.com/6945691/60220361-a4a78080-982a-11e9-8564-209a50edabe2.gif)
![tabbing issue - book view](https://user-images.githubusercontent.com/6945691/60220365-a7a27100-982a-11e9-8bf4-55ee40e10dd7.gif)

**Comment by cbeer** [comment]
Fixed by  #3083
