### ISSUE TITLE
Cannot initialize mirador w/ the same manifest twice

### ISSUE THREAD

**Issue by jkeck** [ProjectMirador/mirador#2823]
```js
     var miradorInstance = Mirador.viewer({
       id: 'mirador',
       windows: [{
         manifestId: 'https://purl.stanford.edu/fg165hz3589/iiif/manifest',
         canvasIndex: 1,
       },
       {
         manifestId: 'https://purl.stanford.edu/fg165hz3589/iiif/manifest',
         canvasIndex: 2,
       }],
     });
```

This throws the error:
`Window.js?2d91:59 Uncaught TypeError: Cannot read property 'mosaicWindowActions' of undefined` from https://github.com/ProjectMirador/mirador/blob/98bdf84f27c33773c5b8940ae2e36d0497c6c01c/src/components/Window.js#L59

**Comment by cbeer** [comment]
I'm not able to reproduce this.

**Comment by jkeck** [comment]
Weird, I just cleared my node_modules and re-installed and it works fine now.  Something must have been wonky w/ my setup locally.
