### ISSUE TITLE
Bottom panel not scrollable in FF-Chrome on Ubuntu

### ISSUE THREAD

**Issue by regisrob** [ProjectMirador/mirador#285]
The bottom panel with thumbnails is not scrollable in Firefox 32.0.3/Chromium 37.0.2062.120 on Ubuntu 14.04: the horizontal scrollbar is present but it is so thin that you almost can't use it (provided you've seen it). It seems the combination of "margin-top:10px" and "height:100%"on div.panel-thumbnail-view is involved.

![capture du 2014-10-09 22 21 49](https://cloud.githubusercontent.com/assets/402117/4583486/fa8d3ffc-4ff1-11e4-867b-92526ab204df.png)

Not relevant anymore if it is considered to add next/prev buttons in the left/right edges of the panel

**Comment by aeschylus** [comment]
Is this still happening?

**Comment by regisrob** [comment]
Yes it is :confused:

Screenshot: Firefox on the left (scrollbar is 1px height, so not usable at all) ; Chrome on the right (scrollbar is a bit more visible and almost usable)
![capture du 2015-03-05 23 06 33](https://cloud.githubusercontent.com/assets/402117/6515854/d6024c76-c38d-11e4-91bf-4824e13ae781.png)

Turning off "margin-top:10px;" in Devtools/Firebug make the entire scrollbar appear.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
