### ISSUE TITLE
Unable to set page margin in book view

### ISSUE THREAD

**Issue by bilz01** [ProjectMirador/mirador#2854]
I am trying to adjust the margin between the two pages in book view mode. I like to set it to none so both pages are joined with no gap in between. Unable to find the relevant css portion. Help needed please

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
