### ISSUE TITLE
What version of iiif does Mirador 3 use?

### ISSUE THREAD

**Issue by GroovinChip** [ProjectMirador/mirador#2862]
It seems to me to be version 2, but I wanted to make sure.

**Comment by jkeck** [comment]
There is support for both, although the support for V2 is much more robust as that is what we were primarily developing against.

See #2816 where Presentation API V3 support was added for more details.

**Comment by mejackreed** [comment]
You can also see Prezi v3 in action here: https://mirador-dev.netlify.com/__tests__/integration/mirador/v3.html

**Comment by GroovinChip** [comment]
Thanks guys! This is very helpful.
