### ISSUE TITLE
Setting canvasIndex higher than available canvas count breaks Mirador

### ISSUE THREAD

**Issue by ewlarson** [ProjectMirador/mirador#2869]
Ran into this issue on the B1G Geoportal. @mejackreed solved the problem for us. Full details here:
https://github.com/BTAA-Geospatial-Data-Project/geoportal/issues/240

[Our Mirador configuration](https://github.com/BTAA-Geospatial-Data-Project/geoportal/blob/a03fdf91ed968167878ad0fec0cc07121768906e/app/assets/javascripts/geoblacklight/viewers/iiif_manifest.js#L21) mistakenly hardcoded a canvasIndex value of 2 -- would have been the title page of a book IIIF Manifest. Subsequent IIIF Manifests with only two or less canvases would not display, leaving the Mirador viewer as only a white box.

<img width="633" alt="Screen Shot 2019-08-01 at 9 08 15 AM" src="https://user-images.githubusercontent.com/69827/62305567-d58c5e00-b445-11e9-83a7-77d729213237.png">

So! If you foolishly config your canvasIndex value at a higher count than canvases available Mirador will break.

Solution: Consider falling back to canvasIndex 0, when the configured value is not present in the IIIF Manifest.

**Comment by stefan-it** [comment]
I'm also highly interested in this bugfix 🤗

@cbeer would it possible that this issue can be added to the 3.0.0 milestone :heart:

**Comment by cbeer** [comment]
Is this still a problem? I'm not seeing it in the latest code in master, at least.
