### ISSUE TITLE
HTML transcription support 

### ISSUE THREAD

**Issue by krunal86** [ProjectMirador/mirador#2871]
We are integrating HTML transcription in Mirador. We are passing formatted HTML with bullets, bold and italic. But when it's getting rendered into Mirador. I have noticed that all the HTML tags are getting replaced with **span** tag. 

**Formatted Transcription in IIIF manifest editor:**
![Formatted Transcription jpeg](https://user-images.githubusercontent.com/29122081/64068666-2384b500-cbf0-11e9-9fc3-c0f4c2363454.png)

**This is how it looks in Mirador**
![Formatted HTML Transcription in Mirador jpeg](https://user-images.githubusercontent.com/29122081/64068668-27183c00-cbf0-11e9-916a-f4fe0c636783.png)

 
**Sample Manifest** 
https://gist.github.com/krunal86/37a708d6626d189487286dfa263b1675

**Sample Annotation List**
https://gist.github.com/krunal86/98076498e9e86e2792bc123ad356ab5e 

**Use Case**

1. Scholars needing to cut and paste content from annotations pane where annotations contain detailed lists and formatting, such as complex arguments in a theological dictionary. Or more simply, theological manuscripts, such as letters, where dates, greetings, body text, and salutations lose meaning outside the context of their original format. Thus it's critical to retain as much formatting as possible in the transcription

2. Newspaper content or any content with multiple columns, where formatting is critical to retain the flow of the dialogue.

**Comment by mejackreed** [comment]
Hi @krunal86 . Do you think you could link the sample AnnotationList in the Sample Manifest so that we could do development work on this and test that it is behaving as expected? Thanks!
