### ISSUE TITLE
Forcing mode: "wrap" to add plugin components to unsupported Mirador components crashes the Window

### ISSUE THREAD

**Issue by GroovinChip** [ProjectMirador/mirador#2874]
Sample plugin component:
```
import React from "react";
import WebAnnotationsIconButton from "./WebAnnotationsIconButton";

const WebAnnotationsPlugin = props => {
  console.log(props);
  return <div id="WebAnnotationsPlugin">
    <props.TargetComponent {...props} />
    <WebAnnotationsIconButton />
  </div>;
};

export default {
  name: "WebAnnotationsPlugin",
  target: "WindowSideBarButtons",
  mode: "wrap",
  component: WebAnnotationsPlugin
};
```

Since `WindowSideBarButtons` is not a component that supports `mode: "add"`, @mejackreed suggested I use `<props.TargetComponent {...props} />` with `mode: "wrap"` to allow for adding my plugin to that component. 

When I click on the hamburger button to open the sidebar, the entire `Window` crashes and goes blank. I ran the debugger in the web console and found that an exception occurs at the following line in `mirador.min.js`: 
```
e.removeAttribute("tabindex"), e.setAttribute("aria-selected", "true");
```
The exception is: `TypeError: e is undefined`

Why would this be happening, and what can I do to fix it? 

Also, is there anything I can do to help more components support `mode: "add"`? I'd be happy to submit a pull request if I can be pointed to the exact part of the codebase that determines which components support which modes.

**Comment by charbugs** [comment]
I think the problem here is that you pass the props of the plugin component down to the target component instead of only the props of the target component. Does the fix bellow solve the problem?

```javascript
return (
  <div id="WebAnnotationsPlugin">
    <props.TargetComponent {...props.targetProps} />
    <WebAnnotationsIconButton />
  </div>;
)
```

**Comment by GroovinChip** [comment]
Yes, that works! Thank you!
