### ISSUE TITLE
How do I access Mirador functions when using it as a dependency?

### ISSUE THREAD

**Issue by GroovinChip** [ProjectMirador/mirador#2876]
I am using Mirador as a dependency and modifying it by adding my own button to the WindowSideBarAnnotationsPanel, and I'd like to create a new sidebar panel when clicking that button. How can I access the functions that control this?

**Comment by mejackreed** [comment]
Plugins enable a user to wrap or add to a component. For your usecase, I would recommend now using the companion window registry to accomplish this.

```javascript
{
        companionWindowKey: 'xyz',
        component: ComponentA,
        mode: 'add',
        target: 'CompanionWindowFactory',
},
```
