### ISSUE TITLE
Support Web Annotation model in Mirador 3 selectors and models

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#2877]
Similar to https://github.com/ProjectMirador/mirador/issues/1479

Mirador Annotation selectors and related pieces assume the Open Annotation model. This ticket aims to support Web Annotation in our selector structure to support a broader range of annotations.

Areas of codebase for enhancement:
 - `Annotation` https://github.com/ProjectMirador/mirador/blob/master/src/lib/Annotation.js
 - `AnnotationResource` https://github.com/ProjectMirador/mirador/blob/master/src/lib/AnnotationResource.js
 - Selector locations https://github.com/ProjectMirador/mirador/blob/master/src/state/selectors/annotations.js

**Comment by GroovinChip** [comment]
Seems to me that we should start with `AnnotationResource`, since `Annotation` relies on it.

**Comment by mejackreed** [comment]
This has now been resolved in #2898
