### ISSUE TITLE
Custom Annotation Fields

### ISSUE THREAD

**Issue by Teifun2** [ProjectMirador/mirador#2878]
I'm trying to find out if it there is a way to add custom fields to annotations. As an example i would like to have a drop-down with some "Types" that can be selected in addition to the text or the tag?
I have found nothing on this topic so far through my search. If someone has an idea how to achieve this i would be very great full.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
