### ISSUE TITLE
Thumbnails native.jpg

### ISSUE THREAD

**Issue by doobybug** [ProjectMirador/mirador#2885]
Hi, I was working locally and I notice that the thumbnails are default.jpg. As soon as I transferred my work to a remote server the thumbnails extension changed to native.jpg resulting into the images not being loaded. Any idea how I can solve this pls?

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
