### ISSUE TITLE
manifest.json in the URL

### ISSUE THREAD

**Issue by defaliz** [ProjectMirador/mirador#2887]
hello,
i want to pass the manifest in the url as in this website 
https://iiif.si.edu/mirador/?manifest=https://bibliotheque-numerique.inha.fr/iiif/20612/manifest

but with my mirador installation that's doesn't works
https://iiif.inha.fr/mirador/?manifest=https://bibliotheque-numerique.inha.fr/iiif/20612/manifest

do you know why ?
thanks for replies
Alain

**Comment by mejackreed** [comment]
Thanks for creating the issue @defaliz . Mirador intentionally doesn't handle state or data through the URL. However, several adopters have implemented something similar.

Here is an example using Mirador 3:

https://vkwllpkzy.csb.app/?manifest=https://bibliotheque-numerique.inha.fr/iiif/20612/manifest

Code available at: https://codesandbox.io/s/vkwllpkzy
