### ISSUE TITLE
Search input label overlays text when focus moves

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2888]
Place cursor in the search input: label moves up above the input.
Type search term, submit search.
Move focus out of the search box:  label overlays the search text.

The label should stay in place above the input until the user clears the search.

![searchlabel2](https://user-images.githubusercontent.com/6945691/67534651-f4387480-f683-11e9-80ce-6555831b0628.gif)

**Comment by mejackreed** [comment]
To whomever takes this on. I _think_ this might be fixed with an update to MaterialUI

**Comment by camillevilla** [comment]
Confirmed this has been resolved.
