### ISSUE TITLE
Search doesn't accept typeahead selection

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2889]
Type in the search box until the typehead popup appears.
Click a term in the typeahead list.
Search is submitted with what is in the search box, not with the typeahead selection. Depending on the letters typed and the language, the result might be zero or a stemmed search - but it's not specifically searching the selected term.

![typeahead](https://user-images.githubusercontent.com/6945691/67534799-b0923a80-f684-11e9-9cf5-985adc83e593.gif)

**Comment by camillevilla** [comment]
Tried to recreate this one and it looks like it's been resolved.

![typeahead-selection](https://user-images.githubusercontent.com/5402927/94843303-5e4bb480-03d1-11eb-9443-4a3cfe474938.gif)

Sample manifest: https://purl.stanford.edu/qs858rw6303/iiif/manifest
