### ISSUE TITLE
Search typeahead is not keyboard accessible

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#2890]
Start typing in the search box... typeahead list will appear. (Mostly. Sometimes it just doesn't.)

There's no way to get the keyboard into the typeahead list. Screenreader announces the presence of the list, but neither arrows nor tab will move into the list to read it or select.
 
![VO on search](https://user-images.githubusercontent.com/6945691/67535124-1e8b3180-f686-11e9-9c58-c82d98cfe495.gif)

**Comment by camillevilla** [comment]
Tried to recreate this and it looks like this has been resolved. You can get to the typeahead by using the up and down arrow keys.
![typeahead-keyboard-nav](https://user-images.githubusercontent.com/5402927/94840843-f2b41800-03cd-11eb-94eb-3eb5b4e89c95.gif)
