### ISSUE TITLE
how to use osd2.4.1 overlay in Mirador2.7 ?

### ISSUE THREAD

**Issue by jeanphilippegoldman** [ProjectMirador/mirador#2892]
Hi,
does anybody would know how to use osd2.4,1's overlays in Mirador as examplified in http://openseadragon.github.io/examples/ui-overlays/ ?
Note: I'm not interested in annotations, only overlays.
many thanks

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
