### ISSUE TITLE
Add an Arabic translation for Mirador 3

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#2893]

**Comment by caaster** [comment]
@mejackreed my understanding from discussing this with @jacobhill yesterday is that this would be nice to have in the future (including right to left display for the viewer), but it is not a priority deliverable/requirement for this work cycle.

**Comment by mejackreed** [comment]
Great... just tracking the work upstream in Mirador. @tristanr-cogapp previously contributed a translation for Mirador 2, so perhaps other community members might see this and be able to contribute.

**Comment by JacobHill** [comment]
Sorry, wrong Jacob Hill.

On Nov 5, 2019 9:24 AM, caaster <notifications@github.com> wrote:

@mejackreed<https://github.com/mejackreed> my understanding from discussing this with @JacobHill<https://github.com/JacobHill> yesterday is that this would be nice to have in the future (including right to left display for the viewer), but it is not a priority deliverable/requirement for this work cycle.

**Comment by mejackreed** [comment]
Resolved in #3022
