### ISSUE TITLE
Adding a Serbian cyrillic translation for localisation

### ISSUE THREAD

**Issue by DigitLib** [ProjectMirador/mirador#2899]
Here is a link
https://github.com/DigitLib/mirador-serbian/tree/master/locales/rs

For Mirador3 will be soon

**Comment by mejackreed** [comment]
Excellent! Thanks so much @DigitLib ! Will you be making a pull request for Mirador 3?

**Comment by DigitLib** [comment]
@mejackreed Of course as soon as finish it.

**Comment by mejackreed** [comment]
Thank you, thats great to hear! Let us know if we can assist in anyway.

**Comment by DigitLib** [comment]
Great!!! I will, through Github or?

**Comment by mejackreed** [comment]
Yes please, a GitHub pull request is preferred. Here is an example of how the Italian translation was added: https://github.com/ProjectMirador/mirador/pull/2866 . Having everything in 1 commit would also be fine.

**Comment by DigitLib** [comment]
Great! Thank you! As soon as finished a PR run!

**Comment by camillevilla** [comment]
Thanks again for contributing, @DigitLib 👏
