### ISSUE TITLE
Drag and Drop captures window level events & prevents embedding in app with DnD

### ISSUE THREAD

**Issue by rogerhyam** [ProjectMirador/mirador#2903]
Thanks for all your work on Mirador 3 - a great thing!

I'm looking at embedding Mirador in a React based app. I can create it as a component following instructions here in github. Looks cool!

The issue is as soon as I instantiate a Mirador instance the drag and drop of my own components external to Mirador stops working. These are based on plain HTML5 DnD not a library.

I believe this is because Mirador (actually the react-dnd library) captures window level dragstart events (see screenshot).

![Screenshot 2019-12-03 at 16 46 02](https://user-images.githubusercontent.com/1799028/70071060-9f760b00-15ec-11ea-939f-9bb5601dba8a.png)

If I remove the listeners in Chrome I get my DnD back.

I tried moving my DnD functionality over to using the react-dnd library but then I ran into an issue that you can't create two overlapping HTML5Backend s in react-dnd - it only expects one per application. The DndProvider needs to wrap the whole app.

Is this a bug? I'm not sure. It is a failure of encapsulation but I'm not sure how you might fix it or I might find a work around. Any ideas welcome.

How dependent are you on the react-dnd library?

My current options are to redesign my app to not use DnD (bad) or find some way to remove the event listeners and filter whether events start in my components or Mirador (possibly crazy).

I'm pretty new to react & redux so I may be being naive!

**Comment by rogerhyam** [comment]
I think I have a work around. It is a hack but I'm up for that! I thought I'd have to proxy the event handlers that were added to the window but if I just prevent the dragstart and dragover handlers then I get my DnD functionality back and Mirador seems to be working fine. I'm guessing the Window level event listeners are only used for touch events. 

This may cause problems in the future ... 
<pre>
Window.prototype.realAddEventListener =
  HTMLAnchorElement.prototype.addEventListener;

Window.prototype.addEventListener = function(a, b, c) {
  if (a === "dragstart" || a === "dragover") {
    console.log("Prevented " + a + " listener on window");
    console.log(b);
  } else {
    this.realAddEventListener(a, b, c);
  }
};
</pre>

**Comment by mejackreed** [comment]
@rogerhyam thanks for raising this issue. Mirador relies on react-dnd via its react-mosaic dependency. It seems like there could be some work done upstream in react-mosaic to better isolate this, however I haven't looked into this all too much.
