### ISSUE TITLE
Manifests do now show thumbnails

### ISSUE THREAD

**Issue by GroovinChip** [ProjectMirador/mirador#2904]
Example: https://rosetest.library.jhu.edu/rosademo/iiif/rose/SeldenSupra57/manifest

In the list of manifests, it will be blank where the thumbnail should be

**Comment by mejackreed** [comment]
I think Mirador expects that the `thumbnail` `@id` is a resolvable image. In this example, `https://image.library.jhu.edu/iiif/rose%2fSeldenSupra57%2fcropped%2fSeldenSupra57.001r` does not return an image.

I'm not 100% sure if this is spec compliant but all of the examples from https://iiif.io/api/presentation/2.1/ seem to show resolvable image urls as the `@id`.
