### ISSUE TITLE
Annotation boxes remain on canvas after pagination

### ISSUE THREAD

**Issue by ewg118** [ProjectMirador/mirador#2911]
I have been using Mirador for at least two years and have known about a long-running problem that I have never reported. I have verified this is a problem in 2.7 and whatever code is most current in the master branch.

When annotations are currently present on a canvas, paging to another canvas that does *not* have an annotation on it, the rectangle for the annotation stays on the screen for subsequent canvases until one is finally loaded that has a fresh set of annotations. Note that the content of the annotation isn't present (no popup window when hovering), only the rectangular box. It can be reproduced by following:

First: go to http://numismatics.org/mirador/?manifest=http://numismatics.org/archives/manifest/nnan187715 and enable the annotations.

There will be annotations on the first two pages in the manifest, Loose 1 and Loose 2. Click the next page arrow button or the thumbnail image for Loose 3, and you will see the box appear again. Click back or click forward to Page 1 until the canvas resets with new annotations.

I should note that my use cases rely on loading mirador.min.js and the CSS file from build. Mirador isn't being run as a nodejs instance. Please let me know if that itself is the problem.

**Comment by mejackreed** [comment]
I hope that this is resolved for you in Mirador 3 @ewg118 . However, I noticed that by default annotations from numistatics.org referenced here will not display, as Mirador 3 filters by motivation.

http://numismatics.org/archives/manifest/nnan187715/list/nnan0-187715_X006

`/s/motiviation/motivation`

**Comment by ewg118** [comment]
What do you mean by motivation? The annotations follow the Embedded Content spec: https://iiif.io/api/presentation/2.0/#embedded-content

**Comment by mejackreed** [comment]
In the linked example:
```json
{
  "@id": "http://numismatics.org/archives/manifest/nnan187715/list/nnan0-187715_X006",
  "@type": "sc:AnnotationList",
  "resources": [
    {
      "@id": "_:an_f0112d8e3cebcd8fb1125b482e38d777",
      "@type": "oa:Annotation",
      "motiviation": "sc:painting",
      "resource": {
        "@id": "_:an_f0112d8e3cebcd8fb1125b482e38d777#1",
        "@type": "cnt:ContentAsText",
        "chars": "<a href='http://numismatics.org/pella/id/price.4' target='_blank'>Price 4</a>",
        "format": "text/html",
        "language": "en"
      },
      "on": "http://numismatics.org/archives/manifest/nnan187715/canvas/nnan0-187715_X006#xywh=185,367,89,54"
    },
...
```
The json key `motiviation` has a typo and should be `motivation`. Mirador 3 filters annotations by displayable motivation and these are discarded.

**Comment by ewg118** [comment]
OK, thanks. I just fixed the typo.
