### ISSUE TITLE
Consider containing Material UI styling overrides to the mirador components

### ISSUE THREAD

**Issue by kennethsn** [ProjectMirador/mirador#2913]
Hi Mirador team! 👋

I am an engineer for ScienceStories.io (a proud integrator of the Mirador viewer).

### Context:
We are currently redesigning our platform with React on the front-end and as we started building our new integration with Mirador, we noticed that the React Material-UI package is a shared dependency between our project and yours.

### Issue:
We found that there may be some custom css styles applied for Mirador that override the default MUI styling (which look great btw!). However, the Mirador button styles now override MUI for the entire project which caused some pretty awkward UI bugs on pages which have buttons (as you could imagine, this would be all pages haha)

### Ask:
We would greatly appreciate it if we could isolate MUI button styles defined in the mirador library to just the components inside. I suspect this could be done easily with an existing scss file, and if this wasn't already scoped, I could create a pull request to give it a shot! 

Thank you so much, and again, we LOVE the work you all have been doing and can't wait to show it off in our re-launch of Science Stories next year

**Comment by charbugs** [comment]
Hi @kennethsn,

A question upfront: Are you familiar with [nested MUI themes](https://material-ui.com/customization/theming/#nesting-the-theme)?

**Comment by kennethsn** [comment]
Hi @charbugs, 
Thank you for the quick reply! 
I'm familiar with nesting themes, but still fairly a newcomer to MUI theming so definitely open to any advice.

**Comment by mejackreed** [comment]
Thanks for creating this issue @kennethsn . We definitely want to strive to have Mirador style/theming isolated.

@charbugs have you been able to isolate theming using nested themes?

**Comment by charbugs** [comment]
I think it's necessary to provide a mui theme at root level if there's another theme provider down in the component tree. this root mui theme can be the default theme or a custom theme.

Example:
```jsx
import { ThemeProvider, createMuiTheme } from '@material-ui/core/styles'
// ...

function App() {
  return (
    // the root theme provider with the default theme.
    <ThemeProvider theme={createMuiTheme()}>
      {/* uses the default theme */}
      <MyComponent/>
      {/* uses the mirador theme, because mirador has it's own (nested) theme provider */}
      <Mirador />
    </ThemeProvider>
  )  
}
```

**Comment by kennethsn** [comment]
@charbugs , thank you for explaining! 

Funny enough, this actually resembles my current integration.  Unfortunately, I can't seem to get this top-level theme to take precedent once the Mirador viewer is rendered, though.  

I used this sandbox example shared on the readme to make a Mirador react component to plug into my application:
https://codesandbox.io/s/mirador-plugin-example-pgg5k

Here's a stripped down example of my issue:
https://codesandbox.io/s/mirador-plugin-example-hdge2

If you comment/uncomment line 7 of Mirador.js, you can see the button's style go back and forth

I suspect this is because the mirador package interface is abstracted from it's underlying React components, so I don't think MUI has a way of containing the mirador theming without additional magic.

**Comment by charbugs** [comment]
> I suspect this is because the mirador package interface is abstracted from it's underlying React components, so I don't think MUI has a way of containing the mirador theming without additional magic.

You are right, that will not work.

There are two ways to integrate Mirador 3 in a React application: The one you showed in you sandbox example and another that uses the unbundled es6 modules (see https://github.com/ProjectMirador/mirador/wiki/M3-Embedding-in-Another-Environment). I assumed you would use the second solution. 

I changed you example using the second solution and it seems to work: https://codesandbox.io/s/mirador-plugin-example-hryrg

Note that there are still unsolved issues with integrating Mirador in a React application using the unbundled modules. For example, if you use Redux then you will end up having two stores in your app, which is actually [discouraged by the community](https://redux.js.org/style-guide/style-guide#only-one-redux-store-per-app). You can lift the Mirador state to your own Redux store but that may cause other trouble.

**Comment by kennethsn** [comment]
Oh wow, I never came across this Wiki! This is super helpful, and I agree the second approach is the way to go for my use case. 

I appreciate you highlighting the concern about Redux. We currently use Redux as well, so I will figure out a game-plan for that if it becomes an problem for us, but that's unrelated to this issue, so I'm satisfied with closing this ticket in favor of your solution. 

Thanks again, @charbugs (and @mejackreed) ! 
Cheers!
