### ISSUE TITLE
Plugins: Support `WindowSideBar` for 'add' mode

### ISSUE THREAD

**Issue by GroovinChip** [ProjectMirador/mirador#2918]
**Example Case:** User wants to view external resources related to the canvas currently in view
**Potential Solution:** The developer would create several components: a `WindowSideBarButton` to placed in the `WindowSideBar` and a `WindowSideBarPanel` that would be navigated to when the `WindowSideBarButton` is clicked; a custom `CompanionWindow` would be returned by the new sidebar panel. The plugin would handle fetching and displaying the external resources within this `CompanionWindow`.

**Comment by mejackreed** [comment]
Thanks for opening this issue. In a related discussion with @ggeisler we discussed various options for doing something simliar. I think there was a design goal not to continue to add additional buttons here. So making this configurable is going to be a bit larger than making it compatible w/ `add` mode.

**Comment by mejackreed** [comment]
See https://github.com/ProjectMirador/mirador/pull/3018 for resolution and an example of how this can be done.
