### ISSUE TITLE
Password re-set glitch

### ISSUE THREAD

**Issue by apn122** [ProjectMirador/mirador#2926]
Hello, I am an educator with virtually no coding experience; I use Mirador to show images in history courses. Unfortunately, I have forgotten my password, and the password reset option returns the following message: "We're sorry, but something went wrong. If you are the application owner check the logs for more information." I'm posting here in the hope of retrieving my saved collections. Thank you.

**Comment by mejackreed** [comment]
Can you please email me at pjreed@stanford.edu about this? Thanks!
