### ISSUE TITLE
[Feature Request] Allow user configuration for default sidebar panel width

### ISSUE THREAD

**Issue by GroovinChip** [ProjectMirador/mirador#2947]
We are looking to maximize our use of the Annotations panel of the sidebar and one of the things we'd like to do is be able to set the default width of the panel. A larger surface area gives us more room to work with annotations.

I have done some digging through the source code and found that the default width for panels is set in `src/components/CompanionWindow.js` at [this line](https://github.com/ProjectMirador/mirador/blob/master/src/components/CompanionWindow.js#L75). I would like to add a configuration option in `settings.js` for default panel width and pass that down to `CompanionWindow.js`. Does adding a property to `settings.js` put that value in Mirador's state, and therefore accessible via props, or do I need to do more to make that happen?

**Comment by camillevilla** [comment]
hey @GroovinChip! Adding a property `settings.js` makes it available via `state`, but I think you'll need to then map state to props to use it in a component. 

To create your setting you'll need to 
1. create a prop and plug it into the boolean you found in `src/components/CompanionWindow.js` 
2. Add that prop to `settings.js`
3. Map that state to props in the `src/containers/CompanionWindow`. 

Here's a nice compact example that @surreal8 contributed:
https://github.com/ProjectMirador/mirador/pull/2880/files#diff-09f74b447a8923de952c2fc0057b3d8bL18

**Comment by GroovinChip** [comment]
Thank you very much!

**Comment by mejackreed** [comment]
@GroovinChip is this a feature you no longer need anymore?

**Comment by mejackreed** [comment]
Gotcha 👍  Is this a feature you would like to see in Mirador? If so I think it makes sense to leave the issue open.

**Comment by GroovinChip** [comment]
It would certainly be nice to have, it's just outside of our scope in the sense that we can't spare the time for me to contribute directly to Mirador for this. I'll reopen.
