### ISSUE TITLE
Consider unifying terminology for CompanionWindow and SidebarPanel

### ISSUE THREAD

**Issue by camillevilla** [ProjectMirador/mirador#2951]
See @ggeisler and @jvine's [UI map](https://github.com/ProjectMirador/mirador/wiki/M3---UI-map). 

![UI map displaying thumbnail navigation at the bottom](https://user-images.githubusercontent.com/6945691/53903423-88bc6c80-3ff8-11e9-8983-974eec5fcc97.png)

On the component level, we refer to these movable content areas (16,18) as `CompanionWindow`s . However, in the settings we refer to these as `panel`s.
https://github.com/ProjectMirador/mirador/blob/b5fd191f6d6a0a9cc5955256e234111a5d828ef1/src/config/settings.js#L225-L236

Before releasing Mirador 3, would it be worth renaming `CompanionWindow` to `Panel`? This might make it easier for newer contributors to find the component they need.

**Comment by mprove** [comment]
Is this a documentation issue?
b/c I cannot find "CompanionWindow" in the user interface.

**Comment by mejackreed** [comment]
It is a component naming issue in the codebase.
