### ISSUE TITLE
Clicking on the 'Change Layout' button in the main menu bar inactivates the 'close thumbnail tray' button.

### ISSUE THREAD

**Issue by stephanpauls** [ProjectMirador/mirador#2983]
Hi,

If you use the 'Change layout' button in the main menu bar to add windows, the  'close thumbnail tray' buttons of the already existing windows will be blocked.

Regards,

Stephan

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
