### ISSUE TITLE
Any views on a release for version 3

### ISSUE THREAD

**Issue by baptiste-roussot** [ProjectMirador/mirador#2997]
Just wondering if you have some visibility on when a first release of version 3 could be published ?
Currently using the in developement version, I'd like to know (if possible) when I can use a 3.x release.

**Comment by mejackreed** [comment]
Hi @baptiste-roussot . Thanks for using the development version of Mirador. The latest version just released is https://github.com/ProjectMirador/mirador/releases/tag/v3.0.0-beta.7 . We are hoping for a final beta release in the next few weeks.

**Comment by baptiste-roussot** [comment]
Hi, thanks for the answear, few weeks would be great, I'm waiting for it !
