### ISSUE TITLE
Indicate first or last image in next/previous buttons

### ISSUE THREAD

**Issue by rsinghal** [ProjectMirador/mirador#300]
They already don't do anything when clicked, but appear clickable.  Make it clearer to the user that the button won't do anything and is not clickable.

**Comment by rsinghal** [comment]
Not hiding the previous button if you load directly into ImageView from window settings.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
