### ISSUE TITLE
Canvases without image's service breaks BookView

### ISSUE THREAD

**Issue by regisrob** [ProjectMirador/mirador#3006]
BookView is broken with Manifests that does not have image's `service` on a Canvas. 
When switching to BookView, Mirador throws the error `Uncaught TypeError: Cannot read property 'id' of undefined` (infoResponse.js?:75).

Fixtures from the IIIF Cookbook:
- https://preview.iiif.io/cookbook/0009-book-1/recipe/0009-book-1/manifest.json
- https://preview.iiif.io/cookbook/0010-book-2-viewing-direction/recipe/0010-book-2-viewing-direction/manifest-rtl.json
- https://preview.iiif.io/cookbook/master/recipe/0001-mvm-image/manifest.json

(the first two of them at least should be fixed soon)

**Comment by cbeer** [comment]
@regisrob do you know  if the image urls in those manifests are supposed to work?

https://iiif.io/api/image/3.0/example/reference/59d09e6773341f28ea166e9f3c1e674f-gallica_ark_12148_bpt6k1526005v_f19/full/max/0/default.jpg

In v3.0.0-beta.8, I'm not  seeing that type error, only an error loading the images.

**Comment by regisrob** [comment]
@cbeer I think so. It's weird because they used to work, and they are supposed to since they are hosted as fixtures for the official IIIF Cookbook. So It seems like a problem for @glenrobson (see also this broken page: https://fixtures.iiif.io/info.html?file=/images/BnF/12148_bpt6k1526005v/gallica_ark_12148_bpt6k1526005v_f19.jpg)

**Comment by glenrobson** [comment]
The images above should work now. There is a deployment problem with the reference image server which I'm looking into.

**Comment by cbeer** [comment]
Thanks. Ok, I'm seeing the same problem now.
