### ISSUE TITLE
M3 does not display static thumbnails for some Manifests

### ISSUE THREAD

**Issue by regisrob** [ProjectMirador/mirador#3038]
M3 seems to have a problem displaying canvas' thumbnails without an image service. I've already faced this issue while working on a recipe for the IIIF cookbook, but I've fixed the Manifest in the meantime by adding a thumbnail's service... 
There are other fixtures Manifests from the cookbook that have the same issue (see [this one](https://github.com/IIIF/cookbook-recipes/blob/0010-book-2-viewing-direction/recipe/0010-book-2-viewing-direction/manifest-rtl.json) by @triplingual), but unfortunately the IIIF service on iiif.io is currently broken...

Otherwise I have this sample Manifest to test with (https://regisrob.fr/iiif/manifest/Dioscoride_Codex_vindobonensis). The thumbnails are not displayed at all in M3 (in Gallery view nor in the Thumbnail list)

```
"thumbnail":
  {
     "@id": "https://species-id.net/o/media/thumb/8/81/62-Dioscoride_A.jpg/100px-62-Dioscoride_A.jpg",
    "@type": "dctypes:Image",
    "format": "image/jpeg",
    "height": 119,
    "width": 100
}
```

But this one works fine (https://gallica.bnf.fr/iiif/ark:/12148/btv1b10500687r/manifest.json), thumbnails are displayed as expected:
```
"thumbnail": {
  "@id": "https://gallica.bnf.fr/ark:/12148/btv1b10500687r/f1.thumbnail"
}
```

**Comment by mejackreed** [comment]
@regisrob this seems to now be resolved in `master`. Can you confirm?

**Comment by regisrob** [comment]
Yes it is, @mejackreed ;), except that it does not render the static thumbnail itself in some situations, i.e. when a Canvas just has a url string in `thumbnail` or `thumbnail['@id']` and the canvas' image has a IIIF service, which makes totally sense from M3's point of view (in that it does not want to "trust" what can be found at this url, and also for UI consistency in gallery view, thumbnails list etc.). It's just that it's a little bit of a problem when the static thumbnail turns out to be (or is designed to be) faster than a IIIF request to `/full/,120/`. This makes a noticeable difference with Gallica manifests, but I guess it is something that should be reworked in their manifests by providing a level 0 service for thumbnails or anything else that will be recommended in a future Thumbnails cookbook recipe)
