### ISSUE TITLE
Controlling the starting position and order of windows in M3.

### ISSUE THREAD

**Issue by jpadfield** [ProjectMirador/mirador#3041]
Sorry if I have missed it. 

Is there a way to define the starting position and order in which multiple windows appear in Mirador 3, defining specific rows and or columns a bit like in Mirador 2?

The example I would like to adjust is: https://jpadfield.github.io/simple-mirador/Complex%20Example.html

Thanks

Joe

**Comment by mejackreed** [comment]
I've added the answer and an example to the faq here: https://github.com/ProjectMirador/mirador/wiki/M3---Mirador-3-Frequently-Asked-Questions#q-how-can-i-control-the-starting-position-and-order-of-windows-in-mirador-3

**Comment by jpadfield** [comment]
Thank you for the example, however the logic of the process still did not seem to be completely clear. I have spent a while playing with it and looking into the code and finally got it to work.

I wondered if the following example might also be useful  to others (I have selected images to try to relate to the IDs :-) )

Joe


```
windows: [
    { "id": "a",
    "manifestId": "https://media.ng-london.org.uk/iiif/000-04SP-0000/manifest.json" },
  { "id": "b",
    "manifestId": "https://media.ng-london.org.uk/iiif/000-0176-0000/manifest.json" },
  { "id": "c",
    "manifestId": "https://media.ng-london.org.uk/iiif/000-03UK-0000/manifest.json"},
{ "id": "d",
    "manifestId": "https://media.ng-london.org.uk/iiif/000-0BW4-0000/manifest.json" },
 { "id": "e",
    "manifestId": "https://manifests.britishart.yale.edu/manifest/54347" },
  { "id": "f",
    "manifestId": "https://media.ng-london.org.uk/iiif/000-05LR-0000/manifest.json"}
  ],
  workspace: {
    layout: {
      direction: "row",
      first: {
        first: "a",
        second: "d",
        direction: "column"
      },
      second: {
        first: {
          first: "b",
          second: "e",
          direction: "column"
        },
        second: {
          first: "c",
          second: "f",
          direction: "column"
        },
        direction: "row"
      },
      splitPercentage: 33.33
    }
  }```

**Comment by mejackreed** [comment]
Thanks so much for that feed back @jpadfield . I've updated the example and wiki with your excellent example.
