### ISSUE TITLE
Enable annotation highlighting via canvas

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#3058]
I think this has been generally discussed but I'm not sure has been ticketed so...

Currently, annotation highlighting can only be done via the "Highlight all" option and navigating (mouse hover and keyboard focus) annotations in the Annotation sidebar. I think we might also want to enable annotation highlighting via hovering over the annotation target on the canvas, when the "Highlight all" option turned on.

Currently, if the user has the "Highlight all" option turned on, all annotation targets are highlighted in blue (by default) on the canvas, but by design there is no corresponding highlighting of the annotations in the sidebar. This new requirement would recognize when the user has hovered over a canvas target and _highlight_ (not _select_) the corresponding annotation in the Annotation sidebar. When the user moved off the canvas target, the sidebar annotation highlight would be removed (similar to how the highlighting works as the user hovers over and then moves past an annotation in the sidebar).

The value of this is it would enable the user to quickly explore the visible canvas annotation targets and see each target's corresponding annotation text in the sidebar.

There might be some additional design needed (for example, do we need to support keyboard accessibility for this feature by making the canvas targets keyboard accessible) but for now I just want to add this ticket for potential discussion of details, objections, etc.

**Comment by cbeer** [comment]
Some questions:
- what's the behavior with multiple annotations that cover the same point?
- do we scroll the annotation companion window to show the newly highlighted annotation (and, again, what to do with multiple..)
- I wonder if we need click-to-select behavior?

Canvas targets are not keyboard accessible (and effectively can't be.. as far as the browser is concerned, there's nothing there except an image).

**Comment by ggeisler** [comment]
Good questions. I was trying to avoid the click-to-select to keep the interaction the same as in the Annotation sidebar, but you're right, the multiple annotations associated with the same target scenario complicates that, even if we do add some automatic sidebar scrolling (no guarantee any annotations beyond the first one will be visible in the scrolled window).

So we might have to go with click-to-select after all. 

Click to select a target. Scroll the sidebar if necessary to put the associated annotation at the top of the sidebar window. Maybe add a small notification at the bottom of the sidebar to indicate when there are other annotations associated with the target, so the user knows there is also something to manually scroll to see? 

I'll discuss with @jvine and see if we can provide a good answer to this.
