### ISSUE TITLE
Add info on how to override default view types

### ISSUE THREAD

**Issue by camillevilla** [ProjectMirador/mirador#3070]
Setting up some Mirador demos. To set a default gallery view, override `window`: `views` like so: (remove `behaviors`).
```
       window: {
        defaultView: 'gallery',
        views: [
          { key: 'single'},
          { key: 'gallery' }
        ],
```
Figure out where to throw this in documentation later...

**Comment by mejackreed** [comment]
Is this answered here? https://github.com/ProjectMirador/mirador/wiki/M3---Mirador-3-Frequently-Asked-Questions#q-how-can-i-enable-book-view-for-manifests-that-are-not-specified-as-paged
