### ISSUE TITLE
Accessibility audit: headings for info panel sections

### ISSUE THREAD

**Issue by cbeer** [ProjectMirador/mirador#3108]
> The headings "Current item/Object" (or "Left" and "Right"), "Resource/Resource" and "Related/Similar" are only tagged with span elements.
> Here semantic heading elements h4 should be used for marking. Alternatively, the caption could also be integrated into the button element of the respective pop-up button.

**Comment by jvine** [comment]
Making the `<span>` section names into `<h4>` seems completely reasonable. There are nested `<h4>` within these sections that will need to be changed to `<h5>`. If we do that without changing the typography classes, then there's no visual change but better structure. (And making sure to retain the current click behaviour where you can click on the section title to expand/collapse as well as the button.)

<img width="297" alt="Screen Shot 2020-06-16 at 11 52 36 AM" src="https://user-images.githubusercontent.com/6945691/84815793-66b9e400-afc8-11ea-9a0b-1a74848c9aa8.png">

I also think we should add `aria-expanded="true/false"` to the button. Report doesn't mention it explicitly in this context, but it's valid.

> Alternatively, the caption could also be integrated into the button element of the respective pop-up button.

I'd prefer to keep the control separate from the section title. The section name is already incorporated in the button label. (E.g. "Expand resource section")
