### ISSUE TITLE
init experience : improve "addItem"

### ISSUE THREAD

**Issue by mprove** [ProjectMirador/mirador#3182]
Currently, during Mirador's init phase  a plus and "addItem" is displayed in the main view. 
What's the purpose of this message? Who should react in what way if most of the time the IIIF content will be displayed pretty soon.
I guess there is room for improvement.

Suggested new behaviour:
1) Do not display misleading messages if content is being loaded. Display nothing or if loading takes more than a moment display a progress spinner.
1a) Idea: Does Mirador have an logo? This might be the spot to briefly display a logo and a version number.

2) If no content is loaded then display a meaningful message.
2a) Is this a drop area? Then the '+' makes sense. Can it be clicked? Then it might be an idea to add a flavour of a button.
2b) "addItem" looks like an engineering string. Do we have terminology guidelines? "Add Item…" or "Add item…" would be better.
2c) What is an item, anyhow? Can we provide info what kind of items can be added?

**Comment by ggeisler** [comment]
@mprove Thanks for creating this ticket. Can you provide some screenshots to clarify where in the application you are referring to? It's not clear, at least to me. (I assume you are referring to Mirador version 3, which is completely different than Mirador 2, but screenshots would also clarify that.)

**Comment by cbeer** [comment]
Hi @mprove -- I see your issue came in without the Mirador2 or Mirador3 label. Could you let us know what version of mirador you're asking about and/or include a screenshot or GIF capture so we're on the same page?

**Comment by mprove** [comment]
e.g. Harvard Collection https://id.lib.harvard.edu/digital_collections/990123374870203941

![Mirador-Harward-Init](https://user-images.githubusercontent.com/1712125/86294653-49565e00-bbf5-11ea-8b38-39ddf8fa3c9e.jpg)

BTW I cannot assign labels.

**Comment by mejackreed** [comment]
Thanks for filing this and providing screenshots @mprove . I think a lot of the community agrees with you and thus our significant user experience changes in Mirador 3. See https://mirador-dev.netlify.app/__tests__/integration/mirador/ for the latest look of it. I think Harvard may be using a customized fork of Mirador 2 in these screenshots, but maybe @rsinghal or @cgoines could confirm?

We are not maintaining Mirador 2 any longer, and most of our future efforts are on improving Mirador 3.

**Comment by cgoines** [comment]
Hi Jack - we are using a standard fork of M2 with our own customizations outside of the main code base. Having said that, we do plan on moving to Mirador 3 this fall and will not be using M2 going forward.
