### ISSUE TITLE
UI RFE: provide feedback for new resource

### ISSUE THREAD

**Issue by mprove** [ProjectMirador/mirador#3186]
- add a new resource /screenshot1
=> no feedback is provided that the new resource has been added successfully (the list of resources just shows a brief flick) /screenshot2

Therefore:
- scroll the new resource into view and highlight the item

![mirador3-addresource1](https://user-images.githubusercontent.com/1712125/86330026-59972900-bc47-11ea-9e50-388e74cc183c.jpg)
![mirador3-addresource2](https://user-images.githubusercontent.com/1712125/86330049-6156cd80-bc47-11ea-9244-3b7831257eee.jpg)

**Comment by ggeisler** [comment]
Related to #2126 where similar behavior was suggested but it seemed like we needed to wait on something. Perhaps some references in that ticket will help us figure out where we are with this goal.
