### ISSUE TITLE
Bug on nav controls in Book view

### ISSUE THREAD

**Issue by regisrob** [ProjectMirador/mirador#3209]
I've noticed a strange bug while checking [this Manifest](https://preview.iiif.io/cookbook/0009-book-1/recipe/0009-book-1/manifest.json) in the latest v3.0.0-rc.3 (seems to me that it used to work fine in one of the previous M3 release).

To reproduce:
- open the Manifest in a mirador window (the images are displayed in Book view by default)
- click on the "next" button once or several times to browse through the canvases
- now click on the "prev" button: you can't go back in the canvas sequence, clicking on "next" has no effect, except that the counter is being updated (3 of 5, 2 of 5 etc.), so you're stuck on the last view.

Is there a problem with this Manifest specifically?

Environment:
MacOS 10.13.6, Firefox 79.0b5 and Chrome 83.0.4103.116

**Comment by cbeer** [comment]
Thanks -- looks like an issue with image v3 APIs.

**Comment by regisrob** [comment]
👍 thanks
