### ISSUE TITLE
Mirador3 javascript options

### ISSUE THREAD

**Issue by ydvelaitzky** [ProjectMirador/mirador#3212]
Hi
Where can I find a detailed documentation about how to use the mirador3 , to embed it in my application. I see some of the options to setup the mirador object, like  "id","windows", "workspace" etc, as shown in https://github.com/ProjectMirador/mirador/wiki/M3---Mirador-3-Frequently-Asked-Questions, so that I need to dig and find what I look for. If I need some events like onInit  or imageChanged , Is there any place that details all of the mirador setup options and parameters in javascript   ?
Thank you!

**Comment by mejackreed** [comment]
The file `settings.js` is a comprehensive list of settings used throughout Mirador 3. I recommend using that as a starting point.

https://github.com/ProjectMirador/mirador/blob/master/src/config/settings.js

While this file is the best place to get started it doesn't fully express everything available.

Mirador 3 also doesn't use events, it uses redux actions. You can subscribe and dispatch actions the full list of those are available here: https://github.com/ProjectMirador/mirador/blob/master/src/state/actions/action-types.js

**Comment by ydvelaitzky** [comment]
Hi
Perhaps something very fundamental in embedding Mirador is not clear enough for me:
In anothrer issue I've opened before (https://github.com/ProjectMirador/mirador/issues/3205) – you  have answered that we can use the mirador.js file alone , In that case how  will we use the settings.js ? The mirador.js does not references that file.
Are there 2 different type of embedding mirador, one by using single mirador.js file , and the other is by using the whole opened pack of the mirador files (included js,css and much more)? If so, Can I use the whole pack of the files in a HTML document with javascript (and not in react app)?  And which file my html will reference from all those files?
 – I would thank you very much to let me understand it, and to organize my mess…

**Comment by mejackreed** [comment]
Ah thanks for clarifying the question some more. 

You can use Mirador's `dist/mirador.min.js` file to get the [umd](https://github.com/umdjs/umd) build version of Mirador. Then you can use the settings from `settings.js` mentioned to initialize Mirador with customized options or themes.

There is an example here: https://glitch.com/edit/#!/mirador-start?path=index.html

**Comment by ydvelaitzky** [comment]
Can you please let me understand how to subscribe and dispatch an event via **mirador instance** in umd version?
maybe something like :` miradorInstance.store.subscribe(....what arguments to send here?....)`
or: ` miradorInstance.store.dispatch(.... and what here? ....)`
I read the documentation in https://github.com/ProjectMirador/mirador/wiki/M3-State-Management:-Reducers,-Actions,-Events 
but it seems like it talks about doing it in a react app, not in umd

Also in this doc there is line like the following :
`import { createTableReducer, createSingeltonReducer } from './createReducers';`
In my mirador installation (mirador@3.0.0-rc.5) there is no file by the name of: 'createReducers'.
Where can I find that file in my installed version?

Thank you
