### ISSUE TITLE
Image manipulation in mirador3?

### ISSUE THREAD

**Issue by ydvelaitzky** [ProjectMirador/mirador#3214]
In mirador 2.7 there is a usefull feature named: "Image manipulation", included rotating ,adjust contrast and brightness, invert colors etc
The question is if mirador3-rc has also that feature? I didn't see it in its demo (https://mirador-dev.netlify.app/__tests__/integration/mirador/)

Thank you!

**Comment by mejackreed** [comment]
In Mirador 3 this feature is in a plugin, [mirador-image-tools](https://github.com/ProjectMirador/mirador-image-tools).

You can see a demo of it here: https://mirador-image-tools.netlify.com/

**Comment by ydvelaitzky** [comment]
Tank you very much!
The mirador-image-tools package doesn't contain the dist folder as shown in https://unpkg.com/browse/mirador-image-tools@0.8.0/ . Reference to the only https://unpkg.com/browse/mirador-image-tools@0.8.0/umd/mirador-image-tools.js  file  (or its "min" version) - can not be embedded correct  in my html and javascript project (not react). Can you let me know how to embed that mirador-image-tools package in my app?

**Comment by mejackreed** [comment]
Yes thanks for mentioning this. It seems like we may need to provide a different option for users of plugins who are using the umd builds. Perhaps this is also related to #2260? I'll look into this.

**Comment by ydvelaitzky** [comment]
The  mirador-image-tools plugin must have a dist folder, as its' js files import modules from dist folder hard-coded, for example- the "miradorImageToolsPlugin.js" 's first line is: import * as actions from 'mirador/dist/es/src/state/actions';

So,  will you be able to tell me how can I install a complete umd version of The  mirador-image-tools plugin, contains the build folder, or how can I create it by myself?
Thank you again.

**Comment by ydvelaitzky** [comment]
Will you be able to tell me where can I download a complete umd version of The  mirador-image-tools plugin, contains the build folder, or how can I create it by myself?

**Comment by mejackreed** [comment]
Please checkout this repository: https://github.com/ProjectMirador/mirador-integration

It has a basic setup of mirador-image-tools here: https://github.com/ProjectMirador/mirador-integration/blob/master/src/index.js

And options to get up and going using webpack or parcel
