### ISSUE TITLE
Multiple independant Mirador instances

### ISSUE THREAD

**Issue by guillaumer** [ProjectMirador/mirador#3215]
Hello,

According to the mirador-start glitch (https://glitch.com/edit/#!/mirador-start?path=index.html), we can observe that the first Mirador instance (id "_mirador_") is directly impacted by the second Mirador instance (id "_mirador2_") upon its loading. 
This is something I have also experienced while trying to integrate it in a very different environment. If we remove the second initialization code, the first window acts very differently.

I'm not too sure how this is a normal and expected behavior and if so, what is the way to create multiple completely independent Mirador instances in separate elements?

Thanks.

**Comment by mejackreed** [comment]
Thanks for reporting this bug @guillaumer . This is also present here: https://mirador-dev.netlify.app/__tests__/integration/mirador/embedding.html
