### ISSUE TITLE
Is there a way to specify tooltip text for custom WindowSideBarButtons?

### ISSUE THREAD

**Issue by jabrah** [ProjectMirador/mirador#3225]
I have been playing around with a custom CompanionWindow plugin, along with a custom WindowSideBarButton to add to he window sidebar. Almost everything seems functional, except I cannot quite figure out if I can use a custom tooltip for the button. Currently, the newly added button uses a generic tooltip of `openCompanionWindow`, seen in the screenshot

![image](https://user-images.githubusercontent.com/5167587/88089946-dc324a80-cb5a-11ea-95aa-d57e088e977e.png)

Here's my testing repo, if the code is at all helpful: https://github.com/jabrah/mirador-side-panel-plugin-test

**Comment by mejackreed** [comment]
Yes, you should be able to use i18next "Context" functionality: https://www.i18next.com/translation-function/context to specify a translation key. 

For instance, similar to here: https://github.com/ProjectMirador/mirador/issues/3020 updating the config with a new translation that has the key:

`openCompanionWindow_CustomKey1` I think would be what you want.

**Comment by jabrah** [comment]
Awesome, that worked. To document this workaround:

### Problem
 As described above, a plugin adds a custom WindowSideBarButtons, but was unable to directly specify the rendered tooltip. 

### Solution
(Note this is my sort of naive understanding)

Mirador looks for a specific i18next translation key for the tooltip, in my case specifically it looked up `openCompanionWindow_CustomKey1`. We can add this translation key to Mirador in our instance's configuration. Some example code:

_MyButtonPlugin.js_
``` javascript
import React from 'react';

const CustomButton = () => (
  <span id="custom-side-panel-a-button">😀</span>
);
CustomButton.value = 'CustomKey1';

export default {
  target: 'WindowSideBarButtons',
  mode: 'add',
  component: CustomButton
};
```

In the plugin, note the value property inserted added to the `CustomButton` component. This is the value used in the translation key that Mirador fetches for the button's tooltip.

_index.js : this is where we define and configure our Mirador instance with our plugin_
``` javascript
import Mirador from 'mirador';
import MyButtonPlugin from '<wherever_this_lives>';

const config = {
  id: 'demo',
  window: {
    defaultView: 'single',
    sideBarOpenByDefault: true,
  },
  windows: [
    {
      loadedManifest: '<your_manifest_here>'
    }
  ],
  translations: {
    en: {
      openCompanionWindow_CustomKey1: 'This is a moo'
    }
  }
};

Mirador.viewer(config, [ MyButtonPlugin ]);
```

You can see where we inserted our proper translation key and value. Mirador now knows about it and the tooltip should render as expected.

IMO this is an acceptable workaround that would require good documentation by the plugin. I think letting the plugin.js itself define the translation (while allowing overrides in Mirador config) would be a bit more friendly to users integrating Mirador, but ultimately instantiating M3 still requires at least a little JS knowhow. (Pure conjecture) It might be reasonable to expect an integrator to explicitly set translation keys in their M3 configuration, based on proper plugin documentation.
