### ISSUE TITLE
Initialize mirador after clear DOM element

### ISSUE THREAD

**Issue by ydvelaitzky** [ProjectMirador/mirador#3234]
Hi

The Html :
`<div id="viewer1" allowfullscreen="allowfullscreen"></div>`

The script  to init  mirador::
```
Mirador.viewer({
        id: "viewer1",
        windows: [
          {
              manifestId:
                "https://iiif.bodleian.ox.ac.uk/iiif/manifest/e32a277e-91e2-4a6d-8ba6-cc4bad230410.json"
          }
        ],
    });
```
Everything works well.
But in some case,  I need to clear  the element that the mirador exists in it, in order to display another content, instead of mirador viewer.
I do it by javascript: : 
`document.getElementById('viewer1').innerHTML = "";`
But then, when I want to redisplay the mirador by running the above code that inits the viewer, I have some javascript  errors:
TypeError: Cannot read property 'appendChild' of null
TypeError: Cannot read property 'innerTracker' of undefined
Digging into the mirador code in order to get more details about that error is difficult, as I use the minimized code
Am I doing something wrong? 

Thank you very much for your support!

**Comment by mejackreed** [comment]
I think this might be due to hanging on references of the mirador instance to the dom. Something like this works for me:

```javascript
let viewer = document.getElementById('viewer1');
viewer.parentNode.removeChild(viewer);
viewer = null;
let elem = document.createElement('div')
elem.id = "viewer1"
document.body.appendChild(elem)
// reinitialize mirador
```

**Comment by ydvelaitzky** [comment]
Thanks !
After changing the code to what you've offered above - It still occurs.
you can see the js errors in[ that sample.](https://fjmstest.genizah.org/Temp/testMirador.html) click on one of the buttons to discover the problem...
Any idea?

**Comment by mejackreed** [comment]
Can you also initialize Mirador to a variable that can be released?

```javascript
let viewerInstance = Mirador.viewer({...});
// when removing
viewerInstance = null
// when reinitializing
viewerInstance = Mirador.viewer();
```

**Comment by mejackreed** [comment]
@ydvelaitzky we added a new function that can help here in #3286 .. see that implementation which can help out when tearing down an instance.

**Comment by ydvelaitzky** [comment]
I updated mirador package to insert your fix.
And the js error does not occur anymore. 
But now there is a little problem - the navigation area (mirador-osd-navigation) is hidden after reload mirador.
The [sample](https://fjmstest.genizah.org/Temp/testMirador.html) that we've created before contains the updated version, so that you can see this problem there.
Can you help us? Thanks!

**Comment by mejackreed** [comment]
I'm not seeing that fix in the source code in the sample yet. If you are using Mirador v3.0.0-rc.7 here is an example of how this could work:

https://codesandbox.io/s/mirador-3-teardown-4bi6e?file=/index.html
