### ISSUE TITLE
Is it possible to init a search phrase?

### ISSUE THREAD

**Issue by Sozialarchiv** [ProjectMirador/mirador#3236]
Something like 

```javascript
 var miradorInstance = Mirador.viewer({
        id: 'mirador',
        state: {
            search: 'xyz',
        }
    });
```

**Comment by mejackreed** [comment]
Yes it is! Please see: https://github.com/ProjectMirador/mirador/wiki/M3---Mirador-3-Frequently-Asked-Questions#q-is-it-possible-to-show-search-results-directly-without-the-user-typing-in-the-search-term

Please reopen if that isn't what you are looking for.

**Comment by Sozialarchiv** [comment]
Thank you very much.
