### ISSUE TITLE
Book view: navigating to previous item displays wrong canvas (1st canvas only) 

### ISSUE THREAD

**Issue by camillevilla** [ProjectMirador/mirador#3240]
Reported by Astrid Smith, Stanford University Libraries

To replicate:
1. Open a manifest in book view ([Example: Wunder der Vererbung](https://wellcomelibrary.org/iiif/b18035723/manifest)). You should see 1 canvas.
2. Navigate to the next item. You should see 2 canvases.
3. Navigate to the previous item. You should now see 2 canvases: the 1st and 3rd canvases stitched together.

![navigation demo](https://user-images.githubusercontent.com/5402927/89846216-6f94e500-db35-11ea-99d8-d0d68a67bbe8.gif)

**Comment by cbeer** [comment]
Looks like a regression introduced by https://github.com/ProjectMirador/mirador/pull/3197  -- lodash's merge will deep merge  arrays too. ugh.
