### ISSUE TITLE
Book view pagination problem for Internet Archive IIIF manifests

### ISSUE THREAD

**Issue by amandelman** [ProjectMirador/mirador#3244]
When using book view with IIIF manifests from the Internet Archive, some pagination error results in displaying the pages with the spine on the outside edge instead of in the middle. It looks like this could be because IA inserts an extra cover page showing calibration marks, which then throws off the pagination sequence, but I'm not sure.

Example manifests:

- https://iiif.archivelab.org/iiif/americabeinglate00mont/manifest.json
- https://iiif.archivelab.org/iiif/siguenseunosbrev01gilb/manifest.json
- https://iiif.archivelab.org/iiif/arteyvocabulario00unkn/manifest.json

**Comment by camillevilla** [comment]
@amandelman Unfortunately this would be something to bring up with the Internet Archive. Viewers like Mirador and [Universal Viewer](https://universalviewer.io/uv.html?manifest=https://iiif.archivelab.org/iiif/americabeinglate00mont/manifest.json#?c=0&m=0&s=0&cv=4) are taking their cue from the `viewingHint: paged` in these manifests. 

> `paged`: Valid on manifest, sequence and range. Canvases with this viewingHint represent pages in a bound volume, and should be presented in a page-turning interface if one is available. The first canvas is a single view (the first recto) and thus the second canvas represents the back of the object in the first canvas.
Source: [Presentation 2.1: viewingHint](https://iiif.io/api/presentation/2.1/#viewinghint)

To fix this, IA would need to add some additional IIIF metadata to their manifests to make sure the 2nd page appears as an individual canvas. @mekarpeles works on IA's IIIF stack, but I'm not sure where they're tracking feedback like this.

**Comment by camillevilla** [comment]
If you're looking for a more aesthetic workaround in your application, some ideas include: 
- instruct Mirador to open the work in single page view beginning with `canvasId:1`
- grab the `thumbnail` image for browsing in a containing application (we use this approach in [the Parker Library](https://exhibits.stanford.edu/parker/catalog?f%5Bformat_main_ssim%5D%5B%5D=Archive%2FManuscript&q=&search_field=search), where the curator selected non-first canvases and encoded them as the manifest's `thumbnail`)

**Comment by mekarpeles** [comment]
Thanks for the tag @camillevilla and @amandelman! Looking into it :)
