### ISSUE TITLE
Triggering a canvas change via Javascript (eventEmitter?)

### ISSUE THREAD

**Issue by ewg118** [ProjectMirador/mirador#3251]
I am working on migrating from Mirador 2 to 3, and there's been a change in the way a new canvas is loaded by clicking a link/button elsewhere in the page (not in Mirador). My use case is that I have an index of annotated terms, and I want a user to be able to click on a page number next to the index term to trigger Mirador to change the canvas and reload the annotations for that page (see http://numismatics.org/archives/ark:/53695/nnan187715).

The code I wrote for Mirador 2 is this:

    myMiradorInstance = initialize(miradorURI, manifestURI, canvasID, publisher);
    //pagination for index
    $('.page-image').click(function () {
        if (myMiradorInstance.saveController.slots[0].window.id) {
            var windowID = myMiradorInstance.saveController.slots[0].window.id;
            var canvasID = $(this).attr('canvas');
            myMiradorInstance.eventEmitter.publish('SET_CURRENT_CANVAS_ID.' + windowID, canvasID);
            myMiradorInstance.eventEmitter.publish('updateAnnotationList.' + windowId);
        }
        return false;
    });

This function gets a canvasId from the `canvas` element for a .page-image link, which sends an update to the Mirador window. Is there anything equivalent to the eventEmitter in Mirador 3? The last issue that references eventEmitter is for Mirador 2.7: https://github.com/ProjectMirador/mirador/issues/1541

**Also**: what's the option to make all of the annotations visible by default?

**Comment by mejackreed** [comment]
Thanks for the question @ewg118 .

I've added in entry in the FAQ about how to do this: https://github.com/ProjectMirador/mirador/wiki/M3---Mirador-3-Frequently-Asked-Questions#q-how-do-i-programmatically-set-the-canvas

Mirador 3 has moved away from rolling its own event system to using redux state to handle things. Many of the events have redux corollaries and we have found this quite robust in our own custom uses so far. 

All of the configuration options are available https://github.com/ProjectMirador/mirador/wiki/M3---Mirador-3-Frequently-Asked-Questions#q-where-can-i-find-all-of-the-available-configuration-options

And I think the `forceDrawAnntoations` is what you need: https://github.com/ProjectMirador/mirador/blob/master/src/config/settings.js#L263 . You will also need to update your theme annotations `hidden` to a `globalAlpha` that is visible (`1` should work). https://github.com/ProjectMirador/mirador/blob/master/src/config/settings.js#L64

**Comment by ewg118** [comment]
Excellent, I was able to get everything up and running in Mirador 3. Thanks for your help!
