### ISSUE TITLE
Drawing lines on canvas

### ISSUE THREAD

**Issue by ydvelaitzky** [ProjectMirador/mirador#3253]
Hi
We need to let the user drawing a line on the image that displayed in the canvas, so that he will see a tooltip hover that line with its' length in cm (computed by the image dimension metadata and the displayed image dimensions and the drawn line length)

Also we need a way to draw a line (or rectangle) programmability.
Does Mirador 3 have that functionality?

Thanks!

**Comment by mejackreed** [comment]
[mirador-annotations](https://github.com/ProjectMirador/mirador-annotations/) has the ability to draw line and rectangle annotations. However we removed hover popups for user experience concerns. You could create this functionality in a custom plugin though.

**Comment by jvine** [comment]
Is this use case maybe more about the dimensions/measurement aspect? Like a ruler plugin?

**Comment by ydvelaitzky** [comment]
Interesting... 
The mirador-ruler does not have any README.md file or a link to demo.
Can you tell me what is it for?

**Comment by mejackreed** [comment]
Its a plugin that aims to provide real world measurements for images.

See an example here: https://agitated-turing-9ac6ed.netlify.app/

Repo here: https://github.com/ubleipzig/mirador-ruler-plugin

Maybe @glefi can provide more details?

**Comment by camillevilla** [comment]
Here are some examples of ruler plugins from Mirador 2: https://github.com/ProjectMirador/mirador/issues/305

**Comment by ydvelaitzky** [comment]
In our enterprise the metadata of the shapes that must be displayed on the canvas is sent separately from the manifest.
so we need to draw profitability lines or rectangles on the image without using the way mirador-annotaion plugin generally works
Can you help us know if  that mirador-annotaion or another plugin supports it ?
Thanks

**Comment by mejackreed** [comment]
Yes you can do this by just dispatching `receiveAnnotation` and that will automatically add them to the store.

An example of this in a plugin: https://github.com/mejackreed/mirador-tf/blob/master/TensorFlowTool.js#L96

In this plugin we use Tensorflow.js to automatically identify objects in the image and then add them to the annotation store.

**Comment by ydvelaitzky** [comment]
Yes, This plugin is exactly what we need to do in our app.
So, We've downloaded the mirador-tf project. Tried to run it , but got an error: 

> Can't resolve 'mirador/dist/es/src/lib/ManifestoCanvas

And indeed, in that mirador-tf plugin , in the TensorFlowTool.js file, Line no 3:

> import ManifestoCanvas from 'mirador/dist/es/src/lib/ManifestoCanvas';

But there is no 'ManifestoCanvas' file in mirador project.
Can you please help us know what to do in order to make this plugin working correctly?

**Comment by mejackreed** [comment]
I've just pushed an update to mirador-tf to update it to handle the API changes in the latest release of Mirador. https://github.com/mejackreed/mirador-tf/commit/ce674bbefc3952404187631e4c750dc920a83dec

**Comment by ydvelaitzky** [comment]
Thank you. Now it works.

**Comment by ydvelaitzky** [comment]
As an addition to the previos issue, the receiveAnnotation action gets an annotationJson parameter, which contains data of the x, y, w, h coordinate of the shape.
Is there a way to add an annotation of a **diagonal line** by not sending the x, y, w, h, but sending the x, y of the 2 vertices of that line?
Thanks again for helping us.

**Comment by mejackreed** [comment]
Mirador 3 supports both `FragmentSelector` and `SvgSelector`. You could use `SvgSelector` to target a specfic line on a canvas.

https://github.com/ProjectMirador/mirador/wiki/Annotation-compatibility-support

Some examples in IIIF v3: https://github.com/ProjectMirador/mirador/blob/master/__tests__/fixtures/version-3/001.json#L276-L311

**Comment by ydvelaitzky** [comment]
Thank you very much!

**Comment by ydvelaitzky** [comment]
My annotationJson looks like the following:

```
var items = [{
    id: canvasId + annotInd,
    'type': 'Annotation',
    motivation: 'commenting',
    "target": {
      "id": canvasId,
      "selector": {
        "type": "SvgSelector",
        "value": "<path xmlns=\"http://www.w3.org/2000/svg\" d=\"M5548 1800,0 300,M5548 1500,0 0\" fill=\"none\" fill-rule=\"nonzero\" stroke=\"#00bfff\" stroke-width=\"1\" stroke-linecap=\"butt\" stroke-linejoin=\"miter\" stroke-miterlimit=\"10\" stroke-dasharray=\"\" stroke-dashoffset=\"0\" font-family=\"none\" font-weight=\"none\" font-size=\"none\" text-anchor=\"none\" style=\"mix-blend-mode: normal\"/>"
        
    }
},
    body: {
      type: 'TextualBody',
      value: title
    },
  }
  ];
```
That annotation draws 2 lines on the canvas, using SvgSelector.
I am looking for a way to display a tool-tip on those lines in the canvas. (Preferable a different tool-tip for each line of the canvas)
What is the best way to implement it?
Thanks again.

**Comment by mejackreed** [comment]
Mirador removed the ability to provide tool tips as it had usability issues in the past. However, you could implement this yourself using the `hoveredAnnotationIds` slice of the `window` redux state. This would require some custom plugin programming.

**Comment by ydvelaitzky** [comment]
Can you show me an example of that implementation?
