### ISSUE TITLE
Cancel image margins in the canvas

### ISSUE THREAD

**Issue by ydvelaitzky** [ProjectMirador/mirador#3256]
Hi 
When an image is placed on the canvas, It actually does not take all canvas area, but there are wide margins on left and right sides
Can I remove theses margins, so that the canvas size should be same as the image size ? or alternatively is there a way to know the x and y position of the image within the canvas?

**Comment by mejackreed** [comment]
Well it depends, Mirador uses OpenSeadragon to "fit" the image onto the canvas (fitting by height or width). You could size the window you are using Mirador in to the same aspect ratio of the image and that should give you the desired effect.

Also several plugins add to the `OpenSeadragonViewer` component allowing access to the raw OpenSeadragon object. This would enable you to query it and use image coordinates directly in your own plugin. 

We also would invite you to come to the biweekly Mirador call if you would like to talk through some of these things or answer more in depth questions. Details are posted in the IIIF Slack #mirador channel .

**Comment by camillevilla** [comment]
@ydvelaitzky Here's information on the IIIF slack channel: https://docs.google.com/forms/d/e/1FAIpQLSdGV9QSFo8i2z1R5iIMP7B2JVhS9akHqcykWF5_y4mtWqVrBA/viewform

Our next Mirador community call will be on October 1st:
https://iiif.io/community/groups/

**Comment by ydvelaitzky** [comment]
You noted that "Also several plugins add to the OpenSeadragonViewer component allowing access to the raw OpenSeadragon object" 
Can you mention some of them, so that I will be able to add them and get image coordinates ?

**Comment by mejackreed** [comment]
`OSDReferences` concept is used to show how you can access the OpenSeadragon object.

Some examples are here: https://github.com/search?q=org%3AProjectMirador+osdreferences&type=code

Checkout https://github.com/ProjectMirador/mirador-plugin-demos/blob/f7af009c0358274576bcb7b083cdcdf16dfc21bc/src/plugins/download-image.js#L241
