### ISSUE TITLE
Painting annotations with xywh parameters (V3 Api) not correctly displayed

### ISSUE THREAD

**Issue by choje** [ProjectMirador/mirador#3265]
- I am the author or maintainer of this manifest: yes 
- URL: [https://pdnpreprod.unicaen.fr/iiif-tests/Hamilton-v3.json](https://pdnpreprod.unicaen.fr/iiif-tests/Hamilton-v3.json)
- Manifest hosting institution  : University of Caen, France

Here is the original manifest (Api V2) : [https://dvp.prtd.app/hamilton/manifest.json](https://dvp.prtd.app/hamilton/manifest.json)

The v3 manifest was generated with [Prezi 2 to 3](https://github.com/IIIF/prezi-2-to-3)

### Observed behavior
- Description: in M3, painting annotations with xywh parameters in their target values are not well-placed. xywh parameter seems to be ignored.
- Screenshots 

   - ok (manifest V2)

![hamilton-ok](https://user-images.githubusercontent.com/17949344/94010118-caad2f00-fda5-11ea-87c6-1be6120fae84.png)

  - not ok (manifest v3)
![hamilton-nok](https://user-images.githubusercontent.com/17949344/94010204-e7e1fd80-fda5-11ea-857c-e439c6829567.png)

**Comment by mejackreed** [comment]
I think this may be the case where we haven't setup support for v3 of this type of targeting. Thanks for filling an issue and hopefully we can get this resolved in the next release.
