### ISSUE TITLE
BookView in Mirador 3

### ISSUE THREAD

**Issue by daynewss** [ProjectMirador/mirador#3278]
Hello,

is there any possibility that BookView will be added to Mirador 3?

**Comment by mejackreed** [comment]
Yes "BookView" is already a part of Mirador 3. 

See:

![image](https://user-images.githubusercontent.com/1656824/95205679-f3202a80-07a2-11eb-8457-0a2be15dee4e.png)

**Comment by daynewss** [comment]
Oh, my bad :) What configuration word/option enables it? I couldn't find it in configuration :(

**Comment by mejackreed** [comment]
It should be enabled by default for manifests that have the paged viewing behavior. You can enable it for others by following this FAQ: https://github.com/ProjectMirador/mirador/wiki/M3---Mirador-3-Frequently-Asked-Questions#q-how-can-i-enable-book-view-for-manifests-that-are-not-specified-as-paged

**Comment by daynewss** [comment]
God bless you, man :) You saved another two weeks for me :D

**Comment by daynewss** [comment]
And maybe there are all config variables somewhere on github? Or somewwhere else? Because I was trying to get more configs by reversing example web pages. Or maybe you can confirm, that all of configs are here https://github.com/ProjectMirador/mirador/blob/master/src/config/settings.js ?

**Comment by mejackreed** [comment]
Yes all of the configs should be on that settings page.

**Comment by daynewss** [comment]
Thank you.
