### ISSUE TITLE
Paging on Mirador 3

### ISSUE THREAD

**Issue by daynewss** [ProjectMirador/mirador#3279]
Hello,

is Paging Pluggin or functionality will be added to Mirador 3?

**Comment by mejackreed** [comment]
Thanks for filing the issue @daynewss . Can you say more please about what you mean by paging?

**Comment by daynewss** [comment]
I mean functionality when you can select to which page you want to go, go to first/last page. Something like Universal Viewer has on the top of the working window.

**Comment by mejackreed** [comment]
Got it.. by default Mirador 3 has a few different ways to do this. Selecting the "index" companion window will enable this type of page or thumbnail navigation.
![Screen Shot 2020-10-06 at 7 42 53 AM](https://user-images.githubusercontent.com/1656824/95209487-a428c400-07a7-11eb-943b-461714f1aa8a.png)


https://mirador-dev.netlify.app/__tests__/integration/mirador/

**Comment by daynewss** [comment]
Well, yeah, but you have to go to somewhere and then select something, and then.. I mean it's quite good, but like user, I wuold like to go to page X directly from main window.
Maybe we will have to try write my own plugin for this.
Thanks

**Comment by mejackreed** [comment]
Gotcha. You can initialize the window with that companion window open by setting the `sideBarPanel` to `canvas` in the settings: https://github.com/ProjectMirador/mirador/blob/master/src/config/settings.js#L259

**Comment by daynewss** [comment]
Thanks.
I will do that.
