### ISSUE TITLE
Import of global CSS in Next.js not allowed

### ISSUE THREAD

**Issue by tarjelavik** [ProjectMirador/mirador#3282]
- Mirador version (release, commit, etc.): 3.0.0-rc.6
  - "next": "^9.5.4

Dynamically loading of Mirador3 in Next.js results in errors caused by global CSS import. There might be a webpack solution, but Next recommends asking maintainers to provide a compiled version of their dependencies (see https://err.sh/next.js/css-npm).

Error: 

```
./node_modules/react-mosaic-component/react-mosaic-component.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/mirador/dist/es/src/components/WorkspaceMosaic.js
```

**Comment by mejackreed** [comment]
Thanks for filing the issue @tarjelavik . Do you have an example repo where this issue is recreated?

I was able to recreate and resolve this issue referenced with https://github.com/ProjectMirador/mirador/pull/3283 but I don't really understand how next.js works so was not able to test how to integrate mirador in a better way.

**Comment by tarjelavik** [comment]
Sure, https://github.com/tarjelavik/next-mirador3-issue3282. Mind, i am new to Next, but their stance against global CSS seems sensible to me.
Mirador3 is such a great viewer and i would like to use it everywhere :-). So far i have only manage to get it working in a Svelte/Sapper app.

**Comment by mejackreed** [comment]
Great thanks so much for that.

Ok, so by using a local built copy of mirador with changes in #3283 everything seemed to work out. I just needed one minor change.

https://github.com/tarjelavik/next-mirador3-issue3282/compare/main...mejackreed:main

**Comment by tarjelavik** [comment]
Fantastic! Yeah, sorry about the "minor change", forgot to commit and push the last local fix...

I guess it might be part of a rc7? Do you mind me skipping a test on my end? 

I am building this monstrosity, https://github.com/seidhr/sanity-template-muna, so i have loads of other stuff to solve :-/
