### ISSUE TITLE
Manage IR-sanctioned "Default" Annotations

### ISSUE THREAD

**Issue by sdellis** [ProjectMirador/mirador#329]
Expands on #318 

As a repository curator/administrator 
I want to be able to specify annotations that will always appear with the manifest
So that I can moderate/vet a list of institutionally-sanctioned annotations (accurate transcriptions, translations, faculty annotations, etc.)

As a repository curator/administrator 
I want to be able to specify annotations that will be indexed for in-manifest or manifest-discovery search
So that users can search full-text in various languages

**Comment by mejackreed** [comment]
Is this still actionable @sdellis ? Mirador 3 supports annos that are referenced in the manifest, and a plugin can get external annos.
