### ISSUE TITLE
Clicking on items in canvas pane pushes entire viewer window up

### ISSUE THREAD

**Issue by helrond** [ProjectMirador/mirador#3302]
Clicking on a items in a canvas pane pushes the entire viewer window up.

This is cool:
<img width="1439" alt="Screen Shot 2020-10-23 at 1 52 22 PM" src="https://user-images.githubusercontent.com/607621/97037245-03702d80-1537-11eb-84a7-4f098fe793a8.png">

But this is not:
<img width="1431" alt="Screen Shot 2020-10-23 at 1 56 32 PM" src="https://user-images.githubusercontent.com/607621/97037648-927d4580-1537-11eb-9d91-9c28ac9817a0.png">

Per @mejackreed on Slack this may be a bug in the way the scroll state of canvases is saved.

**Comment by helrond** [comment]
I just noticed that this doesn't happen if you first click on the "Thumbnail list" or "Item list" icons in the canvas panel before you click on one of the items. IDK if that's helpful or a red herring? 🐟

**Comment by mejackreed** [comment]
Thanks @helrond. I've taken a look at this and haven't found a workaround yet. I'll keep digging and see if others have an idea.

**Comment by helrond** [comment]
@mejackreed I'm embarrassed I didn't check this first, but it looks like this might actually be caused by my local stylesheets overriding Mirador styling in weird ways.

**Comment by mejackreed** [comment]
Oh interesting. Similar issues exist in our instalations as well: https://purl.stanford.edu/wz026zp2442
1. Scroll page down
2. Open "item list" companion window
3. Selected canvas jumps to middle of entire window (not viewer)

**Comment by helrond** [comment]
I had generic styles applied to `section` elements which was causing the issue for me.
