### ISSUE TITLE
An issue with some IA manifest thumbnails

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#3305]
These thumbnails are not loading: https://iiif.archivelab.org/iiif/ceremoniesreligi03pica/manifest.json

**Comment by cbeer** [comment]
It looks like.. despite advertising the image service as level2-compatible, it isn't serving up images for `sizeByConfinedWh` requests?

**Comment by mejackreed** [comment]
What about the top level thumb?

```
  "thumbnail": {
    "@id": "https://ia800406.us.archive.org/BookReader/BookReaderPreview.php?id=ceremoniesreligi03pica&subPrefix=ceremoniesreligi03pica&itemPath=/15/items/ceremoniesreligi03pica&server=ia800406.us.archive.org&page=preview&"
  },
```

**Comment by cbeer** [comment]
I think it might be the same deal; because the manifest thumb isn't a IIIF image, we try to get the starting canvas thumbnail.

**Comment by mejackreed** [comment]
Got it.. closing this since we can't really do anything about that.
