### ISSUE TITLE
Mirador 3: Drag & Drop Manifest URLs?

### ISSUE THREAD

**Issue by barryspearce** [ProjectMirador/mirador#3331]
In Mirador 2 I used to be able to drag and drop manifest URLs into the viewer.
Is Mirador 3 going to support D&D of manifest URLs in the same way?

This feature is really useful when you can set up 2 or 3 sources for comparison simply by opening up one and then D&D in the others.

**Comment by mejackreed** [comment]
Thanks for filling the issue @barryspearce . Yes, Mirador 3 already supports drag and drop. Are you seeing an issues using it yet?

**Comment by barryspearce** [comment]
@mejackreed 

Yes I am seeing issues - i have no drag & drop working at all under v3 rc7.

It does not accept any dropping of any manifest URL under Chromium.
In all cases it produces a document icon across the screen) with grey-overlay across mirador and then ignores the drop. (Image attached) - sorry for the quality but should show what I see.

The only way I can get URLs into rc7 are 1. Add it programmatically, 2. Under add resource I have to manually paste the URL into the box. It won't drop - behaviour as above.

Behaviour under v2 (https://projectmirador.org/demo/) 
1st drop on active view adds to objects.
2nd drop on active view shows the object in the active view
Go into replace object I can drop the manifest URL into the URL box top right.
No other drop areas appear to be provided.

This behaviour is a little quirky - as I would expect the behaviour of the 1st drop to be combined 1st & 2nd drops and I was hoping this would be ironed out in v3. 

![IMG_20201103_150413](https://user-images.githubusercontent.com/18211861/98003291-7ce50700-1de6-11eb-9cd8-423715c5bfd9.jpg)

The deployed mirador is here: https://bsip.org.uk/mirador

**Comment by mejackreed** [comment]
Thanks for posting that deploy link, it is very helpful. Do you have an implementation handy of where your Drag and Drop urls are coming from? Or ones that aren't working for you? 

I was able to get it working via the IIIF logo from here: https://searchworks.stanford.edu/catalog?f%5Biiif_resources%5D%5B%5D=available

But perhaps we haven't accounted for other implementations?

**Comment by barryspearce** [comment]
> Thanks for posting that deploy link, it is very helpful. Do you have an implementation handy of where your Drag and Drop urls are coming from? Or ones that aren't working for you?

The public side of the database doesn't go live until 01 Jan so the manifest link isn't accessible to anyone not logged in - and at the moment that means me!

However, I have noticed that the difference is my link was simply a raw url to an iiif manifest, and does not follow the <host>/<page>?manifest=<url> format. That is most likely where the issue is - whereas v2 accepted a raw url.

I will add an explanation page to my website and alter the generated URLs for conform to the url format.

Thanks for your help and bringing the url format to my attention!
Cheers
Barry

**Comment by regisrob** [comment]
I am aware that the Content State API is not yet stable but it might be useful to support the `iiif-content` parameter in drag'n drop URLs, at least to be able to import a single manifest (see https://preview.iiif.io/api/content-state-comments/api/content-state/0.3/#initialization-mechanisms-link). 
We can hope that this parameter will not change in future versions of the spec... 
Anyway this makes sense with respect to the `iiif-content` parameter that is already supported in [this Mirador instance](https://projectmirador.org/embed/?iiif-content=https://iiif.io/api/cookbook/recipe/0009-book-1/manifest.json) (even if I guess it is handled outside of Mirador itself)

Example URL: https://portail.biblissima.fr/info-iiif?iiif-content=https://gallica.bnf.fr/iiif/ark:/12148/btv1b10533304x/manifest.json

This small change in [IIIFDropTarget.js#L18](https://github.com/ProjectMirador/mirador/blob/master/src/components/IIIFDropTarget.js#L18) seems to do the trick:
`const manifestId = url.searchParams.get('manifest') || url.searchParams.get('iiif-content');`

Of course further code would be needed to support a base64url-encoded contentState (see examples in https://preview.iiif.io/api/content-state-comments/api/content-state/0.3/#initialization-mechanisms-link)

Example URL (base64url-encoded IIIF annotation that represents a contentState with a manifest URL + canvas URL): https://portail.biblissima.fr/info-iiif?iiif-content=eyJtb3RpdmF0aW9uIjogWyJjb250ZW50U3RhdGUiXSwgInR5cGUiOiAiQW5ub3RhdGlvbiIsICJ0YXJnZXQiOiB7InR5cGUiOiAiQ2FudmFzIiwgImlkIjogImh0dHBzOi8vZ2FsbGljYS5ibmYuZnIvaWlpZi9hcms6LzEyMTQ4L2J0djFiMTA1MzMzMDR4L2NhbnZhcy9mODciLCAicGFydE9mIjogW3sidHlwZSI6ICJNYW5pZmVzdCIsICJpZCI6ICJodHRwczovL2dhbGxpY2EuYm5mLmZyL2lpaWYvYXJrOi8xMjE0OC9idHYxYjEwNTMzMzA0eC9tYW5pZmVzdC5qc29uIn1dfX0=
