### ISSUE TITLE
Mirador crashes with misused service property

### ISSUE THREAD

**Issue by regisrob** [ProjectMirador/mirador#3341]
- I am the author or maintainer of this manifest: **No**
- URL: https://digi.ub.uni-heidelberg.de/diglit/iiif/cpgraec129/manifest.json
- Manifest hosting institution: Universitätsbibliothek Heidelberg

### Observed behavior
- Description: Mirador crashes when opening this Manifest (after clicking on it in the catalog) with the error pasted below. It seems related to the `service` property, which is not used appropriately by the provider.
- Errors or warnings from [IIIF Presentation Validator](https://iiif.io/api/presentation/validator/service/): `Validation Error: Unknown type for label`, which is not very useful...

Mirador error:
```
TypeError
can't access property "hasOwnProperty", object is null

Utils.traverseAndFind
  node_modules/manifesto.js/dist-esmodule/Utils.js:679:13
 Utils.traverseAndFind
  node_modules/manifesto.js/dist-esmodule/Utils.js:684:31
 Utils.traverseAndFind
  node_modules/manifesto.js/dist-esmodule/Utils.js:684:31
 Utils.traverseAndFind
  node_modules/manifesto.js/dist-esmodule/Utils.js:684:31
 Utils.getResourceById
  node_modules/manifesto.js/dist-esmodule/Utils.js:671:23
 Utils.getServices
  node_modules/manifesto.js/dist-esmodule/Utils.js:712:30
 Utils.getService
  node_modules/manifesto.js/dist-esmodule/Utils.js:661:29
 ManifestResource.prototype.getService
  node_modules/manifesto.js/dist-esmodule/ManifestResource.js:88:64
 getManifestSearchService<
  node_modules/mirador/dist/es/src/state/selectors/manifests.js:368:32
 createSelectorCreator/
  node_modules/reselect/es/index.js:75:25
```

**Comment by cbeer** [comment]
Mirador no longer crashes 🤷
