### ISSUE TITLE
Enable tilting image in any degree

### ISSUE THREAD

**Issue by ydvelaitzky** [ProjectMirador/mirador#3348]
Hi
Your mirador-image-tools plugin that we use now, enables rotating image by 45, 90, 135, 180 degrees left and right.
We need a way to enable tilting image in any degree, and not only the above.
Does Mirador have a way to achieve this?
Thanks!

**Comment by mejackreed** [comment]
Yes the `toggleRotate` method in `mirador-image-tools` demonstrates how to dispatch an `updateViewport` action with a rotation change to enable this type of functionality.

https://github.com/ProjectMirador/mirador-image-tools/blob/master/src/plugins/MiradorImageTools.js#L121
