### ISSUE TITLE
Specify catalog 

### ISSUE THREAD

**Issue by mnscholz** [ProjectMirador/mirador#3349]
- Manifest URLs (if any): any

The setting `catalog` allows for populating the resource list by specifying a list of manifest urls.

Is there the possibility to not pass the list directly but specify a separate json file with all the manifests which then gets loaded by mirador?

What would be the preferred way to load the catalog from a separate file if there is no such option?

**Comment by mejackreed** [comment]
> Is there the possibility to not pass the list directly but specify a separate json file with all the manifests which then gets loaded by mirador?

No sorry Mirador does not support that

> What would be the preferred way to load the catalog from a separate file if there is no such option?

You have a few options, you could always load a IIIF Collection manifest, but this would not add directly to the catalog, see https://mirador-dev.netlify.app/__tests__/integration/mirador/collections.html for an example

Or you could request and parse the JSON file of items you are looking to add to the catalog. Then you could either initialize Mirador with those items in the `catalog` property or dispatch an `addResource` action to programatically add them to the catalog.

An example of dispatching an action is here: https://github.com/ProjectMirador/mirador/wiki/M3---Mirador-3-Frequently-Asked-Questions#q-how-do-i-programmatically-set-the-canvas

However in your case you would create an action `addResource("http://example.com/manifest.json")`. This will add the resource to the catalog and fetch it for you.
