### ISSUE TITLE
Zooming without mouse-roller

### ISSUE THREAD

**Issue by ydvelaitzky** [ProjectMirador/mirador#3363]
Does Mirador have a way to enable the user  zooming the image without  a mouse-roller ?
Thanks!

**Comment by camillevilla** [comment]
@ydvelaitzky Yes! Zoom control buttons are turned off by default. You can turn them on via the UI: 
<img width="274" alt="Screen Shot 2020-12-03 at 5 01 25 PM" src="https://user-images.githubusercontent.com/5402927/101108389-3c191300-3589-11eb-9aae-ffa95aa74978.png">

<img width="814" alt="Screen Shot 2020-12-03 at 5 00 31 PM" src="https://user-images.githubusercontent.com/5402927/101108302-17bd3680-3589-11eb-8fc0-326a903d8d99.png">

Or you can have your Mirador instance show them by default via the settings:
https://github.com/ProjectMirador/mirador/blob/51f5ab29290fedda0c24d80892f64afaadc962ab/src/config/settings.js#L311

**Comment by camillevilla** [comment]
You can also use keyboard controls + and -. I believeeeee we get those keyboard controls from OpenSeaDragon.
