### ISSUE TITLE
Multilingual support for mirador plugins

### ISSUE THREAD

**Issue by ydvelaitzky** [ProjectMirador/mirador#3371]
The multilingual support as shown in [https://github.com/ProjectMirador/mirador/blob/master/src/locales/en/translation.json](https://github.com/ProjectMirador/mirador/blob/master/src/locales/en/translation.json)
is very usefull for us. But we need that support also for the mirador-image-tools plugin.
Does Mirador have a multilingual support also for its plugins?

Thanks!

**Comment by mejackreed** [comment]
Yes it does. We have set them up in mirador-image-tools here: https://github.com/ProjectMirador/mirador-image-tools/blob/master/src/translations.js
