### ISSUE TITLE
Optionally pass the mount element to the viewer constructor directly

### ISSUE THREAD

**Issue by charbugs** [ProjectMirador/mirador#3382]
When instantiating Mirador you have to pass an element id to the `Mirador.viewer` function. The constructor then searches for the element by `document.getElementById` and renders the viewer to that element. The `mirador.unmount` function again searches for that element by id and unmounts the viewer from that element. That means the constructor/unmount functions assume that the element is already/still connected to the DOM. But this may not always be the case.

For example a part of your code that is not aware of Mirador may remove the mount element without warning. In this case you have no chance to tell Mirador to deconstruct properly because the `unmount` function will fail. This may result in dangling style-elements under the head element. Another use case is that you want instantiate Mirador to perform some actions on it but render it later. This is currently not possible because the mount element must be connected to the DOM.

I propose to create an option to pass the mount element directly to the `Mirador.viewer` function. That way the constructor and unmount function would work even if the mount element is not connected to the DOM yet/anymore.

**Comment by cbeer** [comment]
I think #3429 may have addressed this/part of this.
