### ISSUE TITLE
Write all annotations to a single layer osd overlay, and link the coordinate systems

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#340]
Overlays use multiple html elements and scale along with events on the canvas, however, more flexible shapes, such as polygons or painted annotations, will be difficult to implement using multiple svg elements on the canvas. A bridge should be written that will allow a single svg canvas to provide the backdrop for the annotations, allowing them to be manipulated by d3.js or similar library while still scaling and panning with the navigation of the openSeadragon canvas.

Experiments to perform: 
1. Create a single svg canvas in the osd overlay layer and set `pointer-events:none` to allow interaction with the canvas. Set the correct styling properties, and width, height, and viewbox attributes on the canvas to allow osd to handle all the normal scaling.  
2. Create an svg canvas and absolutely position it to the offset parent of the osd canvas (as the current overlays div is), and automatically update the scale and panning attributes on the svg canvas through javascript (synchronising the coordinate systems).

Whichever of these two approaches may be used, it should greatly enrich the user experience and allow more powerful control over the display of annotations and controls on the canvas. For instance, synchronising zoom levels between the two canvas would allow showing and hiding annotations in a simplified manner for the user according to the context of use. Compare this [cluttered map](https://cartastrophe.files.wordpress.com/2012/01/dialectszoom.png?w=655) with too many carelessly coloured layers to [this map](http://www.advancedcustomfields.com/wp-content/uploads/2013/11/acf-google-maps-field-2.png) with a clear hierarchy aware of the context of use. 

Having greater control over annotations on a separate, but mathematically-linked canvas, would allow more sensitive display and classification of annotations.

Any Approach taken needs to support the following functions:
1. Draw to a single SVG Canvas overlaying the OSD canvas.
2. Have consistent layering when the SVG drawing is programmatically edited.
3. Have the SVG scale with the pan and zoom of the canvas.
4. Allow properly synchronised listening to the precise zoom level and viewport dimensions, enabling visualisations such as the minimap/preview already built into OSD to be made on top of the canvas.

One added benefit of approach 2 is that it makes integrating the hud controls into the same layer straightforward, so that there can be static overlays and dynamic overlays handled by the same code. For example, the up, down, next, and previous buttons can maintain their position and size while overlays are zoomed and scaled by dragging and scrolling.

**Comment by aeschylus** [comment]
Hi Ian, 

This is great. I am testing it out today and will let you know. Is there any chance we could get started on #339? I am available for any clarification through "issues", and we can also cover it this Wednesday.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
