### ISSUE TITLE
Annotations without neither SvgSelector nor xywh fragments cause error

### ISSUE THREAD

**Issue by lutzhelm** [ProjectMirador/mirador#3401]
Text annotations that lack any fragment selector, SVG selector or xywh URI fragment cause the error `fragment is null` at this line:
https://github.com/ProjectMirador/mirador/blob/5ca33205bf9bac636ba5ef0faf820f58c0d9751d/src/lib/CanvasAnnotationDisplay.js#L108

The error can be easily reproduced by saving a new annotation without selecting a target in the [annotation plugin demo](https://mirador-annotations.netlify.app/).

This is caused by a missing check in `CanvasAnnotationDisplay.toContext()` - if an annotation does not contain a SvgSelector, it's assumed that a fragment selector is present.

https://github.com/ProjectMirador/mirador/blob/5ca33205bf9bac636ba5ef0faf820f58c0d9751d/src/lib/CanvasAnnotationDisplay.js#L19-L26

I see two possibilities to fix this:
* just add a condition in `toContext()` - annotations that address the whole Canvas (or only have unknown selectors) will not be displayed on the Canvas
* assume a Canvas sized fragment selector if no (known) selector is present - said annotations will appear as a box around the Canvas

Personally I think I'd prefer variant 1.

**Comment by mejackreed** [comment]
I think variant 1 sounds good
