### ISSUE TITLE
Support v3 logo for provider in manifest providers

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#3404]
Example manifest: https://preview.iiif.io/cookbook/0234-provider/recipe/0234-provider/manifest.json

Cookbook recipe: https://preview.iiif.io/cookbook/0234-provider/recipe/0234-provider/

**Comment by mejackreed** [comment]
Closing a duplicate of #3405

**Comment by triplingual** [comment]
Apologies for missing this -- I thought I searched first.

**Comment by mejackreed** [comment]
No worries! I snuck it in early this morning
