### ISSUE TITLE
Support `logo` image within `provider` in IIIF Presentation v3 manifest

### ISSUE THREAD

**Issue by triplingual** [ProjectMirador/mirador#3405]
- I am the author or maintainer of this manifest: Yes
- ~URL: https://preview.iiif.io/cookbook/0234-provider/recipe/0234-provider/manifest.json~
- URL: https://iiif.io/api/cookbook/recipe/0234-provider/manifest.json
- Manifest hosting institution: IIIF

### Observed behavior

- Description: The Manifest itself is loading, but the image in the `logo` in the `provider` property is not. I even set the `logo` content to be the known-working JSON from issue #3269 and nothing.
- 
![Screen Shot 2021-04-01 at 12 49 28](https://user-images.githubusercontent.com/1789625/113327293-c62f7900-92e8-11eb-982b-4aecd0bb21f5.png)

- No pertinent errors or warnings from the UI, developer console, or the [IIIF Presentation Validator](https://iiif.io/api/presentation/validator/service/) that I can see, but I could be missing something or ignorant about this.

**Comment by triplingual** [comment]
(Noting that my only edit to the comment just now was to change the manifest URI to the more nearly permanent one now that the recipe is formally published in the cookbook.)

**Comment by marlo-longley** [comment]
Closed by #3657
