### ISSUE TITLE
defaultView="single" doesn't seem to be respected

### ISSUE THREAD

**Issue by jeffreycwitt** [ProjectMirador/mirador#3426]
I would like my mirador instance to default to "single" view rather than "book view". 
So following the settings document, I'm using the following config settting: 

```
{
               id: 'mirador',
               window: {
                defaultView: 'single',
                sideBarOpen: true,
                sideBarPanel: "canvas"
               },
               catalog: manifests,
               view: "catalogueView",
               workspace: {
                isWorkspaceAddVisible: true,
               }
       });
```

I keep getting: 
![image](https://user-images.githubusercontent.com/1146685/115741022-5e0b0a80-a35d-11eb-82ff-f5840bab6efe.png)

However, as seen above this doesn't seem to be working for me.

You can try it with this 
https://scta.info/iiif/wodehamordinatio/sorb193/manifest 
and in my live instance here: https://mirador.scta.info/

(make sure to go the second page to see the default book view. The first page will look like it is in single view, because it is showing the first page as a single because it is first)

**Comment by lutzhelm** [comment]
If no view has been set in the state for a window yet,
* the `window.view` config is checked for any suitable entry that matches the `viewingHint` or `behaviors` of the manifest
* if there is none, the default view is used

https://github.com/ProjectMirador/mirador/blob/b51faeefa1b815fb949bdcf60026d6275b4847d4/src/state/selectors/windows.js#L56-L61

In your case, the entry with the key `book` is returned; see default config below.

What would help you would be changing the default config from

https://github.com/ProjectMirador/mirador/blob/master/src/config/settings.js#L281-L286

to 

    views: [
      { key: 'single', behaviors: ['individuals', 'paged'] },
      { key: 'book', behaviors: ['paged'] },
      { key: 'scroll', behaviors: ['continuous'] },
      { key: 'gallery' },
    ],         

i.e. insert `paged` to the key `single` and put this to the `window` config key.

While this might help @jeffreycwitt, it does not look a very comprehensible general solution.

**Comment by jeffreycwitt** [comment]
This seems to work. I had to insert "views" as a child of `window` which I guess is what you meant when you said "put this to the `window` config key". 

Here's what I have now:

```
          {
             id: 'mirador',
             window: {
                defaultView: 'single',
                sideBarOpen: true,
                sideBarPanel: "canvas",
                views: [
                  { key: 'single', behaviors: ['individuals', 'paged'] },
                  { key: 'book', behaviors: ['individuals'] },
                  { key: 'scroll', behaviors: ['continuous'] },
                  { key: 'gallery' }
                ]
               },
             view: "catalogueView",
             workspace: {
                isWorkspaceAddVisible: true,
               },
              
           }
```
