### ISSUE TITLE
Support for "within" in manifests is missing

### ISSUE THREAD

**Issue by ulb-sa-schmilj** [ProjectMirador/mirador#3430]
The support for collections exists, see #3026.

The current implementation handle a presentation from a collection down to the manifests.
Sample: https://wellcomelibrary.org/iiif/collection/b18031511

But if the volume is directly opened. The UI ignores "within" with a link to the collection manifest completely.
Sample: https://wellcomelibrary.org/iiif/b18031511-1/manifest

For a better changing between volumes/manifests it is also necessary to come from a manifest up to the linked collection.

**Comment by cbeer** [comment]
Thanks for filing the issue.

I recall some discussion about `within` at the time, and we struggled to find consistent usage across IIIF implementations and what `within` pointed at (is it a IIIF collection JSON or some random web page). IIIF v3  removed/replaced `within` with `partOf` and resolves some of the ambiguity, but there weren't too many examples of its use at the time.

**Comment by ulb-sa-schmilj** [comment]
Is `partOf` implemented? Currently we use the presentation api in version 2.1. But that would be a reason to switch to version 3.0

**Comment by cbeer** [comment]
Yes, it is.
