### ISSUE TITLE
Invalid/unnecessary HTTP-Request for a thumbnail - for a collection manifest with have no thumbnail

### ISSUE THREAD

**Issue by ulb-sa-schmilj** [ProjectMirador/mirador#3431]
- I am the author or maintainer of this manifest: No
- URL: https://wellcomelibrary.org/iiif/collection/b18031511

### Observed behavior
- Description: If mirador loads an collection manifest without thumbnail. A http request with status code 404 is thrown.
  Samples of the same manifest with mirador hosted on different location: 
    - https://mirador-dev.netlify.app/__tests__/integration/mirador/undefined
    - https://opendata.uni-halle.de/viewers/undefined
    - "baseUrlOfMirador"/undefined
- Errors can be found in the developer tools of the browser
```
GET https://opendata.uni-halle.de/viewers/undefined 404                  undefined:1
```

A thumbnail for a collection is recommended and not required. I think if no thumbnail is in the JSON, mirador should not try to load a thumbnail from a not existing resource (./undefined). 
If the UI must have a thumbnail, mirador should only request an existing default thumbnail - delivered from the viewer instance (Sample: ./no_thumbnail_exists.png).

**Comment by camillevilla** [comment]
Thanks for submitting this issue @ulb-sa-schmilj. This was resolved in #3447.
