### ISSUE TITLE
Customize pagination format when in book view

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#3438]
Currently we use the same pagination format whether the user is in single view or in book view. The pagination display makes sense when you are in single view but can be confusing to users when in book view. I don't how challenging this is technically, but from a UX point of view, when the user is in book view, it would be helpful if the pagination format adapted to reflect that the user can be viewing two pages at a time, instead of one.

For example, the pagination display for a [5-page document](https://purl.stanford.edu/sw982tb4758) in single view is straightforward:

- 1 of 5 • Page 1
- 2 of 5 • Page 2
- 3 of 5 • Page 3
- 4 of 5 • Page 4
- 5 of 5 • Page 5

If that same document is viewed in book view, however, after the first (single) page, that pagination format doesn't really match what the user sees ("of 5" is really "of 3" in this context because there are only 3 spreads that the user can navigate to, and "Page x" is really "Pages x and y" because two pages are being displayed):

**Pages 2 and 3:**

<img width="796" alt="Screen Shot 2021-05-21 at 2 39 34 PM" src="https://user-images.githubusercontent.com/101482/119201321-81e86b80-ba43-11eb-884c-fe94bffd74e8.png">

**Pages 4 and 5:**

<img width="796" alt="Screen Shot 2021-05-21 at 2 39 40 PM" src="https://user-images.githubusercontent.com/101482/119201349-94fb3b80-ba43-11eb-9335-f76ffa3540d5.png">

--- 

Ideally, we would use a pagination format in book view that would correspond more closely to what the user is actually seeing. Specifically, the first part ("x of y") represents the number of views/spreads the user can navigate to for this object in book view, and the second part represents the actual page numbers being displayed (usually 2 rather than 1):

- 1 of 3 • Page 1
- 2 of 3 • Pages 2 and 3
- 3 of 3 • Pages 4 and 5

Here's that same scheme mocked up:

**Page 1 (but now of 3 "spreads"):**

<img width="796" alt="Screen Shot 2021-05-21 at 2 40 07 PM" src="https://user-images.githubusercontent.com/101482/119201578-0cc96600-ba44-11eb-8569-8f471d15390d.png">

**Pages 2 and 3:**

<img width="796" alt="Screen Shot 2021-05-21 at 2 40 39 PM" src="https://user-images.githubusercontent.com/101482/119201603-1a7eeb80-ba44-11eb-8b91-c493b42acbd5.png">

**Pages 4 and 5:**

<img width="796" alt="Screen Shot 2021-05-21 at 2 41 08 PM" src="https://user-images.githubusercontent.com/101482/119201609-1eab0900-ba44-11eb-829d-0c5bdb2a18e9.png">

**Comment by cbeer** [comment]
The text after the dot is from the IIIF manifest, so I don't think we have any control over that and can't merge or combine the canvas labels.

**Comment by cbeer** [comment]
@ggeisler and I discussed this ticket; we're going to close this now as most of the confusion is from the manifest-provided labels (after the dot). With the mirador-provided page numbers (before the dot), either approach can probably be justified or may required more sophisticated display when dealing with (non)facing pages or providing consistency toggling between different views.

Maybe there's some future design work on this whole bar 🤷‍♂️
