### ISSUE TITLE
Using Mirador with Alto Files

### ISSUE THREAD

**Issue by miriamg16** [ProjectMirador/mirador#3439]
hello

 In our library site we use Mirador viewer (3)  to display digital images
now we want to integrate **ALTO files** to display the transcriptions of these images.
Is there a good way to use Mirador with Alto?

Looking forward to any reply

**Comment by lutzhelm** [comment]
Hi @miriamg16, if you just want to display transcriptions in ALTO XML you might want to have a look at the [mirador-textoverlay](https://github.com/dbmdz/mirador-textoverlay/#requirements-for-supported-iiif-manifests) plugin. One of the supported methods of providing transcriptions for this plugin is linking ALTO XML in `seeAlso` at the Canvas level.

**Comment by miriamg16** [comment]
Thanks
That's great for me
