### ISSUE TITLE
Hebrew support in mirador-textoverlay plugin

### ISSUE THREAD

**Issue by miriamg16** [ProjectMirador/mirador#3441]
Hello
I'm trying to implement the 'mirador-textoverlay' plugin
to integrate ALTO files In the Mirador, to view a transcription of the image

It seems to me that there is a problem with Hebrew support
Or there is another definition that needs to be defined.

I check on the demo site
https://mirador-textoverlay.netlify.app/
with this manifest
https://vf.genizah.org/testManifest/FL45509099/manifest1.json
That has an ALTO file (the reference to it is in the manifest)
https://vf.genizah.org/testManifest/FL45509099/FL45509099_Alto.xml

The problem is that it looks really bad,
I attached a screenshot.
![Capture](https://user-images.githubusercontent.com/83166064/120989753-8bced600-c788-11eb-8a14-2db195949a22.JPG)

I would be happy for any help!

**Comment by camillevilla** [comment]
Hi @miriamg16. I think it would be best to track this discussion in dbmdz/mirador-textoverlay#150. If changes need to be implemented in Mirador core, dbmdz/mirador-textoverlay maintainers can file additional tickets with implementation details.

If you have any others suggestions for how Mirador can better support Hebrew in the core interface, please feel free to file new tickets.

You are also welcome to get troubleshooting suggestions from other IIIF implementers on the #mirador channel on [IIIF slack](http://bit.ly/iiif-slack).
