### ISSUE TITLE
Can you add M3 plugins via a simple javascript file?

### ISSUE THREAD

**Issue by jpadfield** [ProjectMirador/mirador#3481]
Hi,

It is possible to add an instance of mirador 3 to a basic webpage simply by including one javascript file like: https://cdn.jsdelivr.net/npm/mirador@3.2.0/dist/mirador.min.js

Now my question is, is it possible to add in plugins the same way? The instructions all seem to relate to downloading and building code into a project. 

For example I can see that https://www.jsdelivr.com/package/npm/mirador-image-tools is also listed on jsdeliver, but the default script does seem to deliver that simple add in and play type option.

The use case is being able to add it into webpages similar to: https://jpadfield.github.io/simple-site/Mirador%20IIIF%20viewer.html

Thanks

**Comment by jbaiter** [comment]
I don't think this is currently possible, I always ran into inscrutable errors regarding react/redux when I tried this with my own plugin :-/

Your best bet is currently to use a simple bundler like Parcel (should be zero config for this use case) and bundle up your custom mirador package that includes the plugins of your choice.

**Comment by jpadfield** [comment]
Ok, thanks I will have a look.
