### ISSUE TITLE
Display Summary Value

### ISSUE THREAD

**Issue by mlhale7** [ProjectMirador/mirador#3485]
Currently it doesn't look like Mirador displays summary values. I wanted to check and see if there are plans to include summary values in the Mirador viewer in the future? According to the [Presentation 3.0 guidelines](https://iiif.io/api/presentation/3.0/#31-descriptive-properties), a manifest should have a summary property and this value should be displayed when the metadata entries for the resource aren't.  For the short term we plan to simply add the summary value to the metadata section of the manifest, but it would be helpful to know if work is planned in this area or if others have interest in this improvement.

**Comment by cbeer** [comment]
Hi @mlhale7 , can you share some example manifests that are using that property? I think that'd give us a better idea how that property is used in the real world.

**Comment by mlhale7** [comment]
@cbeer - thanks for this! Here's an example manifest - https://digital.lib.utk.edu/assemble/manifest/galston/697 We are generating our manifests directly from our MODS metadata, so the summary value in the manifest is the same as a mods:abstract. I can see some instances where including the full abstract might be problematic (if it's too long), but I think this example meets what IIIF sets out as the goal of the summary ("used as a brief description for item level search results, for small-screen environments, or as an alternative user interface when the metadata property is not currently being rendered."). We are new (at University of Tennessee) to IIIF/manifest generation.

**Comment by mlhale7** [comment]
Here are a few additional ones: 1. https://digital.lib.utk.edu/assemble/manifest/galston/722
2. https://digital.lib.utk.edu/assemble/manifest/galston/723
3. https://digital.lib.utk.edu/assemble/manifest/tenncities/116
