### ISSUE TITLE
Does mirador viewer have navigator panel functionality?

### ISSUE THREAD

**Issue by qudratullah1061** [ProjectMirador/mirador#3487]
Hi, I want to know is there any functionality to know zoom current position by using navigation panel in Mirador Viewer like "Universal Viewer" or some other viewers have? A screenshot is attached.

![navigator panel](https://user-images.githubusercontent.com/32341027/129769223-0ae7b653-dad7-48a3-926d-39e0e88a34e6.png)

If no, can you please let me know do you have this functionality to implement in your Todo list?

Thanks.

**Comment by jbaiter** [comment]
You can pass any OpenSeadragon option via the Mirador configuration under the `osdConfig` key: https://github.com/ProjectMirador/mirador/blob/master/src/config/settings.js#L337-L343

Simply add `showNavigator:  true` there (https://openseadragon.github.io/examples/ui-viewport-navigator/) and you should see one in your Mirador windows!

**Comment by qudratullah1061** [comment]
Thanks a lot for your quick response. As I am using mirador v2. Is this functionality available in mirador viewer v2?

I am using it like this but not working.

Mirador({
                    "id": "viewer",
                    "layout": "1x1",
                    "data": [
                        {"manifestUri": "URL HERE", "location": "Website"}
                    ],
                    "windowObjects": windowObjects,

                    "windowSettings": {
                        "sidePanelVisible": true
                    },
                    osdConfig: {// Default config used for OpenSeadragon
                        alwaysBlend: false,
                        blendTime: 0.1,
                        preserveImageSizeOnResize: true,
                        preserveViewport: true,
                        showNavigationControl: true,
                        showNavigator: true
                    }
                });

Please guide. 
Thanks

**Comment by jbaiter** [comment]
Are you sure that you tested this properly?

Here's a CodePen with the standard Mirador 3 demo setup, with the only difference that it includes `osdConfig: { showNavigator: true }`:
https://codepen.io/jbaiter/pen/BaRXyam

As you can see, the navigator is visible in the upper right corner of each window in the Mirador instance. If you want to change the position, you can set the `navigatorPosition` option, e.g. `navigatorPosition: "BOTTOM_LEFT"`.

**Comment by jbaiter** [comment]
Sorry, as stated in the README, Mirador 2 is no longer supported.
But looking at the source code, it doesn't seem to be support custom options for OSD anyways:
https://github.com/ProjectMirador/mirador2/blob/main/js/src/widgets/imageView.js#L696-L703
