### ISSUE TITLE
Webpack issue with react-mosaic-component (Can't resolve @blueprintjs/icons, @blueprintjs/core)

### ISSUE THREAD

**Issue by D-Groenewegen** [ProjectMirador/mirador#3493]
- Mirador 3.0.0 and 3.2.0
- Description of use case: installation not successful with webpack

Because I'm interested in using (existing) plugins with an instance of Mirador 3, I followed the instructions over on https://github.com/ProjectMirador/mirador-integration, using webpack and the default example given there (Mirador + image tools), along with the latest "getting started" instructions from webpack. My provider won't let me use a CLI so the plan is install locally and transfer relevant files to the server when ready. 

The main.js and its ancillary files (like 130.main.js, etc.) were transpiled with five warnings. Some of these we can probably ignore (recommended size exceeded and mode option not set), but there is one that probably merits attention:

```
WARNING in ../node_modules/mirador/node_modules/react-mosaic-component/lib/util/OptionalBlueprint.js 33:8-45
Module not found: Error: Can't resolve '@blueprintjs/icons' in '/Users/dennisgroenewegen/dngr/node_modules/mirador/node_modules/react-mosaic-component/lib/util'
```
[Similar to this issue](https://github.com/nomcopter/react-mosaic/issues/88).

I checked the html file in my browser and while the interface and metadata are loaded, the mosaic does not show me any image. The browser console reports:

```
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

Because the versions in package.json look a little outdated, I updated them and repeated my steps, but the result remains the same. 

I suspect that this has nothing to do with Mirador directly. I ended up with two `node_modules` directories, a pre-existing one (before using webpack) and the one in my project folder for Mirador, so maybe there's some sort of confusion between global and local installations, but this is new territory for me.

**Comment by ColeDCrawford** [comment]
Also seeing this issue. I'm trying to integrate M3 into a Vue frontend using Vuera and after installing Mirador, react, and react-dom I am running into the above `react-component-mosaic` issue.

**Comment by D-Groenewegen** [comment]
Well, I don't quite understand how but I must have solved it one way or another. The `Can't resolve '@blueprintjs/icons'` errors are still there after compilaton, but they do not prevent the new build from being usable. Maybe the previous one was pointing to the version of React or Mirador in the global `node_modules` folder, resulting in a mismatch.

**Comment by charbugs** [comment]
The blueprint compile warning is most likely not related to the runtime error reported by @D-Groenewegen. The blueprint warning is annoying but it does not impact the functionality of Mirador. The authors of react-mosaic could not solve it so far (see https://github.com/nomcopter/react-mosaic/pull/92). If you don't want to see this warning anymore you can use the webpack ignore plugin as we do in Mirador (see https://github.com/ProjectMirador/mirador/blob/master/webpack.config.js#L44)

**Comment by D-Groenewegen** [comment]
Thanks, Mathias, for clarifying the warning. It's reassuring to hear that it doesn't have any negative effect.
