### ISSUE TITLE
Mirador crashes when the value of a property is null

### ISSUE THREAD

**Issue by regisrob** [ProjectMirador/mirador#3524]
- I am the author or maintainer of this manifest: No
- URL: https://digi.ub.uni-heidelberg.de/diglit/iiif/cpgraec129/manifest.json
- Manifest hosting institution: Heidelberg University

### Observed behavior

Mirador crashes with this Manifest as soon as you open the sidebar ([example in M3](https://projectmirador.org/embed/?iiif-content=https://digi.ub.uni-heidelberg.de/diglit/iiif/cpgraec129/manifest.json)). This is due to a Range label with a value `null`, so it is not a problem with Mirador itself... But maybe it still needs a security belt to avoid this problem. I have seen some other Manifests from Heidelberg which make Mirador crash because of a property with `null` (e.g. a `"license": null`). I did report the problem to them on Slack and via email a while ago but it is not fixed yet, so I thought it may be a good thing to "solve" it on the Mirador side 🤷‍♂️

**Comment by camillevilla** [comment]
We chatted more about this at community call today. 
https://iiif.io/api/presentation/3.0/#54-range 

We'd like to avoid crashing Mirador... but it seems like we'd be adding a lot of logic to handle an invalid manifest. @lutzhelm also mentions that this issue crashes the window, but not the entire Mirador instance.

**Comment by regisrob** [comment]
Ok thanks for taking a look @camillevilla, I understand the rationale. Let's hope Heidelberg will fix the problem one day!
