### ISSUE TITLE
A/V Caption files in Canvas annotations are not used, cookbook recipe does not work

### ISSUE THREAD

**Issue by lutzhelm** [ProjectMirador/mirador#3538]
At the time A/V with captions had been implemented in Mirador, the cookbook recipe preview manifest contained the captions directly in the painting annotation body as a second entry to the video: https://github.com/IIIF/cookbook-recipes/blob/a8299877e67ff8d960b9ca82da0e959476f18e53/recipe/0219-using-caption-file/manifest.json

However, the [published recipe](https://iiif.io/api/cookbook/recipe/0219-using-caption-file/) suggests that captions should be provided as separate supplementing annotation in the Canvas annotations:
https://iiif.io/api/cookbook/recipe/0219-using-caption-file/manifest.json
https://preview.iiif.io/cookbook/0219-using-caption-file/recipe/0219-using-caption-file/manifest.json

Therefore the captions do not work in the [video demo](https://github.com/ProjectMirador/mirador/blob/057b6eea2950ff37cd5e26b4eddeeaa1e0ed8677/__tests__/integration/mirador/video.html):
https://mirador-dev.netlify.app/__tests__/integration/mirador/video.html

**Comment by phil-plencner-hl** [comment]
Fixed with this PR: 
https://github.com/ProjectMirador/mirador/pull/3664
