### ISSUE TITLE
Navigating to specific canvas in specific manifest

### ISSUE THREAD

**Issue by MehranDHN** [ProjectMirador/mirador#3548]
Would you please someone point me to a resource to find out how can I implement links to specific Canvas in a specific manifest?
Suppose I have a Query String that includes both the Manifest Id and Canvas id and I want to use them to navigate to a given canvas in a specified manifest. 
Thanks

**Comment by lutzhelm** [comment]
You can either [provide the Canvas ID via the Mirador configuration](https://github.com/ProjectMirador/mirador/blob/8dae6b6e64ccc5e85dc6e72e94ebcf2b9d6e9b1e/__tests__/integration/mirador/index.html#L20-L21) or [programmatically set the Canvas](https://github.com/ProjectMirador/mirador/wiki/M3---Mirador-3-Frequently-Asked-Questions#q-how-do-i-programmatically-set-the-canvas) after loading Mirador.

**Comment by lutzhelm** [comment]
Closing this issue; please reopen if the question has not entirely been answered.
