### ISSUE TITLE
Cannot load manifest to viewer

### ISSUE THREAD

**Issue by eu-genia** [ProjectMirador/mirador#3551]
- I am the author or maintainer of this manifest: No
- URL: http://idb.ub.uni-tuebingen.de/opendigi/MaIX2/manifest
- Manifest hosting institution Tuebingen University Library 

### Observed behavior
- Description: I cannot add manifests of the Tuebingen University Library via the "Add Resource" button or otherwise on my local Mirador instance (https://betamasaheft.eu/manuscripts/viewer); it does not get loaded to https://mirador-dev.netlify.app/__tests__/integration/mirador/ either (or to the universalviewer for testing purposes)

- Errors or warnings from the UI, developer console, or the [IIIF Presentation Validator](https://iiif.io/api/presentation/validator/service/)
```
URL Tested: http://idb.ub.uni-tuebingen.de/opendigi/MaIX2/manifest

Validation Error API2: sc:Manifest['license'] must have a URI or resource, got 'To the best of our knowledge this work is free of known copyrights or related property rights (public domain).'
Warnings:
The remote server did not use the requested gzip transfer compression, which will slow access. (Content-Encoding: )

Validation Errors API3
Error 1 of 3. Message: 'Retuʿa haymanot [= der Rechtgläubige]' is not of type 'object'
Detail: Language string, must have a language and value must be an array.
Path: /label/['Retuʿa haymanot [= der Rechtgläubige]' is not of type 'object']
Description:
"Retuʿa haymanot [= der Rechtgläubige]"
Error 2 of 3. Message: 'id' is a required property
Detail: Classes MUST have an id and type property and MAY have a label.
Path: /['id' is a required property]
Description:
{"attribution":"University Library Tübingen","@type":"sc:Manifest","seeAlso":"[ ... ]","viewingHint":"paged","@id":"http://idb.ub.uni-tuebingen.de/opendigi/MaIX2/manifest","@context":"http://iiif.io/api/presentation/2/context.json","sequences":"[ ... ]","license":"To the best of our knowledge this work is free of known copyrights or related property rights (public domain).","label":"Retuʿa haymanot [= der Rechtgläubige]"}
Error 3 of 3. Message: 'http://iiif.io/api/presentation/2/context.json' is not of type 'array'
Detail:
Path: /@context/['http://iiif.io/api/presentation/2/context.json' is not of type 'array']
Description:
"http://iiif.io/api/presentation/2/context.json"
```
It looks like there is a problem with manifest yet it does work on http://iiif.gdmrdigital.com/mirador/ - is there a way to have it loaded?

**Comment by regisrob** [comment]
This is a [mixed-content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) issue: web browsers cannot load http resources from an https domain, that is why it does not work from `https://betamasaheft.eu/` or `https://mirador-dev.netlify.app/`, whereas it does work from `http://iiif.gdmrdigital.com...`. 
This is a general security blocking which completely breaks interoperability for client applications based on Javascript (like IIIF viewers). Thus using HTTPS everywhere is highly recommended, but this is up to Tuebingen to fix that.

**Comment by eu-genia** [comment]
Thank you, I was wondering if that was the reason, but was hoping there may be some trick. Thank you for setting this straight!
