### ISSUE TITLE
Replace Enzyme 

### ISSUE THREAD

**Issue by cbeer** [ProjectMirador/mirador#3597]
Enzyme (our testing library) seems like it won't be updated to support modern versions of React. Other libraries (e.g. react-testing-library) operate at the DOM level instead of interacting with React components directly, which may require substantially rewriting Mirador's test suite.

**Comment by cbeer** [comment]
react-testing-library: #3642

**Comment by jbaiter** [comment]
I have some experience with react-testing-library and Mirador 3 in my `mirador-textoverlay` plugin (e.g. https://github.com/dbmdz/mirador-textoverlay/blob/main/__tests__/components/MiradorTextOverlay.test.js).

I'd gladly help porting the existing tests over. Any components I should look at first?

**Comment by cbeer** [comment]
That'd be great, thanks @jbaiter.

So far, I've been taking a random selection of tests to make sure react-testing-library is a good-enough fit (so far so good; there's some quirks and I've had to some some refactoring to stay on the happy path with RTL, but besides diving into the DOM more than RTL would like, it seems ok.)

To distribute the remaining work, here's a haphazard grouping of the remaining tests that use enzyme. I'll make some tickets  to track each grouping. Hopefully we can get #3642 merged and then throw PRs up as we go along.

- [ ] Window:
__tests__/src/components/PrimaryWindow.test.js
__tests__/src/components/Window.test.js
__tests__/src/components/WindowCanvasNavigationControls.test.js
__tests__/src/components/WindowSideBar.test.js
__tests__/src/components/WindowTopBar.test.js
__tests__/src/components/WindowTopBarPluginArea.test.js
__tests__/src/components/WindowTopBarPluginMenu.test.js
__tests__/src/components/WindowTopBarTitle.test.js
__tests__/src/components/WindowTopMenu.test.js
__tests__/src/components/WindowTopMenuButton.test.js

- [ ] Companion windows:
__tests__/src/components/AnnotationSettings.test.js
__tests__/src/components/AttributionPanel.test.js
__tests__/src/components/CanvasAnnotations.test.js
__tests__/src/components/CanvasInfo.test.js
__tests__/src/components/CanvasLayers.test.js
__tests__/src/components/CollectionInfo.test.js
__tests__/src/components/LabelValueMetadata.test.js
__tests__/src/components/LayersPanel.test.js
__tests__/src/components/ManifestInfo.test.js
__tests__/src/components/ManifestRelatedLinks.test.js
__tests__/src/components/SearchHit.test.js
__tests__/src/components/SearchPanel.test.js
__tests__/src/components/SearchPanelControls.test.js
__tests__/src/components/SearchPanelNavigation.test.js
__tests__/src/components/SearchResults.test.js
__tests__/src/components/SidebarIndexItem.test.js
__tests__/src/components/SidebarIndexList.test.js
__tests__/src/components/SidebarIndexTableOfContents.test.js
__tests__/src/components/SidebarIndexThumbnail.test.js
__tests__/src/components/ThumbnailCanvasGrouping.test.js
__tests__/src/components/WindowSideBarAnnotationsPanel.test.js
__tests__/src/components/WindowSideBarButtons.test.js
__tests__/src/components/WindowSideBarCanvasPanel.test.js
__tests__/src/components/WindowSideBarInfoPanel.test.js

- [ ] App:
__tests__/src/components/App.test.js
__tests__/src/components/AppProviders.test.js
__tests__/src/components/CollectionDialog.test.js
__tests__/src/components/LocalePicker.test.js
__tests__/src/components/LanguageSettings.test.js
__tests__/src/components/FullScreenButton.test.js
__tests__/src/lib/MiradorViewer.test.js
__tests__/src/components/AccessTokenSender.test.js
__tests__/src/components/IIIFAuthentication.test.js
__tests__/src/components/WindowAuthenticationBar.test.js
__tests__/src/components/NewWindow.test.js

- [ ] Viewer:
__tests__/src/components/AnnotationsOverlay.test.js
__tests__/src/components/OpenSeadragonViewer.test.js
__tests__/src/components/GalleryView.test.js
__tests__/src/components/GalleryViewThumbnail.test.js
__tests__/src/components/VideoViewer.test.js
__tests__/src/components/ViewerInfo.test.js
__tests__/src/components/ViewerNavigation.test.js
__tests__/src/components/WindowViewer.test.js
__tests__/src/components/WindowThumbnailSettings.test.js
__tests__/src/components/WindowViewSettings.test.js

- [ ] Design system:
__tests__/src/components/CollapsibleSection.test.js
__tests__/src/components/CompanionArea.test.js
__tests__/src/components/CompanionWindow.test.js
__tests__/src/components/CompanionWindowFactory.test.js
__tests__/src/components/ErrorDialog.test.js
__tests__/src/components/MiradorMenuButton.test.js
__tests__/src/components/SanitizedHtml.test.js
__tests__/src/components/ScrollIndicatedDialogContent.test.js
__tests__/src/components/ScrollTo.test.js
__tests__/src/components/NestedMenu.test.js
__tests__/src/components/BackgroundPluginArea.test.js
__tests__/src/components/PluginHook.test.js
__tests__/src/extend/withPlugins.test.js

- [ ] Workspace:
__tests__/src/components/ManifestForm.test.js
__tests__/src/components/ManifestListItem.test.js
__tests__/src/components/ManifestListItemError.test.js
__tests__/src/components/Workspace.test.js
__tests__/src/components/WorkspaceAdd.test.js
__tests__/src/components/WorkspaceAddButton.test.js
__tests__/src/components/WorkspaceArea.test.js
__tests__/src/components/WorkspaceControlPanel.test.js
__tests__/src/components/WorkspaceControlPanelButtons.test.js
__tests__/src/components/WorkspaceElastic.test.js
__tests__/src/components/WorkspaceElasticWindow.test.js
__tests__/src/components/WorkspaceExport.test.js
__tests__/src/components/WorkspaceImport.test.js
__tests__/src/components/WorkspaceMenu.test.js
__tests__/src/components/WorkspaceMenuButton.test.js
__tests__/src/components/WorkspaceMosaic.test.js
__tests__/src/components/WorkspaceOptionsButton.test.js
__tests__/src/components/WorkspaceOptionsMenu.test.js
__tests__/src/components/MosaicRenderPreview.test.js
__tests__/src/components/WindowList.test.js
__tests__/src/components/WindowListButton.test.js
