### ISSUE TITLE
Upgrade to Material UI v5

### ISSUE THREAD

**Issue by cbeer** [ProjectMirador/mirador#3598]
Material UI v4 doesn't support current versions of React. Visual changes are surprisingly minimal, but there's a substantial amount of back-end reworking needed to upgrade to v5.

**Comment by cbeer** [comment]
Leipzig is interested in contributing to this effort.

**Comment by whunter** [comment]
If I was going to try to make some of these updates I should follow this to get up and running?
https://github.com/ProjectMirador/mirador/wiki/M3-Developer-Tooling-and-Workflow
Is that correct?

And then just upgrade the material-ui package and start seeing what breaks?

**Comment by enriquediaz** [comment]
Closing this out because this work was successfully completed per release of [v4.0.0.alpha-1](https://github.com/ProjectMirador/mirador/releases/tag/v4.0.0.alpha-1)
