### ISSUE TITLE
Address Material-UI deprecations

### ISSUE THREAD

**Issue by cbeer** [ProjectMirador/mirador#3599]
- [ ] theming
- [ ] jss -> Emotion
- [ ] ???

**Comment by enriquediaz** [comment]
@cbeer at the last Mirador Community Call a question was raised regarding the move away from JSS to new styling engines. Though it is not necessary for the upgrade to MUI 5, it will definitely come up for future releases. The question is whether this step should be undertaken now within the upgrade? If yes, is there a preference for the new engine? (see [Migrating from JSS (optional) - Material UI](https://mui.com/material-ui/migration/migrating-from-jss/#migrating-from-jss-to-emotion)). We'd like to know what thoughts you might have on this, and if share them here, I'm happy to relay them at the next call.

**Comment by enriquediaz** [comment]
@cbeer people on the last Community Call felt the work on this issue has been done, meaning that the move to Emotion for JSS styling is complete and Material UI deprecations have been addressed. Okay to close?
