### ISSUE TITLE
Use new codecov uploader

### ISSUE THREAD

**Issue by cbeer** [ProjectMirador/mirador#3603]
https://about.codecov.io/blog/codecov-uploader-deprecation-plan/
https://github.com/marketplace/actions/codecov

**Comment by enriquediaz** [comment]
Codecov dependency addressed in https://github.com/ProjectMirador/mirador/commit/6b86b827477d08d37ed08ed24e12baf2aff137fe

PR merged to main in https://github.com/ProjectMirador/mirador/pull/3624
