### ISSUE TITLE
Create consistent styleguide.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#363]
The visual and interactive language needs to be clearly specified. 

Dropdowns need consistent styling of states and elements (the list box, etc.), and consistent behaviour.

Buttons should have consistent selected, hover, active, and neutral states. 

Layers or modal menus should have `esc` key functionality and consistent styling that persists with the state of the mode. Top menu especially.

All animations should execute a similar "pace". The application should have a psychologically regular tempo. So big animations might take slightly longer, but should seem to match the faster, smaller animations.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets. We hope that some of this has been addressed by implementing the Material UI framework.
