### ISSUE TITLE
Rewrite Enzyme tests with react-testing-library: Viewer-related tests

### ISSUE THREAD

**Issue by cbeer** [ProjectMirador/mirador#3652]
- [x] __tests__/src/components/OpenSeadragonViewer.test.js
- [x] __tests__/src/components/GalleryView.test.js
- [x] __tests__/src/components/GalleryViewThumbnail.test.js
- [x] __tests__/src/components/VideoViewer.test.js
- [x] __tests__/src/components/ViewerInfo.test.js
- [x] __tests__/src/components/ViewerNavigation.test.js
- [x] __tests__/src/components/WindowViewer.test.js
- [x] __tests__/src/components/WindowThumbnailSettings.test.js
- [x] __tests__/src/components/WindowViewSettings.test.js

Extracted from #3597

**Comment by phil-plencner-hl** [comment]
PR for ViewerInfo.test.js:
https://github.com/ProjectMirador/mirador/pull/3662

**Comment by phil-plencner-hl** [comment]
PR for `WindowViewer.test.js` and `WindowThumbnailSettings.test.js` here:
https://github.com/ProjectMirador/mirador/pull/3672

**Comment by phil-plencner-hl** [comment]
PR for `VideoViewer.test.js` and `WindowViewSettings.test.js` here:
https://github.com/ProjectMirador/mirador/pull/3677

**Comment by phil-plencner-hl** [comment]
PR for `GalleryView.test.js` here:
https://github.com/ProjectMirador/mirador/pull/3687

**Comment by phil-plencner-hl** [comment]
Branch for OpenSeadragonViewer.test.js here:
https://github.com/ProjectMirador/mirador/tree/open-seadragon-viewer-test
Commit here:
https://github.com/ProjectMirador/mirador/commit/57c5395fbd136142d397934b807542d05c7016ea

cc: @cbeer @marlo-longley

**Comment by phil-plencner-hl** [comment]
Moved `__tests__/src/components/AnnotationsOverlay.test.js` to Tricky Enzyme Tests issue: https://github.com/ProjectMirador/mirador/issues/3673
