### ISSUE TITLE
Rewrite Enzyme tests with react-testing-library: Workspace-adjacent tests

### ISSUE THREAD

**Issue by cbeer** [ProjectMirador/mirador#3653]
- [x] `__tests__/src/components/ManifestForm.test.js`
- [x] `__tests__/src/components/ManifestListItem.test.js`
- [x] `__tests__/src/components/ManifestListItemError.test.js`
- [x] `__tests__/src/components/Workspace.test.js`
- [x] `__tests__/src/components/WorkspaceAdd.test.js`
- [x] `__tests__/src/components/WorkspaceAddButton.test.js`
- [x] `__tests__/src/components/WorkspaceArea.test.js`
- [x] `__tests__/src/components/WorkspaceControlPanel.test.js`
- [x] `__tests__/src/components/WorkspaceControlPanelButtons.test.js`
- [x] `__tests__/src/components/WorkspaceElastic.test.js`
- [x] `__tests__/src/components/WorkspaceElasticWindow.test.js`
- [x] `__tests__/src/components/WorkspaceExport.test.js`
- [x] `__tests__/src/components/WorkspaceImport.test.js`
- [x] `__tests__/src/components/WorkspaceMenu.test.js`
- [x] `__tests__/src/components/WorkspaceMenuButton.test.js`
- [x] `__tests__/src/components/WorkspaceMosaic.test.js`
- [x] `__tests__/src/components/WorkspaceOptionsButton.test.js` (ML)
- [x] `__tests__/src/components/WorkspaceOptionsMenu.test.js` (ML)
- [x] `__tests__/src/components/MosaicRenderPreview.test.js`
- [x] `__tests__/src/components/WindowList.test.js`
- [x] `__tests__/src/components/WindowListButton.test.js`

Extracted from #3597

**Comment by marlo-longley** [comment]
@cbeer Since I am refactoring those components I will rewrite the tests for:
```
__tests__/src/components/WorkspaceOptionsButton.test.js
__tests__/src/components/WorkspaceOptionsMenu.test.js
```
