### ISSUE TITLE
User interface review by Stanford UX team - preliminary reivew

### ISSUE THREAD

**Issue by snydman** [ProjectMirador/mirador#367]
In November 2014 three members of the Stanford user experience and web team (who do not regularly work on Mirador) did a review of the Mirador user experience.  It is important to note that the review was a first pass intended to give high-level guidance to the team on possible UI/UX improvements.  They reviewed UI elements, visual design and style, keyboard accessibility, screen layout and mental model/workflow. The team has started digesting and discussing the feedback with the anticipation of UI improvements in the coming months.  

You can see the review at:  http://goo.gl/44PkS8

**Comment by mejackreed** [comment]
Closing this historical issue.
