### ISSUE TITLE
installation on Windows - file path too long

### ISSUE THREAD

**Issue by Sean20** [ProjectMirador/mirador#374]
Windows has a limit on the length of a file path around 255/260 characters. When copying a successful build from a Mac to Windows, the copy failed because some files had path lengths exceeding the maximum length supported by windows. The actual number of fails is dependent on the number of characters in the path to the directory in which the copy or installation is taking place. Examples encountered are 3 to 8 files could not be copied. See attached screen shot
![destination path too long](https://cloud.githubusercontent.com/assets/10401019/5672368/c071cc7e-9787-11e4-852b-3044f0db2b23.jpg)

**Comment by thehabes** [comment]
I was able to build many times today.  You must first clone into whatever server you are going to use (I clone into my apache webapps folder), then run npm install on that folder then run grunt.  This will build the build folder and put mirador.js into it and from there you can start up your server. 

If you clone into a folder that is outside of a server, do the npm install and grunt, then copy these files into a new folder location (like the webapps folder I mentioned before), it will give you the "file name too long" error.  
Just skip the ones that are too long during the copy process.  Once it is done, go to the folder you were just copying into and run npm install and grunt and you will have the files that could not be copied.  Then start your sever.

If you would like to just use the grunt server, then clone the project into any folder, run npm install and grunt.  Then just type grunt server and the m2 project will run at localhost:8000.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
