### ISSUE TITLE
Thumbnails not loading as expected

### ISSUE THREAD

**Issue by JoshuaAPhillips** [ProjectMirador/mirador#3767]
- I am the author or maintainer of this manifest: Yes
- URL: [Digital Anon test manifests](https://raw.githubusercontent.com/JoshuaAPhillips/digital-anon/main/manifests/m1-8-1-manifest.json)
- Manifest hosting institution N/A - using [serverless-iiif](https://github.com/samvera/serverless-iiif)

### Observed behavior
- Description: Images and metadata resolve correctly, but thumbnails do not load using an instance of vanilla Mirador loaded via CDN. I'm using [pyIIIFpres](https://github.com/giacomomarchioro/pyIIIFpres) to generate presentation manifests, which validate fine, and I've tested the links to the thumbnail manifests, which resolve. Thumbs don't load either in the 'Add Resource' screen or in the thumbnail navbar.

- Screenshots / screen recordings / GIFs

![Screenshot 2023-05-04 at 16 47 15](https://user-images.githubusercontent.com/21149530/236261013-851e093f-a1c1-417d-9cfd-704e83343411.png)
![Screenshot 2023-05-04 at 16 47 39](https://user-images.githubusercontent.com/21149530/236261033-de8e42e6-29c2-46ea-aa4a-1b8a9070f12e.png)

Many thanks,
Joshua

**Comment by lutzhelm** [comment]
Just to add, if you want to use a IIIF image service for thumbnails, you'll need to add the `service` property to the `thumbnail`.

[From the spec](https://iiif.io/api/presentation/3.0/#57-content-resources):

> If the content resource is an Image, and a IIIF Image service is available for it, then the id property of the content resource may be a complete URI to any particular representation supported by the Image Service, such as https://example.org/image1/full/1000,/0/default.jpg, but must not be just the URI of the IIIF Image service. Its type value must be the string Image. Its media type may be listed in format, and its height and width may be given as integer values for height and width respectively. The Image should have the service [referenced](https://iiif.io/api/presentation/3.0/#12-terminology) from it using the service property.

**Comment by JoshuaAPhillips** [comment]
Hi both, 

Thanks for your quick reply. Referencing the image directly worked a charm - thank you!
