### ISSUE TITLE
Change side of the SideBar

### ISSUE THREAD

**Issue by Aylambo** [ProjectMirador/mirador#3773]
Hey there,

I'm looking for a way to change the location of the SideBar to the right side of the screen.

I'm trying to do that from the configuration and not in a "bad" way through the CSS.
From what I found online nothing seems to work,
Not sure if any of them are even a real option in the config, but that's some of what I tried:

 sidePanelOptions: {   
        position: 'right',
      },
 sideBarPanel: {
    defaultSide: 'right',
  },
  sideBarPanel: {
    defaultSidebarPanelLocation: 'right',
  },

Any help will be welcome
Thanks,
Aylam

![image](https://github.com/ProjectMirador/mirador/assets/81359906/79993b46-f9b1-44ac-84cb-e01e4d1fe1c3)

**Comment by lutzhelm** [comment]
While browsing through our demos I stumbled upon a theme option that changes the order of all UI elements from LTR to RTL. That does not only move the side bar panel to the right but also the close button to the left etc. Maybe this is something you can work with.

https://github.com/ProjectMirador/mirador/blob/master/__tests__/integration/mirador/rtl.html#L49-L51

https://mirador-dev.netlify.app/__tests__/integration/mirador/rtl.html

**Comment by Aylambo** [comment]
Yep, that definitely helped:)
Cheers!

**Comment by sete-arch** [comment]
> ![image](https://user-images.githubusercontent.com/81359906/249098290-79993b46-f9b1-44ac-84cb-e01e4d1fe1c3.png)

Question not related to the issue, but not sure how I could ask otherwise.
Did you use a plugin for the buttons in the top right corner of the side panel ? (although I couldn't find any)
Or is it custom ?

**Comment by Aylambo** [comment]
Yes, some of them are custom plugins that I've created and added to the mirador-image-tools (the full-screen and gallery buttons). The others were 'moved' there using jQuery and CSS. 
However, we eventually decided not to use them and returned everything to its original place because it created too much mess when we started working with multiple images in the side-by-side view.

**Comment by lutzhelm** [comment]
@Aylambo Do you still see any open questions regarding this issue? Otherwise I would like to close it.

**Comment by Aylambo** [comment]
@lutzhelm I'm all good , Thanks a lot :)
