### ISSUE TITLE
The "rendering" property of a canvas is not displayed

### ISSUE THREAD

**Issue by dimitrove** [ProjectMirador/mirador#3774]
- I am the author or maintainer of this manifest: Yes
- URL: 
- Manifest hosting institution 

### Observed behavior
- Description:I can not be sure my manifest file is correct. It is attached bellow.
The image on the canvas is displayed. Nothing is displayed related to the "rendering" property.
```
[manifest_2.txt](https://github.com/ProjectMirador/mirador/files/11970089/manifest_2.txt)

**Comment by enriquediaz** [comment]
Hello @dimitrove! The official IIIF website hosts a Presentation API Validator that you can upload your manifest to for it to run checks: https://presentation-validator.iiif.io/ 

Depending on the version of the Presentation API you wish to comply with you will see different sets of warnings or errors that should help you determine what is amiss.

**Comment by lutzhelm** [comment]
Mirador does currently only support `rendering` at the Manifest level:

https://github.com/ProjectMirador/mirador/blob/3c121dbe99bae4eab910cb2df00e93904bc123ea/src/containers/ManifestRelatedLinks.js#L24

https://github.com/ProjectMirador/mirador/blob/3c121dbe99bae4eab910cb2df00e93904bc123ea/src/state/selectors/manifests.js#L164-L173

**Comment by dimitrove** [comment]
Thank you.
