### ISSUE TITLE
Sidebar icons vanish when specifying 'window' setting

### ISSUE THREAD

**Issue by JoshuaAPhillips** [ProjectMirador/mirador#3777]
Hello all,

I might be missing something blindingly obvious, but the sidebar icons in my mirador test install (from CDN) have vanished. Screencap below and HTML. I've replicated the bug on Safari and Chrome, and it persists with different workspace settings. I'd be grateful for any insight into this.

HTML:

```
<script type="text/javascript">
var mirador = Mirador.viewer({
  "id": "my-mirador",
  "catalog": [
        {...}
    ],
    window: [
      {defaultView: 'single'}
    ]
});
</script>
```

<img width="1440" alt="Screenshot 2023-07-26 at 21 42 54" src="https://github.com/ProjectMirador/mirador/assets/21149530/6b4dae17-54bb-458d-a691-33a2e1108a7e">

UPDATE: this error seems to occur when specifying a 'defaultView' setting for 'window' as so:

```
            window: [
            {
              defaultView: 'gallery'
            }
          ]
```
Specifying `allowWindowSidebar` doesn't seem to make a difference, and even an empty `Window` variable will trigger the bug...

**Comment by lutzhelm** [comment]
The `window` config property needs to be an object instead of an array. Please try
```
window: {
  defaultView: 'gallery'
}
```

**Comment by JoshuaAPhillips** [comment]
Thanks @lutzhelm, this has worked a treat.
