### ISSUE TITLE
Missing dependency '@babel/plugin-proposal-private-property-in-object'

### ISSUE THREAD

**Issue by PR-Obst** [ProjectMirador/mirador#3778]
When trying to run mirador after installing with npm it throws an error because of missing package:
 
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Cannot find package '@babel/plugin-proposal-private-property-in-object' imported from /home/user/mirador/babel-virtual-resolve-base.js

**Comment by lutzhelm** [comment]
This seems to have been fixed by #3779, is that correct?

**Comment by PR-Obst** [comment]
Yes, seems so! Great :)
