### ISSUE TITLE
Bug in tiling code: unsorted image sizes

### ISSUE THREAD

**Issue by dellamonica** [ProjectMirador/mirador#3783]
- I am the author or maintainer of this manifest: No
- URL: https://cdm16003.contentdm.oclc.org/digital/iiif/p16003coll20/1596/info.json
- Manifest hosting institution OCLC.org

### Observed behavior

Tiling is broken. I believe the reason is that the sizes array in the source is sorted by _descending measures_ instead of ascending. This causes the tile calculation to produce negative values and issue hundreds of "Bad Requests" due to negative width/height URL parameters.

This could be fixed by sorting the sizes in the code (I have no control over the image manifest).

![image](https://github.com/ProjectMirador/mirador/assets/6547066/505491a5-c1ba-4ce5-b808-bbf4530d42dc)

**Comment by lutzhelm** [comment]
This is an issue in [OpenSeadragon](https://github.com/openseadragon/openseadragon/), not in Mirador's code itself. As far as I understand, neither version 2 nor version 3 of the Image API make any assumptions about the order of `sizes`. Assuming this is correct, I'm going to have a look and file an issue with Open Seadragon; I might also suggest a PR to fix this myself. However, we will be dependent on an OpenSeadragon release to fix this in Mirador.

**Comment by dellamonica** [comment]
> As far as I understand, neither version 2 nor version 3 of the Image API make any assumptions about the order of `sizes`. 

This is my understanding as well. Please post the link to the OpenSeadragon issue here if possible, or let me know if you prefer that I file the issue myself.
