### ISSUE TITLE
MUI5: CompanionArea is popping closed on WindowSidebarButton selection

### ISSUE THREAD

**Issue by marlo-longley** [ProjectMirador/mirador#3844]
main branch (correct)

https://github.com/ProjectMirador/mirador/assets/1328900/113b2fd9-7a20-41b6-806d-6b86587dc7b6

mui5 (glitchy!)

https://github.com/ProjectMirador/mirador/assets/1328900/a5fbddaf-64a1-4731-90f1-14aa75789b2b

**Comment by cbeer** [comment]
It looks like the `minWidth` styling got dropped in 9c8185bec4fafa8a19dddf208c8e9e723e3c46c7

**Comment by marlo-longley** [comment]
Thanks @cbeer -- confirmed this fix works for me locally.
