### ISSUE TITLE
Internet Explorer 8 Won't build Mirador.

### ISSUE THREAD

**Issue by thehabes** [ProjectMirador/mirador#389]
I am using internet explorer 8, version 8.0.7601.17514 and trying to run off my local machine. The grunt build is successful and I am running it off an apache tomcat instance which starts up with no errors. The same build works fine in Chrome and Firefox off the tomcat localhost server.

**Comment by thehabes** [comment]
I traced the error down to slotObjects, and when slotObjects attempts to be defined it never happens and breaks on the line 
return slotObjects;

**Comment by aeschylus** [comment]
Good catch. We'll test this out.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
