### ISSUE TITLE
OSD v4.1.0 handling (impacts to M4, serverless)

### ISSUE THREAD

**Issue by mnyrop** [ProjectMirador/mirador#3897]
Hi all, starting a new ticket to wrap additional context around #3783 and create a spot to discuss.

Recap:
- OSD v4.1.0 breaks tiling for IIIF image API sources that don't specify hard-coded `sizes`  (e.g., [serverless-iiif](https://github.com/samvera/serverless-iiif), cc @mbklein @mathewjordan)
  + See: [Demo with OSD v3.1](https://mnyrop.github.io/osd-region-bug-demo/osd/v3-1-0/) (works)
  + See: [Demo with OSD v4.1](https://mnyrop.github.io/osd-region-bug-demo/osd/v4-1-0/) (funky)
- Mirador v4.x alpha versions use the buggy OSD.
  + See: [Demo with 4.0.0-alpha.1](https://mnyrop.github.io/osd-region-bug-demo/mirador/v4-alpha/) (funky)
  + (This version is deployed to the [Mirador demo](https://mirador-dev.netlify.app/__tests__/integration/mirador/), so users are *using* it if not deploying it)
- Progress/conversation so far with OSD maintainer(s):
  + OSD main branch includes working fix (see: [Demo from HEAD](https://mnyrop.github.io/osd-region-bug-demo/osd/head/))
  + Maintainer(s) waiting for major release to include fix (See: https://github.com/openseadragon/openseadragon/issues/2452#issuecomment-1892586216)
  + @mbklein started discussion to advocate for an OSD v4.1.1 patched release before major version (See: https://github.com/openseadragon/openseadragon/discussions/2501)

Some questions/ideas:
 - Can Mirador v4.x-alpha roll back to OSD v3.1.0 or v4.0.0?
 - If not, can the prod Mirador 4-RC wait until a fixed OSD is available?
 - Anyone from Mirador able to chime in over on the OSD discussion? https://github.com/openseadragon/openseadragon/discussions/2501 to coordinate?

Thanks for your time! Hopefully this verbose ticket will help coordinate across OSD, Mirador, and Serverless-IIIF since the issue exists ambiguously between them.

**Comment by mbklein** [comment]
OpenSeadragon v4.1.1 has been released with a fix for this issue. It might be worth updating
```json
"openseadragon": "^2.4.2 || ^3.0.0 || ^4.0.0",
```
to something like
```json
"openseadragon": "^2.4.2 || ^3.0.0 || ^4.0.0 <4.1.0 || ^4.0.0 >=4.1.1",
```
to specifically exclude the buggy version.
