### ISSUE TITLE
Images from Harvard manifest in the Mirador demo are not working, service answers with AWS WAF challenge header

### ISSUE THREAD

**Issue by lutzhelm** [ProjectMirador/mirador#3928]
Mirador uses the Havard Art Museums' manifest [Self-Portrait Dedicated to Paul Gauguin](https://iiif.harvardartmuseums.org/manifests/object/299843) for one of the two initial workspace windows of the demo workspace. Currently, the image service at https://ids.lib.harvard.edu/ids/iiif/47174896/ answers fetch requests with an empty HTTP `202 Accepted` response with an `x-amzn-waf-action: challenge` header.

This leads to an error modal as the first thing to encounter if someone visits https://mirador-dev.netlify.app .

We should ever replace the manifest with a working example or find out if we can get this to work again somehow.

**Comment by jcoyne** [comment]
WAF = Web Application Firewall

**Comment by lutzhelm** [comment]
Just two short additions:
* There's an update about what is happening by @enriquediaz in the "general" channel of the IIIf Slack.
* The problem also affects the local execution of integration tests that rely on the availability Havard manifests.

**Comment by cbeer** [comment]
It looks like this has been resolved?
