### ISSUE TITLE
IIIF Authorization Flow 2.0 support

### ISSUE THREAD

**Issue by agomeister** [ProjectMirador/mirador#3934]
Hello

Does anybody know is there [IIIF Authorization Flow](https://iiif.io/api/auth/2.0/) 2.0 API support in Mirador 4.x ? 

Thank you!

**Comment by lutzhelm** [comment]
Duplicate of #3789

Sorry for the late answer. Mirador 4 does not currently IIIF Authorization Flow API 2.0; it does still need to be implemented.
