### ISSUE TITLE
When searching it calls the search endpoint twice

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [ProjectMirador/mirador#3936]
Hi,

I noticed this on our own Mirador instance and have confirmed it on the [mirador demo](https://mirador-dev.netlify.app/). If IIIF search is enabled and you run a search through the interface, you'll notice that it makes two identical calls to the search service at the same time, so I'm wondering if there's some minor bug in the code. It doesn't prevent it from working but does add unnecessary overhead to the search service. See in the screenshot, you can see the duplication in the dev panel for the Wellcome example in the demo (the first is for the autocomplete, but the next two are just identical).

![image](https://github.com/user-attachments/assets/adf371ae-5329-43a9-9d89-ccc862be1661)

Thanks,

Joe

**Comment by fstoe** [comment]
One fetch is for the autocomplete, the other fetch is the actual fetching of the results. 
They look similar in the network console but have different request urls `https://iiif.wellcomecollection.org/search/v0/b18035723?q=the` vs `https://iiif.wellcomecollection.org/search/autocomplete/v1/b18035723?q=wei`
