### ISSUE TITLE
In light of customizable layouts, do we need "freeform mode" or simply the ability to move slots around?

### ISSUE THREAD

**Issue by snydman** [ProjectMirador/mirador#395]

**Comment by blalbrit** [comment]
I could see arguments for both.  Moving slots around (or re-sizing slots) might be adequate for most comparison use-cases.

**Comment by aeschylus** [comment]
What would it mean to "move slots around"? Is this the same as resizing them?

**Comment by aeschylus** [comment]
Would this include moving objects between slots/switching places?

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

We now have this functionality in Mirador 3!
