### ISSUE TITLE
babel-plugin-lodash is no longer maintained

### ISSUE THREAD

**Issue by jcoyne** [ProjectMirador/mirador#3965]
https://github.com/lodash/babel-plugin-lodash

This causes deprecated "glob 7.2.3"

**Comment by marlo-longley** [comment]
I wonder how much of lodash can be written in vanilla JS these days. We seem to rely on `lodash/flatten` and `lodash/omit` most heavily.

**Comment by jcoyne** [comment]
The babel plugin was deprecated by lodash: https://github.com/lodash/lodash/issues/5570

**Comment by jcoyne** [comment]
Actually, it seem like lodash has no maintainer at the moment.

**Comment by marlo-longley** [comment]
Closed by https://github.com/ProjectMirador/mirador/pull/4038
