### ISSUE TITLE
Design needed for allowing multiple annotation endpoints

### ISSUE THREAD

**Issue by rsinghal** [ProjectMirador/mirador#403]
User needs to be able to select which endpoint to create/read/update/delete from.  How to visually differentiate between annotations from different endpoints?

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
