### ISSUE TITLE
Embedded events need to be completed when killed by parent page (iframe)

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#406]
In an embedded mirador instance, go to a zooming view and drag the canvas to move it. Releasing the click outside of the canvas (in the parent page where the child cannot register it) will cause the dragging behaviour to "stick" to the mouse until somehow a mouseup event is registered. But clicking inside of the child will just register another mousedown, causing a permanent disruption of dragging behaviour in openseadragon.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
