### ISSUE TITLE
Can we add a place to input percentage of zoom

### ISSUE THREAD

**Issue by jeffreycwitt** [ProjectMirador/mirador#411]
Can we add a place to input percentage of zoom? The mouse zoom is a nice feature. But as someone who transcribing text using an image in mirador, it actually very hard to the right level of zoom using a mouse (especially with a mac tracpad). It would be a lot easier, if I could just put in the precise percentage of desired zoom.

**Comment by beaudet** [comment]
I suggest adding this to Mirador 2.1 release in some form.  Simply building acceleration into the zoom rather than using a fixed increment might suffice for Mirador 2.1

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
