### ISSUE TITLE
Navigation for right-to-left objects in all views (including film strip, scroll, etc)

### ISSUE THREAD

**Issue by snydman** [ProjectMirador/mirador#419]

**Comment by rsinghal** [comment]
Also, the HUD arrows need to know when it's a right-to-left objects.

**Comment by rsinghal** [comment]
This also affects the display of thumbnails/text on the manifest list page.

**Comment by lavigne** [comment]
Is there any update on this issue?  I'm working on a project that requires right-to-left navigation but this doesn't seem to be in place yet in Mirador.  Our manifests are setting the viewingDirection property but Mirador doesn't seem to be using it.  I've even hard-coded Mirador's internal "viewingDirection" attribute to "right-to-left" just to see if the functionality was there but that doesn't seem to have any affect either.

**Comment by mejackreed** [comment]
Resolved in Mirador 3
