### ISSUE TITLE
Preserve zoom level on window itself between layout changes (not just in save configuration), and check for it when "updating" the window.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#485]

**Comment by aeschylus** [comment]
To clarify. Operations like opening and closing the table of contents can "see-saw" the image out to a minimum zoom level, since expanding the image area keeps the zoom level and contracting it does not, for whatever reason.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
