### ISSUE TITLE
When thumbnails first load, not all thumbs are requested unless the user begins to scroll.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#529]
![screen shot 2015-04-30 at 13 36 29](https://cloud.githubusercontent.com/assets/145874/7422004/22fbfb86-ef3e-11e4-9536-8c8fc118b6e2.png)

**Comment by blalbrit** [comment]
Also noting that clicking a second time on the thumbnail icon will get the rest loading.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
