### ISSUE TITLE
Make annotation selectable

### ISSUE THREAD

**Issue by rsinghal** [ProjectMirador/mirador#535]
And won't hide until annotation is de-selected.  This is helpful, for example, when a video is embedded and a user wants to watch without it disappearing.

**Comment by aeschylus** [comment]
Pretty sure this one is closed.

**Comment by rsinghal** [comment]
Not implemented yet

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
