### ISSUE TITLE
Support drag and drop for non-IIIF resources

### ISSUE THREAD

**Issue by snydman** [ProjectMirador/mirador#537]
As a user, if I find an image on the web I want to drag that image to an empty Mirador slot so that I can compare that image to other images in my mirador workspace. 

Related to #520

**Comment by rsinghal** [comment]
related to #536

**Comment by camillevilla** [comment]
@snydman it's here! (I honestly have no idea when this was implemented?? @mejackreed)
![dragndrop](https://user-images.githubusercontent.com/5402927/101119457-3bd84200-35a0-11eb-8fbe-f9cb14b9fae4.gif)
..)

**Comment by mejackreed** [comment]
@cbeer gets the credit on this one!
