### ISSUE TITLE
Annotation with motivation and resource as objects rather than array fails to update

### ISSUE THREAD

**Issue by glenrobson** [ProjectMirador/mirador#568]
See IIIF/iiif.io#475 for background on why I have motivation and resources as objects but when I try and edit an annotation it results in motivation being converted into an array of characters and resource is removed. This is the original unedited annotation:

```
{
    "@id" : "http://dev.llgc.org.uk/annotation/1435013176681",
    "@type" : "oa:Annotation",
    "resource" : {
      "@id" : "_:b2",
      "@type" : "dctypes:Text",
      "format" : "text/html",
      "chars" : "<p>THE NATIONAL LIBRARY OF WALES</p>"
    },
    "on" : {
      "@id" : "_:b0",
      "@type" : "oa:SpecificResource",
      "selector" : {
        "@id" : "_:b1",
        "@type" : "oa:FragmentSelector",
        "value" : "xywh=1716,2751,1300,72"
      },
      "source" : "http://dams.llgc.org.uk/iiif/4574752/canvas/4574755.json"
    },
    "motivation" : "oa:commenting"
  }
```

and after editing it looks like this:

```
{
    "@id" : "http://dev.llgc.org.uk/annotation/1435013176681",
    "@type" : "oa:Annotation",
    "resource" : ,
    "on" : {
      "@id" : "_:b0",
      "@type" : "oa:SpecificResource",
      "selector" : {
        "@id" : "_:b1",
        "@type" : "oa:FragmentSelector",
        "value" : "xywh=1716,2751,1300,72"
      },
      "source" : "http://dams.llgc.org.uk/iiif/4574752/canvas/4574755.json"
    },
    "motivation" : [ "o","a",":","c","o","m","m","e","n","t","i","n","g" ]
  }
```

I've traced where this conversion occurs and it seems to be in [osd-canvas-renderer.js](../blob/master/js/src/annotations/osd-canvas-renderer.js) and the following lines:

```
403        //remove all tag-related content in annotation
404        oaAnno.motivation = jQuery.grep(oaAnno.motivation, function(value) {
405            return value !== "oa:tagging";
406        });
407        oaAnno.resource = jQuery.grep(oaAnno.resource, function(value) {
408            return value["@type"] !== "oa:Tag";
409        });
```

reading the docs for jQuery.grep it expects an array as a parameter, for motivation which is a string it seems to convert this into an array of characters. For the resource which is an object it seems to just remove it.

**Comment by rsinghal** [comment]
@glenrobson Does this manifest have a public URL I can use to test against?

**Comment by aeschylus** [comment]
Similarly curious about this in light of all the new annotation work that has been done.

**Comment by glenrobson** [comment]
Hi,

Sorry both for the delay in getting back to you. Ill create a public manifest for testing now. I came across this issue when developing the Simple Annotation Server and in the end created a local context.json which specifies motivation as an array (see [iiif-2.0.json](https://github.com/glenrobson/SimpleAnnotationServer/blob/master/src/main/webapp/contexts/iiif-2.0.json) - motivation has @set). If this issue can be fixed then I can go back to using the standard IIIF context.json.

Thanks

Glen

**Comment by glenrobson** [comment]
Testing with a more recent version of mirador and it seems the initial problem is fixed. It now handles the motivation as an object and doesn't throw any errors. I've done some further testing and found one issue. If you update an annotation that had a comment and add a new tag you get the following in the annotation:

```
{
  "@id" : "http://dev.llgc.org.uk/annotation/1462748538293",
  "@type" : "oa:Annotation",
  "resource" : [ {
    "@type" : "oa:Tag",
    "chars" : "tag"
  } ],
  "on" : {
    "@id" : "_:b0",
    "@type" : "oa:SpecificResource",
    "selector" : {
      "@id" : "_:b1",
      "@type" : "oa:FragmentSelector",
      "value" : "xywh=3402,1497,512,437"
    },
    "full" : "http://dev.llgc.org.uk/iiif/examples/photos/canvas/3891216.json"
  },
  "motivation" : [ "o", "a", ":", "c", "o", "m", "m", "e", "n", "t", "i", "n", "g", "oa:tagging" ],
  "@context" : "file:///Users/gmr/development/mvn/SAS/master/SimpleAnnotationServer/src/main/webapp/contexts/iiif-2.0.json"
}
```
which is missing the annotation text and has converted the oa:commenting to an array of characters. Creating a new annotation with a comment and a tag works correctly. Editing an annotation that already had a comment and tag also works OK so this only seems a problem if you add a tag to an annotation that only had a comment. 

Steps to reproduce:

 * Download SAS
 * replace [iiif-2.0.json](https://github.com/glenrobson/SimpleAnnotationServer/blob/master/src/main/webapp/contexts/iiif-2.0.json) with the iiif version [context.json](http://iiif.io/api/presentation/2/context.json).
 * start SAS (mvn jetty:run)
 * navigate to http://localhost:8888/index.html
 * select one of the manuscripts
 * create an annotation on one of the pages adding only a comment
 * edit the annotation and add a tag.
 * when you click update save the annotation will only show the tag not the comment.

happy to do more testing if you want to avoid doing the above.

Glen

**Comment by glenrobson** [comment]
Note I'm using the master branch build of Mirador from 2016-02-29.

**Comment by aeschylus** [comment]
@rsinghal 

In your review of annotation PR's/cleanup for 2.1, can you confirm that this data munging isn't happening any more? We should also write some tests for this.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
