### ISSUE TITLE
Links to URIs in HTML formatted metadata do not show properly

### ISSUE THREAD

**Issue by hashimmm** [ProjectMirador/mirador#571]
Some HTML markup is allowed in certain IIIF Presentation manifest metadata fields. But if they contain absolute URL links, those links do not show up properly because Mirador tries to convert them into links again.
A simple solution could be something like this: https://github.com/IIIF/mirador/commit/297f7eb34fd39392b976eeba464e224acf4f5b52

**Comment by rsinghal** [comment]
An example manifest would be helpful

**Comment by jbaiter** [comment]
Here is an example manifest of one of our manuscripts that has an absolute Link in a metadata field:
https://gist.github.com/jbaiter/4adc5e1d357e4a0a630bdc0104a9f3c6
