### ISSUE TITLE
Delay manifest loading until windows open, loading only the necessary manifests.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#575]
Currently we order the manifest requests, but send them off before the windows are loaded. This can cause an interactive delay as all the manifests arrive at nearly the same time. The [queuing of the JS event loop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop) is such that those events that finish first, get to call their (synchronous) rendering callbacks first. Therefore, if a bunch of requests finish around the same time, it can be 500ms or more before the requests that drive the display of the open windows get to run their rendering code.

We should prioritise the window manifests accordingly by delaying the _initial dispatch_ of the other, low-priority manifests requests.

**Comment by mejackreed** [comment]
This is resolved in Mirador 3, where only window manifests are loaded, until the load screen is shown.
