### ISSUE TITLE
Create a placeholder for empty canvases (something like "this page blank")

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#577]
Collections mode will make this much easier, since we can now initialise canvases without a tilesource, write text and annotations onto them without any background image, etc.

**Comment by aeschylus** [comment]
Regis writes (in https://github.com/IIIF/m1/issues/83#issuecomment-118314472):

Here is the manifest of the virtual reconstruction of the "Florus dispersus" manuscript (http://demos.biblissima-condorcet.fr/iiif/metadata/florus-dispersus/manifest.json) (see Mirador demo, showing the known lacunae w/ empty canvases and the internal codicological/intellectual structure by means of ranges).

Possible fixture object for this ticket and this one in the new repo: Presentation API 2.0 support for ranges and table of contents display

NB:

images coming from e-codices and Gallica
empty canvases: no "images" property and fictive height/width to be compliant with P-API [1]
[1] The data model supports this use case, and the cardinality between Canvas and Content is (0..*) according to P-API, but on the other hand the spec says that height and a width are mandatory.
P-API 2.0: "Each canvas should have one or more content resources associated with it. Zero is possible but unlikely; it represents the case where the page exists (or existed) but has not been digitized."
=> this is a case of unlikelihood :blush: (ping @azaroth42)

**Comment by aeschylus** [comment]
#913 is a duplicate of this.

**Comment by regisrob** [comment]
Here is an example of a manifest with blank canvases (and canvas-level metadata): http://iiif.biblissima.fr/bbmn-1713-t1/manifest.json
