### ISSUE TITLE
Add mirador as bower package

### ISSUE THREAD

**Issue by edsu** [ProjectMirador/mirador#583]
It would be useful to add mirador as a package to bower, for integration in other projects that use bower.

**Comment by aeschylus** [comment]
Agreed. Our build system needs a bit of work. Others have also requested it as an npm package (for use with browserify). I will see if I can add it to bower this weekend.

**Comment by tpendragon** [comment]
@aeschylus I realize this was over a year ago, but any word?

**Comment by mejackreed** [comment]
I think the goal is to move forward with NPM instead of bower. I'd vote for closing this issue. 

From bower.io
<img width="969" alt="screen shot 2017-10-27 at 8 55 25 am" src="https://user-images.githubusercontent.com/1656824/32104938-9f10e64e-baf4-11e7-82f2-517b1322a6f5.png">

**Comment by mejackreed** [comment]
Mirador is now published successfully on npm. WIth bower deprecated, I'm closing this issue.
