### ISSUE TITLE
Verify if canvas/image scaling works when image is larger than canvas

### ISSUE THREAD

**Issue by azaroth42** [ProjectMirador/mirador#587]
e.g. the color image on the first canvas of http://dlss-dev-azaroth.stanford.edu/prezi/m804/manifest.json

The annotation areas don't line up, but the rest of the canvases do. Data /looks/ correctly scaled against the canvas size, which is smaller than the image size.

**Comment by aeschylus** [comment]
Closed since this manifest no longer resolves, and I believe this issue was handled sometime around 2.5.
