### ISSUE TITLE
Right panel should have controls to move it to the bottom of screen.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#592]
"Flexibly rearrange tools, panels, etc. (above or below, big or small)"

**Comment by aeschylus** [comment]
![transcription panel to the right](https://cloud.githubusercontent.com/assets/145874/9038696/5572e98c-39c4-11e5-9ae2-346b15d1c093.png)
![transcription panel on the bottom](https://cloud.githubusercontent.com/assets/145874/9038695/55725f44-39c4-11e5-9a4e-4e80d9c4c070.png)
![reading with everything](https://cloud.githubusercontent.com/assets/145874/9038697/5573ba92-39c4-11e5-8e33-53276401ea0b.png)

**Comment by camillevilla** [comment]
What a time! This functionality was implemented in Mirador 3.
