### ISSUE TITLE
Annotation module - determine whether user has right to modify Annotation/AnnotationList

### ISSUE THREAD

**Issue by mikeapp** [ProjectMirador/mirador#593]
Transcription UI must know whether to allow user to modify the membership of the AnnotationList (i.e., add/remove Annotations).   Ideally it would also be able to determine permissions at the Annotation level, in case they are not the same as those for the list.    The annotation module should have API calls to query these permissions, but nothing is specified in the Presentation API that would provide this information.

**Comment by rsinghal** [comment]
I have written some code to do that with CATCH.  Look at [catchEndpoint.js](https://github.com/IIIF/mirador/blob/master/js/src/annotations/catchEndpoint.js#L165) and [annotationTooltip.js](https://github.com/IIIF/mirador/blob/master/js/src/annotations/annotationTooltip.js#L72)

Permissions are on an annotation level basis with Catch.

**Comment by azaroth42** [comment]
:-1: to relying on the Annotator permissions block. Even the annotator devs think it's a bad idea.  It makes the results un-cache-able, as the representation is necessarily user specific for all users, regardless of whether they even have a client that can make changes, let alone the desire, let alone the permissions.

**Comment by rsinghal** [comment]
That is absolutely a requirement in a MOOC.  Each annotation must have user specific permissions.  Each endpoint can define how it handles permissions - I had to write it based on how CATCH stores permissions.  Mirador doesn't need to know the specifics, it simply needs to request whether or not something is available to a particular user.

**Comment by aeschylus** [comment]
The catchModule and all other similar modules (the FrickEndpoint
<https://gist.github.com/Wedjaa/1f8a1fd0c0c4a904572d>, for example, or
those created by Shaun and Glen for their simple backends) are written in
such a way that they can be changed out when a better solution has emerged.
Annotator.js does not exist in the Mirador codebase anymore, so this is
only something for the backend to make use of.

Another question is whether this kind of querying can be done outside
Mirador (hopefully), but it will still require some way to communicate
permissions to the user.

What does the spec have to say about this very central use case? I have
found no mention of permissions or authorisation on annotation lists in the
presentation API. Perhaps it's possible in OA?

**Comment by azaroth42** [comment]
The specs intentionally say nothing at all about authorization or permissions.  Even the authentication specification says nothing about authorization, because that is all business logic.  It's not possible in OA. Nor in the WG model (at least so far).  For any resource.  There's also no IIIF resource creation/management specification -- as these use cases were not prioritized for work this year at the London WG meeting.

There are several ways to implement permissions better than embedding user/transaction specific information in the representation:
 * Associate WebACLs with the resources 
 * Check the Allow HTTP Header for the resource for the methods allowed when retrieving it (with GET)
 * Better, make an OPTIONS request and check the Allow HTTP header on that response.

**Comment by aeschylus** [comment]
@rsinghal Is there a way Catch can be modified to intercept these from the incoming header? If it is sent from Catch, I'm certain we could parse it out of the response headers. I'm really not familiar with the level at which Catch is operating (it is just dealing with the contents, or is there a wider range of modification that would allow this to be written?).

**Comment by rsinghal** [comment]
Adding @jmiranda to this discussion,  I doubt this can be changed in CATCH because it is used by a number of applications.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
