### ISSUE TITLE
Keyboard shortcuts in editing mode.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#596]
With editing area focused:
"tab" or "down": should focus the first/next item in the list.
"ctrl+enter": finishes editing and goes to the next item in the list, entering edit mode.
"shift+arrow": bump/pan canvas in that direction

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
