### ISSUE TITLE
Saving system (bookmarking) failing very often.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#616]

**Comment by markmatney** [comment]
Any current info on the status of this ticket (cases that fail, or any progress that's been made)?

**Comment by aeschylus** [comment]
The last time it was discussed, we were decided on removing the remote/url-based part of the saving system entirely, but making it very easy to implement through the API. Other than that, I think the only work that's been done is to merge Weedja's PR implementing JSONBlob storage as a plugin (similar to the annotation apaptor). 

One thing that might be useful is to create a demo page with the way to implement these outside of Mirador. Currently, turning off saving also makes it hard to get the full state into local storage (instead of it being automatic). As an intermediate step, it probably would have made more sense to provide an option that would use localStorage, but not jsonblob/a remote json store.

**Comment by markmatney** [comment]
Ah, okay. It looks like the code hasn't been fully merged to `release2.1`, since I'm getting different behavior compared to `master`.

**Comment by rsinghal** [comment]
@aeschylus That's not true.  Saving your session to local storage is a different control than the bookmark functionality.  You can have one without the other.

@markmatney What code hasn't been fully merged into `release2.1`?  It should be fully merged with `master` plus all of the additional new work.

**Comment by markmatney** [comment]
@rsinghal sorry bad choice of words, I'm just noting that between those two branches, the bookmarking feature behaves differently (and seems to work better on `master`)

**Comment by rsinghal** [comment]
How so?  There is nothing fundamentally different between the two branches, other than the fact that we don't refer to `parent` in `bookmarkPanel` in `release2.1` and we get state from the state object.

**Comment by markmatney** [comment]
Nevermind, I was mistaken.

**Comment by aeschylus** [comment]
@rsinghal Thanks, I think I've been out of the grind for too long. Should make things interesting in May!

**Comment by markmatney** [comment]
Okay, so to clarify:

1) Is bookmarking by `POST`ing and `GET`ting JSONBlobs going to be enabled by default? The code on `refactor` indicates yes, since the app `POST`s to the JSONBlobAPI endpoint whenever the workspace layout changes.

2) The session will either be stored in localStorage, or at the JSONBlobAPI endpoint, but not both, right?

**Comment by rsinghal** [comment]
Good point, @markmatney.  We should fix that particular conditional.  The goal is to prevent local storage/URL manipulation if saveSession is off, but loading from a bookmark should not be prevented by that particular setting.

In general, the bookmark feature is really problematic.  It assumes that Mirador takes up the entire page and so therefore, you are bookmarking this Mirador instance.  If someone is embedding Mirador into their application, they should rightfully disable bookmarking and get the Mirador state and use that information to craft some sort of URL.  Or something like that.  It may be best, going forward, to have bookmarking set to false by default, and let developers enable it if they understand the caveats.

**Comment by beaudet** [comment]
The approach taken for dragging and dropping manifests into Mirador involves parsing a URL.  I wonder if a similar approach could be taken for such bookmarking.  That is,  the URL of the containing page might have a Mirador instance ID (for cases of multiple instances per page) as a parameter name and value as corresponding bookmark GUID or encoded configuration data?




-------- Original message --------

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
