### ISSUE TITLE
Zoom into and frame annotation region on list item click

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#618]
https://github.com/IIIF/m1/blob/ed07999d16fe8ea9f9577607217998b46b806b1c/js/src/annotationLayerRegionController.js

specifically: https://github.com/IIIF/m1/blob/ed07999d16fe8ea9f9577607217998b46b806b1c/js/src/annotationLayerRegionController.js#L91-L103

Here is some code that did that in Mirador 1.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
