### ISSUE TITLE
Improve CSS styling of Annotation/Edit Panel

### ISSUE THREAD

**Issue by sdellis** [ProjectMirador/mirador#619]
Use similar approach to the "thumbs filmstrip" with some transparency over dark background.  Perhaps eventually we can allow the user to configure this for personal preference.

**Comment by sdellis** [comment]
I can't add the "Transcription" label, but this refers to the current transcription branch work.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
