### ISSUE TITLE
Adjust height of thumbnail strip when editor window loaded

### ISSUE THREAD

**Issue by sdellis** [ProjectMirador/mirador#620]
The viewer window, thumbnail strip, and annotations/editor panel must be "stackable."

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
