### ISSUE TITLE
Annotations should auto-save

### ISSUE THREAD

**Issue by sdellis** [ProjectMirador/mirador#623]
Like many single page web apps, the annotation content should be automatically saved in the background.  Instead of a "Save" button, there should be a "Publish" button so the user can make annotations discoverable/accessible to the public (or eventually groups).  This allows the user to work on content over a span of time before releasing the annotation.

(This is an important part of the Transcription/Translation work.)

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
