### ISSUE TITLE
Clarify behavior for adding first annotation to a list on a canvas

### ISSUE THREAD

**Issue by sdellis** [ProjectMirador/mirador#625]
If an endpoint is specified, should there be an empty list so we can toggle the annotations/editor panel?  Should the number of annotations on the list be represented like in this image?

![transcription-panel- on-the-bottom](https://cloud.githubusercontent.com/assets/609368/9203278/2c738e90-4024-11e5-9e90-d04ff0b79b1e.png)

**Comment by aeschylus** [comment]
Seems reasonable to indicate the number of annotations. For the current sprint I think the list/layer/endpoint UI element should always be defined.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
