### ISSUE TITLE
Add "Box Annotation" edit button

### ISSUE THREAD

**Issue by sdellis** [ProjectMirador/mirador#628]
Add this to the toolbar of the Annotations/Editor Panel.  When selected, multiple boxes can be drawn in the view window.  This should create corresponding blank annotation items in the Editor Panel, with the cursor focused on the textarea that corresponds to the last box created.  Additional Boxes can be drawn until user deselects Box Annotation Edit Button.  When a region is selected on the canvas, the corresponding item should be highlighted (and zoomed?).  

Question: Is there a separate "edit" button, or does selecting an annotation instantly make it editable by anyone who has permission?  I don't see an "edit" button in the mocks (see image).

![transcription panel to the right](https://cloud.githubusercontent.com/assets/609368/9203640/4fdaabe6-4026-11e5-8f02-aee1a62621c5.png)

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
