### ISSUE TITLE
Add Inline Editing of Annotations to Annotations/Editor Panel

### ISSUE THREAD

**Issue by sdellis** [ProjectMirador/mirador#629]
See #626 and #628.  Clicking an annotation should allow privileged user to edit it inline.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
