### ISSUE TITLE
Restore non-dragging state on slots when a bad drop (of an invalid resource) completes.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#658]
Currently the drop target never resets and the user is unable to use the slot again. This can happen if they try to drop in a random (non-iiif) image they've found, or a mal-formed iiif link, etc.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
