### ISSUE TITLE
Line breaks/styling issues with translation files

### ISSUE THREAD

**Issue by rsinghal** [ProjectMirador/mirador#697]
Some translations (in particular, German) are longer than their English counterparts, which cause styling issues.

**Comment by aeschylus** [comment]
Can you create some screenshots for this? Or, how do I reproduce this? Are there manifests you recommend, or do I need to change the translation settings forcibly somehow?

**Comment by rsinghal** [comment]
This was mentioned to me by someone from Leipzig, so presumably, it was their manifests that were creating that problem, but I don't have any specific example manifests.  If you change your browser setting to German, the library will automatically load German translations.

**Comment by rsinghal** [comment]
I actually don't think it is specifically an issue with the manifest, but the i18n library and the translations for the terms used in Mirador

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
