### ISSUE TITLE
configurable slot menu items

### ISSUE THREAD

**Issue by beaudet** [ProjectMirador/mirador#704]
ConservationSpace would like to add a new slot menu item "Add Images" that executes a custom callback when selected.  It seems like there is not currently a way to configure Mirador with a custom slot menu like there is for the main Mirador menu.  We would like this feature to avoid having to hack the behavior of the existing "new object" menu item.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
