### ISSUE TITLE
provide mechanism for customizing callback for the empty slot (+) icon

### ISSUE THREAD

**Issue by beaudet** [ProjectMirador/mirador#705]
The ConservationSpace project would like the (+) icon that appears on an empty slot to bypass the manifest gallery and to open up a custom image search dialog instead.

**Comment by rsinghal** [comment]
Alternatively, the manifest gallery page can be customizable, and you can drop your image search into that.  @aeschylus also suggested of a system that changes the size of Mirador when a user wants to add a new object, image, etc.  Mirador would scale down to a small icon in a corner (like youtube works on a phone) to expose a more advanced search/gallery.  Clicking on an item in the search results populates Mirador and maximizes it again.

**Comment by beaudet** [comment]
We were going back and forth internally about whether to override the (+) or to customize the gallery.  Since we determined that there is to be a "preview" mode allowing for external manifests to be added (but not persisted), we cannot do away with the gallery page.  So, at this point, I think customizing the gallery page is the simplest approach.  How do you recommend proceeding with that?  Is there a preferred mechanism and is the answer affected by the refactoring effort?

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
