### ISSUE TITLE
create configurable filter for manifest URLs

### ISSUE THREAD

**Issue by beaudet** [ProjectMirador/mirador#708]
Create a manifest URL filter configuration in Mirador that accepts a regular expression that is applied to all manifest URLs.  Mirador then only loads manifests passing through the filter - including drag & drop - so this should be enforced at the data loading layer.

**Comment by aeschylus** [comment]
I'm considering removing this from the milestone. How important is this? It could be simple, but requires some more discussion (and design).

**Comment by beaudet** [comment]
It's of minor importance at this point, so you can remove it from the 2.1 release but please leave it as an active feature request.

**Comment by aeschylus** [comment]
I moved it to 2.2. It's definitely something that gets asked for a lot.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

Filtering manifests in in the add manifest selection process has not been implemented in Mirador 3. Once there are some proposed designs for this, it could be implemented as a plugin.
