### ISSUE TITLE
User experience of drag and drop when no new window available

### ISSUE THREAD

**Issue by snydman** [ProjectMirador/mirador#719]
When you drag and drop a IIIF icon into a Mirador window that is occupied by an image it appears that it replaces the object. Is this the user interaction we want?  Or do we want a user interaction that asks the user if they want to replace or add new window?

What we have now is probably fine for starters, but making the ticket for future consideration.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
