### ISSUE TITLE
Accessibility note: using h1 tags for buttons or labels is discouraged

### ISSUE THREAD

**Issue by lduarte1991** [ProjectMirador/mirador#724]
A quick example of this can be found in [slot.js](https://github.com/IIIF/mirador/blob/master/js/src/workspaces/slot.js#L190).

```
'<h1 class="plus" role="presentation" aria-label="Add item using Link">',
    '<span>+</span>',
    '<div class="dropIcon">',
        '<i class="fa fa-level-down"></i>',
    '</div>',
'</h1>',
'<h1 class="addItemText">{{t "addItem"}}</h1>',
'<h1 class="dropMeMessage">Drop to Load Manifest</h1>',
```

Using header tags for items like this is discouraged because when using a screenreader or the web rotor in VoiceOver for Mac, headers are listed/itemized to give people a better understanding of what is on this page. Using them to label sections or for important items is acceptable, but in this case they seem to serve only an aesthetic purpose (i.e. I'm assuming that what you wanted was the style of a header 1 and not its actual context). I'd recommend making them divs or spans instead.

**Comment by lduarte1991** [comment]
Requested by @rsinghal [here](https://github.com/IIIF/mirador/pull/721#discussion_r47655884).

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
