### ISSUE TITLE
"Load" translation needed

### ISSUE THREAD

**Issue by rsinghal** [ProjectMirador/mirador#729]
Add "Load" to the translation files and update the manifests panel template to use that

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets. Information about contributing to translations can be found on the [wiki](https://github.com/ProjectMirador/mirador/wiki/M3-Internationalization-(i18n)).
