### ISSUE TITLE
Convert modules to webpack.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#739]

**Comment by aeschylus** [comment]
- 1. Remove jQuery closure.
-  2. Remove dollar signs on prototype and constructor definitions.
-  3. Add 'use strict' at top of file.
-  4. Add `module.exports = MODULENAME;` to end of file.

**Comment by aindlq** [comment]
If you decided to make such refactoring, I would recommend to use ES6 module syntax instead of commonjs "module.exports".

**Comment by aeschylus** [comment]
Thanks @aindlq; It's a possibility. For reference, Das Rauschmeister has [an article](http://www.2ality.com/2014/09/es6-modules-final.html) on this syntax from 2014, and here is the most recent ["official" account](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import). Will this require the entire module to be written in ES6 syntax?

Do you know of a good resource for setting up ES6 modules with webpack that doesn't require re-writing everything in ES6?

**Comment by aindlq** [comment]
You don't have to write everything in ES6 syntax. In fact, to fully use ES6 you will need some kind of transpiler like  https://github.com/babel/babel.

But the good thing is that for modules you don't need any transplier, latest webpack supports ES6 modules out of the box - https://github.com/webpack/webpack/releases/tag/v2.0.2-beta. Do not be scared by beta, from my experience it is quite stable.

**Comment by jbaiter** [comment]
Is anybody working on this? If not, I'd like to give it a shot, using ES6 modules (without babel, as suggested by @aindlq).

An added benefit of this should be a significant reduction of the size of the generated bundle, since Webpack 2 supports "tree shaking", where unused exports are purged from the bundle. Mirador's production build currently is >2MiB, it would be great to get this down a bit.

**Comment by La0** [comment]
@jbaiter Did you manage to work on this ? I would be interested in a webpack-compatible version of Mirador...

**Comment by mejackreed** [comment]
No sorry we never got to this. Though for Mirador 3, Webpack/Rollup (or something compatible) will be built in from the start.
