### ISSUE TITLE
Tags reorder unpredictably

### ISSUE THREAD

**Issue by lizfischer** [ProjectMirador/mirador#744]
After creating an annotation, tags appear in a different order. If they were made to be alphabetical, I would understand, but there is no discernible pattern that I see.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations). Note that tag creation has not been implemented, but designs are being reviewed in ProjectMirador/mirador-annotations#7
