### ISSUE TITLE
Local storage runs out of space

### ISSUE THREAD

**Issue by rsinghal** [ProjectMirador/mirador#746]
This will not likely affect the average user, but if you use Mirador enough with saveSession on, it will fill up the local storage with so many new sessions that it will run out of space, causing `Failed to execute 'setItem' on 'Storage': Setting the value of '[key]' exceeded the quota.` in Chrome

**Comment by markmatney** [comment]
I'd like to start a discussion about what a solution for this problem would look like. Operating under the assumption that this issue would require end users themselves to manually clear unneeded entries from their local storage:
- enable (and encourage) users to add some additional metadata to a workspace (name and/or description), perhaps prompting them for it whenever a new workspace and associated UUID is generated
- whenever the `DOMException` is thrown by `localStorage.setItem`, catch it and show some UI element that contains a table with one row for each workspace entry in local storage (names, description, layout (e.g., '4x3'), UUID, etc.) with a trash can button next to each to allow for deletion
- potentially, this new table could be accessible at any time (as a main menu panel?) to allow a user to edit the additional workspace metadata

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
