### ISSUE TITLE
Stacking order of overlapping annotation targets

### ISSUE THREAD

**Issue by jharward** [ProjectMirador/mirador#750]
The stacking order of annotations in Mirador should be predictable and persistent (unless we provide a mechanism for the user to change it). One motivation for this is that it takes effort to scroll the annotations in the small annotation frame so the first annotation is much easier to see, and the  annotator may well want to reserve that position for the “most important” annotation. In a current example I am working on, I am annotating both a whole line of text from a mmanuscript with transcription and translation but also the iconography of the illuminated initial letters that overlap but are much smaller than the whole line annotations. So, in this case, when I hover over the illuminated letter, I would like the iconography annotation to appear first, because in that position it is more important. More generally, if we make the stacking order persistent, it would be great if there were an editing control that could move a particular annotation up or down the stack.

Current unpredictable behavior:
1.       Draw bounding box A and annotate. Draw box B on top of it and annotate.
2.       Now hover mouse over the intersection of A and B.
3.       Annotation A appears on top.
4.       Now move to a separate page and then move back.
5.       Hover mouse again over the same spot. Annotation B appears on top.

This may be related to the unpredictability of tag ordering (#744).

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
