### ISSUE TITLE
enhancement suggestion: drag-able thumbnail bar

### ISSUE THREAD

**Issue by comstock** [ProjectMirador/mirador#753]
For items that have many pages -- like a digitized reel of microfilm that may include a sequence of a 1000 page-images -- it would be great if one could drag the thumbnail bar left and right so that a reader could more quickly scan for title changes, indexes, section headings, illustrations...all of structures that can be identified by scanning page layouts.

**Comment by aeschylus** [comment]
Shift+scroll/horizontal scroll does this. It also works with a laptop trackpad and dragging/flicking on a touchscreen. The horizontal scrollbar is present as well, but we plan to replace this with a better-looking control.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

This suggestion was implemented in Mirador 3 🎉
