### ISSUE TITLE
Combine the info and TOC panels into one.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#787]
This probably relates to a number of existing issues regarding the side panel, so a link to those would be helpful.

<img width="996" alt="screen shot 2016-03-07 at 10 33 45" src="https://cloud.githubusercontent.com/assets/145874/13579034/3028890c-e450-11e5-8725-6b869ad70efb.png">

Design needed. This side panel is also meant to control the image choice and detail image display properties.

**Comment by aeschylus** [comment]
This may be a way to accommodate canvas and image resource-level metadata. For example, an info button could be on the top bar, representing the manifest, and also in the side panel, invoking metadata that pertains specifically to the thing being viewed.

**Comment by beaudet** [comment]
It is especially important for the museum community to display canvas and image resource specific metadata.  I would suggest that when viewing / navigating a canvas, the canvas and image resource specific metadata is contextually more important than the manifest level metadata.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
