### ISSUE TITLE
karma:cover is failing for annotation-work branch

### ISSUE THREAD

**Issue by gigamorph** [ProjectMirador/mirador#796]
I've pulled the latest of the "annotation-work" branch (5716c5d0555df569dc71ca09dce3baa5e7cec92f)  and

`grunt karma:cover`

is failing:

> $ grunt karma:cover
> Running "karma:cover" (karma) task
> INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
> INFO [launcher]: Starting browser PhantomJS
> INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket -DwEOVuE0lPJXZLLyxBZ with id 61280026
> PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 10 of 71 SUCCESS (0 secs / 0.033 secsPhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 11 of 71 SUCCESS (0 secs / 0.034 secsPhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 12 of 71 SUCCESS (0 secs / 0.051 secsPhantomJS 1.9.8 (Mac OS X 0.0.0) Overlay toggleDrawingTool FAILED
>   TypeError: 'undefined' is not a function (evaluating 'this.viewer.viewport.getBounds(true)')
>       at /Users/sk/home/workspace/git/3rdparty/mirador/js/src/annotations/osd-svg-overlay.js:9
>       at /Users/sk/home/workspace/git/3rdparty/mirador/js/src/annotations/osd-svg-overlay.js:9
>       at /Users/sk/home/workspace/git/3rdparty/mirador/spec/annotations/osd-svg-overlay.test.js:86
>   TypeError: 'undefined' is not an object (evaluating 'this.overlay.currentTool')
>       at /Users/sk/home/workspace/git/3rdparty/mirador/spec/annotations/osd-svg-overlay.test.js:96
> PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 13 of 71 (1 FAILED) (0 secs / 0.054 sPhantomJS 1.9.8 (Mac OS X 0.0.0) Overlay toggleDefaultDrawingTool FAILED

**Comment by stanislavkostadinov** [comment]
I think this fix is enough:
https://github.com/SirmaITT/mirador/commit/719fdf6fe56b1521ae19eff13c7f5db76d058ec2#diff-aec23ca6f7af900f7da29e783bbe1592

**Comment by mejackreed** [comment]
No longer relevant with Mirador 3 work.
