### ISSUE TITLE
Support emerging IIIF search specification

### ISSUE THREAD

**Issue by jeffreycwitt** [ProjectMirador/mirador#803]
I wanted to open at ticket to suggest that we try to put search within on the road map for 2.2.

I have a fork supporting this spec, but it needs MAJOR revisions in light of mirador redesign and 2.1 release. 

[https://github.com/jeffreycwitt/mirador/tree/feature/search-within](https://github.com/jeffreycwitt/mirador/tree/feature/search-within)

@jabrah at hopkins has contributed to this and made some further development.

**Comment by jeffreycwitt** [comment]
A link to a working design document [https://docs.google.com/document/d/1OX0Ehj3W9s74K99dXmbh5xKt_GUPjHAwQ1gse3G27Rw](https://docs.google.com/document/d/1OX0Ehj3W9s74K99dXmbh5xKt_GUPjHAwQ1gse3G27Rw)

**Comment by snydman** [comment]
The Stanford design team did a review of these mocks are related demos and produced an updated set of mockups and design specs for Search Within in Mirador. See and comment at:

https://docs.google.com/document/d/1uvwgAvPGxhM94wYylMItSV6nd39V9uObd82NrjoDI9Y/edit?usp=sharing

Thanks @ggeisler

**Comment by mejackreed** [comment]
I wonder if this ticket should now be resolved based on the current search functionality in core

**Comment by jeffreycwitt** [comment]
agreed. I'll close and someone can re-open if they disagree
