### ISSUE TITLE
text-transform: capitalize; not working perfectly

### ISSUE THREAD

**Issue by rsinghal** [ProjectMirador/mirador#817]
We shouldn't use that because it transforms something like `Creator(s)` to `Creator(S)` in the metadata view.

Example manifest: http://manifests.britishart.yale.edu/manifest/5009

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
