### ISSUE TITLE
Translation needed

### ISSUE THREAD

**Issue by rsinghal** [ProjectMirador/mirador#827]
@tristanr-cogapp @regisrob @jbhoward-dublin @netsensei 

For any non-English languages you know, can you please post the correct translation for 'Gallery View' or 'Thumbnails View' - whatever makes the most sense in that particular language.  This will be a part of the dropdown for the different view types of Mirador, and we are adding the all thumbnails view to it.  Thanks!

**Comment by gigamorph** [comment]
I could provide with Korean translations. By the way, how am I supposed to activate each language in Mirador? Is it documented somewhere? Thanks.

**Comment by rsinghal** [comment]
I used google translate for the other translations, so please take a look in `release2.1` for any inaccuracies, if you have the time!  Many thanks.

**Comment by rsinghal** [comment]
@gigamorph i18ln currently defaults to using the browser language

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets. [Wiki: Internationalization (i18n)](https://github.com/ProjectMirador/mirador/wiki/M3-Internationalization-(i18n)) has more information about contributing translations.
