### ISSUE TITLE
Fix icon creation workflow

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#83]
There are two sets of icons, which are annoying to work with and behave differently from one another: the set of custom image-based icons we have from Mirador 1, and the font-awesome icons used for more generic icons. Every time we need a new icon, the icon palette needs to be manually updated and all relevant CSS hand-tweaked to adapt to the new icon, with all its states having been manually created, to be added. 

With icon fonts you just change the color, opacity, size, or any other property with css in a centralised manner. All the icons take up the space of a single font block and are black as pseudo-elements in the links they represent. We should load our custom icons into [Fontello](https://github.com/fontello/fontello) with [Fontelli-cli](https://github.com/paulyoung/fontello-cli) and built this into the grunt tasks for the project. This way, when we need a new icon, or a contributor needs to add a new icon, they make one SVG icon, but it in a folder, and the build task incorporates it into the icon font in a consistent, cross-browser manner.

**Comment by mejackreed** [comment]
Resolved in Mirador 3
