### ISSUE TITLE
Missing wiki content

### ISSUE THREAD

**Issue by dicksonlaw583** [ProjectMirador/mirador#831]
The following sections of the Wiki are missing:
- "Code Tours"
- Bottom of "Configuration Guides"
- "Configuring Persistent Bookmarking" (this is critical as the dependency on jsonblob.com may become a widespread problem if it shuts down parse.com-style)
- "Conservation Space"
- "Creating a Canvas Tool"
- "Developer Tooling and Workflow"
- "Extensions, Modifications, and Use Cases"
- "Frequently Asked Questions"

Please look into filling in the above sections and removing obsolete sections once 2.1 work becomes stable enough to document.

**Comment by gigamorph** [comment]
I'd also like some documentation on the following:
- Embedding Mirador in another web application (how to communicate with the host application (events, etc.), what role does a manifest play in this, etc.)
- How locales (translations in different languages) work. 
- Using the latest implementation of annotation layer (non-rectangular shapes, modifying existing shapes, creating multiple annotations per shape, assigning multiple shapes to an annotation, labeling, etc.)
- List of events (or an official API for plugins and/or embedding).

**Comment by rsinghal** [comment]
https://github.com/IIIF/mirador/wiki/Events-in-Mirador already exists

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

Mirador 2 wiki pages have been archived at projectmirador/mirador-2-wiki.
