### ISSUE TITLE
TinyMCE editor in the tooltip is being cut off in iOS.

### ISSUE THREAD

**Issue by gigamorph** [ProjectMirador/mirador#853]
I'm observing this from an iPad Pro. You can see from the screenshot from below that the popup editor is cut off at the bottom (no scroll either); for example, you cannot see the save and cancel buttons.

The direct causes seems to be a possible bug in TinyMCE and Mirador.css (https://github.com/IIIF/mirador/blob/release2.1/css/mirador.css) setting `max-height` for `.qtip-content` is set to `200px`. If I remove the line I can see the whole content.

![tinymce_mirador](https://cloud.githubusercontent.com/assets/86015/14921484/84775f72-0e00-11e6-816d-f856878ac5b6.png)

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
