### ISSUE TITLE
IPad Pro and Apple Pencil support

### ISSUE THREAD

**Issue by gigamorph** [ProjectMirador/mirador#854]
I don't know if this is an appropriate place for such feature request or suggestions, but currently iOS in general and events generated by Apple Pencil (e.g., simple "clicks") are not being handled by Mirador. I have a client who wants to use iPad Pro and Apple Pencil for drawing up annotations and I think this kind of demand will increase pretty soon.

**Comment by rsinghal** [comment]
Currently, we don't officially support mobile devices and there is no firm timeline for when we will.  I have created a new label for mobile-related issues to make it easier to organize.

**Comment by aeschylus** [comment]
This is a cool idea and worth experimenting.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
