### ISSUE TITLE
Annotations Viewer remains open after leaving Mirador element

### ISSUE THREAD

**Issue by lduarte1991** [ProjectMirador/mirador#855]
When Mirador is both iframed in and when it's used as an element within a larger place, if you hover over an annotation close to the edge and leave the element/iframe, then the annotation remains opened instead of closing. 

This is an issue when the annotation viewer covers up buttons on any of the corners since the qtip window appears over the controls.

**Comment by csbailey5t** [comment]
The fix that was initially merged in through PR #1304 introduced a bug that broke multi window annotation. 

Effectively, when you opened two windows, opened the annotation tools in the first window, selected the rectangle tool, and tried to draw in the first window, it would initially open the annotation editor, but if you moved your mouse away then back on to the editor, it would disappear, sometimes leaving a tooltip for the tinymce editor behind. If you then highlighted over that, it would highlight parts of the second window. It was reproduced reliably by another person specifically by moving the annotation editor around on the page and then hovering off then onto the editor. 

![anno_bug](https://cloud.githubusercontent.com/assets/4672869/24013165/c69f73d2-0a3d-11e7-8305-e0f90a942830.gif)

We have reverted the PR from the `2.3.0` branch and reopened this issue.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
