### ISSUE TITLE
ScrollView should use the canvas thumbnail only when there is a IIIF service

### ISSUE THREAD

**Issue by regisrob** [ProjectMirador/mirador#872]
Given a canvas with the value of "thumbnail" pointing to a small image (without any "service"). Mirador uses that thumbnail in the scroll view, which results in a stretched image.

For example if you have a manifest with:

```
"thumbnail" : "http://gallica.bnf.fr/ark:/12148/btv1b8449043q/f3.thumbnail"
```

or

```
"thumbnail" : {
    "@id" : "http://gallica.bnf.fr/ark:/12148/btv1b8449043q/f3.thumbnail"
}
```

... although the Presentation-API says it is "recommended that a IIIF Image API service be available for this image for manipulations such as resizing" :grimacing: 

<img width="958" alt="capture d ecran 2016-05-04 a 00 51 32" src="https://cloud.githubusercontent.com/assets/402117/15000755/6e3de77c-1192-11e6-91c5-2db7dd9a979d.png">

**Comment by rsinghal** [comment]
Part of what created this problem is that we reuse the code for ThumbnailsView and ScrollView, which mostly works, except for in this particular situation.  However, both of these views will be superseded by IIIFManifestLayouts, so I include this issue there so they can properly account for it.  Do you have a manifest we can use for testing?

**Comment by regisrob** [comment]
> Do you have a manifest we can use for testing?

Sure, now we have thousands and thousands of them in Gallica :v: (example: http://gallica.bnf.fr/iiif/ark:/12148/btv1b8449043q/manifest.json)

I think it is a mistake originally: the developer inadvertently put an `@id` in the `thumbnail` field, rather than a simple URI string.
A good practice would have been to add a `service` too (as recommended by the spec), but actually I think we do not want that for the following reason: in the BnF manifests, the URL given in `thumbnail` points to a real static thumbnail image (e.g. http://gallica.bnf.fr/ark:/12148/btv1b8449043q/f8.thumbnail), which is way faster than a IIIF request like "/full/,150/0/default.jpg". Gallica uses this kind of static thumbnail in its own viewer (i.e. the image URL ending with a ".thumbnail" Ark qualifier) and this is what we want Mirador to use in the thumbnailsView for obvious performance reasons.

But of course this small thumbnail is not an appropriate image for the scrollView, so in this case `getThumbnailForCanvas` should fall back to https://github.com/IIIF/mirador/blob/release2.1/js/src/utils/utils.js#L47 (i.e. using the image annotation IIIF "service")

**Comment by rsinghal** [comment]
That makes sense and _should_ be fixed with IIIFManifestLayouts.  We will double check that is fixed once it is fully integrated.

**Comment by regisrob** [comment]
Just another example manifest with the same problem (from the Vatican): http://digi.vatlib.it/iiif/MSS_Vat.lat.3225/manifest.json

**Comment by randystern** [comment]
Here is another sample manifest - https://iiif.lib.harvard.edu/manifests/drs:49915795  This problem of scroll view using the thumbnail image affects nearly all of Harvard's manifests.

**Comment by cindychaopeng** [comment]
We ran into this issue recently at nga.gov. So if scrollview intentionally use thumbnail, what is the proper definition of the thumbnail section? We are using iiif service to provide the thumbnail image, How can you define a size which is good for both thumbnail view(,150) and scrollview?

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
