### ISSUE TITLE
Support for Canvas metadata

### ISSUE THREAD

**Issue by azaroth42** [ProjectMirador/mirador#93]
Canvases can also have metadata, and there currently isn't support for displaying that metadata.  The metadata for a canvas should be able to be displayed in the same manner as for the manifest level information, but with a different UI trigger event.
(See #92 for more details)

**Comment by rsinghal** [comment]
The design for this can be a part of #789

**Comment by azaroth42** [comment]
Necessary for IPTC news integration.

**Comment by radpet** [comment]
+1 nice to have it inside the CS project too

**Comment by regisrob** [comment]
+1 for a Mirador demo showcasing a reconstructed volume (as part of a larger digital edition, yet to be published)

Would be more and more needed as manifest authoring tools appear.

**Comment by regisrob** [comment]
Here is an example of a manifest with canvas-level metadata: http://iiif.biblissima.fr/bbmn-1713-t1/manifest.json

**Comment by aeschylus** [comment]
@regisrob Thanks for the fixture.

**Comment by azaroth42** [comment]
Please? We need this for our manuscripts and multi-view images.

**Comment by regisrob** [comment]
I have already implemented this as a quick and temporary solution for one of our demo use case: http://demos.biblissima-condorcet.fr/bbmn-1713/mirador/ (see [commit](https://github.com/regisrob/mirador/commit/2fd2e4445bfa1e14054e1a4df924773a5fcc9f44)). 
@rsinghal Is there still a plan at Harvard to implement this properly in the coming weeks?

**Comment by beaudet** [comment]
+1 from NGA for this

**Comment by notand** [comment]
+1 for a purely virtual collection of pics (as opposed to a digital representation of some existing/reconstructed material object), with the pics mostly being collected from diverse sources/manifests. Not sure if since the last comment from February, there is another place where I should look for a solution, or for the implementation status?

**Comment by mejackreed** [comment]
Canvas level metadata is now supported in Mirador 3. Closing this issue.
