### ISSUE TITLE
Saved Image with saveSession is zoomed out after document is reloaded

### ISSUE THREAD

**Issue by radpet** [ProjectMirador/mirador#930]
[mirador 3.zip](https://github.com/IIIF/mirador/files/284737/mirador.3.zip)

When loading image with saved state mirador is zooming out the one which was loaded in `display:none` parent.

Steps to reproduce:
1 Put the files on simple http-server
2 Open test.html
3 Open tab1 and choose image
4 Zoom in and align the image in order to remember its position
Open tab 2 and do steps 3&4
Click refresh button
See that the both/only the image which was in the hidden tab has changed its position and zoom level

This is causing an issue with embedding Mirador in ConservationSpace.

**Comment by rsinghal** [comment]
I can't recreate this bug as I get the correct zoom and pan levels.

**Comment by radpet** [comment]
I will record video as soon I can and upload it here.

**Comment by rsinghal** [comment]
@radpet I don't need a video, as I believe it is happening to you.  Since it is happening to you, I recommend you dive into the code a bit to pinpoint parts of the code that might be causing this issue.  This could be a browser or OS specific issue and having that information would be helpful.

**Comment by radpet** [comment]
@rsinghal  Well we have tested this under linux/windows under Chrome, under FF  this issue arises https://github.com/IIIF/mirador/issues/929

**Comment by radpet** [comment]
Can this be openseadragon issue because of https://github.com/IIIF/mirador/blob/release2.1/js/src/widgets/imageView.js#L428

The values received when iframes refreshed with display:block and display:none are identical but when it is refreshed in display:none iframe the issue arises.Any ideas what else might be doing this?

**Comment by radpet** [comment]
I updated mirador with the latest openseadragon release and the issue is there too. I am searching for solution in their code. I posted issue on their repo few hours ago.

https://github.com/openseadragon/openseadragon/issues/957

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
