### ISSUE TITLE
Behavior of thumbnails in manifest page

### ISSUE THREAD

**Issue by rsinghal** [ProjectMirador/mirador#940]
Currently, when a user resizes their window such that it is too narrow to show any thumbnails, we switch to showing an ellipsis icon.  However, would it be better to always show a little bit of the first thumbnail, even if it's a bit cut off?  [Google Art Project](https://www.google.com/culturalinstitute/u/0/collections?projectId=art-project) does that - something to consider.

Also, the fix in #931 for very wide images does always show a little bit of the thumbnail, because those images are too wide to fully show, so it's always cut off, even on resize.  http://iiif.ub.uni-leipzig.de/0000000001/manifest.json for an example of a very wide image.

**Comment by fe-kre** [comment]
Is this the behaviour you've expected?

![viewer](https://cloud.githubusercontent.com/assets/17549789/15813158/d857e0ce-2bbc-11e6-86bb-065b946ac284.png)

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
