### ISSUE TITLE
[2.0] Physical size ruler support

### ISSUE THREAD

**Issue by azaroth42** [ProjectMirador/mirador#97]
Process the physical size service from either the Image API info.json response or the Presentation API in order to rescale the ruler to the appropriate size.
See: http://iiif.io/api/annex/services/#physical-dimensions

**Comment by markmatney** [comment]
Can we close this issue and direct discussion to https://github.com/ProjectMirador/mirador/issues/305? The two issues seem to be duplicates, and 305 has more comments.
