### ISSUE TITLE
Tools hud shown when out of annotation creation mode

### ISSUE THREAD

**Issue by radpet** [ProjectMirador/mirador#979]
When I load mirador in annotation discovery mode sometimes (it seems race condition to me) the whole set of tools is shown, although they are not active.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3 annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
