### ISSUE TITLE
[2.0] Collection support

### ISSUE THREAD

**Issue by azaroth42** [ProjectMirador/mirador#98]
Now that we have collections, Mirador should use them to populate the initial load window (or whatever the new name for the much improved m2 version is).

**Comment by azaroth42** [comment]
Fixture with some of the manifests from sul-reader-test:  http://dlss-dev-azaroth.stanford.edu/prezi/colls/top.json

**Comment by azaroth42** [comment]
bump; +1 from the Librarian of University College Dublin.
> We're disappointed, though, that Mirador development has not implemented robust support for IIIF collections, and none at all for collections of collections

**Comment by edsu** [comment]
👍

**Comment by azaroth42** [comment]
+1 from newspaper WG, which requires collection support.

**Comment by azaroth42** [comment]
From iiif-discuss:  "We're looking at the Universal Viewer because of its built-in support for displaying collections."

Mirador is losing users hand over fist by not supporting the specification.

**Comment by azaroth42** [comment]
+1 from Museum WG, which needs this for exhibition viewing.

[I wonder why I bother with this, honestly]

**Comment by coy123** [comment]
+1 from National Library of Austria

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

Collections are now supported in Mirador 3.
