### ISSUE TITLE
Panning stays locked if the viewer is in an iframe and the mouse is released outside it

### ISSUE THREAD

**Issue by dicksonlaw583** [ProjectMirador/mirador#980]
If you pan an iframe-embedded Mirador viewer by dragging from the middle of the canvas, releasing the mouse outside the iframe would cause the viewer to lock into panning mode and follow the mouse around no matter how many times I click or release the left mouse button.

Example: http://individual.utoronto.ca/dicksonlaw/mirador_drag_lock/

We also have some reports of the same locking behaviour on a full-screen viewer in a standalone page, though thus far I have been unable to replicate it. It is probably related to this in some way.

**Comment by radpet** [comment]
I think this is a problem with the openseadragon canvas. Take a look at https://github.com/openseadragon/openseadragon/issues/697

**Comment by beaudet** [comment]
Then Drew can fix it! ☺

**Comment by rsinghal** [comment]
related to #406 and #468

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
