### ISSUE TITLE
Request to support file:// scheme for manifests

### ISSUE THREAD

**Issue by beaudet** [ProjectMirador/mirador#988]
It would be nice if it were possible to enter a manifest URL using the file:// scheme, e.g.

file:///C:/tmp/manifest.json

**Comment by beaudet** [comment]
Ok, this suggestion is a little half-baked since a file:// resource might only be accessible if Mirador is also loaded from a file:// based resource.  Alternatively, an "upload" button for manifests might be even easier and HTML5 now supports reading files directly with JavaScript using the File API.

**Comment by cbeer** [comment]
Mirador 3 allows you to drag and drop manifest files from the desktop.
