### ISSUE TITLE
influence mirador instance programmatically before start of rendering

### ISSUE THREAD

**Issue by nicolasfranck** [ProjectMirador/mirador#999]
Now the mirador instance starts rendering, based on the supplied configuration.
That's handy for simple use cases. But there are use cases where you
want to influence the instance before it starts rendering.

e.g. select specific canvas, use image manipulation tools on it

one cannot simple put all of this in configuration

cf. https://github.com/IIIF/mirador/pull/996

**Comment by aeschylus** [comment]
Interesting. Ideally, I think we should make t possible to define the complete state of the application in the initial configuration (we have to be able to do so for saving and back button protection).

However, this would also be a really useful feature, especially if there are asynchronous processes whose effects need to be applied after Mirador's instance is alive but before anything is visible. Perhaps we could allow the programmer to explicitly "pause" the initialisation process and call a global "render()" method on the entire instance once all their modifications have been completed.

**Comment by rsinghal** [comment]
Including @pobocks who had a similar use case at Harvard Library and could speak to how they solved it there

**Comment by nicolasfranck** [comment]
Ah you probably mean this:

http://iiif.lib.harvard.edu/manifests/view/drs:13836021$3i

with javascript code:

http://iiif.lib.harvard.edu/static/manifests/prod.js

That's where I got the idea in the first place ;-)
I tried it myself here (master branch of mirador!):

http://shared.ugent.be/local/mirador_master

with javascript file:

http://shared.ugent.be/local/mirador_master/mirador_config.js

I managed to catch the change of canvasID, and change the url accordingly,
as he did, but restoring the the current canvas by means of the index as it loads,
requires more information: the server has to preload the manifest, select the
canvasID by index, and supply it to windowObject.

Below this file:

http://iiif.lib.harvard.edu/manifests/view/drs:13836021$3i

You see this static information:
```
script type="text/javascript">
   window.harvard_md_server = {
     PDS_VIEW_URL: "http://pds.lib.harvard.edu/pds/view/",
     IDS_VIEW_URL: "http://ids.lib.harvard.edu/ids/view/",
     FTS_VIEW_URL: "http://fts.lib.harvard.edu/fts/search",
     MIRADOR_DATA: [       
       {"manifestUri": "http://iiif.lib.harvard.edu/manifests/drs:13836021", "location": "Harvard University", "title": "Mozart, Wolfgang Amadeus, 1756-1791.  [Divertimenti, K. 247, F major].  Grand sextuor : pour deux violons, deux cors, alt & basse / compos\u00e9s par W. A. Mozart.  Augsbourg : chez Gombart et Comp:, [1799]. Merritt Mus 745.1.218.5 BMEO"}       
     ],
     MIRADOR_WOBJECTS: [       
       {"canvasID": "http://iiif.lib.harvard.edu/manifests/drs:13836021/canvas/canvas-13836598.json", "loadedManifest": "http://iiif.lib.harvard.edu/manifests/drs:13836021", "viewType": "ImageView"}       
     ],
     PATH_DATA:     
     {"i18nPath": "/static/manifests/prod/locales/", "logosLocation": "/static/manifests/prod/images/logos/"}     ,
     LAYOUT: "1x1"
   };
```

So I thought doing it like this:
```
$.subscribe('manifestReceived',function(evt,m){
      manifest = m.jsonLd;
});
```
And select the canvasID myself. But that happens AFTER the start of Mirador.
So everything is probably already loaded..

**Comment by mejackreed** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

@nicolasfranck this is now possible in Mirador 3 with the [mirador-image-tools plugin](https://github.com/ProjectMirador/mirador-image-tools).
